function audit = assertAOnlyCost(cost, label, protocol)
%ASSERTAONLYCOST Reject any Gram or non-direct subspace execution.

arguments
    cost (1, 1) struct
    label (1, 1) string
    protocol (1, 1) struct = r34.config()
end

required = ["carrierCount", "directCount", "gramSuccessCount", ...
    "fallbackCount", "method"];
if ~all(isfield(cost, required))
    error("r34:IncompleteSolverAudit", ...
        "The %s cost record lacks a required solver field.", label);
end
methods = string(cost.method(:));
pass = ~protocol.implementation.useGram ...
    && cost.gramSuccessCount == 0 ...
    && cost.fallbackCount == 0 ...
    && cost.directCount == cost.carrierCount ...
    && numel(methods) == cost.carrierCount ...
    && all(startsWith(methods, "direct"));
if ~pass
    error("r34:GramOrNonDirectSolverRejected", ...
        "The %s path used Gram, fallback, or a non-direct solver.", label);
end
audit = struct(label=label, solver="direct-covariance-eig", ...
    carrierCount=cost.carrierCount, directCount=cost.directCount, ...
    gramSuccessCount=cost.gramSuccessCount, ...
    fallbackCount=cost.fallbackCount, ...
    allMethodsDirect=true, acceptedImplementation=protocol.estimatorVersion);
end
