function authorization = assertFinalTestAuthorized(packageFolder, identity)
%ASSERTFINALTESTAUTHORIZED Enforce an exact future user-issued authorization.

arguments
    packageFolder (1, 1) string
    identity (1, 1) struct
end

file = fullfile(packageFolder, "FINAL_TEST_AUTHORIZATION.mat");
if ~isfile(file)
    error("r34:FinalTestNotAuthorized", ...
        "The R34 final test is locked and no authorization exists.");
end
saved = load(file, "authorization");
if ~isfield(saved, "authorization")
    error("r34:MalformedFinalAuthorization", ...
        "The final authorization file has no authorization record.");
end
authorization = saved.authorization;
required = ["approved", "designHash", "sourceDigest", ...
    "protocolVersion", "estimatorVersion", "statisticsVersion"];
if ~all(isfield(authorization, required)) ...
        || ~authorization.approved ...
        || authorization.designHash ~= identity.designHash ...
        || authorization.sourceDigest ~= identity.sourceDigest ...
        || authorization.protocolVersion ~= identity.protocol.version ...
        || authorization.estimatorVersion ...
        ~= identity.protocol.estimatorVersion ...
        || authorization.statisticsVersion ...
        ~= identity.protocol.statisticsVersion
    error("r34:FinalAuthorizationIdentityMismatch", ...
        "Authorization does not match this exact source, design, and method.");
end
end
