function protocol = config()
%CONFIG Freeze the final engineering integration around accepted R33 A-only.

protocol.version = "R34-final-engineering-integration-v1";
protocol.estimatorVersion = "R33-A-q-only-invariants-direct-EVD-v1";
protocol.acceptedIdentity = "R33-A-equivalent-implementation-accepted-v1";
protocol.statisticsVersion = ...
    "R34-R32-frozen-statistics-bootstrap-index-fix-v1";
protocol.orchestrationVersion = "R34-final-orchestration-v1";
protocol.r32 = r32.config();
protocol.r33 = r33.config();
protocol.implementation = struct( ...
    useFastResponse=true, useGram=false, ...
    subspaceSolver="direct-covariance-eig", ...
    methods=["P_A", "C_enhanced", "H_A", "C_public"], ...
    diagnostic="F_L06", ...
    optimizationStatus="closed-no-further-method-selection");
protocol.statistics = protocol.r32.statistics;
protocol.statistics.bootstrapIndexImplementation = ...
    "explicit-column-preserving-reshape";
protocol.finalTest = protocol.r32.finalTest;
protocol.finalTest.designHash = ...
    "e1f6cc945644e88806432a52d2b6e18d0df026024c279790c9bf26edb9792cd6";
protocol.finalTest.expectedRows = 1400;
protocol.finalTest.expectedShardCount = 2;
protocol.finalTest.expectedRowsPerShard = 700;
protocol.finalTest.expectedPositionsPerShard = 100;
protocol.finalTest.status = "LOCKED-WAITING-FOR-EXPLICIT-USER-AUTHORIZATION";
protocol.finalTest.authorized = false;
protocol.finalTest.authorizationPhrase = ...
    "I_EXPLICITLY_AUTHORIZE_R34_FINAL_1400";
protocol.development = struct( ...
    allowedSeeds=[36200001, 36300001, 36400001], ...
    role="engineering-smoke-only-excluded-from-final-results");
end
