function result = finalTrial(cfg, scan, row, inputHash, protocol)
%FINALTRIAL Run one frozen shared trial without Java calls on the worker.

arguments
    cfg (1, 1) struct
    scan (1, 1) struct
    row (1, :) table
    inputHash (1, 1) struct
    protocol (1, 1) struct = r34.config()
end

result = struct(success=false, errorIdentifier="", errorMessage="", ...
    version="R34-A-only-final-performance-trial-v1", seed=row.seed, ...
    positionId=row.positionId, snrDb=row.snrDb, ...
    estimatorVersion=protocol.estimatorVersion, ...
    implementationOptions=struct(UseFastResponse=true, UseGram=false));
timer = tic;
try
    if inputHash.seed ~= row.seed ...
            || ~all(isfield(inputHash, ["observation", "snapshots"]))
        error("r34:InputHashIdentityMismatch", ...
            "The client-side input hash does not match this trial row.");
    end
    replay = fsjad.replayRound27Data(cfg, scan, row);
    estimate = r34.sharedPerformanceSet(cfg, replay.observation, ...
        replay.snapshots, scan, protocol);
    result.methodNames = ["P_A", "C_enhanced", "H_A", ...
        "C_public", "F_L06"];
    result.thetaDeg = [estimate.P_A.thetaDeg, ...
        estimate.C_enhanced.thetaDeg, estimate.H_A.thetaDeg, ...
        estimate.C_public.thetaDeg, estimate.front.selected.thetaDeg];
    result.rangeM = [estimate.P_A.rangeM, ...
        estimate.C_enhanced.rangeM, estimate.H_A.rangeM, ...
        estimate.C_public.rangeM, estimate.front.selected.rangeM];
    result.diagnostics = compactDiagnostics(estimate);
    result.solverAudit = estimate.solverAudit;
    result.counts = estimate.counts;
    result.hash = inputHash;
    result.generationVersion = replay.version;
    result.success = all(isfinite(result.thetaDeg)) ...
        && all(isfinite(result.rangeM));
catch exception
    result.errorIdentifier = string(exception.identifier);
    result.errorMessage = string(getReport( ...
        exception, "extended", "hyperlinks", "off"));
end
result.sessionSeconds = toc(timer);
end

function output = compactDiagnostics(estimate)
output = struct();
output.front = struct(version=estimate.front.version, ...
    selected=estimate.front.selected, ...
    peakCarrierIndex=estimate.front.peakCarrierIndex, ...
    candidateCount=height(estimate.front.candidateBank), ...
    retainedCount=height(estimate.front.selectedBank), ...
    subsetEvaluations=estimate.front.subsetEvaluations, ...
    fullEvaluations=estimate.front.fullEvaluations);
output.C_enhanced = estimate.C_enhanced.estimate;
output.H_A = estimate.H_A.estimate;
output.P_A = struct(angle=estimate.P_A.estimate, ...
    profile=estimate.P_A.profile);
output.C_public = estimate.C_public.estimate;
output.sharedPerformanceComputation = true;
output.deploymentTimingSource = ...
    "R33-complete-online-timing-a-only-not-this-shared-session";
end
