function [candidates, levels] = fsjadJointSearchSpace
%FSJADJOINTSEARCHSPACE Deterministic full joint search for FSJAD.

levels.fusionCarrierCount = [65, 129, 257, 513, 1025, 2047];
levels.subarraySize = [32, 64, 96, 128, 160, 192, 224];
levels.angleHalfWidthDeg = [0.005, 0.01, 0.02, 0.05, ...
    0.1, 0.2, 0.5, 1];
levels.rangeHalfWidthM = [0.0025, 0.005, 0.01, 0.02, ...
    0.05, 0.1, 0.25, 0.5, 1];
levels.gridSizes = {[21, 15, 11], [31, 21, 15], [37, 27, 19], ...
    [41, 31, 21], [49, 35, 25], [61, 41, 31]};
levels.profileHalfWidthM = [0.1, 0.2, 0.3, 0.5, 1, 2, 3];
levels.profileSpacingM = [0.025, 0.05, 0.075, 0.1, ...
    0.15, 0.2, 0.3, 0.5];
levels.profileLambda = [0, 0.25, 0.5, 0.7, 0.8, 0.9, 0.95, 1];

baseCounts = [numel(levels.fusionCarrierCount), ...
    numel(levels.subarraySize), numel(levels.angleHalfWidthDeg), ...
    numel(levels.rangeHalfWidthM), numel(levels.gridSizes)];
[halfIndex, spacingIndex] = find(validProfilePairs(levels));
profilePairCount = numel(halfIndex);
fullCount = prod(baseCounts) * profilePairCount ...
    * numel(levels.profileLambda);
levels.fullDiscreteSpaceCount = fullCount;

stream = RandStream("mt19937ar", Seed=20260905);
numRandomCandidates = 128;
covered = false;
while ~covered
    linearIndex = randperm(stream, fullCount, numRandomCandidates).';
    [baseLinearIndex, pairIndex, lambdaIndex] = ind2sub( ...
        [prod(baseCounts), profilePairCount, ...
        numel(levels.profileLambda)], linearIndex);
    [fusionIndex, subarrayIndex, angleIndex, rangeIndex, gridIndex] = ...
        ind2sub(baseCounts, baseLinearIndex);
    indices = [fusionIndex, subarrayIndex, angleIndex, rangeIndex, ...
        gridIndex, halfIndex(pairIndex), spacingIndex(pairIndex), ...
        lambdaIndex];
    covered = coversEveryLevel(indices, levels);
end

anchors = anchorIndices(levels);
indices = unique([indices; anchors], "rows", "stable");
while size(indices, 1) < 136
    extraLinear = randi(stream, fullCount);
    [baseLinear, pair, lambda] = ind2sub([prod(baseCounts), ...
        profilePairCount, numel(levels.profileLambda)], extraLinear);
    [fusion, subarray, angle, range, grid] = ...
        ind2sub(baseCounts, baseLinear);
    extra = [fusion, subarray, angle, range, grid, ...
        halfIndex(pair), spacingIndex(pair), lambda];
    indices = unique([indices; extra], "rows", "stable");
end
if size(indices, 1) > 136
    indices = indices(1:136, :);
end

fusionCarrierCount = levels.fusionCarrierCount(indices(:, 1)).';
subarraySize = levels.subarraySize(indices(:, 2)).';
angleHalfWidthDeg = levels.angleHalfWidthDeg(indices(:, 3)).';
rangeHalfWidthM = levels.rangeHalfWidthM(indices(:, 4)).';
gridIndex = indices(:, 5);
profileHalfWidthM = levels.profileHalfWidthM(indices(:, 6)).';
profileSpacingM = levels.profileSpacingM(indices(:, 7)).';
profileLambda = levels.profileLambda(indices(:, 8)).';
gridLevels = strings(size(gridIndex));
for row = 1:numel(gridIndex)
    gridLevels(row) = strjoin(string(levels.gridSizes{gridIndex(row)}), "/");
end
candidateId = (1:size(indices, 1)).';
candidates = table(candidateId, fusionCarrierCount, subarraySize, ...
    angleHalfWidthDeg, rangeHalfWidthM, gridIndex, gridLevels, ...
    profileHalfWidthM, profileSpacingM, profileLambda);
end

function valid = validProfilePairs(levels)
valid = levels.profileHalfWidthM(:) ...
    >= levels.profileSpacingM(:).';
end

function covered = coversEveryLevel(indices, levels)
counts = [numel(levels.fusionCarrierCount), ...
    numel(levels.subarraySize), numel(levels.angleHalfWidthDeg), ...
    numel(levels.rangeHalfWidthM), numel(levels.gridSizes), ...
    numel(levels.profileHalfWidthM), numel(levels.profileSpacingM), ...
    numel(levels.profileLambda)];
covered = all(arrayfun(@(column) ...
    numel(unique(indices(:, column))) == counts(column), 1:8));
end

function anchors = anchorIndices(levels)
values = [ ...
    513, 96, 0.02, 0.02, 3, 1, 0.15, 0.9; ...
    513, 128, 1, 1, 6, 1, 0.1, 0.9; ...
    1025, 224, 0.1, 0.0025, 3, 1, 0.1, 0.9; ...
    2047, 224, 0.2, 0.01, 6, 2, 0.025, 1; ...
    257, 64, 0.02, 0.01, 2, 0.5, 0.1, 0.9; ...
    513, 96, 0.02, 0.02, 6, 2, 0.1, 0.9; ...
    513, 96, 0.02, 0.02, 3, 1, 0.15, 1; ...
    65, 32, 1, 1, 1, 3, 0.5, 0];
anchors = zeros(size(values));
for row = 1:size(values, 1)
    anchors(row, :) = [ ...
        levelIndex(levels.fusionCarrierCount, values(row, 1)), ...
        levelIndex(levels.subarraySize, values(row, 2)), ...
        levelIndex(levels.angleHalfWidthDeg, values(row, 3)), ...
        levelIndex(levels.rangeHalfWidthM, values(row, 4)), ...
        values(row, 5), ...
        levelIndex(levels.profileHalfWidthM, values(row, 6)), ...
        levelIndex(levels.profileSpacingM, values(row, 7)), ...
        levelIndex(levels.profileLambda, values(row, 8))];
end
end

function index = levelIndex(levels, value)
index = find(abs(levels - value) <= 10 * eps(max(1, abs(value))), 1);
assert(~isempty(index), "fsjadJointSearchSpace:MissingAnchorLevel");
end
