function output = r40AngleVariants(cfg, context, thetaGridDeg, ...
    selectedIndex, rangeM, protocol)
%R40ANGLEVARIANTS Compute fixed-range control and primary Schur step.

arguments
    cfg (1, 1) struct
    context (1, 1) struct
    thetaGridDeg (1, :) double {mustBeFinite}
    selectedIndex (1, 1) double {mustBeInteger, mustBePositive}
    rangeM (1, 1) double {mustBeFinite, mustBePositive}
    protocol (1, 1) struct = r40SchemeGProtocol()
end

if selectedIndex > numel(thetaGridDeg) || numel(thetaGridDeg) < 3 ...
        || any(diff(thetaGridDeg) <= 0)
    error("r40:InvalidFinalAngleGrid", ...
        "Scheme G requires the ordered final P_A angle grid.");
end
thetaBaseDeg = thetaGridDeg(selectedIndex);
linearTimer = tic;
linearization = r40VariableProjectionLinearization( ...
    cfg, context, deg2rad(thetaBaseDeg), rangeM);
linearizationSeconds = toc(linearTimer);
scalars = r40LocalStepScalars( ...
    linearization.gradient, linearization.information, protocol);
if selectedIndex == 1 || selectedIndex == numel(thetaGridDeg)
    bracketDeg = [thetaBaseDeg, thetaBaseDeg];
    fixed = endpointResult("fixed", thetaBaseDeg, rangeM, ...
        linearization, scalars, linearizationSeconds, bracketDeg);
    schur = endpointResult("schur", thetaBaseDeg, rangeM, ...
        linearization, scalars, linearizationSeconds, bracketDeg);
else
    bracketDeg = thetaGridDeg(selectedIndex+[-1, 1]);
    fixed = evaluateVariant("fixed", scalars.fixedRawStepRad, ...
        scalars.fixedValid, cfg, context, thetaBaseDeg, rangeM, ...
        bracketDeg, linearization, scalars, linearizationSeconds, protocol);
    schur = evaluateVariant("schur", scalars.schurRawStepRad, ...
        scalars.schurValid, cfg, context, thetaBaseDeg, rangeM, ...
        bracketDeg, linearization, scalars, linearizationSeconds, protocol);
end
output = struct(version=protocol.version, thetaBaseDeg=thetaBaseDeg, ...
    rangeBaseM=rangeM, bracketDeg=bracketDeg, ...
    linearization=compactLinearization(linearization), scalars=scalars, ...
    linearizationSeconds=linearizationSeconds, fixed=fixed, schur=schur, ...
    stepDifferenceDeg=schur.thetaDeg-fixed.thetaDeg, ...
    rawStepDifferenceDeg=rad2deg(scalars.schurRawStepRad ...
    -scalars.fixedRawStepRad));
end

function result = evaluateVariant(name, rawStepRad, valid, cfg, context, ...
    thetaBaseDeg, rangeM, bracketDeg, linearization, scalars, ...
    linearizationSeconds, protocol)
timer = tic;
result = baseResult(name, thetaBaseDeg, rangeM, linearization, ...
    scalars, linearizationSeconds, bracketDeg);
if ~valid || ~isfinite(rawStepRad)
    result.status = "invalid-information-retained";
    result.fallbackReason = "invalid-information";
    result.variantSeconds = toc(timer);
    result.standaloneAngleSeconds = linearizationSeconds+result.variantSeconds;
    return;
end
rawThetaDeg = thetaBaseDeg+rad2deg(rawStepRad);
candidateThetaDeg = min(max(rawThetaDeg, bracketDeg(1)), bracketDeg(2));
deltaThetaRad = deg2rad(candidateThetaDeg-thetaBaseDeg);
deltaRangeM = -(scalars.gRange ...
    +scalars.jThetaRange*deltaThetaRad)/scalars.jRangeRange;
candidateRangeM = rangeM+deltaRangeM;
result.rawThetaDeg = rawThetaDeg;
result.rawStepDeg = rad2deg(rawStepRad);
result.candidateThetaDeg = candidateThetaDeg;
result.clippedStepDeg = candidateThetaDeg-thetaBaseDeg;
result.clippedToBracket = rawThetaDeg ~= candidateThetaDeg;
result.boundarySelected = candidateThetaDeg == bracketDeg(1) ...
    || candidateThetaDeg == bracketDeg(2);
result.rawArrayNuisanceDeltaRangeM = deltaRangeM;
result.arrayCandidateRangeM = candidateRangeM;
if ~isfinite(candidateRangeM) || candidateRangeM <= 0 ...
        || candidateRangeM < cfg.rangeLimitsM(1) ...
        || candidateRangeM > cfg.rangeLimitsM(2)
    result.status = "invalid-array-range-retained";
    result.fallbackReason = "array-range-outside-physical-limits";
    result.variantSeconds = toc(timer);
    result.standaloneAngleSeconds = linearizationSeconds+result.variantSeconds;
    return;
end
costTimer = tic;
candidateCost = r40ConcentratedCost(cfg, context, ...
    deg2rad(candidateThetaDeg), candidateRangeM);
candidateCostSeconds = toc(costTimer);
delta = [deltaThetaRad; deltaRangeM];
predictedReduction = -(linearization.gradient.'*delta ...
    +0.5*delta.'*linearization.information*delta);
actualReduction = linearization.cost-candidateCost;
tolerance = protocol.numerical.costScaleTolerance ...
    *max([1, abs(linearization.cost), abs(candidateCost)]);
accepted = isfinite(candidateCost) && actualReduction > tolerance;
result.candidateCost = candidateCost;
result.predictedCostReduction = predictedReduction;
result.actualCostReduction = actualReduction;
result.costTolerance = tolerance;
result.candidateCostSeconds = candidateCostSeconds;
result.fullArrayEvaluationCount = 2;
if accepted
    result.thetaDeg = candidateThetaDeg;
    result.selectedStepDeg = candidateThetaDeg-thetaBaseDeg;
    result.selectedArrayNuisanceDeltaRangeM = deltaRangeM;
    result.accepted = true;
    result.selectedSource = name+"-one-step";
    result.status = "completed-accepted";
else
    result.fallbackReason = "concentrated-cost-not-decreased";
    result.status = "candidate-rejected-P_A-retained";
end
result.variantSeconds = toc(timer);
result.standaloneAngleSeconds = linearizationSeconds+result.variantSeconds;
end

function result = endpointResult(name, thetaDeg, rangeM, linearization, ...
    scalars, linearizationSeconds, bracketDeg)
result = baseResult(name, thetaDeg, rangeM, linearization, scalars, ...
    linearizationSeconds, bracketDeg);
result.status = "final-grid-endpoint-retained";
result.fallbackReason = "final-grid-endpoint";
end

function result = baseResult(name, thetaDeg, rangeM, linearization, ...
    scalars, linearizationSeconds, bracketDeg)
result = struct(version="R40-angle-variant-v1", name=name, ...
    thetaBaseDeg=thetaDeg, rangeBaseM=rangeM, bracketDeg=bracketDeg, ...
    thetaDeg=thetaDeg, rawThetaDeg=thetaDeg, ...
    candidateThetaDeg=thetaDeg, rawStepDeg=0, clippedStepDeg=0, ...
    selectedStepDeg=0, clippedToBracket=false, ...
    boundarySelected=false, accepted=false, ...
    rawArrayNuisanceDeltaRangeM=0, ...
    selectedArrayNuisanceDeltaRangeM=0, ...
    arrayCandidateRangeM=rangeM, oldCost=linearization.cost, ...
    candidateCost=linearization.cost, predictedCostReduction=0, ...
    actualCostReduction=0, costTolerance=0, ...
    normalizedCoupling=scalars.normalizedCoupling, ...
    effectiveInformationRatio=scalars.effectiveInformationRatio, ...
    fullArrayEvaluationCount=1, ...
    linearizationSeconds=linearizationSeconds, ...
    candidateCostSeconds=0, variantSeconds=0, ...
    standaloneAngleSeconds=linearizationSeconds, ...
    selectedSource="P_A-retained", status="not-run", ...
    fallbackReason="");
end

function output = compactLinearization(input)
output = struct(version=input.version, cost=input.cost, ...
    gradient=input.gradient, information=input.information, ...
    residualEnergy=input.residualEnergy, ...
    carrierCount=input.carrierCount, ...
    fullArrayEvaluationCount=input.fullArrayEvaluationCount);
end

