function output = r40SummarizeSchemeG(design, results, protocol, population)
%R40SUMMARIZESCHEMEG Summarize one fixed Scheme G evidence stage.

arguments
    design table
    results cell
    protocol (1, 1) struct = r40SchemeGProtocol()
    population (1, 1) string = "development60"
end

if numel(results) ~= height(design) || any(cellfun(@isempty, results)) ...
        || any(cellfun(@(x) ~x.success, results))
    error("r40:IncompleteSchemeGResults", ...
        "Scheme G summary requires every fixed row.");
end
perUser = buildPerUser(design, results);
methodSummary = summarizeMethods(perUser);
aggregate = equalSnrAggregate(methodSummary);
pairedComparisons = pairedComparisonsTable(perUser);
mechanismDiagnostics = mechanismTable(perUser);
mechanismSummary = summarizeMechanism(perUser);
rangeTransportDiagnostics = rangeTransportTable(perUser);
rangeTransportSummary = summarizeRangeTransport(perUser);
runtimeBreakdown = runtimeTable(perUser);
gate = engineeringGate(methodSummary, aggregate, perUser, protocol, population);
decision = table(population, all(gate.pass(gate.hardGate)), ...
    all(gate.pass), mean(perUser.runtime_G_schur) ...
    /mean(perUser.runtime_P_A), ...
    'VariableNames', {'population', 'hardGatePassed', ...
    'allIncludingTargetPassed', 'runtimeRatioToPA'});
output = struct(version=protocol.version+"-summary-v1", ...
    population=population, perUser=perUser, ...
    methodSummary=methodSummary, equalSnrAggregate=aggregate, ...
    pairedComparisons=pairedComparisons, ...
    mechanismDiagnostics=mechanismDiagnostics, ...
    mechanismSummary=mechanismSummary, ...
    rangeTransportDiagnostics=rangeTransportDiagnostics, ...
    rangeTransportSummary=rangeTransportSummary, ...
    runtimeBreakdown=runtimeBreakdown, gate=gate, decision=decision, ...
    hardGatePassed=decision.hardGatePassed);
end

function perUser = buildPerUser(design, results)
methods = ["P_A", "C_enhanced", "E_single", "F", ...
    "G_fixed", "G_schur"];
perUser = design(:, ["seed", "trialIndex", "snrDb", ...
    "truthThetaDeg", "truthRangeM"]);
for method = methods
    perUser.("theta_"+method) = cellfun( ...
        @(x) x.(method).thetaDeg, results);
    perUser.("range_"+method) = cellfun( ...
        @(x) x.(method).rangeM, results);
    perUser.("runtime_"+method) = cellfun( ...
        @(x) x.(method).runtimeSeconds, results);
    perUser.("responseCount_"+method) = cellfun( ...
        @(x) x.(method).responseEvaluationCount, results);
    perUser.("musicCount_"+method) = cellfun( ...
        @(x) x.(method).musicEvaluationCount, results);
    perUser.("evdCount_"+method) = cellfun( ...
        @(x) x.(method).evdCount, results);
    perUser.("profilePasses_"+method) = cellfun( ...
        @(x) x.(method).completeProfilePassCount, results);
end
perUser.runtimeOrder = string(cellfun(@(x) x.runtimeOrder, ...
    results, UniformOutput=false));
perUser.baselineIdentityPass = cellfun( ...
    @(x) x.baselineIdentity.pass, results);
perUser.maximumBaselineIdentityDifference = cellfun( ...
    @(x) max([x.baselineIdentity.thetaDifferencePA, ...
    x.baselineIdentity.rangeDifferencePA, ...
    x.baselineIdentity.thetaDifferenceC, ...
    x.baselineIdentity.rangeDifferenceC, ...
    x.baselineIdentity.finalGridMaximumDifferenceDeg]), results);
variants = ["fixed", "schur"];
for variant = variants
    record = "G_"+variant;
    perUser.("rawStepDeg_"+record) = cellfun( ...
        @(x) x.angle.(variant).rawStepDeg, results);
    perUser.("selectedStepDeg_"+record) = cellfun( ...
        @(x) x.angle.(variant).selectedStepDeg, results);
    perUser.("arrayDeltaRangeRaw_"+record) = cellfun( ...
        @(x) x.angle.(variant).rawArrayNuisanceDeltaRangeM, results);
    perUser.("arrayDeltaRangeSelected_"+record) = cellfun( ...
        @(x) x.angle.(variant).selectedArrayNuisanceDeltaRangeM, results);
    perUser.("oldCost_"+record) = cellfun( ...
        @(x) x.angle.(variant).oldCost, results);
    perUser.("candidateCost_"+record) = cellfun( ...
        @(x) x.angle.(variant).candidateCost, results);
    perUser.("predictedReduction_"+record) = cellfun( ...
        @(x) x.angle.(variant).predictedCostReduction, results);
    perUser.("actualReduction_"+record) = cellfun( ...
        @(x) x.angle.(variant).actualCostReduction, results);
    perUser.("accepted_"+record) = cellfun( ...
        @(x) x.angle.(variant).accepted, results);
    perUser.("clipped_"+record) = cellfun( ...
        @(x) x.angle.(variant).clippedToBracket, results);
    perUser.("boundary_"+record) = cellfun( ...
        @(x) x.angle.(variant).boundarySelected, results);
    perUser.("fallbackReason_"+record) = string(cellfun( ...
        @(x) x.angle.(variant).fallbackReason, results, ...
        UniformOutput=false));
    perUser.("qDeltaRangeRaw_"+record) = cellfun( ...
        @(x) x.(variant+"Transport").rawDisplacementM, results);
    perUser.("qDeltaRangeSelected_"+record) = cellfun( ...
        @(x) x.(variant+"Transport").selectedDisplacementM, results);
    perUser.("qTransportSelected_"+record) = cellfun( ...
        @(x) x.(variant+"Transport").selectedSource ...
        == "implicit-transport", results);
    perUser.("contextSeconds_"+record) = cellfun( ...
        @(x) x.(record).contextSeconds, results);
    perUser.("linearizationSeconds_"+record) = cellfun( ...
        @(x) x.(record).fullArrayLinearizationSeconds, results);
    perUser.("safeguardSeconds_"+record) = cellfun( ...
        @(x) x.(record).safeguardSeconds, results);
    perUser.("qTransportSeconds_"+record) = cellfun( ...
        @(x) x.(record).qTransportSeconds, results);
    perUser.("incrementalSeconds_"+record) = cellfun( ...
        @(x) x.(record).incrementalSeconds, results);
end
perUser.jThetaTheta = cellfun( ...
    @(x) x.angle.scalars.jThetaTheta, results);
perUser.jRangeRange = cellfun( ...
    @(x) x.angle.scalars.jRangeRange, results);
perUser.jThetaRange = cellfun( ...
    @(x) x.angle.scalars.jThetaRange, results);
perUser.normalizedCoupling = cellfun( ...
    @(x) x.angle.scalars.normalizedCoupling, results);
perUser.effectiveInformationRatio = cellfun( ...
    @(x) x.angle.scalars.effectiveInformationRatio, results);
perUser.stepDifferenceDeg = cellfun( ...
    @(x) x.angle.stepDifferenceDeg, results);
perUser.rawStepDifferenceDeg = cellfun( ...
    @(x) x.angle.rawStepDifferenceDeg, results);
end

function output = summarizeMethods(perUser)
methods = ["P_A", "C_enhanced", "E_single", "F", ...
    "G_fixed", "G_schur"];
output = table();
for method = methods
    theta = perUser.("theta_"+method);
    rangeM = perUser.("range_"+method);
    runtime = perUser.("runtime_"+method);
    response = perUser.("responseCount_"+method);
    music = perUser.("musicCount_"+method);
    evd = perUser.("evdCount_"+method);
    profiles = perUser.("profilePasses_"+method);
    for snrDb = unique(perUser.snrDb).'
        selected = perUser.snrDb == snrDb;
        angleError = theta(selected)-perUser.truthThetaDeg(selected);
        rangeError = rangeM(selected)-perUser.truthRangeM(selected);
        positionError = positionErrorM(theta(selected), rangeM(selected), ...
            perUser.truthThetaDeg(selected), perUser.truthRangeM(selected));
        output = [output; table(method, snrDb, nnz(selected), ...
            mean(angleError.^2), sqrt(mean(angleError.^2)), ...
            median(abs(angleError)), quantile(abs(angleError), 0.90), ...
            quantile(abs(angleError), 0.95), mean(rangeError.^2), ...
            sqrt(mean(rangeError.^2)), nnz(abs(rangeError) > 1), ...
            sqrt(mean(positionError.^2)), mean(runtime(selected)), ...
            mean(response(selected)), mean(music(selected)), ...
            mean(evd(selected)), mean(profiles(selected), "omitnan"), ...
            'VariableNames', {'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', ...
            'angleMedianAbsoluteErrorDeg', 'angleP90AbsoluteErrorDeg', ...
            'angleP95AbsoluteErrorDeg', 'rangeMseM2', 'rangeRmseM', ...
            'rangeMissOver1mCount', 'positionRmseM', ...
            'meanRuntimeSeconds', 'meanResponseEvaluationCount', ...
            'meanMusicEvaluationCount', 'meanEvdCount', ...
            'meanCompleteProfilePassCount'})]; %#ok<AGROW>
    end
end
end

function output = equalSnrAggregate(summary)
output = table();
for method = unique(summary.method).'
    rows = summary(summary.method == method, :);
    output = [output; table(method, sum(rows.n), ...
        mean(rows.angleMseDeg2), sqrt(mean(rows.angleMseDeg2)), ...
        mean(rows.rangeMseM2), sqrt(mean(rows.rangeMseM2)), ...
        sqrt(mean(rows.positionRmseM.^2)), ...
        mean(rows.meanRuntimeSeconds), ...
        mean(rows.meanResponseEvaluationCount), ...
        mean(rows.meanMusicEvaluationCount), mean(rows.meanEvdCount), ...
        mean(rows.meanCompleteProfilePassCount, "omitnan"), ...
        'VariableNames', {'method', 'n', 'angleMseDeg2', ...
        'angleRmseDeg', 'rangeMseM2', 'rangeRmseM', ...
        'positionRmseM', 'meanRuntimeSeconds', ...
        'meanResponseEvaluationCount', 'meanMusicEvaluationCount', ...
        'meanEvdCount', 'meanCompleteProfilePassCount'})]; %#ok<AGROW>
end
end

function output = pairedComparisonsTable(perUser)
pairs = ["G_schur", "P_A"; "G_schur", "C_enhanced"; ...
    "G_schur", "F"; "G_schur", "G_fixed"];
output = table();
for index = 1:size(pairs, 1)
    output = [output; pairedRows(perUser, ...
        pairs(index, 1), pairs(index, 2))]; %#ok<AGROW>
end
end

function output = pairedRows(perUser, candidate, reference)
output = table();
snrValues = unique(perUser.snrDb).';
candidateMse = zeros(numel(snrValues), 1);
referenceMse = zeros(numel(snrValues), 1);
allDifference = zeros(0, 1);
for index = 1:numel(snrValues)
    selected = perUser.snrDb == snrValues(index);
    candidateError = (perUser.("theta_"+candidate)(selected) ...
        -perUser.truthThetaDeg(selected)).^2;
    referenceError = (perUser.("theta_"+reference)(selected) ...
        -perUser.truthThetaDeg(selected)).^2;
    difference = candidateError-referenceError;
    candidateMse(index) = mean(candidateError);
    referenceMse(index) = mean(referenceError);
    output = [output; comparisonRow(candidate, reference, ...
        "per-SNR", snrValues(index), difference, ...
        candidateMse(index), referenceMse(index))]; %#ok<AGROW>
    allDifference = [allDifference; difference]; %#ok<AGROW>
end
output = [output; comparisonRow(candidate, reference, "equal-SNR", ...
    nan, allDifference, mean(candidateMse), mean(referenceMse))];
end

function row = comparisonRow(candidate, reference, scope, snrDb, ...
    difference, candidateMse, referenceMse)
ratio = candidateMse/referenceMse;
row = table(candidate, reference, scope, snrDb, numel(difference), ...
    candidateMse, referenceMse, ratio, 100*(1-sqrt(ratio)), ...
    mean(difference), nnz(difference < 0), nnz(difference == 0), ...
    nnz(difference > 0), 'VariableNames', {'candidate', 'reference', ...
    'scope', 'snrDb', 'n', 'candidateAngleMseDeg2', ...
    'referenceAngleMseDeg2', 'angleMseRatio', ...
    'angleRmseImprovementPercent', ...
    'meanCandidateMinusReferenceSquaredError', ...
    'winCount', 'tieCount', 'lossCount'});
end

function output = mechanismTable(perUser)
output = perUser(:, ["seed", "trialIndex", "snrDb", ...
    "jThetaTheta", "jRangeRange", "jThetaRange", ...
    "normalizedCoupling", "effectiveInformationRatio", ...
    "rawStepDeg_G_fixed", "rawStepDeg_G_schur", ...
    "selectedStepDeg_G_fixed", "selectedStepDeg_G_schur", ...
    "stepDifferenceDeg", "rawStepDifferenceDeg", ...
    "accepted_G_fixed", "accepted_G_schur", ...
    "clipped_G_fixed", "clipped_G_schur", ...
    "boundary_G_fixed", "boundary_G_schur", ...
    "predictedReduction_G_fixed", "predictedReduction_G_schur", ...
    "actualReduction_G_fixed", "actualReduction_G_schur", ...
    "fallbackReason_G_fixed", "fallbackReason_G_schur"]);
end

function output = summarizeMechanism(perUser)
output = table();
for snrDb = [unique(perUser.snrDb).', nan]
    if isnan(snrDb)
        selected = true(height(perUser), 1);
        scope = "all-SNR";
    else
        selected = perUser.snrDb == snrDb;
        scope = "per-SNR";
    end
    output = [output; table(scope, snrDb, nnz(selected), ...
        mean(perUser.normalizedCoupling(selected)), ...
        median(perUser.normalizedCoupling(selected)), ...
        mean(abs(perUser.normalizedCoupling(selected))), ...
        mean(perUser.effectiveInformationRatio(selected)), ...
        mean(abs(perUser.stepDifferenceDeg(selected))), ...
        finiteCorrelation(perUser.selectedStepDeg_G_fixed(selected), ...
        perUser.selectedStepDeg_G_schur(selected)), ...
        nnz(abs(perUser.stepDifferenceDeg(selected)) > 1e-15), ...
        nnz(perUser.accepted_G_fixed(selected)), ...
        nnz(perUser.accepted_G_schur(selected)), ...
        nnz(perUser.clipped_G_fixed(selected)), ...
        nnz(perUser.clipped_G_schur(selected)), ...
        nnz(perUser.boundary_G_fixed(selected)), ...
        nnz(perUser.boundary_G_schur(selected)), ...
        mean(perUser.predictedReduction_G_schur(selected)), ...
        mean(perUser.actualReduction_G_schur(selected)), ...
        'VariableNames', {'scope', 'snrDb', 'n', ...
        'meanNormalizedCoupling', 'medianNormalizedCoupling', ...
        'meanAbsoluteNormalizedCoupling', ...
        'meanEffectiveInformationRatio', ...
        'meanAbsoluteSchurFixedStepDifferenceDeg', ...
        'fixedSchurStepCorrelation', 'changedStepCount', ...
        'fixedAcceptedCount', 'schurAcceptedCount', ...
        'fixedClippedCount', 'schurClippedCount', ...
        'fixedBoundaryCount', 'schurBoundaryCount', ...
        'meanSchurPredictedCostReduction', ...
        'meanSchurActualCostReduction'})]; %#ok<AGROW>
end
end

function output = rangeTransportTable(perUser)
base = perUser(:, ["seed", "trialIndex", "snrDb"]);
output = [variantRangeRows(base, perUser, "G_fixed"); ...
    variantRangeRows(base, perUser, "G_schur")];
end

function output = variantRangeRows(base, perUser, variant)
output = base;
output.variant = repmat(variant, height(base), 1);
output.arrayDeltaRangeRawM = perUser.("arrayDeltaRangeRaw_"+variant);
output.arrayDeltaRangeSelectedM = ...
    perUser.("arrayDeltaRangeSelected_"+variant);
output.qDeltaRangeRawM = perUser.("qDeltaRangeRaw_"+variant);
output.qDeltaRangeSelectedM = perUser.("qDeltaRangeSelected_"+variant);
output.qTransportSelected = perUser.("qTransportSelected_"+variant);
output.signAgreement = sign(output.arrayDeltaRangeRawM) ...
    == sign(output.qDeltaRangeRawM);
output.absoluteMagnitudeRatioArrayToQ = abs(output.arrayDeltaRangeRawM) ...
    ./max(abs(output.qDeltaRangeRawM), realmin);
end

function output = summarizeRangeTransport(perUser)
output = table();
for variant = ["G_fixed", "G_schur"]
    arrayStep = perUser.("arrayDeltaRangeRaw_"+variant);
    qStep = perUser.("qDeltaRangeRaw_"+variant);
    for snrDb = [unique(perUser.snrDb).', nan]
        if isnan(snrDb)
            selected = true(height(perUser), 1);
            scope = "all-SNR";
        else
            selected = perUser.snrDb == snrDb;
            scope = "per-SNR";
        end
        currentArray = arrayStep(selected);
        currentQ = qStep(selected);
        nonzero = abs(currentQ) > realmin;
        ratios = abs(currentArray(nonzero))./abs(currentQ(nonzero));
        output = [output; table(variant, scope, snrDb, nnz(selected), ...
            finiteCorrelation(currentArray, currentQ), ...
            mean(sign(currentArray) == sign(currentQ)), ...
            median(ratios, "omitnan"), mean(abs(currentArray)), ...
            mean(abs(currentQ)), ...
            nnz(sign(currentArray) ~= sign(currentQ)), ...
            'VariableNames', {'variant', 'scope', 'snrDb', 'n', ...
            'arrayQRangeStepCorrelation', 'signAgreementFraction', ...
            'medianAbsoluteMagnitudeRatioArrayToQ', ...
            'meanAbsoluteArrayStepM', 'meanAbsoluteQStepM', ...
            'signDisagreementCount'})]; %#ok<AGROW>
    end
end
end

function output = runtimeTable(perUser)
base = perUser(:, ["seed", "trialIndex", "snrDb", ...
    "runtime_P_A", "runtime_C_enhanced"]);
output = [variantRuntimeRows(base, perUser, "G_fixed"); ...
    variantRuntimeRows(base, perUser, "G_schur")];
end

function output = variantRuntimeRows(base, perUser, variant)
output = base;
output.variant = repmat(variant, height(base), 1);
output.contextSeconds = perUser.("contextSeconds_"+variant);
output.fullArrayLinearizationSeconds = ...
    perUser.("linearizationSeconds_"+variant);
output.safeguardSeconds = perUser.("safeguardSeconds_"+variant);
output.qTransportSeconds = perUser.("qTransportSeconds_"+variant);
output.incrementalSeconds = perUser.("incrementalSeconds_"+variant);
output.completeRuntimeSeconds = perUser.("runtime_"+variant);
output.runtimeRatioToPA = output.completeRuntimeSeconds./output.runtime_P_A;
output.runtimeRatioToC = output.completeRuntimeSeconds ...
    ./output.runtime_C_enhanced;
end

function output = engineeringGate(summary, aggregate, perUser, protocol, population)
output = table();
for snrDb = unique(summary.snrDb).'
    g = summary(summary.method == "G_schur" ...
        & summary.snrDb == snrDb, :);
    c = summary(summary.method == "C_enhanced" ...
        & summary.snrDb == snrDb, :);
    pa = summary(summary.method == "P_A" & summary.snrDb == snrDb, :);
    output = [output; gateRow(population, "A1", snrDb, ...
        g.angleMseDeg2/c.angleMseDeg2, ...
        protocol.gate.maximumPerSnrAngleMseRatioToC, true, "<=")]; %#ok<AGROW>
    output = [output; gateRow(population, "R1", snrDb, ...
        g.rangeMseM2/c.rangeMseM2, 1, true, "<")]; %#ok<AGROW>
    output = [output; gateRow(population, "R2", snrDb, ...
        g.rangeMseM2/pa.rangeMseM2, ...
        protocol.gate.maximumPerSnrRangeMseRatioToPA, true, "<=")]; %#ok<AGROW>
end
gAggregate = aggregate(aggregate.method == "G_schur", :);
cAggregate = aggregate(aggregate.method == "C_enhanced", :);
output = [output; gateRow(population, "A2", nan, ...
    gAggregate.angleMseDeg2/cAggregate.angleMseDeg2, ...
    protocol.gate.maximumEqualSnrAngleMseRatioToC, true, "<=")];
output = [output; gateRow(population, "C1", nan, ...
    mean(perUser.runtime_G_schur)/mean(perUser.runtime_C_enhanced), ...
    protocol.gate.maximumRuntimeRatioToC, true, "<=")];
profileDeviation = max(abs(perUser.profilePasses_G_schur ...
    -protocol.gate.requiredProfilePasses));
output = [output; gateRow(population, "Profile", nan, ...
    profileDeviation, 0, true, "<=")];
output = [output; gateRow(population, "Runtime-target", nan, ...
    mean(perUser.runtime_G_schur)/mean(perUser.runtime_P_A), ...
    protocol.gate.targetRuntimeRatioToPA, false, "<=")];
end

function row = gateRow(population, gate, snrDb, observed, limit, hard, op)
if op == "<"
    pass = observed < limit;
else
    pass = observed <= limit;
end
row = table(population, gate, snrDb, observed, limit, op, hard, pass, ...
    'VariableNames', {'population', 'gate', 'snrDb', ...
    'observedRatioOrDeviation', 'limit', 'operator', ...
    'hardGate', 'pass'});
end

function value = finiteCorrelation(first, second)
selected = isfinite(first) & isfinite(second);
first = first(selected);
second = second(selected);
if numel(first) < 2 || std(first) == 0 || std(second) == 0
    value = nan;
else
    matrix = corrcoef(first, second);
    value = matrix(1, 2);
end
end

function value = positionErrorM(theta, rangeM, truthTheta, truthRange)
xError = rangeM.*sind(theta)-truthRange.*sind(truthTheta);
yError = rangeM.*cosd(theta)-truthRange.*cosd(truthTheta);
value = hypot(xError, yError);
end

