function protocol = r40SchemeGProtocol()
%R40SCHEMEGPROTOCOL Freeze Scheme G implementation and evidence gates.

protocol.version = "R40-schemeG-full-aperture-range-profiled-v1";
protocol.date = "2026-09-14";
protocol.evidenceRole = "staged-development-calibration-not-independent-final";
protocol.studyLabelDevelopment = ...
    "Development study - not independent final confirmation";
protocol.studyLabelCalibration = ...
    "Calibration study - not independent final confirmation";
protocol.input = struct( ...
    developmentResultSha256= ...
    "935e9bea7bad14fb66986871d6e344eb777b309b8d9b103da6ebfd4260053d89", ...
    eSingleResultSha256= ...
    "400443c8131c41a235233efd8d393e55bf3fc9097e138883f1cfb4e0299fe70d", ...
    calibrationResultSha256= ...
    "20df32a5b235f293e284745bfa6c9ca757dcad13012cb621d7ba17c2c33a5ad3", ...
    calibrationDataDigest= ...
    "39538d66a6724e198d9c569c2f9e24b9185c4d3d979bc4f224724fbf5d50dcc0", ...
    developmentUsers=60, developmentUsersPerSnr=20, ...
    calibrationUsers=600, calibrationUsersPerSnr=200, ...
    snrDb=[-10, 0, 20]);
protocol.system = struct(N=256, M=2048, K=2047, L=160, P=97, ...
    useGram=false, angleGridSizes=[41, 31, 21], ...
    profileHalfWidthM=2, lambda=1);
protocol.model = struct(dataDomain="full-N-raw-array-snapshots", ...
    steering="frozen-Scheme-F-Fresnel", ...
    gainModel="independent-complex-alpha-per-carrier", ...
    cost="normalized-concentrated-residual-energy", ...
    angleUnit="radian", rangeUnit="meter", ...
    primary="Schur-profiled-one-step", control="fixed-range-one-step");
protocol.numerical = struct(informationScaleTolerance=100*eps, ...
    costScaleTolerance=100*eps, thetaIdentityToleranceDeg=1e-12, ...
    rangeIdentityToleranceM=r33.config().validation.rangeToleranceM, ...
    gridIdentityToleranceDeg=1e-12);
protocol.angle = struct(bracket="final-P_A-immediate-neighbors", ...
    optimizer="none-one-analytic-step", lineSearch=false, damping=false, ...
    candidateSafeguard="full-array-cost-at-array-profiled-range");
protocol.range = struct(transportProtocol=r37SingleProfileProtocol(), ...
    completeProfilePasses=1, newCompleteProfilePasses=0, ...
    arrayRangeIsDiagnosticOnly=true);
protocol.gate = struct(maximumPerSnrAngleMseRatioToC=1.00, ...
    maximumEqualSnrAngleMseRatioToC=0.95, ...
    requireRangeMseStrictlyBelowC=true, ...
    maximumPerSnrRangeMseRatioToPA=1.01, ...
    maximumRuntimeRatioToC=1.00, requiredProfilePasses=1, ...
    targetRuntimeRatioToPA=1.05);
protocol.execution = struct(newUsersAllowed=false, ...
    r34FinalAuthorized=false, schemesABDAllowed=false, ...
    parameterGatingAllowed=false, snrAdaptiveSelectorAllowed=false, ...
    alphaShrinkageAllowed=false, learnedSelectorAllowed=false, ...
    bracketExpansionAllowed=false, carrierChangeAllowed=false, ...
    gramAllowed=false, rangeProfileChangeAllowed=false, ...
    alternatingOptimizationAllowed=false, ...
    automaticCalibrationOnlyAfterDevelopmentPass=true, ...
    automaticIndependentConfirmationAllowed=false);
end
