function result = r40SchemeGTrial(cfg, scan, designRow, frozenBaseline, ...
    eSingleReference, rowIndex, r34Protocol, protocol)
%R40SCHEMEGTRIAL Execute one frozen Scheme G row and diagnostic control.

arguments
    cfg (1, 1) struct
    scan (1, 1) struct
    designRow (1, :) table
    frozenBaseline (1, 1) struct
    eSingleReference (1, 1) struct
    rowIndex (1, 1) double {mustBeInteger, mustBePositive}
    r34Protocol (1, 1) struct = r34.config()
    protocol (1, 1) struct = r40SchemeGProtocol()
end

result = failureResult(designRow, rowIndex);
try
    replay = fsjad.replayRound27Data(cfg, scan, designRow);
    [pa, c, runtimeOrder] = executeFrozenBaselines( ...
        cfg, scan, replay, rowIndex, r34Protocol);
    identity = assertFrozenBaselineIdentity( ...
        pa, c, frozenBaseline, protocol);
    finalStage = pa.estimate.stages(end);
    [~, selectedIndex] = min(abs(finalStage.thetaGridDeg-pa.thetaDeg));
    [~, peak] = max(abs(replay.observation).^2);
    carrierIndex = r30.selectLocalCarriers(cfg.numSubcarriers, ...
        r34Protocol.r32.music.carrierCount, peak-1);

    contextTimer = tic;
    context = r38PrepareRawArrayVpmlContext(cfg, ...
        replay.snapshots(:, carrierIndex+1), carrierIndex);
    contextSeconds = toc(contextTimer);
    angle = r40AngleVariants(cfg, context, ...
        finalStage.thetaGridDeg, selectedIndex, pa.rangeM, protocol);

    fixedTransportTimer = tic;
    fixedTransport = r37ImplicitProfileTransport(cfg, scan, ...
        replay.observation, pa.thetaDeg, pa.rangeM, ...
        angle.fixed.thetaDeg, pa.front.selected.rangeM, ...
        protocol.range.transportProtocol);
    fixedTransportSeconds = toc(fixedTransportTimer);
    schurTransportTimer = tic;
    schurTransport = r37ImplicitProfileTransport(cfg, scan, ...
        replay.observation, pa.thetaDeg, pa.rangeM, ...
        angle.schur.thetaDeg, pa.front.selected.rangeM, ...
        protocol.range.transportProtocol);
    schurTransportSeconds = toc(schurTransportTimer);

    paRecord = baselineRecord(pa, 1);
    cRecord = baselineRecord(c, nan);
    fixedRecord = gRecord(paRecord, angle.fixed, fixedTransport, ...
        contextSeconds, fixedTransportSeconds, cfg, context);
    schurRecord = gRecord(paRecord, angle.schur, schurTransport, ...
        contextSeconds, schurTransportSeconds, cfg, context);
    if fixedRecord.completeProfilePassCount ...
            ~= protocol.range.completeProfilePasses ...
            || schurRecord.completeProfilePassCount ...
            ~= protocol.range.completeProfilePasses
        error("r40:CompleteProfilePassViolation", ...
            "Scheme G must use exactly one complete range profile.");
    end

    result.success = true;
    result.runtimeOrder = runtimeOrder;
    result.truthThetaDeg = designRow.truthThetaDeg;
    result.truthRangeM = designRow.truthRangeM;
    result.frontThetaDeg = pa.front.selected.thetaDeg;
    result.frontRangeM = pa.front.selected.rangeM;
    result.P_A = paRecord;
    result.C_enhanced = cRecord;
    result.E_single = eSingleReference;
    result.F = frozenFRecord(frozenBaseline.F_raw_vpml);
    result.G_fixed = fixedRecord;
    result.G_schur = schurRecord;
    result.angle = angle;
    result.fixedTransport = compactTransport(fixedTransport);
    result.schurTransport = compactTransport(schurTransport);
    result.carrierIndex = carrierIndex;
    result.finalGridDeg = finalStage.thetaGridDeg;
    result.selectedGridIndex = selectedIndex;
    result.baselineIdentity = identity;
catch exception
    result.success = false;
    result.errorIdentifier = string(exception.identifier);
    result.errorMessage = string(getReport( ...
        exception, "extended", "hyperlinks", "off"));
end
end

function [pa, c, order] = executeFrozenBaselines( ...
    cfg, scan, replay, rowIndex, protocol)
if mod(rowIndex, 2) == 1
    order = "P_A-then-C_enhanced";
    pa = r34.estimate(cfg, replay.observation, replay.snapshots, ...
        scan, "P_A", protocol);
    c = r34.estimate(cfg, replay.observation, replay.snapshots, ...
        scan, "C_enhanced", protocol);
else
    order = "C_enhanced-then-P_A";
    c = r34.estimate(cfg, replay.observation, replay.snapshots, ...
        scan, "C_enhanced", protocol);
    pa = r34.estimate(cfg, replay.observation, replay.snapshots, ...
        scan, "P_A", protocol);
end
end

function identity = assertFrozenBaselineIdentity(pa, c, frozen, protocol)
thetaPa = abs(pa.thetaDeg-frozen.P_A.thetaDeg);
rangePa = abs(pa.rangeM-frozen.P_A.rangeM);
thetaC = abs(c.thetaDeg-frozen.C_enhanced.thetaDeg);
rangeC = abs(c.rangeM-frozen.C_enhanced.rangeM);
gridDifference = max(abs(pa.estimate.stages(end).thetaGridDeg ...
    -frozen.finalGridDeg));
pass = thetaPa <= protocol.numerical.thetaIdentityToleranceDeg ...
    && rangePa <= protocol.numerical.rangeIdentityToleranceM ...
    && thetaC <= protocol.numerical.thetaIdentityToleranceDeg ...
    && rangeC <= protocol.numerical.rangeIdentityToleranceM ...
    && gridDifference <= protocol.numerical.gridIdentityToleranceDeg;
if ~pass
    error("r40:FrozenBaselineIdentityMismatch", ...
        "Re-executed P_A/C outputs differ from the frozen references.");
end
identity = struct(thetaDifferencePA=thetaPa, rangeDifferencePA=rangePa, ...
    thetaDifferenceC=thetaC, rangeDifferenceC=rangeC, ...
    finalGridMaximumDifferenceDeg=gridDifference, pass=pass);
end

function output = baselineRecord(input, profilePasses)
output = struct(thetaDeg=input.thetaDeg, rangeM=input.rangeM, ...
    runtimeSeconds=input.cost.totalOnlineSeconds, ...
    responseEvaluationCount=responseCount(input), ...
    musicEvaluationCount=input.estimate.evaluationCount, ...
    evdCount=input.cost.directCount, ...
    completeProfilePassCount=profilePasses, ...
    profileEvaluationCount=input.cost.profileResponseCalls);
end

function count = responseCount(input)
count = input.cost.sparseResponseCalls ...
    +input.cost.frontFullResponseCalls+input.cost.profileResponseCalls;
end

function output = gRecord(pa, angle, transport, contextSeconds, ...
    transportSeconds, cfg, context)
incrementalSeconds = contextSeconds+angle.standaloneAngleSeconds ...
    +transportSeconds;
output = struct(thetaDeg=angle.thetaDeg, rangeM=transport.rangeM, ...
    runtimeSeconds=pa.runtimeSeconds+incrementalSeconds, ...
    responseEvaluationCount=pa.responseEvaluationCount ...
    +angle.fullArrayEvaluationCount ...
    +transport.addedResponseEvaluationCount, ...
    musicEvaluationCount=pa.musicEvaluationCount, evdCount=pa.evdCount, ...
    completeProfilePassCount=transport.completeProfilePassCount, ...
    profileEvaluationCount=pa.profileEvaluationCount, ...
    fullArrayEvaluationCount=angle.fullArrayEvaluationCount, ...
    qTransportEvaluationCount=transport.addedResponseEvaluationCount, ...
    contextSeconds=contextSeconds, ...
    fullArrayLinearizationSeconds=angle.linearizationSeconds, ...
    safeguardSeconds=angle.variantSeconds, ...
    qTransportSeconds=transportSeconds, ...
    incrementalSeconds=incrementalSeconds, ...
    estimatedPeakWorkingSetBytes=estimatedWorkingSet(cfg, context), ...
    fullArrayElementCarrierProducts= ...
    angle.fullArrayEvaluationCount*cfg.numAntennas*context.carrierCount);
end

function bytes = estimatedWorkingSet(cfg, context)
complexArrays = 6;
complexScalarsPerCarrier = 3;
bytes = 16*(complexArrays*cfg.numAntennas*context.carrierCount ...
    +complexScalarsPerCarrier*context.carrierCount);
end

function output = frozenFRecord(input)
output = input;
if isfield(input, "profilePassCount")
    output.completeProfilePassCount = input.profilePassCount;
else
    output.completeProfilePassCount = 2;
end
end

function output = compactTransport(input)
output = struct(version=input.version, thetaDeg=input.thetaDeg, ...
    rangeBaseM=input.rangeBaseM, rangeM=input.rangeM, ...
    rawDisplacementM=input.rawDisplacementM, ...
    selectedDisplacementM=input.selectedDisplacementM, ...
    rangeGradient=input.rangeGradient, ...
    rangeCurvature=input.rangeCurvature, ...
    mixedCurvature=input.mixedCurvature, ...
    validTransport=input.validTransport, ...
    clippedToBounds=input.clippedToBounds, endpointHit=input.endpointHit, ...
    scoreGain=input.scoreGain, selectedSource=input.selectedSource, ...
    status=input.status, ...
    completeProfilePassCount=input.completeProfilePassCount, ...
    newCompleteProfilePassCount=input.newCompleteProfilePassCount, ...
    addedResponseEvaluationCount=input.addedResponseEvaluationCount);
end

function result = failureResult(row, rowIndex)
result = struct(success=false, rowIndex=rowIndex, seed=row.seed, ...
    trialIndex=row.trialIndex, snrDb=row.snrDb, ...
    truthThetaDeg=row.truthThetaDeg, truthRangeM=row.truthRangeM, ...
    errorIdentifier="", errorMessage="");
end

