function report = r35AssertCommonProtocol(cfg, protocol)
%R35ASSERTCOMMONPROTOCOL Reject drift before any R35 angle study.

arguments
    cfg (1, 1) struct = jad.defaultConfig()
    protocol (1, 1) struct = r35CommonProtocol()
end

expected = r35CommonProtocol();
if ~isequaln(protocol, expected)
    error("r35:CommonProtocolDrift", ...
        "The R35 common protocol differs from its frozen identity.");
end

r34Protocol = r34.config();
r32.assertFrozenConfig(cfg, r34Protocol.r32);
assertInheritedAlgorithm(r34Protocol, protocol);

matlabRoot = string(fileparts(fileparts(fileparts( ...
    mfilename("fullpath")))));
sourceDigest = r32.sourceDigest(r34.manifest(matlabRoot));
if sourceDigest ~= protocol.frozenSource.sourceDigest
    error("r35:FrozenSourceDrift", ...
        "R34/R33/R32 or an inherited frozen source has changed.");
end

report = struct( ...
    passed=true, protocolVersion=protocol.version, ...
    frozenSourceDigest=sourceDigest, ...
    finalDesignHash=r34Protocol.finalTest.designHash, ...
    estimatorVersion=r34Protocol.estimatorVersion, ...
    evidenceRole=protocol.execution.stage, ...
    estimationExecuted=false);
end

function assertInheritedAlgorithm(r34Protocol, protocol)
r32Protocol = r34Protocol.r32;
identityPass = ...
    r34Protocol.finalTest.expectedRows == protocol.data.r34FinalTrialCount ...
    && r34Protocol.finalTest.designHash ...
    == protocol.frozenSource.finalDesignHash ...
    && r34Protocol.estimatorVersion ...
    == "R33-A-q-only-invariants-direct-EVD-v1" ...
    && r34Protocol.implementation.useFastResponse ...
    && ~r34Protocol.implementation.useGram ...
    && r34Protocol.implementation.subspaceSolver ...
    == protocol.algorithm.subspaceSolver ...
    && ismember("P_A", r34Protocol.implementation.methods) ...
    && ismember("C_enhanced", r34Protocol.implementation.methods) ...
    && r32Protocol.front.candidateId == protocol.algorithm.front ...
    && r32Protocol.music.carrierCount == protocol.system.K ...
    && r32Protocol.music.subarraySize == protocol.system.L ...
    && r32Protocol.music.numSubarrays == protocol.system.P ...
    && r32Protocol.music.angleHalfWidthDeg ...
    == protocol.algorithm.angleHalfWidthDeg ...
    && isequal(r32Protocol.music.gridSizes, ...
    protocol.algorithm.angleGridSizes) ...
    && r32Protocol.profile.halfWidthM == protocol.rangeProfile.halfWidthM ...
    && r32Protocol.profile.lambda == protocol.rangeProfile.lambda ...
    && isequal(r32Protocol.enhancedC.gridSizes, ...
    protocol.algorithm.angleGridSizes);
if ~identityPass
    error("r35:InheritedAlgorithmDrift", ...
        "The frozen P_A or C_enhanced identity no longer matches R35.");
end
end
