function protocol = r35CommonProtocol()
%R35COMMONPROTOCOL Frozen policy for isolated angle-improvement research.

protocol.version = "R35-angle-improvement-common-protocol-v1";
protocol.date = "2026-09-12";
protocol.execution = struct( ...
    stage="development-calibration-evidence-only", ...
    independentFinalValidation=false, ...
    newEstimationExperimentsAuthorized=false);

protocol.frozenSource = struct( ...
    packages=["r34", "r33", "r32"], ...
    readOnly=true, overwriteAllowed=false, ...
    sourceDigest= ...
    "2d40cca46c84cccd580ba8bfc48d1b2bc74dfc4390920f17c80f00428f0a9684", ...
    finalDesignHash= ...
    "e1f6cc945644e88806432a52d2b6e18d0df026024c279790c9bf26edb9792cd6");

protocol.data = struct( ...
    r34FinalTrialCount=1400, ...
    r34FinalReuseAllowed=false, ...
    existingDevelopmentUsers=60, ...
    generateNewDevelopmentUsers=false, ...
    calibrationRequiresSingleSchemeEngineeringPass=true, ...
    existingCalibrationUsersMaximum=600, ...
    generateNewCalibrationUsers=false);

protocol.system = struct(N=256, M=2048, K=2047, L=160, P=97, ...
    thetaLimitsDeg=[-60, 60], rangeLimitsM=[15, 50]);
protocol.algorithm = struct( ...
    front="L06", response="q-only", ...
    subspaceSolver="direct-covariance-eig", useGram=false, ...
    angleHalfWidthDeg=0.2, angleGridSizes=[41, 31, 21]);
protocol.rangeProfile = struct( ...
    kind="frozen-conditional-full-spectrum-profile", ...
    center="frozen-L06-front-range", halfWidthM=2, lambda=1, ...
    rerunAfterAnyNewAngle=true, reusePaRangeForNewAngle=false);
protocol.baselines = struct( ...
    P_A=struct(frozen=true, mutable=false), ...
    C_enhanced=struct(frozen=true, mutable=false));

protocol.outputs = [ ...
    "angle_rmse", "angle_mse", "angle_absolute_error_median", ...
    "angle_absolute_error_p95", ...
    "paired_angle_squared_error_difference_candidate_minus_PA", ...
    "angle_win_tie_loss", "range_rmse_after_frozen_profile", ...
    "position_rmse", "complete_online_runtime", ...
    "response_evaluation_count", "music_evaluation_count"];
protocol.pairing = struct( ...
    squaredErrorDifference="candidate-minus-P_A", ...
    win="difference<0", tie="difference==0", loss="difference>0");

protocol.engineeringGate = struct( ...
    maximumPerSnrAngleMseRatioToPA=1.01, ...
    maximumEqualSnrAggregateAngleMseRatioToPA=0.98, ...
    minimumEqualSnrAggregateAngleMseImprovement=0.02, ...
    maximumPerSnrRangeMseRatioToPA=1.02, ...
    maximumRuntimeRatioToCEnhanced=1.00, ...
    aggregateWeighting="equal-SNR", allConditionsRequired=true);

protocol.prohibited = [ ...
    "alpha", "Gram", "reduced-carrier-mainline", "H/P-gating", ...
    "ML-weighting", "new-users", "R34-final-reuse", ...
    "posthoc-parameter-or-threshold-relaxation"];
end
