function report = r38AssertSchemeFCalibration(project, setup, protocol)
%R38ASSERTSCHEMEFCALIBRATION Verify frozen F, data and references.

arguments
    project (1, 1) string
    setup (1, 1) struct
    protocol (1, 1) struct = r38SchemeFCalibrationProtocol()
end

if ~isequaln(protocol, r38SchemeFCalibrationProtocol())
    error("r38:CalibrationProtocolDrift", ...
        "The Scheme F calibration protocol has changed.");
end
algorithmSource = frozenAlgorithmManifest(project);
algorithmDigest = r32.sourceDigest(algorithmSource);
if algorithmDigest ~= protocol.algorithmDigest
    error("r38:FrozenSchemeFAlgorithmDrift", ...
        "The development-passed Scheme F algorithm has changed.");
end

developmentFolder = fullfile(project, "results", "full_spectrum", ...
    "round38_schemeF_raw_array_vpml_development_v1");
files = ["result.mat", "per_user_outputs.csv", "engineering_gate.csv"];
expected = [protocol.development.resultSha256, ...
    protocol.development.perUserSha256, protocol.development.gateSha256];
for index = 1:numel(files)
    if hashFile(project, fullfile(developmentFolder, files(index))) ...
            ~= expected(index)
        error("r38:DevelopmentEvidenceDrift", ...
            "A frozen Scheme F development artifact has changed.");
    end
end
development = load(fullfile(developmentFolder, "result.mat"), ...
    "identity", "design", "results", "summary");
if ~development.identity.gatePassed ...
        || ~development.summary.gatePassed ...
        || height(development.design) ~= protocol.development.requiredUsers
    error("r38:DevelopmentGateNotSatisfied", ...
        "Scheme F calibration requires the passed 60-user result.");
end

r36File = fullfile(project, "results", "full_spectrum", ...
    "round36_schemeE_calibration600_v1", "result.mat");
r37File = fullfile(project, "results", "full_spectrum", ...
    "round37_schemeE_single_profile_transport_v1", "result.mat");
if hashFile(project, r36File) ~= protocol.calibration.r36ResultSha256 ...
        || hashFile(project, r37File) ...
        ~= protocol.calibration.r37ResultSha256
    error("r38:CalibrationReferenceDrift", ...
        "A frozen calibration reference has changed.");
end
r36Calibration = load(r36File, "identity", "design", "results");
r37Calibration = load(r37File, "identity", "design", "summary");
counts = groupcounts(setup.design, "snrDb");
dataDigest = setup.dataHash.sha256(1);
designPass = height(setup.design) == protocol.calibration.allUsers ...
    && numel(unique(setup.design.seed)) == protocol.calibration.allUsers ...
    && isequal(sort(counts.snrDb).', sort(protocol.calibration.snrDb)) ...
    && all(counts.GroupCount == protocol.calibration.usersPerSnr) ...
    && dataDigest == protocol.calibration.dataHash ...
    && isequaln(setup.design, r36Calibration.design) ...
    && isequaln(setup.design, r37Calibration.design) ...
    && r36Calibration.identity.finalTrialsExecuted == 0 ...
    && r36Calibration.identity.newUsersGenerated == 0 ...
    && r37Calibration.identity.r34FinalTrialsExecuted == 0 ...
    && r37Calibration.identity.newUsersGenerated == 0;
if ~designPass
    error("r38:CalibrationDesignMismatch", ...
        "The existing calibration-600 identity does not match.");
end
developmentMask = ismember(setup.design.seed, development.design.seed);
holdoutMask = ~developmentMask;
holdoutCounts = groupcounts(setup.design(holdoutMask, :), "snrDb");
if nnz(developmentMask) ~= protocol.development.requiredUsers ...
        || nnz(holdoutMask) ~= protocol.calibration.holdoutUsers ...
        || any(holdoutCounts.GroupCount ...
        ~= protocol.calibration.holdoutUsersPerSnr)
    error("r38:CalibrationPartitionMismatch", ...
        "The fixed 60/540 calibration partition is invalid.");
end
report = struct(passed=true, algorithmSource=algorithmSource, ...
    algorithmDigest=algorithmDigest, development=development, ...
    r36Calibration=r36Calibration, r37Calibration=r37Calibration, ...
    developmentMask=developmentMask, holdoutMask=holdoutMask, ...
    dataDigest=dataDigest, allRows=height(setup.design), ...
    holdoutRows=nnz(holdoutMask), estimationExecuted=false);
end

function source = frozenAlgorithmManifest(project)
paths = ["+r38/common/r38CommonProtocol.m"; ...
    "+r38/schemeF/r38SchemeFConfig.m"; ...
    "+r38/schemeF/r38PrepareRawArrayVpmlContext.m"; ...
    "+r38/schemeF/r38RawArrayVpmlScore.m"; ...
    "+r38/schemeF/r38BracketedVpmlRefinement.m"; ...
    "+r38/schemeF/r38SchemeFTrial.m"];
source = fsjad.sourceHashManifest(project, paths);
end

function digest = hashFile(project, file)
if ~isfile(file)
    error("r38:MissingCalibrationInput", ...
        "A required frozen calibration input is missing.");
end
relative = replace(extractAfter(file, strlength(project)+1), ...
    string(filesep), "/");
manifest = fsjad.sourceHashManifest(project, relative);
digest = manifest.sha256(1);
end
