function output = r38SummarizeSchemeFCalibration(design, results, ...
    r37PerUser, developmentMask, developmentResults, commonProtocol, protocol)
%R38SUMMARIZESCHEMEFCALIBRATION Summarize all-600 and holdout-540.

arguments
    design table
    results cell
    r37PerUser table
    developmentMask (:, 1) logical
    developmentResults cell
    commonProtocol (1, 1) struct = r38CommonProtocol()
    protocol (1, 1) struct = r38SchemeFCalibrationProtocol()
end

if numel(results) ~= height(design) || any(cellfun(@isempty, results)) ...
        || any(cellfun(@(x) ~x.success, results)) ...
        || nnz(developmentMask) ~= protocol.development.requiredUsers ...
        || nnz(~developmentMask) ~= protocol.calibration.holdoutUsers
    error("r38:IncompleteSchemeFCalibration", ...
        "Scheme F calibration requires every fixed row and partition.");
end
base = r38SummarizeSchemeF(design, results, commonProtocol);
perUser = attachSingleProfile(base.perUser, r37PerUser, results);
perUser.subset = repmat("holdout540", height(perUser), 1);
perUser.subset(developmentMask) = "development-overlap60";
all600 = populationSummary(perUser, protocol, "all600");
holdout540 = populationSummary( ...
    perUser(~developmentMask, :), protocol, "holdout540");
overlap60 = populationSummary( ...
    perUser(developmentMask, :), protocol, "development-overlap60");
reproduction = reproductionAudit( ...
    design, results, developmentMask, developmentResults, protocol);
gate = [all600.gate; holdout540.gate];
reproductionPassed = all(reproduction.pass);
decision = table(all(all600.gate.pass), all(holdout540.gate.pass), ...
    reproductionPassed, all(gate.pass) && reproductionPassed, ...
    'VariableNames', {'all600GatePassed', 'holdout540GatePassed', ...
    'developmentReproductionPassed', 'calibrationReady'});
output = struct(version="R38-schemeF-calibration600-summary-v1", ...
    dataRole=protocol.evidenceRole, perUser=perUser, all600=all600, ...
    holdout540=holdout540, developmentOverlap60=overlap60, ...
    reproduction=reproduction, gate=gate, decision=decision, ...
    calibrationReady=decision.calibrationReady);
end

function perUser = attachSingleProfile(base, r37, results)
if height(base) ~= height(r37) || ~isequal(base.seed, r37.seed)
    error("r38:SingleProfilePairingMismatch", ...
        "R37 E single-profile rows do not match Scheme F calibration.");
end
perUser = base;
perUser.theta_E_single = r37.theta_E_single;
perUser.range_E_single = r37.range_E_single;
perUser.runtime_E_single = r37.runtime_E_single;
perUser.responseCount_E_single = r37.responseCount_E_single;
perUser.musicCount_E_single = r37.musicCount_E_single;
perUser.evdCount_E_single = r37.evdCount_E_single;
perUser.profilePasses_P_A = r37.profilePasses_P_A;
perUser.profilePasses_E_reference = r37.profilePasses_E_full;
perUser.profilePasses_E_single = r37.profilePasses_E_single;
perUser.profilePasses_F_raw_vpml = 2*ones(height(base), 1);
perUser.profileEvaluations_E_reference = ...
    r37.profileEvaluations_E_full;
perUser.profileEvaluations_E_single = ...
    r37.profileEvaluations_E_single;
perUser.profileEvaluations_F_raw_vpml = cellfun( ...
    @(x) x.F_raw_vpml.profileEvaluationCount, results);
end

function output = populationSummary(perUser, protocol, population)
methodSummary = summarizeMethods(perUser);
comparisons = [pairedAngle(perUser, "F_raw_vpml", "P_A"); ...
    pairedAngle(perUser, "F_raw_vpml", "E_single")];
tradeoff = summarizeTradeoff(perUser);
diagnostics = summarizeDiagnostics(perUser);
gate = engineeringGate(methodSummary, protocol, population);
output = struct(population=population, perUser=perUser, ...
    methodSummary=methodSummary, comparisons=comparisons, ...
    tradeoff=tradeoff, diagnostics=diagnostics, gate=gate, ...
    gatePassed=all(gate.pass));
end

function output = summarizeMethods(perUser)
methods = ["P_A", "E_reference", "E_single", ...
    "F_raw_vpml", "C_enhanced"];
output = table();
for method = methods
    [theta, rangeM, runtime, response, music, evd, passes, evals] = ...
        methodColumns(perUser, method);
    for snrDb = unique(perUser.snrDb).'
        selected = perUser.snrDb == snrDb;
        angleError = theta(selected)-perUser.truthThetaDeg(selected);
        rangeError = rangeM(selected)-perUser.truthRangeM(selected);
        positionError = positionErrorM(theta(selected), rangeM(selected), ...
            perUser.truthThetaDeg(selected), perUser.truthRangeM(selected));
        angleSquared = angleError.^2;
        rangeSquared = rangeError.^2;
        entry = table(method, snrDb, nnz(selected), mean(angleSquared), ...
            sqrt(mean(angleSquared)), median(abs(angleError)), ...
            quantile(abs(angleError), 0.90), ...
            quantile(abs(angleError), 0.95), mean(rangeSquared), ...
            sqrt(mean(rangeSquared)), sqrt(mean(positionError.^2)), ...
            mean(runtime(selected)), mean(response(selected)), ...
            mean(music(selected)), mean(evd(selected)), ...
            mean(passes(selected), "omitnan"), ...
            mean(evals(selected), "omitnan"), ...
            'VariableNames', {'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', ...
            'angleMedianAbsoluteErrorDeg', 'angleP90AbsoluteErrorDeg', ...
            'angleP95AbsoluteErrorDeg', 'rangeMseM2', 'rangeRmseM', ...
            'positionRmseM', 'meanRuntimeSeconds', ...
            'meanResponseEvaluationCount', 'meanMusicEvaluationCount', ...
            'meanEvdCount', 'meanCompleteProfilePassCount', ...
            'meanProfileEvaluationCount'});
        output = [output; entry]; %#ok<AGROW>
    end
end
end

function [theta, rangeM, runtime, response, music, evd, passes, evals] = ...
    methodColumns(input, method)
if method == "P_A"
    name = "P_A";
elseif method == "E_reference"
    name = "E_reference";
elseif method == "E_single"
    name = "E_single";
elseif method == "F_raw_vpml"
    name = "F_raw_vpml";
else
    name = "C_enhanced";
end
theta = input.("theta_"+name);
rangeM = input.("range_"+name);
runtime = input.("runtime_"+name);
response = input.("responseCount_"+name);
music = input.("musicCount_"+name);
evd = input.("evdCount_"+name);
if method == "C_enhanced"
    passes = nan(height(input), 1);
    evals = nan(height(input), 1);
else
    passes = input.("profilePasses_"+name);
    evals = input.("profileEvaluations_"+name);
end
end

function output = pairedAngle(perUser, candidate, reference)
[candidateTheta, ~, ~, ~, ~, ~, ~, ~] = ...
    methodColumns(perUser, candidate);
[referenceTheta, ~, ~, ~, ~, ~, ~, ~] = ...
    methodColumns(perUser, reference);
output = table();
snrValues = unique(perUser.snrDb).';
candidateMse = zeros(numel(snrValues), 1);
referenceMse = zeros(numel(snrValues), 1);
allDifference = zeros(0, 1);
for index = 1:numel(snrValues)
    selected = perUser.snrDb == snrValues(index);
    candidateSquared = (candidateTheta(selected) ...
        -perUser.truthThetaDeg(selected)).^2;
    referenceSquared = (referenceTheta(selected) ...
        -perUser.truthThetaDeg(selected)).^2;
    difference = candidateSquared-referenceSquared;
    candidateMse(index) = mean(candidateSquared);
    referenceMse(index) = mean(referenceSquared);
    output = [output; comparisonRow(candidate, reference, "per-SNR", ...
        snrValues(index), difference, candidateMse(index), ...
        referenceMse(index))]; %#ok<AGROW>
    allDifference = [allDifference; difference]; %#ok<AGROW>
end
output = [output; comparisonRow(candidate, reference, "equal-SNR", ...
    nan, allDifference, mean(candidateMse), mean(referenceMse))];
end

function row = comparisonRow(candidate, reference, scope, snrDb, ...
    difference, candidateMse, referenceMse)
ratio = candidateMse/referenceMse;
row = table(candidate, reference, scope, snrDb, numel(difference), ...
    candidateMse, referenceMse, ratio, 100*(1-sqrt(ratio)), ...
    mean(difference), nnz(difference < 0), nnz(difference == 0), ...
    nnz(difference > 0), 'VariableNames', {'candidate', 'reference', ...
    'scope', 'snrDb', 'n', 'candidateAngleMseDeg2', ...
    'referenceAngleMseDeg2', 'angleMseRatio', ...
    'angleRmseImprovementPercent', ...
    'meanCandidateMinusReferenceSquaredError', 'winCount', ...
    'tieCount', 'lossCount'});
end

function output = summarizeTradeoff(perUser)
output = table();
snrValues = [unique(perUser.snrDb).', nan];
for snrDb = snrValues
    if isnan(snrDb)
        selected = true(height(perUser), 1);
        scope = "all-SNR-pooled";
    else
        selected = perUser.snrDb == snrDb;
        scope = "per-SNR";
    end
    fAngle = mean((perUser.theta_F_raw_vpml(selected) ...
        -perUser.truthThetaDeg(selected)).^2);
    eAngle = mean((perUser.theta_E_single(selected) ...
        -perUser.truthThetaDeg(selected)).^2);
    fRange = mean((perUser.range_F_raw_vpml(selected) ...
        -perUser.truthRangeM(selected)).^2);
    eRange = mean((perUser.range_E_single(selected) ...
        -perUser.truthRangeM(selected)).^2);
    fPosition = mean(positionErrorM( ...
        perUser.theta_F_raw_vpml(selected), ...
        perUser.range_F_raw_vpml(selected), ...
        perUser.truthThetaDeg(selected), ...
        perUser.truthRangeM(selected)).^2);
    ePosition = mean(positionErrorM(perUser.theta_E_single(selected), ...
        perUser.range_E_single(selected), ...
        perUser.truthThetaDeg(selected), ...
        perUser.truthRangeM(selected)).^2);
    output = [output; table(scope, snrDb, nnz(selected), ...
        fAngle/eAngle, fRange/eRange, fPosition/ePosition, ...
        mean(perUser.runtime_F_raw_vpml(selected)) ...
        /mean(perUser.runtime_E_single(selected)), ...
        mean(perUser.responseCount_F_raw_vpml(selected)) ...
        /mean(perUser.responseCount_E_single(selected)), ...
        'VariableNames', {'scope', 'snrDb', 'n', ...
        'FToESingleAngleMseRatio', 'FToESingleRangeMseRatio', ...
        'FToESinglePositionMseRatio', 'FToESingleRuntimeRatio', ...
        'FToESingleResponseRatio'})]; %#ok<AGROW>
end
end

function output = summarizeDiagnostics(perUser)
output = table();
snrValues = [unique(perUser.snrDb).', nan];
for snrDb = snrValues
    if isnan(snrDb)
        selected = true(height(perUser), 1);
        scope = "all-SNR";
    else
        selected = perUser.snrDb == snrDb;
        scope = "per-SNR";
    end
    truthGain = perUser.truthSquaredErrorGainDeg2(selected);
    scoreGain = perUser.scoreGain(selected);
    output = [output; table(scope, snrDb, nnz(selected), ...
        nnz(perUser.optimizerConverged(selected)), ...
        nnz(perUser.bracketEndpointSelected(selected)), ...
        mean(abs(perUser.angleDisplacementDeg(selected))), ...
        max(abs(perUser.angleDisplacementDeg(selected))), ...
        mean(scoreGain), nnz(scoreGain > 0), ...
        nnz(truthGain > 0), nnz(truthGain == 0), nnz(truthGain < 0), ...
        finiteCorrelation(scoreGain, truthGain), ...
        mean(perUser.vpmlFunctionEvaluations(selected)), ...
        mean(perUser.vpmlSeconds(selected)), ...
        mean(perUser.refreshedProfileSeconds(selected)), ...
        'VariableNames', {'scope', 'snrDb', 'n', ...
        'optimizerConvergedCount', 'bracketEndpointSelectedCount', ...
        'meanAbsoluteAngleDisplacementDeg', ...
        'maximumAbsoluteAngleDisplacementDeg', 'meanVpmlScoreGain', ...
        'positiveVpmlScoreGainCount', 'truthImproveCount', ...
        'truthTieCount', 'truthWorseCount', ...
        'scoreTruthGainCorrelation', 'meanVpmlFunctionEvaluations', ...
        'meanVpmlSeconds', 'meanRefreshedProfileSeconds'})]; %#ok<AGROW>
end
end

function gate = engineeringGate(summary, protocol, population)
gate = table();
for snrDb = unique(summary.snrDb).'
    pa = summary(summary.method == "P_A" & summary.snrDb == snrDb, :);
    f = summary(summary.method == "F_raw_vpml" ...
        & summary.snrDb == snrDb, :);
    gate = [gate; gateRow(population, "angle", ...
        "per-SNR-angle-MSE", snrDb, f.angleMseDeg2/pa.angleMseDeg2, ...
        protocol.gate.maximumPerSnrAngleMseRatio)]; %#ok<AGROW>
end
pa = summary(summary.method == "P_A", :);
f = summary(summary.method == "F_raw_vpml", :);
gate = [gate; gateRow(population, "angle", ...
    "equal-SNR-aggregate-angle-MSE", nan, ...
    mean(f.angleMseDeg2)/mean(pa.angleMseDeg2), ...
    protocol.gate.maximumEqualSnrAngleMseRatio)];
for snrDb = unique(summary.snrDb).'
    paRow = pa(pa.snrDb == snrDb, :);
    fRow = f(f.snrDb == snrDb, :);
    gate = [gate; gateRow(population, "range", ...
        "per-SNR-range-MSE", snrDb, ...
        fRow.rangeMseM2/paRow.rangeMseM2, ...
        protocol.gate.maximumPerSnrRangeMseRatio)]; %#ok<AGROW>
end
c = summary(summary.method == "C_enhanced", :);
gate = [gate; gateRow(population, "runtime", "mean-runtime", nan, ...
    mean(f.meanRuntimeSeconds)/mean(c.meanRuntimeSeconds), ...
    protocol.gate.maximumRuntimeRatioToCEnhanced)];
end

function row = gateRow(population, category, name, snrDb, observed, limit)
row = table(population, category, name, snrDb, observed, limit, ...
    observed <= limit, 'VariableNames', {'population', 'category', ...
    'gate', 'snrDb', 'observedRatio', 'maximumAllowedRatio', 'pass'});
end

function output = reproductionAudit( ...
    design, results, mask, developmentResults, protocol)
[found, locations] = ismember(design.seed(mask), ...
    cellfun(@(x) x.seed, developmentResults));
if ~all(found)
    error("r38:DevelopmentReproductionPairing", ...
        "The fixed development rows cannot be paired.");
end
current = results(mask);
reference = developmentResults(locations);
thetaDifference = cellfun(@(a, b) abs(a.F_raw_vpml.thetaDeg ...
    -b.F_raw_vpml.thetaDeg), current, reference);
rangeDifference = cellfun(@(a, b) abs(a.F_raw_vpml.rangeM ...
    -b.F_raw_vpml.rangeM), current, reference);
scoreDifference = cellfun(@scoreDifferenceOne, current, reference);
countDifference = cellfun(@(a, b) abs( ...
    a.refinement.functionEvaluations ...
    -b.refinement.functionEvaluations), current, reference);
sourceMismatch = cellfun(@(a, b) a.refinement.selectedSource ...
    ~= b.refinement.selectedSource, current, reference);
names = ["theta"; "range"; "score"; "function-count"; ...
    "selected-source"];
observed = [max(thetaDifference); max(rangeDifference); ...
    max(scoreDifference); max(countDifference); nnz(sourceMismatch)];
limit = [protocol.reproduction.thetaToleranceDeg; ...
    protocol.reproduction.rangeToleranceM; ...
    protocol.reproduction.scoreTolerance; ...
    protocol.reproduction.functionCountTolerance; 0];
output = table(names, observed, limit, observed <= limit, ...
    'VariableNames', {'identity', 'observedMaximumDifference', ...
    'maximumAllowedDifference', 'pass'});
end

function value = scoreDifferenceOne(first, second)
before = first.refinement.scoreBefore-second.refinement.scoreBefore;
after = first.refinement.scoreAfter-second.refinement.scoreAfter;
value = max(abs([before, after]));
end

function value = finiteCorrelation(first, second)
if std(first) == 0 || std(second) == 0
    value = nan;
else
    matrix = corrcoef(first, second);
    value = matrix(1, 2);
end
end

function value = positionErrorM(theta, rangeM, truthTheta, truthRange)
xError = rangeM.*sind(theta)-truthRange.*sind(truthTheta);
yError = rangeM.*cosd(theta)-truthRange.*cosd(truthTheta);
value = hypot(xError, yError);
end
