function output = r35SummarizeSchemeBRefresh( ...
    design, primaryResults, refreshResults, commonProtocol)
%R35SUMMARIZESCHEMEBREFRESH Summarize the one allowed range refresh.

arguments
    design table
    primaryResults cell
    refreshResults cell
    commonProtocol (1, 1) struct = r35CommonProtocol()
end

if any(cellfun(@isempty, refreshResults)) ...
        || any(cellfun(@(item) ~item.success, refreshResults))
    error("r35:IncompleteSchemeBRangeRefresh", ...
        "Every allowed Scheme B range refresh must complete.");
end

paRange = cellfun(@(x) x.P_A.rangeM, primaryResults);
bRange = cellfun(@(x) x.rangeM, refreshResults);
theta = cellfun(@(x) x.thetaDeg, refreshResults);
paTheta = cellfun(@(x) x.P_A.thetaDeg, primaryResults);
paPosition = positionError(paTheta, paRange, design);
bPosition = positionError(theta, bRange, design);
perUser = table(design.seed, design.trialIndex, design.snrDb, ...
    design.truthThetaDeg, design.truthRangeM, theta, paRange, bRange, ...
    paRange-design.truthRangeM, bRange-design.truthRangeM, ...
    paPosition, bPosition, ...
    cellfun(@(x) x.profileEvaluationCount, refreshResults), ...
    cellfun(@(x) x.profileSeconds, refreshResults), ...
    cellfun(@(x) x.completeRuntimeSeconds, refreshResults), ...
    'VariableNames', {'seed', 'trialIndex', 'snrDb', ...
    'truthThetaDeg', 'truthRangeM', 'theta_B', 'range_P_A', ...
    'range_B_refresh', 'rangeError_P_A', 'rangeError_B_refresh', ...
    'positionError_P_A', 'positionError_B_refresh', ...
    'profileEvaluationCount', 'profileSeconds', ...
    'completeRuntimeSeconds'});

summary = table();
gate = table();
for snrDb = unique(design.snrDb).'
    selected = design.snrDb == snrDb;
    paMse = mean(perUser.rangeError_P_A(selected).^2);
    bMse = mean(perUser.rangeError_B_refresh(selected).^2);
    entry = table(snrDb, nnz(selected), paMse, bMse, ...
        sqrt(paMse), sqrt(bMse), ...
        sqrt(mean(perUser.positionError_P_A(selected).^2)), ...
        sqrt(mean(perUser.positionError_B_refresh(selected).^2)), ...
        mean(perUser.profileEvaluationCount(selected)), ...
        mean(perUser.profileSeconds(selected)), ...
        'VariableNames', {'snrDb', 'n', 'rangeMse_P_A', ...
        'rangeMse_B_refresh', 'rangeRmse_P_A', 'rangeRmse_B_refresh', ...
        'positionRmse_P_A', 'positionRmse_B_refresh', ...
        'meanProfileEvaluationCount', 'meanProfileSeconds'});
    summary = [summary; entry]; %#ok<AGROW>
    ratio = bMse/paMse;
    gate = [gate; table(snrDb, ratio, ...
        commonProtocol.engineeringGate.maximumPerSnrRangeMseRatioToPA, ...
        ratio <= commonProtocol.engineeringGate.maximumPerSnrRangeMseRatioToPA, ...
        'VariableNames', {'snrDb', 'observedRatio', ...
        'maximumAllowedRatio', 'pass'})]; %#ok<AGROW>
end
output = struct(perUser=perUser, summary=summary, gate=gate, ...
    gatePassed=all(gate.pass));
end

function errorM = positionError(theta, range, design)
xError = range.*sind(theta) ...
    -design.truthRangeM.*sind(design.truthThetaDeg);
yError = range.*cosd(theta) ...
    -design.truthRangeM.*cosd(design.truthThetaDeg);
errorM = hypot(xError, yError);
end
