function output = r35SummarizeSchemeB( ...
    design, results, schemeAReadOnly, commonProtocol)
%R35SUMMARIZESCHEMEB Apply frozen angle metrics and gates.

arguments
    design table
    results cell
    schemeAReadOnly table
    commonProtocol (1, 1) struct = r35CommonProtocol()
end

if numel(results) ~= height(design) || any(cellfun(@isempty, results))
    error("r35:IncompleteSchemeBResults", ...
        "Scheme B requires all 60 frozen development rows.");
end
if any(cellfun(@(item) ~item.success, results))
    error("r35:SchemeBPrimaryTrialFailure", ...
        "At least one Scheme B primary row failed.");
end

schemeA = alignSchemeA(design, results, schemeAReadOnly);
perUser = buildPerUser(design, results, schemeA);
methodRows = buildMethodRows(perUser);
summary = summarizeMethods(methodRows, perUser);
comparisons = [pairedRows(methodRows, "B_primary", "P_A"); ...
    pairedRows(methodRows, "B_primary", "C_enhanced"); ...
    pairedRows(methodRows, "C_FS_angle_control", "C_enhanced"); ...
    pairedRows(methodRows, "B_primary", "C_FS_angle_control")];
refinement = [refinementRows(perUser, "B"); ...
    refinementRows(perUser, "C_FS")];
schemeAComparison = compareSchemeA(perUser);
gate = engineeringGate(summary, commonProtocol);
angleRows = gate.category == "angle";

output = struct(version="R35-schemeB-development-summary-v1", ...
    dataRole="existing-60-user-development-only", ...
    perUser=perUser, methodRows=methodRows, summary=summary, ...
    comparisons=comparisons, refinement=refinement, ...
    schemeAComparison=schemeAComparison, gate=gate, ...
    primaryAngleGatePassed=all(gate.pass(angleRows)), ...
    overallPrimaryGatePassed=all(gate.pass));
end

function schemeA = alignSchemeA(design, results, input)
[found, location] = ismember(design.seed, input.seed);
if ~all(found) || numel(unique(input.seed)) ~= height(input)
    error("r35:SchemeAReadOnlyIdentityMismatch", ...
        "The saved Scheme A diagnostic rows do not match the 60 users.");
end
schemeA = input(location, :);
paTheta = cellfun(@(x) x.P_A.thetaDeg, results);
paRange = cellfun(@(x) x.P_A.rangeM, results);
if any(abs(paTheta-schemeA.theta_P_A) > 1e-10) ...
        || any(abs(paRange-schemeA.range_P_A) > 1e-7) ...
        || ~isequal(design.snrDb, schemeA.snrDb)
    error("r35:SchemeAReadOnlyBaselineDrift", ...
        "The saved Scheme A file does not share the frozen P_A identity.");
end
end

function perUser = buildPerUser(design, results, schemeA)
paTheta = cellfun(@(x) x.P_A.thetaDeg, results);
paRange = cellfun(@(x) x.P_A.rangeM, results);
cTheta = cellfun(@(x) x.C_enhanced.thetaDeg, results);
cRange = cellfun(@(x) x.C_enhanced.rangeM, results);
bTheta = cellfun(@(x) x.B_primary.thetaDeg, results);
cFsTheta = cellfun(@(x) x.C_FS_angle_control.thetaDeg, results);
bBracket = cell2mat(cellfun(@(x) x.bRefinement.bracketDeg, ...
    results, UniformOutput=false));
cBracket = cell2mat(cellfun(@(x) x.cRefinement.bracketDeg, ...
    results, UniformOutput=false));
bBracketBoundaryHit = bracketBoundaryHit(bTheta, bBracket);
cBracketBoundaryHit = bracketBoundaryHit(cFsTheta, cBracket);
bTruthGain = (paTheta-design.truthThetaDeg).^2 ...
    -(bTheta-design.truthThetaDeg).^2;
aTruthGain = (paTheta-design.truthThetaDeg).^2 ...
    -(schemeA.theta_A_cont-design.truthThetaDeg).^2;

perUser = table(design.seed, design.trialIndex, design.snrDb, ...
    design.truthThetaDeg, design.truthRangeM, paTheta, paRange, ...
    cTheta, cRange, bTheta, cFsTheta, ...
    bBracket(:, 1), bBracket(:, 2), cBracket(:, 1), cBracket(:, 2), ...
    cellfun(@(x) x.bRefinement.scoreBefore, results), ...
    cellfun(@(x) x.bRefinement.scoreAfter, results), ...
    cellfun(@(x) x.cRefinement.scoreBefore, results), ...
    cellfun(@(x) x.cRefinement.scoreAfter, results), ...
    cellfun(@(x) x.bRefinement.displacementDeg, results), ...
    cellfun(@(x) x.cRefinement.displacementDeg, results), ...
    cellfun(@(x) x.bRefinement.functionEvaluations, results), ...
    cellfun(@(x) x.cRefinement.functionEvaluations, results), ...
    cellfun(@(x) x.bRefinement.converged, results), ...
    cellfun(@(x) x.cRefinement.converged, results), ...
    cellfun(@(x) x.bRefinement.boundaryFlag, results), ...
    cellfun(@(x) x.cRefinement.boundaryFlag, results), ...
    bBracketBoundaryHit, cBracketBoundaryHit, ...
    string(cellfun(@(x) x.bRefinement.selectedSource, ...
    results, UniformOutput=false)), ...
    string(cellfun(@(x) x.cRefinement.selectedSource, ...
    results, UniformOutput=false)), ...
    bTruthGain, schemeA.aDisplacementDeg, aTruthGain, ...
    string(cellfun(@(x) x.runtimeOrder, results, UniformOutput=false)), ...
    cellfun(@(x) x.P_A.runtimeSeconds, results), ...
    cellfun(@(x) x.B_primary.runtimeSeconds, results), ...
    cellfun(@(x) x.C_enhanced.runtimeSeconds, results), ...
    cellfun(@(x) x.C_FS_angle_control.runtimeSeconds, results), ...
    cellfun(@(x) x.bRefinement.runtimeSeconds, results), ...
    cellfun(@(x) x.cRefinement.runtimeSeconds, results), ...
    cellfun(@(x) x.responseContextSeconds, results), ...
    cellfun(@(x) x.responseContextBytes, results), ...
    cellfun(@(x) x.P_A.responseEvaluationCount, results), ...
    cellfun(@(x) x.C_enhanced.responseEvaluationCount, results), ...
    cellfun(@(x) x.B_primary.responseEvaluationCount, results), ...
    cellfun(@(x) x.C_FS_angle_control.responseEvaluationCount, results), ...
    cellfun(@(x) x.P_A.musicEvaluationCount, results), ...
    cellfun(@(x) x.C_enhanced.musicEvaluationCount, results), ...
    cellfun(@(x) x.B_primary.musicEvaluationCount, results), ...
    cellfun(@(x) x.C_FS_angle_control.musicEvaluationCount, results), ...
    'VariableNames', {'seed', 'trialIndex', 'snrDb', ...
    'truthThetaDeg', 'truthRangeM', 'theta_P_A', 'range_P_A', ...
    'theta_C_enhanced', 'range_C_enhanced', 'theta_B', 'theta_C_FS', ...
    'bBracketLowerDeg', 'bBracketUpperDeg', 'cBracketLowerDeg', ...
    'cBracketUpperDeg', 'bScoreBefore', 'bScoreAfter', ...
    'cScoreBefore', 'cScoreAfter', 'bDisplacementDeg', ...
    'cDisplacementDeg', 'bFunctionEvaluations', ...
    'cFunctionEvaluations', 'bConverged', 'cConverged', ...
    'bFeasibleAngleBoundaryFlag', 'cFeasibleAngleBoundaryFlag', ...
    'bBracketBoundaryHit', 'cBracketBoundaryHit', ...
    'bSelectedSource', 'cSelectedSource', 'bTruthAngleGainDeg2', ...
    'schemeADisplacementDeg', 'schemeATruthAngleGainDeg2', ...
    'runtimeOrder', 'runtime_P_A', 'runtime_B', ...
    'runtime_C_enhanced', 'runtime_C_FS', 'runtime_B_refinement', ...
    'runtime_C_refinement', 'responseContextSeconds', ...
    'responseContextBytes', 'responseCount_P_A', ...
    'responseCount_C_enhanced', 'responseCount_B', ...
    'responseCount_C_FS', 'musicCount_P_A', ...
    'musicCount_C_enhanced', 'musicCount_B', 'musicCount_C_FS'});
end

function rows = buildMethodRows(perUser)
methods = ["P_A", "C_enhanced", "B_primary", "C_FS_angle_control"];
thetaFields = ["theta_P_A", "theta_C_enhanced", ...
    "theta_B", "theta_C_FS"];
rangeFields = ["range_P_A", "range_C_enhanced", ...
    "range_P_A", "range_C_enhanced"];
runtimeFields = ["runtime_P_A", "runtime_C_enhanced", ...
    "runtime_B", "runtime_C_FS"];
rows = table();
for index = 1:numel(methods)
    theta = perUser.(thetaFields(index));
    range = perUser.(rangeFields(index));
    angleError = theta-perUser.truthThetaDeg;
    rangeError = range-perUser.truthRangeM;
    xError = range.*sind(theta) ...
        -perUser.truthRangeM.*sind(perUser.truthThetaDeg);
    yError = range.*cosd(theta) ...
        -perUser.truthRangeM.*cosd(perUser.truthThetaDeg);
    positionError = hypot(xError, yError);
    current = table(perUser.seed, perUser.trialIndex, perUser.snrDb, ...
        repmat(methods(index), height(perUser), 1), theta, range, ...
        angleError, rangeError, positionError, ...
        perUser.(runtimeFields(index)), ...
        'VariableNames', {'seed', 'trialIndex', 'snrDb', 'method', ...
        'thetaDeg', 'rangeM', 'angleErrorDeg', 'rangeErrorM', ...
        'positionErrorM', 'runtimeSeconds'});
    rows = [rows; current]; %#ok<AGROW>
end
end

function summary = summarizeMethods(rows, perUser)
summary = table();
for method = unique(rows.method, "stable").'
    for snrDb = unique(rows.snrDb).'
        current = rows(rows.method == method & rows.snrDb == snrDb, :);
        squared = current.angleErrorDeg.^2;
        rangeSquared = current.rangeErrorM.^2;
        positionSquared = current.positionErrorM.^2;
        [changed, displacement, responses, music] = ...
            methodDiagnostics(method, snrDb, perUser);
        entry = table(method, snrDb, height(current), mean(squared), ...
            sqrt(mean(squared)), median(abs(current.angleErrorDeg)), ...
            quantile(abs(current.angleErrorDeg), 0.90), ...
            quantile(abs(current.angleErrorDeg), 0.95), ...
            mean(rangeSquared), sqrt(mean(rangeSquared)), ...
            sqrt(mean(positionSquared)), ...
            changed, mean(abs(displacement)), max(abs(displacement)), ...
            mean(current.runtimeSeconds), mean(responses), mean(music), ...
            'VariableNames', {'method', 'snrDb', 'n', 'angleMseDeg2', ...
            'angleRmseDeg', 'angleMedianAbsoluteErrorDeg', ...
            'angleP90AbsoluteErrorDeg', 'angleP95AbsoluteErrorDeg', ...
            'rangeMseM2', 'rangeRmseM', 'positionRmseM', ...
            'fractionChanged', 'meanAbsoluteDisplacementDeg', ...
            'maximumAbsoluteDisplacementDeg', 'meanRuntimeSeconds', ...
            'meanResponseEvaluationCount', 'meanMusicEvaluationCount'});
        summary = [summary; entry]; %#ok<AGROW>
    end
end
end

function [changed, displacement, responses, music] = ...
    methodDiagnostics(method, snrDb, perUser)
selected = perUser.snrDb == snrDb;
count = nnz(selected);
if method == "B_primary"
    displacement = perUser.bDisplacementDeg(selected);
    responses = perUser.responseCount_B(selected);
    music = perUser.musicCount_B(selected);
elseif method == "C_FS_angle_control"
    displacement = perUser.cDisplacementDeg(selected);
    responses = perUser.responseCount_C_FS(selected);
    music = perUser.musicCount_C_FS(selected);
elseif method == "P_A"
    displacement = zeros(count, 1);
    responses = perUser.responseCount_P_A(selected);
    music = perUser.musicCount_P_A(selected);
elseif method == "C_enhanced"
    displacement = zeros(count, 1);
    responses = perUser.responseCount_C_enhanced(selected);
    music = perUser.musicCount_C_enhanced(selected);
else
    displacement = zeros(count, 1);
    responses = nan(count, 1);
    music = nan(count, 1);
end
changed = mean(displacement ~= 0);
end

function output = pairedRows(rows, candidateName, referenceName)
output = table();
snrValues = unique(rows.snrDb).';
candidateMse = zeros(numel(snrValues), 1);
referenceMse = zeros(numel(snrValues), 1);
allDifference = zeros(0, 1);
for index = 1:numel(snrValues)
    [entry, difference, candidateMse(index), referenceMse(index)] = ...
        pairedEntry(rows, candidateName, referenceName, snrValues(index));
    output = [output; entry]; %#ok<AGROW>
    allDifference = [allDifference; difference]; %#ok<AGROW>
end
aggregateCandidate = mean(candidateMse);
aggregateReference = mean(referenceMse);
aggregate = table(candidateName, referenceName, "equal-SNR", nan, ...
    numel(allDifference), aggregateCandidate, aggregateReference, ...
    aggregateCandidate/aggregateReference, ...
    100*(1-sqrt(aggregateCandidate/aggregateReference)), ...
    mean(allDifference), nnz(allDifference < 0), ...
    nnz(allDifference == 0), nnz(allDifference > 0), ...
    mean(allDifference < 0), mean(allDifference == 0), ...
    mean(allDifference > 0), 'VariableNames', ...
    output.Properties.VariableNames);
output = [output; aggregate];
end

function [entry, difference, candidateMse, referenceMse] = ...
    pairedEntry(rows, candidateName, referenceName, snrDb)
candidate = sortrows(rows(rows.method == candidateName ...
    & rows.snrDb == snrDb, :), "seed");
reference = sortrows(rows(rows.method == referenceName ...
    & rows.snrDb == snrDb, :), "seed");
if ~isequal(candidate.seed, reference.seed)
    error("r35:UnpairedSchemeBRows", ...
        "Scheme B comparisons require identical old users.");
end
candidateSquared = candidate.angleErrorDeg.^2;
referenceSquared = reference.angleErrorDeg.^2;
candidateMse = mean(candidateSquared);
referenceMse = mean(referenceSquared);
difference = candidateSquared-referenceSquared;
entry = table(candidateName, referenceName, "per-SNR", snrDb, ...
    height(candidate), candidateMse, referenceMse, ...
    candidateMse/referenceMse, ...
    100*(1-sqrt(candidateMse/referenceMse)), mean(difference), ...
    nnz(difference < 0), nnz(difference == 0), ...
    nnz(difference > 0), mean(difference < 0), ...
    mean(difference == 0), mean(difference > 0), ...
    'VariableNames', {'candidate', 'reference', 'scope', 'snrDb', ...
    'n', 'candidateAngleMseDeg2', 'referenceAngleMseDeg2', ...
    'angleMseRatio', 'angleRmseImprovementPercent', ...
    'meanPairedSquaredErrorDifference', 'winCount', 'tieCount', ...
    'lossCount', 'winRate', 'tieRate', 'lossRate'});
end

function output = refinementRows(perUser, label)
if label == "B"
    scoreGain = perUser.bScoreAfter-perUser.bScoreBefore;
    truthGain = perUser.bTruthAngleGainDeg2;
    displacement = perUser.bDisplacementDeg;
    evaluations = perUser.bFunctionEvaluations;
    converged = perUser.bConverged;
    feasibleBoundary = perUser.bFeasibleAngleBoundaryFlag;
    bracketBoundary = perUser.bBracketBoundaryHit;
    runtime = perUser.runtime_B_refinement+perUser.responseContextSeconds;
else
    scoreGain = perUser.cScoreAfter-perUser.cScoreBefore;
    truthGain = (perUser.theta_C_enhanced-perUser.truthThetaDeg).^2 ...
        -(perUser.theta_C_FS-perUser.truthThetaDeg).^2;
    displacement = perUser.cDisplacementDeg;
    evaluations = perUser.cFunctionEvaluations;
    converged = perUser.cConverged;
    feasibleBoundary = perUser.cFeasibleAngleBoundaryFlag;
    bracketBoundary = perUser.cBracketBoundaryHit;
    runtime = perUser.runtime_C_refinement+perUser.responseContextSeconds;
end
output = table();
snrValues = unique(perUser.snrDb).';
for index = 1:numel(snrValues)+1
    if index <= numel(snrValues)
        snrDb = snrValues(index);
        selected = perUser.snrDb == snrDb;
        scope = "per-SNR";
    else
        snrDb = nan;
        selected = true(height(perUser), 1);
        scope = "all-SNR";
    end
    score = scoreGain(selected);
    truth = truthGain(selected);
    absoluteDisplacement = abs(displacement(selected));
    entry = table(label, scope, snrDb, nnz(selected), ...
        mean(score), median(score), max(score), ...
        mean(truth), nnz(truth > 0), nnz(truth == 0), ...
        nnz(truth < 0), finiteCorrelation(score, truth), ...
        finiteCorrelation(absoluteDisplacement, truth), ...
        mean(absoluteDisplacement), max(absoluteDisplacement), ...
        mean(evaluations(selected)), nnz(converged(selected)), ...
        nnz(feasibleBoundary(selected)), ...
        nnz(bracketBoundary(selected)), mean(runtime(selected)), ...
        'VariableNames', {'refinement', 'scope', 'snrDb', 'n', ...
        'meanScoreGain', 'medianScoreGain', 'maximumScoreGain', ...
        'meanTruthSquaredErrorReduction', 'truthImproveCount', ...
        'truthTieCount', 'truthWorseCount', ...
        'scoreTruthPearsonCorrelation', ...
        'absoluteDisplacementTruthCorrelation', ...
        'meanAbsoluteDisplacementDeg', 'maximumAbsoluteDisplacementDeg', ...
        'meanFunctionEvaluations', 'convergedCount', ...
        'feasibleAngleBoundaryCount', 'bracketBoundaryHitCount', ...
        'meanExtraRuntimeSeconds'});
    output = [output; entry]; %#ok<AGROW>
end
end

function output = compareSchemeA(perUser)
output = table();
snrValues = unique(perUser.snrDb).';
for index = 1:numel(snrValues)+1
    if index <= numel(snrValues)
        snrDb = snrValues(index);
        selected = perUser.snrDb == snrDb;
        scope = "per-SNR";
    else
        snrDb = nan;
        selected = true(height(perUser), 1);
        scope = "all-SNR";
    end
    b = perUser.bDisplacementDeg(selected);
    a = perUser.schemeADisplacementDeg(selected);
    aTruth = perUser.schemeATruthAngleGainDeg2(selected);
    bTruth = perUser.bTruthAngleGainDeg2(selected);
    lowSnrAWorse = aTruth < 0 ...
        & perUser.snrDb(selected) <= 0;
    entry = table(scope, snrDb, nnz(selected), ...
        finiteCorrelation(b, a), mean(sign(b) == sign(a)), ...
        mean(abs(b))/mean(abs(a)), mean(abs(b-a)), max(abs(b-a)), ...
        nnz(lowSnrAWorse), nnz(lowSnrAWorse & bTruth > 0), ...
        'VariableNames', {'scope', 'snrDb', 'n', ...
        'displacementPearsonCorrelation', 'sameDirectionFraction', ...
        'meanAbsoluteMagnitudeRatioBOverA', ...
        'meanAbsoluteDisplacementDifferenceDeg', ...
        'maximumAbsoluteDisplacementDifferenceDeg', ...
        'schemeAWorseLowSnrCount', 'bReverseImproveCount'});
    output = [output; entry]; %#ok<AGROW>
end
end

function value = finiteCorrelation(first, second)
if std(first) == 0 || std(second) == 0
    value = nan;
else
    matrix = corrcoef(first, second);
    value = matrix(1, 2);
end
end

function hit = bracketBoundaryHit(theta, bracket)
width = bracket(:, 2)-bracket(:, 1);
tolerance = max(10*r35SchemeBConfig().tolXDeg, 1e-3*width);
distance = min(theta-bracket(:, 1), bracket(:, 2)-theta);
hit = distance <= tolerance;
end

function gate = engineeringGate(summary, protocol)
gate = table();
for snrDb = unique(summary.snrDb).'
    pa = summary(summary.method == "P_A" & summary.snrDb == snrDb, :);
    b = summary(summary.method == "B_primary" ...
        & summary.snrDb == snrDb, :);
    ratio = b.angleMseDeg2/pa.angleMseDeg2;
    gate = [gate; gateRow("angle", "per-SNR-angle-MSE", ...
        snrDb, ratio, ...
        protocol.engineeringGate.maximumPerSnrAngleMseRatioToPA)]; %#ok<AGROW>
end
paRows = summary(summary.method == "P_A", :);
bRows = summary(summary.method == "B_primary", :);
aggregateRatio = mean(bRows.angleMseDeg2)/mean(paRows.angleMseDeg2);
gate = [gate; gateRow("angle", ...
    "equal-SNR-aggregate-angle-MSE", nan, aggregateRatio, ...
    protocol.engineeringGate.maximumEqualSnrAggregateAngleMseRatioToPA)];
cRows = summary(summary.method == "C_enhanced", :);
runtimeRatio = mean(bRows.meanRuntimeSeconds) ...
    /mean(cRows.meanRuntimeSeconds);
gate = [gate; gateRow("runtime", "mean-runtime", nan, ...
    runtimeRatio, protocol.engineeringGate.maximumRuntimeRatioToCEnhanced)];
end

function row = gateRow(category, name, snrDb, observed, limit)
row = table(category, name, snrDb, observed, limit, observed <= limit, ...
    'VariableNames', {'category', 'gate', 'snrDb', 'observedRatio', ...
    'maximumAllowedRatio', 'pass'});
end
