function result = r35SchemeBPrimaryTrial( ...
    cfg, scan, designRow, rowIndex, r34Protocol, schemeProtocol)
%R35SCHEMEBPRIMARYTRIAL Refine frozen grid angles with coherent spectrum z.

arguments
    cfg (1, 1) struct
    scan (1, 1) struct
    designRow (1, :) table
    rowIndex (1, 1) double {mustBeInteger, mustBePositive}
    r34Protocol (1, 1) struct = r34.config()
    schemeProtocol (1, 1) struct = r35SchemeBConfig()
end

result = failureResult(designRow, rowIndex);
try
    replay = fsjad.replayRound27Data(cfg, scan, designRow);
    if mod(rowIndex, 2) == 1
        order = "P_A-then-C_enhanced";
        pa = r34.estimate(cfg, replay.observation, replay.snapshots, ...
            scan, "P_A", r34Protocol);
        c = r34.estimate(cfg, replay.observation, replay.snapshots, ...
            scan, "C_enhanced", r34Protocol);
    else
        order = "C_enhanced-then-P_A";
        c = r34.estimate(cfg, replay.observation, replay.snapshots, ...
            scan, "C_enhanced", r34Protocol);
        pa = r34.estimate(cfg, replay.observation, replay.snapshots, ...
            scan, "P_A", r34Protocol);
    end

    contextTimer = tic;
    context = r33.prepareResponseContext(cfg, scan, replay.observation);
    contextSeconds = toc(contextTimer);
    contextInfo = whos("context");

    aStage = pa.estimate.stages(end);
    bScore = @(thetaDeg) r33.fixedAngleProfileLogScore( ...
        cfg, thetaDeg, pa.rangeM, context);
    bRefinement = r35BracketedSpectralRefinement(bScore, ...
        aStage.thetaGridDeg, aStage.selectedIndex, schemeProtocol);

    cStage = c.estimate.stages(end);
    cScore = @(thetaDeg) r33.fixedAngleProfileLogScore( ...
        cfg, thetaDeg, c.rangeM, context);
    cRefinement = r35BracketedSpectralRefinement(cScore, ...
        cStage.thetaGridDeg, cStage.selectedThetaIndex, schemeProtocol);

    paResponseCount = pa.cost.sparseResponseCalls ...
        +pa.cost.frontFullResponseCalls+pa.cost.profileResponseCalls;
    cResponseCount = c.cost.sparseResponseCalls ...
        +c.cost.frontFullResponseCalls;
    bRuntime = pa.cost.totalOnlineSeconds ...
        +contextSeconds+bRefinement.runtimeSeconds;
    cFsRuntime = c.cost.totalOnlineSeconds ...
        +contextSeconds+cRefinement.runtimeSeconds;

    result.success = bRefinement.status ~= "optimizer-exception" ...
        && cRefinement.status ~= "optimizer-exception";
    result.runtimeOrder = order;
    result.truthThetaDeg = designRow.truthThetaDeg;
    result.truthRangeM = designRow.truthRangeM;
    result.frontThetaDeg = pa.front.selected.thetaDeg;
    result.frontRangeM = pa.front.selected.rangeM;
    result.P_A = locationRecord(pa.thetaDeg, pa.rangeM, ...
        pa.cost.totalOnlineSeconds, paResponseCount, ...
        pa.estimate.evaluationCount);
    result.C_enhanced = locationRecord(c.thetaDeg, c.rangeM, ...
        c.cost.totalOnlineSeconds, cResponseCount, ...
        c.estimate.evaluationCount);
    result.B_primary = locationRecord(bRefinement.thetaSpectralDeg, ...
        pa.rangeM, bRuntime, ...
        paResponseCount+bRefinement.functionEvaluations, ...
        pa.estimate.evaluationCount);
    result.C_FS_angle_control = locationRecord( ...
        cRefinement.thetaSpectralDeg, c.rangeM, cFsRuntime, ...
        cResponseCount+cRefinement.functionEvaluations, ...
        c.estimate.evaluationCount);
    result.bRefinement = bRefinement;
    result.cRefinement = cRefinement;
    result.aFinalGridDeg = aStage.thetaGridDeg;
    result.cFinalGridDeg = cStage.thetaGridDeg;
    result.responseContextSeconds = contextSeconds;
    result.responseContextBytes = contextInfo.bytes;
    result.bExtraExactResponseEvaluations = ...
        bRefinement.functionEvaluations;
    result.cExtraExactResponseEvaluations = ...
        cRefinement.functionEvaluations;
    result.aSolverAudit = pa.solverAudit;
    result.cSolverAudit = c.solverAudit;
catch exception
    result.success = false;
    result.errorIdentifier = string(exception.identifier);
    result.errorMessage = string(getReport( ...
        exception, "extended", "hyperlinks", "off"));
end
end

function output = locationRecord(thetaDeg, rangeM, runtimeSeconds, ...
    responseEvaluationCount, musicEvaluationCount)
output = struct(thetaDeg=thetaDeg, rangeM=rangeM, ...
    runtimeSeconds=runtimeSeconds, ...
    responseEvaluationCount=responseEvaluationCount, ...
    musicEvaluationCount=musicEvaluationCount);
end

function result = failureResult(designRow, rowIndex)
result = struct(success=false, rowIndex=rowIndex, seed=designRow.seed, ...
    trialIndex=designRow.trialIndex, snrDb=designRow.snrDb, ...
    truthThetaDeg=designRow.truthThetaDeg, ...
    truthRangeM=designRow.truthRangeM, runtimeOrder="", ...
    errorIdentifier="", errorMessage="");
end
