function output = summarize(design, results, protocol)
%SUMMARIZE Build R55 final tables and primary decision.

arguments
    design table
    results (:, 1) cell
    protocol (1, 1) struct = r55.config()
end

if numel(results) ~= height(design) || any(cellfun(@isempty, results)) ...
        || any(cellfun(@(item) ~item.success, results))
    error("r55:IncompleteFinal", ...
        "R55 summary requires all frozen final rows to succeed.");
end
methods = ["P_FALF", "P_FA", "P_A", "G_schur", "C_enhanced"];
perUser = design(:, ["positionId", "seed", "trialIndex", ...
    "snrDb", "truthThetaDeg", "truthRangeM"]);
for method = methods
    theta = cellfun(@(item) item.(method).thetaDeg, results);
    rangeM = cellfun(@(item) item.(method).rangeM, results);
    perUser.("theta_"+method) = theta;
    perUser.("range_"+method) = rangeM;
    perUser.("angleError_"+method) = theta-perUser.truthThetaDeg;
    perUser.("rangeError_"+method) = rangeM-perUser.truthRangeM;
    perUser.("positionError_"+method) = hypot( ...
        rangeM.*sind(theta)-perUser.truthRangeM.*sind(perUser.truthThetaDeg), ...
        rangeM.*cosd(theta)-perUser.truthRangeM.*cosd(perUser.truthThetaDeg));
end
perUser.angleIdentityDifferenceDeg = cellfun( ...
    @(item) item.angleIdentityDifferenceDeg, results);
perUser.rangeShiftM = cellfun(@(item) item.rangeShiftM, results);
perUser.sharedDirectEvdCount = cellfun( ...
    @(item) item.sharedAudit.totalDirectEvdCount, results);
perUser.sharedGramCount = cellfun( ...
    @(item) item.sharedAudit.totalGramCount, results);
perUser.sharedFallbackCount = cellfun( ...
    @(item) item.sharedAudit.totalFallbackCount, results);

methodSummary = buildMethodSummary(perUser, methods, protocol);
comparisons = compareAll(perUser, methods, protocol);
primaryBootstrap = r55.clusterBootstrap( ...
    perUser, "P_FALF", "P_A", protocol, 0);
pfaBootstrap = r55.clusterBootstrap( ...
    perUser, "P_FALF", "P_FA", protocol, 1);
angleIdentityPass = max(perUser.angleIdentityDifferenceDeg) <= 1e-12;
missF = mean(abs(perUser.rangeError_P_FALF) ...
    > protocol.statistics.missThresholdM);
missA = mean(abs(perUser.rangeError_P_A) ...
    > protocol.statistics.missThresholdM);
missPass = missF <= missA;
solverIdentityPass = all(perUser.sharedDirectEvdCount > 0) ...
    && all(perUser.sharedGramCount == 0) ...
    && all(perUser.sharedFallbackCount == 0);
familyPass = all(primaryBootstrap.family.pass);
aggregatePass = primaryBootstrap.aggregate.pass;
primaryPass = angleIdentityPass && missPass && solverIdentityPass ...
    && familyPass && aggregatePass;
decision = table(angleIdentityPass, solverIdentityPass, familyPass, ...
    aggregatePass, missF, missA, missPass, primaryPass, ...
    'VariableNames', {'angleIdentityPass', 'solverIdentityPass', ...
    'rangeFamilyPass', 'aggregateSuperiorityPass', ...
    'candidateMissRate', 'referenceMissRate', 'missRatePass', ...
    'primaryPass'});
diagnostics = table(height(perUser), ...
    max(perUser.angleIdentityDifferenceDeg), ...
    rms(perUser.rangeShiftM), median(abs(perUser.rangeShiftM)), ...
    sum(perUser.sharedDirectEvdCount), sum(perUser.sharedGramCount), ...
    sum(perUser.sharedFallbackCount), ...
    'VariableNames', {'n', 'maxAngleIdentityDifferenceDeg', ...
    'rangeShiftRmsM', 'rangeShiftMedianAbsM', ...
    'totalDirectEvdCount', 'totalGramCount', 'totalFallbackCount'});
output = struct(version="R55-PFALF-final-summary-v1", ...
    perUser=perUser, methodSummary=methodSummary, ...
    comparisons=comparisons, primaryBootstrap=primaryBootstrap, ...
    pfaBootstrap=pfaBootstrap, decision=decision, ...
    diagnostics=diagnostics, primaryPass=primaryPass);
end

function output = buildMethodSummary(perUser, methods, protocol)
output = table();
for method = methods
    for snr = protocol.design.snrDb
        selected = perUser.snrDb == snr;
        ae = perUser.("angleError_"+method)(selected);
        re = perUser.("rangeError_"+method)(selected);
        pe = perUser.("positionError_"+method)(selected);
        output = [output; table(method, snr, nnz(selected), ...
            mean(ae.^2), sqrt(mean(ae.^2)), median(abs(ae)), ...
            quantile(abs(ae), .95), mean(re.^2), sqrt(mean(re.^2)), ...
            median(abs(re)), quantile(abs(re), .90), ...
            quantile(abs(re), .95), ...
            mean(abs(re)>protocol.statistics.missThresholdM), ...
            sqrt(mean(pe.^2)), ...
            'VariableNames', {'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', 'angleMedianAbsDeg', ...
            'angleP95AbsDeg', 'rangeMseM2', 'rangeRmseM', ...
            'rangeMedianAbsM', 'rangeP90AbsM', 'rangeP95AbsM', ...
            'rangeMissRateOver1M', 'positionRmseM'})]; %#ok<AGROW>
    end
end
end

function output = compareAll(perUser, methods, protocol)
output = table();
for candidate = ["P_FALF", "P_FA"]
    for reference = methods(methods ~= candidate)
        for metric = ["angle", "range", "position"]
            candidateMse = zeros(numel(protocol.design.snrDb), 1);
            referenceMse = zeros(numel(protocol.design.snrDb), 1);
            for index = 1:numel(protocol.design.snrDb)
                snr = protocol.design.snrDb(index);
                selected = perUser.snrDb == snr;
                ce = perUser.(metric+"Error_"+candidate)(selected).^2;
                re = perUser.(metric+"Error_"+reference)(selected).^2;
                candidateMse(index) = mean(ce);
                referenceMse(index) = mean(re);
                output = [output; comparisonRow(candidate, reference, ...
                    metric, "per-SNR", snr, ce, re)]; %#ok<AGROW>
            end
            ce = perUser.(metric+"Error_"+candidate).^2;
            re = perUser.(metric+"Error_"+reference).^2;
            row = comparisonRow(candidate, reference, metric, ...
                "equal-SNR", nan, ce, re);
            row.mseRatio = mean(candidateMse)/mean(referenceMse);
            output = [output; row]; %#ok<AGROW>
        end
    end
end
end

function output = comparisonRow(candidate, reference, metric, ...
    scope, snrDb, ce, re)
output = table(candidate, reference, metric, scope, snrDb, numel(ce), ...
    mean(ce), mean(re), mean(ce)/mean(re), ...
    100*(1-sqrt(mean(ce)/mean(re))), ...
    nnz(ce<re), nnz(ce==re), nnz(ce>re), ...
    'VariableNames', {'candidate', 'reference', 'metric', 'scope', ...
    'snrDb', 'n', 'candidateMse', 'referenceMse', 'mseRatio', ...
    'rmseImprovementPct', 'winCount', 'tieCount', 'lossCount'});
end
