function output = validateProtocolPackage(project)
%VALIDATEPROTOCOLPACKAGE Validate the locked R55 package without trials.

arguments
    project (1, 1) string
end

locations = r55.paths(project);
if ~isfile(locations.protocolFile)
    error("r55:MissingProtocolPackage", ...
        "The locked R55 protocol package does not exist.");
end
saved = load(locations.protocolFile, "identity", "protocol", ...
    "design", "source", "r53Source", "r54Source", "pfaSource", ...
    "estimate");
if saved.identity.protocolVersion ~= saved.protocol.version ...
        || r32.designHash(saved.design) ~= saved.identity.designHash ...
        || r41.structHash(saved.protocol.statistics) ...
        ~= saved.identity.statisticsHash ...
        || r32.sourceDigest(r55.sourceManifest(project)) ...
        ~= saved.identity.sourceDigest ...
        || r32.sourceDigest(r53.manifest(project)) ...
        ~= saved.identity.r53SourceDigest ...
        || r32.sourceDigest(r54.manifest(project)) ...
        ~= saved.identity.r54SourceDigest ...
        || r32.sourceDigest(r45.manifest(project)) ...
        ~= saved.identity.pfaSourceDigest
    error("r55:ProtocolPackageDrift", ...
        "The R55 protocol package or frozen dependencies changed.");
end
output = saved;
end
