function assertFrozenConfig(cfg, protocol)
%ASSERTFROZENCONFIG Reject silent drift from the frozen P_A configuration.

arguments
    cfg (1, 1) struct
    protocol (1, 1) struct = r32.config()
end

required = ["numAntennas", "numSubcarriers", "thetaLimitsDeg", ...
    "rangeLimitsM"];
if ~all(isfield(cfg, required))
    error("r32:IncompleteSystemConfig", ...
        "The system configuration is missing a required field.");
end
if cfg.numAntennas ~= 256 || cfg.numSubcarriers ~= 2048 ...
        || protocol.music.subarraySize ~= 160 ...
        || protocol.music.numSubarrays ~= 97 ...
        || protocol.music.carrierCount ~= 2047 ...
        || ~isequal(protocol.music.gridSizes, [41, 31, 21]) ...
        || protocol.music.angleHalfWidthDeg ~= 0.2 ...
        || protocol.profile.halfWidthM ~= 2 ...
        || protocol.profile.lambda ~= 1 ...
        || ~isequal(cfg.thetaLimitsDeg, [-60, 60]) ...
        || ~isequal(cfg.rangeLimitsM, [15, 50])
    error("r32:FrozenConfigurationMismatch", ...
        "P_A requires N256/M2048/K2047/L160/P97 and the frozen windows.");
end
end
