function protocol = config()
%CONFIG Frozen finite-closeout protocol for the P_A candidate.

protocol.version = "R32-PA-finite-closeout-v1";
protocol.methodVersion = "PA-independent-online-R32-v1";
protocol.dataRole = "existing-Round30-60-user-development-only";

protocol.front = struct( ...
    version="R30-sparse-wideband-front-v1", ...
    candidateId="L06", carrierCount=513, rangeSpacingM=0.1, ...
    retainedCandidates=8, maxIterations=10, ...
    angleOffsetsDeg=[-0.2; -0.1; 0; 0.1; 0.2]);
protocol.music = struct( ...
    carrierCount=2047, subarraySize=160, numSubarrays=97, ...
    angleHalfWidthDeg=0.2, gridSizes=[41, 31, 21], ...
    fusionRule="mean-log-MUSIC-geometric-mean", ...
    referenceSubarrayRule="centered-reference-subarray", ...
    constrainToInitialWindow=true);
protocol.profile = struct( ...
    lambda=1, halfWidthM=2, coarseSpacingM=0.05, ...
    minimumIntervals=40, peakCount=8, tolXM=1e-6, ...
    scoreTolerance=1e-10, ...
    score="full-spectrum-concentrated-complex-profile", ...
    refinement="fminbnd-around-retained-grid-peaks", ...
    clipping="intersect-with-15-to-50-m-physical-range");
protocol.enhancedC = struct( ...
    label="same-L06-front-Zhang-R26-enhanced-C", ...
    carrierCount=2047, subarraySize=160, ...
    angleHalfWidthDeg=0.2, rangeHalfWidthM=0.0025, ...
    gridSizes=[41, 31, 21]);
protocol.publicC = struct( ...
    label="transparent-published-region-assumption-not-author-code", ...
    carrierCount=5, subarraySize=128, ...
    angleHalfWidthDeg=1, rangeHalfWidthM=1, ...
    gridSizes=[41, 31, 21]);

% Unchanged engineering development thresholds. These are not statistical
% non-inferiority margins and are never retuned from Round32 outcomes.
protocol.acceptance = struct(angleRmseRatio=1.10, rangeRmseRatio=1.10, ...
    positionRmseRatio=1.10, p95Ratio=1.15, missRateIncrease=0.01);
protocol.statistics = struct(bootstrapCount=20000, ...
    bootstrapSeed=20260910, tailFraction=0.10, missThresholdM=1);
protocol.timing = struct(snrDb=0, positionCount=3, repetitions=3, ...
    warmupsPerMethod=1, ...
    baseOrder=["C_enhanced", "H_A", "P_A", "C_public"], ...
    orderPolicy="deterministic-cyclic-rotation-across-position-repetition");
protocol.modelCheck = struct(snrDb=0, positionCount=20, ...
    residualDelaySeconds=[-0.1e-9, 0, 0.1e-9], ...
    zeroCondition="reuse-existing-R31-result", ...
    stateProjectionTolerance=1e-10, magnitudeTolerance=1e-12);
protocol.finalTest = struct(positionCount=200, ...
    snrDb=-10:5:20, positionSeed=52000000, trialSeedRoot=52100000, ...
    angleLimitsDeg=[-60, 60], rangeLimitsM=[15, 50], ...
    primaryComparison="P_A-versus-C_enhanced", ...
    rangeClaim="superiority-of-paired-mean-squared-range-error", ...
    angleClaim="noninferiority-with-fixed-MSE-ratio-margin-1.21", ...
    angleClaimMarginMseRatio=1.21, ...
    multiplicity="position-cluster-bootstrap-simultaneous-across-seven-SNR", ...
    authorized=false);
end
