function result = estimateC(cfg, observation, snapshots, scan, protocol)
%ESTIMATEC Complete online same-front enhanced two-dimensional C baseline.

arguments
    cfg (1, 1) struct
    observation (:, 1) double {mustBeFinite}
    snapshots (:, :) double
    scan (1, 1) struct = fsjad.prepareScan(cfg)
    protocol (1, 1) struct = r32.config()
end

r32.assertFrozenConfig(cfg, protocol);
totalTimer = tic;
frontProtocol = r30.config();
frontProtocol.frontVersion = protocol.front.version;
frontProtocol.angleOffsetsDeg = protocol.front.angleOffsetsDeg;
frontOutput = r30.front(cfg, observation, scan, ...
    frontProtocol, r32.candidate(protocol));
front = frontOutput.selected;
carrierIndex = r30.selectLocalCarriers(cfg.numSubcarriers, ...
    protocol.enhancedC.carrierCount, frontOutput.peakCarrierIndex);
[state, musicCfg, stateCost] = r30.prepareMusicState(cfg, ...
    snapshots(:, carrierIndex+1), carrierIndex, ...
    front.thetaDeg, front.rangeM, protocol.enhancedC.subarraySize);
searchTimer = tic;
estimate = r31.stagedJointMusic(musicCfg, state, ...
    front.thetaDeg, front.rangeM, protocol.enhancedC.angleHalfWidthDeg, ...
    protocol.enhancedC.rangeHalfWidthM, protocol.enhancedC.gridSizes);
searchSeconds = toc(searchTimer);
result = assemble("C-enhanced-independent-online-R32-v1", ...
    frontOutput, state, musicCfg, carrierIndex, estimate, ...
    stateCost, searchSeconds, toc(totalTimer));
end

function result = assemble(version, front, state, musicCfg, carriers, ...
    estimate, stateCost, searchSeconds, totalSeconds)
result.version = version;
result.front = front;
result.state = state;
result.musicCfg = musicCfg;
result.carrierIndex = carriers;
result.estimate = estimate;
result.cost = struct(frontSeconds=front.runtimeSeconds, ...
    stateSeconds=stateCost.seconds, searchSeconds=searchSeconds, ...
    profileSeconds=0, frontEquivalentResponses=front.fullEquivalentResponses, ...
    phaseAlignmentTerms=stateCost.phaseAlignmentTerms, ...
    covarianceMacs=stateCost.covarianceMacs, ...
    evdCubicUnits=stateCost.evdCubicUnits, ...
    searchEvaluations=estimate.evaluationCount, ...
    projectionMacs=stateCost.carrierCount*stateCost.subarraySize ...
        *estimate.evaluationCount, totalOnlineSeconds=totalSeconds);
end
