function result = estimatePublic(cfg, observation, snapshots, scan, protocol)
%ESTIMATEPUBLIC Complete online transparent public-assumption C baseline.

arguments
    cfg (1, 1) struct
    observation (:, 1) double {mustBeFinite}
    snapshots (:, :) double
    scan (1, 1) struct = fsjad.prepareScan(cfg)
    protocol (1, 1) struct = r32.config()
end

r32.assertFrozenConfig(cfg, protocol);
totalTimer = tic;
frontProtocol = r30.config();
frontProtocol.frontVersion = protocol.front.version;
frontProtocol.angleOffsetsDeg = protocol.front.angleOffsetsDeg;
frontOutput = r30.front(cfg, observation, scan, ...
    frontProtocol, r32.candidate(protocol));
front = frontOutput.selected;
carrierIndex = r30.selectLocalCarriers(cfg.numSubcarriers, ...
    protocol.publicC.carrierCount, frontOutput.peakCarrierIndex);
[state, musicCfg, stateCost] = r30.prepareMusicState(cfg, ...
    snapshots(:, carrierIndex+1), carrierIndex, ...
    front.thetaDeg, front.rangeM, protocol.publicC.subarraySize);
searchTimer = tic;
estimate = r31.stagedJointMusic(musicCfg, state, ...
    front.thetaDeg, front.rangeM, protocol.publicC.angleHalfWidthDeg, ...
    protocol.publicC.rangeHalfWidthM, protocol.publicC.gridSizes);
searchSeconds = toc(searchTimer);
result.version = "C-public-transparent-online-R32-v1";
result.front = frontOutput;
result.state = state;
result.musicCfg = musicCfg;
result.carrierIndex = carrierIndex;
result.estimate = estimate;
result.cost = struct(frontSeconds=frontOutput.runtimeSeconds, ...
    stateSeconds=stateCost.seconds, searchSeconds=searchSeconds, ...
    profileSeconds=0, frontEquivalentResponses=frontOutput.fullEquivalentResponses, ...
    phaseAlignmentTerms=stateCost.phaseAlignmentTerms, ...
    covarianceMacs=stateCost.covarianceMacs, ...
    evdCubicUnits=stateCost.evdCubicUnits, ...
    searchEvaluations=estimate.evaluationCount, ...
    projectionMacs=stateCost.carrierCount*stateCost.subarraySize ...
        *estimate.evaluationCount, totalOnlineSeconds=toc(totalTimer));
end
