function result = estimateHA(cfg, observation, snapshots, scan, protocol)
%ESTIMATEHA Independent H_A ablation that does not evaluate the profile.

arguments
    cfg (1, 1) struct
    observation (:, 1) double {mustBeFinite}
    snapshots (:, :) double
    scan (1, 1) struct = fsjad.prepareScan(cfg)
    protocol (1, 1) struct = r32.config()
end

r32.assertFrozenConfig(cfg, protocol);
if numel(observation) ~= cfg.numSubcarriers ...
        || size(snapshots, 1) ~= cfg.numAntennas ...
        || size(snapshots, 2) ~= cfg.numSubcarriers
    error("r32:OnlineInputSize", ...
        "H_A requires a full z vector and the full N-by-M Y array.");
end
totalTimer = tic;
frontProtocol = r30.config();
frontProtocol.frontVersion = protocol.front.version;
frontProtocol.angleOffsetsDeg = protocol.front.angleOffsetsDeg;
frontOutput = r30.front(cfg, observation, scan, ...
    frontProtocol, r32.candidate(protocol));
front = frontOutput.selected;
carrierIndex = r30.selectLocalCarriers(cfg.numSubcarriers, ...
    protocol.music.carrierCount, frontOutput.peakCarrierIndex);
[state, musicCfg, stateCost] = r30.prepareMusicState(cfg, ...
    snapshots(:, carrierIndex+1), carrierIndex, ...
    front.thetaDeg, front.rangeM, protocol.music.subarraySize);
angleTimer = tic;
angle = r31.stagedAngleMusic(musicCfg, state, front.thetaDeg, ...
    front.rangeM, protocol.music.angleHalfWidthDeg, ...
    protocol.music.gridSizes);
angleSeconds = toc(angleTimer);

result.version = "HA-independent-online-R32-v1";
result.inputContract = "current-z-current-Y-scan-known-config-only";
result.front = frontOutput;
result.state = state;
result.musicCfg = musicCfg;
result.angle = angle;
result.H_A = struct(thetaDeg=angle.thetaDeg, rangeM=front.rangeM, ...
    version=result.version);
result.cost = struct(frontSeconds=frontOutput.runtimeSeconds, ...
    stateSeconds=stateCost.seconds, angleSeconds=angleSeconds, ...
    profileSeconds=0, profileResponses=0, ...
    frontEquivalentResponses=frontOutput.fullEquivalentResponses, ...
    phaseAlignmentTerms=stateCost.phaseAlignmentTerms, ...
    covarianceMacs=stateCost.covarianceMacs, ...
    evdCubicUnits=stateCost.evdCubicUnits, ...
    searchEvaluations=angle.evaluationCount, ...
    angleProjectionMacs=stateCost.carrierCount ...
        *stateCost.subarraySize*angle.evaluationCount, ...
    totalOnlineSeconds=toc(totalTimer));
end
