function result = finalTrial(cfg, scan, row, protocol)
%FINALTRIAL Evaluate the four frozen methods on one shared z/Y realization.

arguments
    cfg (1, 1) struct
    scan (1, 1) struct
    row (1, :) table
    protocol (1, 1) struct = r32.config()
end

result = struct(success=false, errorIdentifier="", errorMessage="", ...
    version="R32-final-shared-components-trial-v1", seed=row.seed, ...
    positionId=row.positionId, snrDb=row.snrDb);
timer = tic;
try
    r32.assertFrozenConfig(cfg, protocol);
    replay = fsjad.replayRound27Data(cfg, scan, row);
    frontProtocol = r30.config();
    frontProtocol.frontVersion = protocol.front.version;
    frontProtocol.angleOffsetsDeg = protocol.front.angleOffsetsDeg;
    frontOutput = r30.front(cfg, replay.observation, scan, ...
        frontProtocol, r32.candidate(protocol));
    front = frontOutput.selected;

    carriersA = r30.selectLocalCarriers(cfg.numSubcarriers, ...
        protocol.music.carrierCount, frontOutput.peakCarrierIndex);
    [stateA, musicCfgA, stateCostA] = r30.prepareMusicState(cfg, ...
        replay.snapshots(:, carriersA+1), carriersA, ...
        front.thetaDeg, front.rangeM, protocol.music.subarraySize);
    angleA = r31.stagedAngleMusic(musicCfgA, stateA, ...
        front.thetaDeg, front.rangeM, protocol.music.angleHalfWidthDeg, ...
        protocol.music.gridSizes);
    profileA = r32.profileAtAngle(cfg, replay.observation, scan, ...
        angleA.thetaDeg, front.rangeM, protocol);
    enhancedC = r31.stagedJointMusic(musicCfgA, stateA, ...
        front.thetaDeg, front.rangeM, ...
        protocol.enhancedC.angleHalfWidthDeg, ...
        protocol.enhancedC.rangeHalfWidthM, protocol.enhancedC.gridSizes);

    carriersPublic = r30.selectLocalCarriers(cfg.numSubcarriers, ...
        protocol.publicC.carrierCount, frontOutput.peakCarrierIndex);
    [statePublic, musicCfgPublic, stateCostPublic] = ...
        r30.prepareMusicState(cfg, ...
        replay.snapshots(:, carriersPublic+1), carriersPublic, ...
        front.thetaDeg, front.rangeM, protocol.publicC.subarraySize);
    publicC = r31.stagedJointMusic(musicCfgPublic, statePublic, ...
        front.thetaDeg, front.rangeM, protocol.publicC.angleHalfWidthDeg, ...
        protocol.publicC.rangeHalfWidthM, protocol.publicC.gridSizes);

    result.methodNames = ["P_A", "C_enhanced", "H_A", "C_public", "F_L06"];
    result.thetaDeg = [angleA.thetaDeg, enhancedC.thetaDeg, ...
        angleA.thetaDeg, publicC.thetaDeg, front.thetaDeg];
    result.rangeM = [profileA.value, enhancedC.rangeM, front.rangeM, ...
        publicC.rangeM, front.rangeM];
    result.front = front;
    result.angleA = angleA;
    result.profileA = profileA;
    result.enhancedC = enhancedC;
    result.publicC = publicC;
    result.cost = struct(frontEquivalentResponses=frontOutput.fullEquivalentResponses, ...
        frontSeconds=frontOutput.runtimeSeconds, stateACost=stateCostA, ...
        statePublicCost=stateCostPublic, ...
        sharedPerformanceComputation=true);
    result.hash = struct(observation=r31.arrayHash(replay.observation), ...
        snapshots=r31.arrayHash(replay.snapshots));
    result.success = all(isfinite(result.thetaDeg)) ...
        && all(isfinite(result.rangeM));
catch exception
    result.errorIdentifier = string(exception.identifier);
    result.errorMessage = string(getReport( ...
        exception, "extended", "hyperlinks", "off"));
end
result.sessionSeconds = toc(timer);
end
