function output = summarizeExisting(project)
%SUMMARIZEEXISTING Add paired statistics to the immutable R31 60-user raw.

arguments
    project (1, 1) string
end

protocol = r32.config();
raw = r31.loadRound30Raw(project);
controlFile = fullfile(project, "results", "full_spectrum", ...
    "round31_angle_controls_v2", "result.mat");
if ~isfile(controlFile)
    error("r32:MissingRound31Raw", ...
        "The complete Round31 60-user result.mat is required.");
end
saved = load(controlFile, "identity", "results");
if numel(saved.results) ~= height(raw.pilot.design) ...
        || any(cellfun(@isempty, saved.results))
    error("r32:IncompleteRound31Raw", ...
        "Round31 must contain every one of the frozen 60 development users.");
end

design = raw.pilot.design;
methods = ["C_enhanced", "H_A", "P_A"];
perUser = table();
for methodIndex = 1:numel(methods)
    theta = cellfun(@(x) x.thetaDeg(methodIndex), saved.results);
    range = cellfun(@(x) x.rangeM(methodIndex), saved.results);
    [angleError, rangeError, positionError] = errors(design, theta, range);
    rows = table(design.seed, design.trialIndex, design.snrDb, ...
        repmat(methods(methodIndex), height(design), 1), theta, range, ...
        angleError, rangeError, positionError, ...
        'VariableNames', {'seed', 'trialIndex', 'snrDb', 'method', ...
        'thetaDeg', 'rangeM', 'angleErrorDeg', 'rangeErrorM', ...
        'positionErrorM'});
    perUser = [perUser; rows]; %#ok<AGROW>
end

methodSummary = table();
for method = methods
    for snrDb = [-10, 0, 20]
        rows = perUser.method == method & perUser.snrDb == snrDb;
        entry = summarizeMethod(perUser(rows, :), protocol.statistics);
        methodSummary = [methodSummary; entry]; %#ok<AGROW>
    end
end

comparisons = table();
for reference = ["C_enhanced", "H_A"]
    for snrDb = [-10, 0, 20]
        candidateRows = perUser(perUser.method == "P_A" ...
            & perUser.snrDb == snrDb, :);
        referenceRows = perUser(perUser.method == reference ...
            & perUser.snrDb == snrDb, :);
        if ~isequal(candidateRows.seed, referenceRows.seed)
            error("r32:UnpairedDevelopmentRows", ...
                "P_A and its reference must share identical seeds.");
        end
        for metric = ["angle", "range", "position"]
            entry = pairedSummary(candidateRows, referenceRows, ...
                metric, protocol.statistics, snrDb, reference);
            comparisons = [comparisons; entry]; %#ok<AGROW>
        end
    end
end

thresholdAudit = thresholdRows(methodSummary, raw.pilot.baseline, protocol);
sameFrontAudit = sameFrontRows(methodSummary);
output = struct(version="R32-existing-raw-statistics-v1", ...
    dataRole=protocol.dataRole, controlIdentity=saved.identity, ...
    protocol=protocol, perUser=perUser, methodSummary=methodSummary, ...
    comparisons=comparisons, thresholdAudit=thresholdAudit, ...
    sameFrontAudit=sameFrontAudit, pilotHash=raw.pilotHash, ...
    baselineHash=raw.baselineHash);
end

function entry = summarizeMethod(rows, statistics)
angleSquared = rows.angleErrorDeg.^2;
rangeSquared = rows.rangeErrorM.^2;
positionSquared = rows.positionErrorM.^2;
entry = table(rows.snrDb(1), rows.method(1), height(rows), ...
    sqrt(mean(angleSquared)), sqrt(mean(rangeSquared)), ...
    sqrt(mean(positionSquared)), quantile(abs(rows.rangeErrorM), 0.95), ...
    mean(abs(rows.rangeErrorM) > statistics.missThresholdM), ...
    tailShare(angleSquared, statistics.tailFraction), ...
    tailShare(rangeSquared, statistics.tailFraction), ...
    tailShare(positionSquared, statistics.tailFraction), ...
    'VariableNames', {'snrDb', 'method', 'n', 'angleRmseDeg', ...
    'rangeRmseM', 'positionRmseM', 'p95RangeM', 'missOver1m', ...
    'angleTop10SseShare', 'rangeTop10SseShare', ...
    'positionTop10SseShare'});
end

function entry = pairedSummary(candidate, reference, metric, ...
    statistics, snrDb, referenceName)
switch metric
    case "angle"
        candidateError = abs(candidate.angleErrorDeg);
        referenceError = abs(reference.angleErrorDeg);
    case "range"
        candidateError = abs(candidate.rangeErrorM);
        referenceError = abs(reference.rangeErrorM);
    otherwise
        candidateError = candidate.positionErrorM;
        referenceError = reference.positionErrorM;
end
deltaSquared = candidateError.^2-referenceError.^2;
stream = RandStream("mt19937ar", Seed=statistics.bootstrapSeed ...
    + 1000*(snrDb+10) + 31*sum(double(char(metric))) ...
    + 7*sum(double(char(referenceName))));
indices = randi(stream, height(candidate), ...
    height(candidate), statistics.bootstrapCount);
bootstrapDelta = mean(deltaSquared(indices), 1);
interval = quantile(bootstrapDelta, [0.025, 0.975]);
strictWin = mean(candidateError < referenceError);
tie = mean(candidateError == referenceError);
entry = table(snrDb, "P_A", referenceName, metric, height(candidate), ...
    mean(deltaSquared), interval(1), interval(2), strictWin, tie, ...
    mean(candidateError <= referenceError), ...
    'VariableNames', {'snrDb', 'candidate', 'reference', 'metric', ...
    'n', 'meanPairedSquaredErrorDifference', 'ci95Low', 'ci95High', ...
    'strictWinRate', 'tieRate', 'nonWorseRate'});
end

function output = thresholdRows(summary, baseline, protocol)
output = table();
for snrDb = [-10, 0, 20]
    pa = summary(summary.method == "P_A" & summary.snrDb == snrDb, :);
    c = baseline(baseline.method == "C_star" & baseline.snrDb == snrDb, :);
    h = baseline(baseline.method == "H_star" & baseline.snrDb == snrDb, :);
    angleDenominator = c.angleRmseDeg;
    rangeDenominator = min(c.rmseM, h.rmseM);
    positionDenominator = min(c.jointRmseM, h.jointRmseM);
    p95Denominator = min(c.p95M, h.p95M);
    missDenominator = min(c.missOver1m, h.missOver1m);
    row = table(snrDb, pa.angleRmseDeg, angleDenominator, ...
        pa.angleRmseDeg/angleDenominator, ...
        protocol.acceptance.angleRmseRatio, pa.rangeRmseM, ...
        rangeDenominator, pa.rangeRmseM/rangeDenominator, ...
        protocol.acceptance.rangeRmseRatio, pa.positionRmseM, ...
        positionDenominator, pa.positionRmseM/positionDenominator, ...
        protocol.acceptance.positionRmseRatio, pa.p95RangeM, ...
        p95Denominator, pa.p95RangeM/p95Denominator, ...
        protocol.acceptance.p95Ratio, pa.missOver1m, missDenominator, ...
        pa.missOver1m-missDenominator, ...
        protocol.acceptance.missRateIncrease, ...
        'VariableNames', {'snrDb', 'paAngleRmseDeg', ...
        'r29AngleDenominatorCstarDeg', 'angleRatio', ...
        'angleLimit', 'paRangeRmseM', 'r29BestRangeDenominatorM', ...
        'rangeRatio', 'rangeLimit', 'paPositionRmseM', ...
        'r29BestPositionDenominatorM', 'positionRatio', ...
        'positionLimit', 'paP95RangeM', 'r29BestP95DenominatorM', ...
        'p95Ratio', 'p95Limit', 'paMissRate', 'r29BestMissRate', ...
        'missIncrease', 'missIncreaseLimit'});
    output = [output; row]; %#ok<AGROW>
end
end

function output = sameFrontRows(summary)
output = table();
for snrDb = [-10, 0, 20]
    pa = summary(summary.method == "P_A" & summary.snrDb == snrDb, :);
    c = summary(summary.method == "C_enhanced" ...
        & summary.snrDb == snrDb, :);
    row = table(snrDb, pa.angleRmseDeg/c.angleRmseDeg, ...
        pa.rangeRmseM/c.rangeRmseM, pa.positionRmseM/c.positionRmseM, ...
        pa.p95RangeM/c.p95RangeM, pa.missOver1m-c.missOver1m, ...
        'VariableNames', {'snrDb', 'angleRmseRatioPaOverC', ...
        'rangeRmseRatioPaOverC', 'positionRmseRatioPaOverC', ...
        'p95RatioPaOverC', 'missRateDifferencePaMinusC'});
    output = [output; row]; %#ok<AGROW>
end
end

function share = tailShare(squaredError, fraction)
count = max(1, ceil(numel(squaredError)*fraction));
ordered = sort(squaredError, "descend");
denominator = sum(ordered);
if denominator == 0
    share = 0;
else
    share = sum(ordered(1:count))/denominator;
end
end

function [angleError, rangeError, positionError] = errors(design, theta, range)
angleError = theta-design.truthThetaDeg;
rangeError = range-design.truthRangeM;
xError = range.*sind(theta)-design.truthRangeM.*sind(design.truthThetaDeg);
yError = range.*cosd(theta)-design.truthRangeM.*cosd(design.truthThetaDeg);
positionError = hypot(xError, yError);
end
