function protocol = config()
%CONFIG Frozen R44 clock-invariant sequential development protocol.

protocol.version = "R44-clock-invariant-sequential-development-v1";
protocol.date = "2026-09-17";
protocol.evidenceRole = "new-development-and-prespecified-timing-stress";
protocol.method = struct(primary="H_seqVP", baseline="P_A", ...
    zhangBaseline="C_enhanced", ablation="H_seqZ");
r32Protocol = r32.config();
protocol.front = r32Protocol.front;
protocol.array = struct(carrierCount=2047, angleHalfWidthDeg=0.2, ...
    coarseAngleGridSize=41, tolXDeg=1e-7);
protocol.profile = r32Protocol.profile;
protocol.development = struct(snrDb=[-10, 0, 20], ...
    positionCount=10, positionSeed=58000000, ...
    trialSeedRoot=58100000, angleLimitsDeg=[-55, 55], ...
    rangeLimitsM=[17, 48], missThresholdM=1);
protocol.gate = struct(maxPerSnrMseRatio=1.05, ...
    maxAggregateAngleMseRatioToPA=0.98, ...
    maxAggregateRangeMseRatioToPA=0.98, ...
    maxAggregateMseRatioToC=1.0);
protocol.timingStress = struct(snrDb=0, ...
    residualDelaySeconds=[-0.1e-9, 0.1e-9], ...
    maxAngleShiftDeg=1e-8, maxRangeShiftM=1e-6);
protocol.execution = struct(r34FinalReadAllowed=false, ...
    r41FinalReadAllowed=false, priorDevelopmentResultReadAllowed=false, ...
    finalTrialsExecuted=0, parameterTuningFromPilotAllowed=false, ...
    calibrationAuthorized=false, independentFinalAuthorized=false);
end
