function result = estimate(cfg, observation, snapshots, scan, protocol)
%ESTIMATE Standalone PA-free and clock-invariant sequential estimator.

arguments
    cfg (1, 1) struct
    observation (:, 1) double {mustBeFinite}
    snapshots (:, :) double
    scan (1, 1) struct = fsjad.prepareScan(cfg)
    protocol (1, 1) struct = r44.config()
end

if numel(observation) ~= cfg.numSubcarriers ...
        || size(snapshots, 1) ~= cfg.numAntennas ...
        || size(snapshots, 2) ~= cfg.numSubcarriers
    error("r44:OnlineInputSize", ...
        "R44 requires a full z vector and the full N-by-M Y array.");
end
totalTimer = tic;
frontProtocol = r30.config();
frontProtocol.frontVersion = protocol.front.version;
frontProtocol.angleOffsetsDeg = protocol.front.angleOffsetsDeg;
front = r30.front(cfg, observation, scan, frontProtocol, r32.candidate());
selectedFront = front.selected;
carrierIndex = r30.selectLocalCarriers(cfg.numSubcarriers, ...
    protocol.array.carrierCount, front.peakCarrierIndex);
context = r42.prepareContext(cfg, scan, observation, ...
    snapshots(:, carrierIndex+1), carrierIndex);
angle = r43.fullArrayAngle(cfg, context, selectedFront, protocol);

zTimer = tic;
zProfile = r32.profileAtAngle(cfg, observation, scan, ...
    angle.thetaDeg, selectedFront.rangeM, r32.config());
zSeconds = toc(zTimer);
vpProfile = r44.profileVpRange( ...
    cfg, context, angle.thetaDeg, selectedFront.rangeM, protocol);

result = struct(version=protocol.version, ...
    inputContract="current-z-current-Y-scan-known-config-only", ...
    nuisanceModel="independent-complex-gain-per-carrier", ...
    front=front, angle=angle, contextCarrierIndex=carrierIndex, ...
    H_seqZ=struct(thetaDeg=angle.thetaDeg, rangeM=zProfile.value, ...
    version="R44-full-array-angle-q-range-v1"), ...
    H_seqVP=struct(thetaDeg=angle.thetaDeg, rangeM=vpProfile.value, ...
    version="R44-full-array-phase-invariant-sequential-v1"), ...
    zProfile=zProfile, vpProfile=vpProfile, ...
    cost=struct(frontSeconds=front.runtimeSeconds, ...
    angleSeconds=angle.runtimeSeconds, zProfileSeconds=zSeconds, ...
    vpProfileSeconds=vpProfile.runtimeSeconds, ...
    totalOnlineSeconds=toc(totalTimer)));
end
