function output = certificates( ...
    cfg, front, angle, profile, arrayContext, split, protocol)
%CERTIFICATES Evaluate the four frozen truth-free support-risk certificates.

arguments
    cfg (1, 1) struct
    front (1, 1) struct
    angle (1, 1) struct
    profile (1, 1) struct
    arrayContext (1, 1) struct
    split (1, 1) struct
    protocol (1, 1) struct = r51.config()
end

[~, gridBestIndex] = max(angle.gridScore);
tolerance = protocol.certificate.angleBoundaryToleranceScale ...
    *eps(max(1, max(abs(angle.boundsDeg))));
continuousBoundary = abs(angle.thetaDeg-angle.boundsDeg(1)) <= tolerance ...
    || abs(angle.thetaDeg-angle.boundsDeg(2)) <= tolerance;
c1 = gridBestIndex == 1 || gridBestIndex == numel(angle.gridDeg) ...
    || continuousBoundary;

rangeTolerance = protocol.certificate.rangeBoundaryIntervals ...
    *profile.coarseSpacingM+64*eps(max(1, max(abs(profile.interval))));
distanceToRangeBoundary = min(abs(profile.value-profile.interval));
c2 = distanceToRangeBoundary <= rangeTolerance;

[oddBest, evenBest, candidateAudit] = splitCandidateRanking( ...
    cfg, front, split, protocol);
sameCandidateBasin = abs(oddBest.thetaDeg-evenBest.thetaDeg) ...
    <= protocol.certificate.sameBasinAngleDeg ...
    && abs(oddBest.rangeM-evenBest.rangeM) ...
    <= protocol.certificate.sameBasinRangeM;
c3 = ~sameCandidateBasin;

angleGeometry = r47.angleUncertainty(cfg, arrayContext, ...
    angle.thetaDeg, front.selected.rangeM, protocol.r50.r48.r47);
responseContext = joinContexts(split, cfg);
rangeGeometry = r50.qHessian( ...
    cfg, responseContext, angle.thetaDeg, profile.value, protocol.r50);
c4Angle = ~angleGeometry.validCurvature;
c4Range = ~rangeGeometry.valid;
c4 = c4Angle || c4Range;

output = struct(version="R51-support-risk-certificates-v1", ...
    C1=c1, C2=c2, C3=c3, C4=c4, C4Angle=c4Angle, C4Range=c4Range, ...
    trigger=c1 || c2 || c3 || c4, ...
    angleRecoveryRequired=c1 || c3 || c4Angle, ...
    rangeRecoveryRequired=c2 || c3 || c4Range, ...
    angleGridBestIndex=gridBestIndex, ...
    angleContinuousBoundary=continuousBoundary, ...
    rangeDistanceToBoundaryM=distanceToRangeBoundary, ...
    oddBestCandidateIndex=oddBest.index, ...
    evenBestCandidateIndex=evenBest.index, ...
    oddBestThetaDeg=oddBest.thetaDeg, oddBestRangeM=oddBest.rangeM, ...
    evenBestThetaDeg=evenBest.thetaDeg, evenBestRangeM=evenBest.rangeM, ...
    splitBestSameBasin=sameCandidateBasin, ...
    angleGeometry=angleGeometry, rangeGeometry=rangeGeometry, ...
    candidateAudit=candidateAudit);
end

function [oddBest, evenBest, audit] = splitCandidateRanking( ...
    cfg, front, split, ~)
count = numel(front.refined);
thetaDeg = zeros(count, 1);
rangeM = zeros(count, 1);
oddScore = zeros(count, 1);
evenScore = zeros(count, 1);
for index = 1:count
    thetaDeg(index) = front.refined{index}.thetaDeg;
    rangeM(index) = front.refined{index}.rangeM;
    oddScore(index) = r33.fixedAngleProfileLogScore( ...
        cfg, thetaDeg(index), rangeM(index), split.odd);
    evenScore(index) = r33.fixedAngleProfileLogScore( ...
        cfg, thetaDeg(index), rangeM(index), split.even);
end
[~, oddIndex] = max(oddScore);
[~, evenIndex] = max(evenScore);
oddBest = struct(index=oddIndex, thetaDeg=thetaDeg(oddIndex), ...
    rangeM=rangeM(oddIndex), score=oddScore(oddIndex));
evenBest = struct(index=evenIndex, thetaDeg=thetaDeg(evenIndex), ...
    rangeM=rangeM(evenIndex), score=evenScore(evenIndex));
audit = table((1:count).', thetaDeg, rangeM, oddScore, evenScore, ...
    'VariableNames', {'candidateIndex', 'thetaDeg', 'rangeM', ...
    'oddLogScore', 'evenLogScore'});
if count ~= 8
    warning("r51:UnexpectedFrontCandidateCount", ...
        "R51 expected eight frozen L06 refined candidates, received %d.", count);
end
end

function context = joinContexts(split, cfg)
carrierCount = numel(split.oddCarrierIndex)+numel(split.evenCarrierIndex);
if carrierCount ~= cfg.numSubcarriers
    error("r51:InvalidSpectrumSplit", ...
        "The fixed spectrum split must cover every carrier exactly once.");
end
% The exact full context is reconstructed from the split pieces without
% changing carrier order.
observation = zeros(cfg.numSubcarriers, 1);
observation(split.oddCarrierIndex+1) = split.odd.observation;
observation(split.evenCarrierIndex+1) = split.even.observation;
context = split.odd;
context.x = split.odd.x;
context.xSquared = split.odd.xSquared;
context.wavenumber = zeros(1, cfg.numSubcarriers);
context.conjugateBeamformer = zeros(cfg.numAntennas, cfg.numSubcarriers);
context.wavenumber(split.oddCarrierIndex+1) = split.odd.wavenumber;
context.wavenumber(split.evenCarrierIndex+1) = split.even.wavenumber;
context.conjugateBeamformer(:, split.oddCarrierIndex+1) = ...
    split.odd.conjugateBeamformer;
context.conjugateBeamformer(:, split.evenCarrierIndex+1) = ...
    split.even.conjugateBeamformer;
context.observation = observation;
context.observationEnergy = real(observation'*observation);
context.carrierCount = cfg.numSubcarriers;
end
