function protocol = config()
%CONFIG Freeze the R51 reliability-certified recovery development study.

protocol.version = "R51-PFARC-reliability-certified-recovery-development-v1";
protocol.date = "2026-09-18";
protocol.evidenceRole = "post-R50-development-mechanism-not-calibration";
protocol.method = struct(primary="P_FARC", base="P_FA", baseline="P_A", ...
    ablations=["trigger_only", "unconditional_wide_global"], ...
    paFree=true, musicFree=true, evdFree=true, ...
    normalFallback="exact-frozen-P_FA");
protocol.r50 = r50.config();
protocol.base = protocol.r50.r48.r47.r45;

protocol.certificate = struct( ...
    angleBoundaryToleranceScale=16, ...
    rangeBoundaryIntervals=1, ...
    sameBasinAngleDeg=0.2, sameBasinRangeM=2.0, ...
    thetaStepDeg=1e-4, rangeStepM=1e-3, curvatureFloor=1e-12, ...
    trigger="C1-or-C2-or-C3-or-C4");
protocol.recovery = struct( ...
    angleHalfWidthDeg=0.6, angleGridSpacingDeg=0.01, ...
    rangeCoarseSpacingM=0.1, peakCount=8, tolXM=1e-6, ...
    scoreTolerance=1e-10, numericalToleranceScale=64, ...
    split="one-based-odd-versus-one-based-even-carrier-indices", ...
    validation="cross-fitted-range-candidates-conditional-on-full-data-trigger", ...
    candidateFamilies=["wide_local", "remote"], ...
    acceptedCandidateRule="largest-minimum-cross-score-gain", ...
    remoteBasinRule="same-side-and-within-frozen-2m-support-width");

protocol.normalDesign = struct(positionCount=20, snrDb=[-10, 0, 20], ...
    angleLimitsDeg=[-60, 60], rangeLimitsM=[15, 50], ...
    positionSeed=66000000, trialSeedRoot=66100000, expectedRows=60);
protocol.stressDesign = struct(positionCount=6, snrDb=[-10, 0, 20], ...
    types=["angle", "range", "joint"], ...
    angleLimitsDeg=[-50, 50], rangeLimitsM=[20, 45], ...
    angleOffsetDeg=0.45, rangeOffsetM=3.0, ...
    positionSeed=66200000, trialSeedRoot=66300000, expectedRows=54, ...
    signRule="alternating-by-position-balanced", ...
    truthUsedOnlyForControlledFrontCenterConstruction=true);

protocol.bootstrap = struct(count=10000, seed=66400000, ...
    confidence=0.95, cluster="positionId", sharedAcrossSnr=true);
protocol.gate = struct( ...
    maxAggregateAngleMseRatioToPFA=1.01, ...
    maxPerSnrAngleMseRatioToPFA=1.02, ...
    maxAggregateRangeMseRatioToPA=1.00, ...
    maxPerSnrRangeMseRatioToPA=1.02, ...
    requireZeroFailures=true, ...
    requireStressTriggerSensitivity=0.80, ...
    maxStressWrongRecoveryAcceptedRate=0.10, ...
    runtimeReference="C_enhanced-matched-standalone");
protocol.timing = struct(positionIds=1:3, snrDb=0, repetitions=2, ...
    warmups=1, methods=["P_FARC", "C_enhanced"]);
protocol.execution = struct(recommendedWorkers=8, batchSize=6, ...
    finalRowsAccessible=false, calibrationAllowed=false, ...
    parameterTuningAllowed=false, modifyFrozenMethods=false, ...
    historicalReplayPositionId=124, historicalReplaySnrDb=-10, ...
    stopAfterDevelopment=true);
end
