function result = fromFront( ...
    cfg, observation, snapshots, scan, front, protocol)
%FROMFRONT Run frozen P_FA, certificates, ablations and primary P_FARC.

arguments
    cfg (1, 1) struct
    observation (:, 1) double {mustBeFinite}
    snapshots (:, :) double
    scan (1, 1) struct
    front (1, 1) struct
    protocol (1, 1) struct = r51.config()
end

totalTimer = tic;
carrierIndex = r30.selectLocalCarriers(cfg.numSubcarriers, ...
    protocol.base.pfa.carrierCount, front.peakCarrierIndex);
contextTimer = tic;
arrayContext = r38PrepareRawArrayVpmlContext( ...
    cfg, snapshots(:, carrierIndex+1), carrierIndex);
contextSeconds = toc(contextTimer);
responseContext = r33.prepareResponseContext(cfg, scan, observation);
split = r51.splitContexts(cfg, observation, scan);

baseTimer = tic;
baseAngle = r45.fullArrayAngle( ...
    cfg, arrayContext, front.selected, protocol.base);
baseProfile = r33.profileAtAngle(cfg, observation, scan, ...
    baseAngle.thetaDeg, front.selected.rangeM, protocol.base.r34.r33);
baseSeconds = toc(baseTimer);
base = struct(thetaDeg=baseAngle.thetaDeg, rangeM=baseProfile.value, ...
    angle=baseAngle, profile=baseProfile);

certificateTimer = tic;
certificate = r51.certificates(cfg, front, baseAngle, baseProfile, ...
    arrayContext, split, protocol);
certificateSeconds = toc(certificateTimer);

recovery = fallbackRecovery(base);
unconditional = location(base.thetaDeg, base.rangeM);
unconditionalSeconds = 0;
if certificate.trigger
    recovery = r51.recover(cfg, front, base, arrayContext, ...
        responseContext, split, certificate, protocol);

    unconditionalTimer = tic;
    wideProtocol = protocol.base;
    wideProtocol.pfa.angleHalfWidthDeg = protocol.recovery.angleHalfWidthDeg;
    wideProtocol.pfa.coarseAngleGridSize = round( ...
        2*protocol.recovery.angleHalfWidthDeg ...
        /protocol.recovery.angleGridSpacingDeg)+1;
    wide = r45.fullArrayAngle(cfg, arrayContext, front.selected, wideProtocol);
    globalProtocol = r49.config();
    globalProfile = r49.globalProfileAtAngle(cfg, wide.thetaDeg, ...
        responseContext, front.selected.rangeM, globalProtocol);
    unconditional = location(wide.thetaDeg, globalProfile.value);
    unconditionalSeconds = toc(unconditionalTimer);
end

primarySeconds = front.runtimeSeconds+contextSeconds+baseSeconds ...
    +certificateSeconds+recovery.runtimeSeconds;
result = struct(version=protocol.version, ...
    P_FA=location(base.thetaDeg, base.rangeM), ...
    P_FARC=location(recovery.thetaDeg, recovery.rangeM), ...
    trigger_only=location(base.thetaDeg, base.rangeM), ...
    unconditional_wide_global=unconditional, ...
    frontThetaDeg=front.selected.thetaDeg, ...
    frontRangeM=front.selected.rangeM, carrierIndex=carrierIndex, ...
    baseAngle=baseAngle, baseProfile=compactProfile(baseProfile), ...
    certificate=certificate, recovery=recovery, ...
    contextSeconds=contextSeconds, baseSeconds=baseSeconds, ...
    certificateSeconds=certificateSeconds, ...
    conditionalRecoverySeconds=recovery.runtimeSeconds, ...
    unconditionalRecoverySeconds=unconditionalSeconds, ...
    primaryCompleteSeconds=primarySeconds, ...
    backendSeconds=toc(totalTimer), musicEvaluationCount=0, evdCount=0);
end

function output = fallbackRecovery(base)
output = struct(version="R51-PFARC-conditional-recovery-v1", ...
    accepted=false, fallback=true, selectedFamily="not-triggered", ...
    selectedCandidateIndex=0, thetaDeg=base.thetaDeg, ...
    rangeM=base.rangeM, wideAngle=struct(), ...
    candidates=repmat(struct(), 0, 1), finalProfile=struct(), ...
    runtimeSeconds=0);
end

function output = compactProfile(input)
output = struct(value=input.value, score=input.score, ...
    interval=input.interval, endpointHit=input.endpointHit, ...
    nearBoundary=input.nearBoundary, ...
    endpointOutwardTrend=input.endpointOutwardTrend, ...
    coarseSpacingM=input.coarseSpacingM, ...
    evaluationCount=input.evaluationCount, ...
    retentionMargin=input.retentionMargin);
end

function output = location(thetaDeg, rangeM)
output = struct(thetaDeg=thetaDeg, rangeM=rangeM);
end
