function output = recover(cfg, front, base, arrayContext, ...
    responseContext, split, certificates, protocol)
%RECOVER Run conditional wide/local and remote split-validated recovery.

arguments
    cfg (1, 1) struct
    front (1, 1) struct
    base (1, 1) struct
    arrayContext (1, 1) struct
    responseContext (1, 1) struct
    split (1, 1) struct
    certificates (1, 1) struct
    protocol (1, 1) struct = r51.config()
end

timer = tic;
wideAngle = emptyAngle(base.thetaDeg);
if certificates.angleRecoveryRequired
    wideProtocol = protocol.base;
    wideProtocol.pfa.angleHalfWidthDeg = protocol.recovery.angleHalfWidthDeg;
    wideProtocol.pfa.coarseAngleGridSize = round( ...
        2*protocol.recovery.angleHalfWidthDeg ...
        /protocol.recovery.angleGridSpacingDeg)+1;
    wideAngle = r45.fullArrayAngle( ...
        cfg, arrayContext, front.selected, wideProtocol);
    candidateThetaDeg = wideAngle.thetaDeg;
else
    candidateThetaDeg = base.thetaDeg;
end

seedRangeM = zeros(numel(front.refined), 1);
for index = 1:numel(front.refined)
    seedRangeM(index) = front.refined{index}.rangeM;
end

candidates = repmat(emptyCandidate(), 0, 1);
if certificates.angleRecoveryRequired
    candidates(end+1, 1) = r51.crossValidateFamily( ...
        cfg, "wide_local", candidateThetaDeg, base.thetaDeg, ...
        base.rangeM, base.profile.interval, split, seedRangeM, protocol); %#ok<AGROW>
end
candidates(end+1, 1) = r51.crossValidateFamily( ...
    cfg, "remote", candidateThetaDeg, base.thetaDeg, ...
    base.rangeM, base.profile.interval, split, seedRangeM, protocol);

accepted = find([candidates.accepted]);
if isempty(accepted)
    output = fallback(base, wideAngle, candidates, toc(timer));
    return;
end
[~, bestLocal] = max([candidates(accepted).minimumCrossGain]);
selectedIndex = accepted(bestLocal);
selected = candidates(selectedIndex);
centerRangeM = mean([selected.oddRangeM, selected.evenRangeM]);
if selected.family == "wide_local"
    finalInterval = base.profile.interval;
else
    finalInterval = [max(cfg.rangeLimitsM(1), ...
        centerRangeM-protocol.certificate.sameBasinRangeM), ...
        min(cfg.rangeLimitsM(2), ...
        centerRangeM+protocol.certificate.sameBasinRangeM)];
end
finalProfile = r51.profileInterval(cfg, selected.thetaDeg, ...
    responseContext, finalInterval, centerRangeM, protocol);
output = struct(version="R51-PFARC-conditional-recovery-v1", ...
    accepted=true, fallback=false, selectedFamily=selected.family, ...
    selectedCandidateIndex=selectedIndex, thetaDeg=selected.thetaDeg, ...
    rangeM=finalProfile.value, wideAngle=wideAngle, ...
    candidates=candidates, finalProfile=compactProfile(finalProfile), ...
    runtimeSeconds=toc(timer));
end

function output = fallback(base, wideAngle, candidates, runtimeSeconds)
output = struct(version="R51-PFARC-conditional-recovery-v1", ...
    accepted=false, fallback=true, selectedFamily="none", ...
    selectedCandidateIndex=0, thetaDeg=base.thetaDeg, ...
    rangeM=base.rangeM, wideAngle=wideAngle, candidates=candidates, ...
    finalProfile=struct(), runtimeSeconds=runtimeSeconds);
end

function output = compactProfile(input)
output = struct(value=input.value, score=input.score, ...
    interval=input.interval, endpointHit=input.endpointHit, ...
    nearBoundary=input.nearBoundary, evaluationCount=input.evaluationCount, ...
    retentionMargin=input.retentionMargin);
end

function output = emptyAngle(thetaDeg)
output = struct(thetaDeg=thetaDeg, score=nan, boundsDeg=[nan, nan], ...
    gridDeg=zeros(0, 1), gridScore=zeros(0, 1), ...
    fullArrayEvaluationCount=0, runtimeSeconds=0);
end

function output = emptyCandidate()
output = struct(version="", family="", thetaDeg=nan, valid=false, ...
    oddRangeM=nan, evenRangeM=nan, oddGeneratedScore=nan, ...
    evenGeneratedScore=nan, oddCrossGain=nan, evenCrossGain=nan, ...
    minimumCrossGain=nan, oddTolerance=nan, evenTolerance=nan, ...
    crossPassOdd=false, crossPassEven=false, basinConsistent=false, ...
    oddSide=0, evenSide=0, accepted=false, evaluationCount=0);
end
