function output = summarize(normalDesign, normalResults, ...
    stressDesign, stressResults, protocol)
%SUMMARIZE Build R51 normal gates and controlled-stress diagnostics.

arguments
    normalDesign table
    normalResults (:, 1) cell
    stressDesign table
    stressResults (:, 1) cell
    protocol (1, 1) struct = r51.config()
end

assertComplete(normalDesign, normalResults, "normal");
assertComplete(stressDesign, stressResults, "stress");
methods = ["P_A", "P_FA", "P_FARC", "trigger_only", ...
    "unconditional_wide_global", "C_enhanced"];
normal = perUserTable(normalDesign, normalResults, methods);
stress = perUserTable(stressDesign, stressResults, methods);
normal = appendDiagnostics(normal, normalResults);
stress = appendDiagnostics(stress, stressResults);

methodSummary = summarizeMethods(normal, methods, protocol.normalDesign.snrDb);
comparisons = compareAll(normal, ...
    ["P_FARC", "unconditional_wide_global"], ["P_A", "P_FA"], ...
    protocol.normalDesign.snrDb);
bootstrap = [ ...
    r51.bootstrapRatio(normal, "P_FARC", "P_FA", "angle", protocol, 1); ...
    r51.bootstrapRatio(normal, "P_FARC", "P_A", "range", protocol, 2); ...
    r51.bootstrapRatio(normal, "P_FARC", "P_FA", "range", protocol, 3)];
normalDiagnostics = diagnosticSummary(normal);
stressSummary = summarizeStress(stress, protocol);
gate = buildGate(comparisons, normalDiagnostics, stressSummary, protocol);
output = struct(version="R51-PFARC-development-summary-v1", ...
    normalPerUser=normal, stressPerUser=stress, ...
    methodSummary=methodSummary, comparisons=comparisons, ...
    bootstrap=bootstrap, normalDiagnostics=normalDiagnostics, ...
    stressSummary=stressSummary, gate=gate, ...
    developmentPass=all(gate.pass));
end

function assertComplete(design, results, label)
if numel(results) ~= height(design) || any(cellfun(@isempty, results)) ...
        || any(cellfun(@(item) ~item.success, results))
    error("r51:IncompleteDevelopment", ...
        "R51 requires every %s development row.", label);
end
end

function output = perUserTable(design, results, methods)
keep = intersect(["positionId", "seed", "trialIndex", "snrDb", ...
    "stressType", "stressSign", "truthThetaDeg", "truthRangeM"], ...
    string(design.Properties.VariableNames), "stable");
output = design(:, keep);
for method = methods
    theta = cellfun(@(item) item.(method).thetaDeg, results);
    rangeM = cellfun(@(item) item.(method).rangeM, results);
    output.("theta_"+method) = theta;
    output.("range_"+method) = rangeM;
    output.("angleError_"+method) = theta-output.truthThetaDeg;
    output.("rangeError_"+method) = rangeM-output.truthRangeM;
end
end

function output = appendDiagnostics(output, results)
output.C1 = cellfun(@(item) item.backend.certificate.C1, results);
output.C2 = cellfun(@(item) item.backend.certificate.C2, results);
output.C3 = cellfun(@(item) item.backend.certificate.C3, results);
output.C4 = cellfun(@(item) item.backend.certificate.C4, results);
output.C4Angle = cellfun(@(item) item.backend.certificate.C4Angle, results);
output.C4Range = cellfun(@(item) item.backend.certificate.C4Range, results);
output.trigger = cellfun(@(item) item.backend.certificate.trigger, results);
output.recoveryAccepted = cellfun( ...
    @(item) item.backend.recovery.accepted, results);
output.recoveryFamily = cellfun( ...
    @(item) string(item.backend.recovery.selectedFamily), results);
output.top8TruthBasinCovered = cellfun( ...
    @(item) item.candidateCoverage.top8TruthBasinCovered, results);
output.minimumTop8AngleErrorDeg = cellfun( ...
    @(item) item.candidateCoverage.minimumTop8AngleErrorDeg, results);
output.minimumTop8RangeErrorM = cellfun( ...
    @(item) item.candidateCoverage.minimumTop8RangeErrorM, results);
output.primaryCompleteSeconds = cellfun( ...
    @(item) item.backend.primaryCompleteSeconds, results);
output.conditionalRecoverySeconds = cellfun( ...
    @(item) item.backend.conditionalRecoverySeconds, results);
end

function output = summarizeMethods(perUser, methods, snrValues)
output = table();
for method = methods
    for snr = snrValues
        selected = perUser.snrDb == snr;
        ae = perUser.("angleError_"+method)(selected);
        re = perUser.("rangeError_"+method)(selected);
        output = [output; table(method, snr, nnz(selected), ...
            mean(ae.^2), sqrt(mean(ae.^2)), mean(re.^2), ...
            sqrt(mean(re.^2)), quantile(abs(re), .95), ...
            mean(abs(re)>1), 'VariableNames', {'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', 'rangeMseM2', ...
            'rangeRmseM', 'rangeP95AbsM', 'rangeMissRateOver1M'})]; %#ok<AGROW>
    end
end
end

function output = compareAll(perUser, candidates, references, snrValues)
output = table();
for candidate = candidates
    for reference = references
        candidateAngleMse = zeros(numel(snrValues), 1);
        referenceAngleMse = zeros(numel(snrValues), 1);
        candidateRangeMse = zeros(numel(snrValues), 1);
        referenceRangeMse = zeros(numel(snrValues), 1);
        for index = 1:numel(snrValues)
            snr = snrValues(index);
            selected = perUser.snrDb == snr;
            ca = perUser.("angleError_"+candidate)(selected).^2;
            ra = perUser.("angleError_"+reference)(selected).^2;
            cr = perUser.("rangeError_"+candidate)(selected).^2;
            rr = perUser.("rangeError_"+reference)(selected).^2;
            candidateAngleMse(index) = mean(ca);
            referenceAngleMse(index) = mean(ra);
            candidateRangeMse(index) = mean(cr);
            referenceRangeMse(index) = mean(rr);
            output = [output; comparisonRow(candidate, reference, ...
                "per-SNR", snr, ca, ra, cr, rr)]; %#ok<AGROW>
        end
        cr = perUser.("rangeError_"+candidate).^2;
        rr = perUser.("rangeError_"+reference).^2;
        output = [output; table(candidate, reference, "equal-SNR", nan, ...
            height(perUser), mean(candidateAngleMse)/mean(referenceAngleMse), ...
            mean(candidateRangeMse)/mean(referenceRangeMse), ...
            nnz(cr<rr), nnz(cr==rr), nnz(cr>rr), ...
            mean(cr-rr), 'VariableNames', output.Properties.VariableNames)]; %#ok<AGROW>
    end
end
end

function output = comparisonRow(candidate, reference, scope, snrDb, ...
    candidateAngle, referenceAngle, candidateRange, referenceRange)
output = table(candidate, reference, scope, snrDb, numel(candidateRange), ...
    mean(candidateAngle)/mean(referenceAngle), ...
    mean(candidateRange)/mean(referenceRange), ...
    nnz(candidateRange<referenceRange), ...
    nnz(candidateRange==referenceRange), ...
    nnz(candidateRange>referenceRange), ...
    mean(candidateRange-referenceRange), ...
    'VariableNames', {'candidate', 'reference', 'scope', 'snrDb', 'n', ...
    'angleMseRatio', 'rangeMseRatio', 'rangeWinCount', ...
    'rangeTieCount', 'rangeLossCount', 'meanRangeSquaredErrorDifference'});
end

function output = diagnosticSummary(perUser)
output = table(height(perUser), mean(perUser.trigger), mean(perUser.C1), ...
    mean(perUser.C2), mean(perUser.C3), mean(perUser.C4), ...
    mean(perUser.recoveryAccepted), mean(perUser.top8TruthBasinCovered), ...
    mean(perUser.primaryCompleteSeconds), ...
    mean(perUser.conditionalRecoverySeconds(perUser.trigger)), ...
    'VariableNames', {'n', 'triggerRate', 'C1Rate', 'C2Rate', ...
    'C3Rate', 'C4Rate', 'recoveryAcceptedRate', ...
    'top8TruthBasinCoverageRate', 'meanPrimaryCompleteSeconds', ...
    'meanConditionalRecoverySecondsWhenTriggered'});
end

function output = summarizeStress(perUser, protocol)
output = table();
for stressType = protocol.stressDesign.types
    selected = perUser.stressType == stressType;
    baseAngle = abs(perUser.angleError_P_FA(selected));
    newAngle = abs(perUser.angleError_P_FARC(selected));
    baseRange = abs(perUser.rangeError_P_FA(selected));
    newRange = abs(perUser.rangeError_P_FARC(selected));
    accepted = perUser.recoveryAccepted(selected);
    output = [output; table(stressType, nnz(selected), ...
        mean(perUser.trigger(selected)), mean(accepted), ...
        mean(perUser.top8TruthBasinCovered(selected)), ...
        mean(baseAngle), mean(newAngle), mean(baseRange), mean(newRange), ...
        nnz(baseRange>1 & newRange<1), nnz(baseRange>1), ...
        mean(accepted & newAngle>baseAngle+1e-12), ...
        mean(accepted & newRange>baseRange+1e-9), ...
        'VariableNames', {'stressType', 'n', 'triggerSensitivity', ...
        'recoveryAcceptedRate', 'top8TruthBasinCoverageRate', ...
        'baseMeanAbsAngleErrorDeg', 'newMeanAbsAngleErrorDeg', ...
        'baseMeanAbsRangeErrorM', 'newMeanAbsRangeErrorM', ...
        'baseOver1MRecoveredCount', 'baseOver1MCount', ...
        'acceptedAngleWorseningRate', 'acceptedRangeWorseningRate'})]; %#ok<AGROW>
end
end

function output = buildGate(comparisons, diagnostics, stress, protocol)
pfa = comparisons(comparisons.candidate == "P_FARC" ...
    & comparisons.reference == "P_FA", :);
pa = comparisons(comparisons.candidate == "P_FARC" ...
    & comparisons.reference == "P_A", :);
aggregateAngle = pfa.angleMseRatio(pfa.scope == "equal-SNR");
perSnrAngle = max(pfa.angleMseRatio(pfa.scope == "per-SNR"));
aggregateRange = pa.rangeMseRatio(pa.scope == "equal-SNR");
perSnrRange = max(pa.rangeMseRatio(pa.scope == "per-SNR"));
stressSensitivity = min(stress.triggerSensitivity);
wrongRecovery = max(stress.acceptedRangeWorseningRate);
metric = ["aggregate-angle/P_FA"; "max-per-SNR-angle/P_FA"; ...
    "aggregate-range/P_A"; "max-per-SNR-range/P_A"; ...
    "minimum-stress-trigger-sensitivity"; ...
    "maximum-stress-wrong-recovery-rate"];
value = [aggregateAngle; perSnrAngle; aggregateRange; perSnrRange; ...
    stressSensitivity; wrongRecovery];
limit = [protocol.gate.maxAggregateAngleMseRatioToPFA; ...
    protocol.gate.maxPerSnrAngleMseRatioToPFA; ...
    protocol.gate.maxAggregateRangeMseRatioToPA; ...
    protocol.gate.maxPerSnrRangeMseRatioToPA; ...
    protocol.gate.requireStressTriggerSensitivity; ...
    protocol.gate.maxStressWrongRecoveryAcceptedRate];
direction = ["<="; "<="; "<="; "<="; ">="; "<="];
pass = [value(1:4) <= limit(1:4); value(5) >= limit(5); value(6) <= limit(6)];
output = table(metric, value, direction, limit, pass);
output.notes = repmat("predeclared-development-engineering-gate", ...
    height(output), 1);
if diagnostics.n == 0
    error("r51:EmptyNormalSummary", "Normal diagnostics cannot be empty.");
end
end
