function ledger = complexityLedger(cfg, counts)
%COMPLEXITYLEDGER Keep symbolic orders and implementation counts separate.

arguments
    cfg (1, 1) struct
    counts (:, :) table
end

required = ["Es", "Ef", "Er", "G_C", "G_A", "G_public", ...
    "enhancedMatrixFormationMacs", "enhancedEvdCubicUnits", ...
    "enhancedRecoveryMacs", "publicMatrixFormationMacs", ...
    "publicEvdCubicUnits", "publicRecoveryMacs"];
if ~all(ismember(required, string(counts.Properties.VariableNames)))
    error("r33:ComplexityCountsMissing", ...
        "The actual-count table is missing one or more required columns.");
end

protocol = r33.config();
verifyFixedDimensions(cfg, protocol);
ledger.fixedConstants = fixedConstants(cfg, protocol);
ledger.componentFormulas = componentFormulas();
ledger.methodFormulas = methodFormulas();
ledger.actualPerUser = actualRows(cfg, protocol, counts);
ledger.actualSummary = summarizeActual(ledger.actualPerUser);
ledger.subspaceComparison = subspaceComparison(protocol);
ledger.responseMemory = responseMemory(cfg, protocol);
ledger.ratioStatements = table( ...
    ["R32_historical_complete_runtime_reduction"; ...
    "frozen_search_point_reduction"], [35.04; ...
    100*(1-sum(protocol.r32.music.gridSizes) ...
    /sum(protocol.r32.enhancedC.gridSizes.^2))], ...
    ["runtime measurement from R32; superseded by R33 timing"; ...
    "MUSIC score-evaluation count only; not total runtime"], ...
    'VariableNames', {'quantity', 'percent', 'interpretation'});
end

function output = responseMemory(cfg, protocol)
realBytes = 8;
complexBytes = 16;
fullElements = cfg.numAntennas*cfg.numSubcarriers;
sparseElements = cfg.numAntennas*protocol.r32.front.carrierCount;
quantity = ["full_q_only_derivative_arrays_not_constructed"; ...
    "sparse_q_only_derivative_arrays_not_constructed"; ...
    "persistent_conjugate_full_beamformer_context"];
bytes = [fullElements*(2*realBytes+2*complexBytes); ...
    sparseElements*(2*realBytes+2*complexBytes); ...
    fullElements*complexBytes];
scope = ["two real distance derivatives plus two complex response derivatives"; ...
    "same four arrays on Q=513 sparse carriers"; ...
    "reused current-call invariant; not an offline answer cache"];
boundary = repmat( ...
    "analytical array storage only; not measured MATLAB peak memory", 3, 1);
output = table(quantity, bytes, scope, boundary);
end

function verifyFixedDimensions(cfg, protocol)
expected = [256, 2048, 513, 2047, 160, 97, 3083, 93];
actual = [cfg.numAntennas, cfg.numSubcarriers, ...
    protocol.r32.front.carrierCount, protocol.r32.music.carrierCount, ...
    protocol.r32.music.subarraySize, protocol.r32.music.numSubarrays, ...
    sum(protocol.r32.enhancedC.gridSizes.^2), ...
    sum(protocol.r32.music.gridSizes)];
if ~isequal(actual, expected)
    error("r33:ComplexityFixedConfigurationMismatch", ...
        "The complexity ledger only describes the frozen R32 configuration.");
end
end

function output = fixedConstants(cfg, protocol)
names = ["N"; "M"; "Q"; "K"; "L"; "P"; "G_C"; "G_A"];
values = [cfg.numAntennas; cfg.numSubcarriers; ...
    protocol.r32.front.carrierCount; protocol.r32.music.carrierCount; ...
    protocol.r32.music.subarraySize; protocol.r32.music.numSubarrays; ...
    sum(protocol.r32.enhancedC.gridSizes.^2); ...
    sum(protocol.r32.music.gridSizes)];
output = table(names, values, 'VariableNames', {'symbol', 'value'});
end

function output = componentFormulas()
component = ["spectral_front"; "direct_subspace_per_carrier"; ...
    "gram_subspace_per_carrier"; "single_target_music_search"];
order = ["O(E_s*N*Q + E_f*N*M)"; ...
    "O(P*L^2 + L^3)"; "O(L*P^2 + P^3 + L*P)"; "O(K*G*L)"];
boundary = ["E_s and E_f are actual response calls"; ...
    "covariance formation and full L-by-L EVD"; ...
    "P-by-P Gram EVD, vector recovery, with declared fallback"; ...
    "current one-signal-vector inner-product implementation"];
output = table(component, order, boundary);
end

function output = methodFormulas()
method = ["original_paper_full_structure"; "C_enhanced"; ...
    "P_A"; "C_public"];
publishedOrReference = [ ...
    "O(M + K_Z*(P_Z*L_Z^2 + L_Z^3 + G_Z*L_Z^2))"; ...
    "O(E_s*N*Q + E_f*N*M + K*P*L + K*P*L^2 + K*L^3 + K*G_C*L)"; ...
    "O(E_s*N*Q + (E_f+E_r)*N*M + K*P*L + K*P*L^2 + K*L^3 + K*G_A*L)"; ...
    "O(E_s*N*Q + E_f*N*M + K_p*P_p*L_p + K_p*P_p*L_p^2 + K_p*L_p^3 + K_p*G_p*L_p)"];
acceptedAOrder = ["not evaluated: K_Z and G_Z remain symbolic"; ...
    "same asymptotic order; q-only removes two unused N-by-M derivative arrays from pure scoring calls"; ...
    "same asymptotic order; q-only removes two unused N-by-M derivative arrays from pure scoring calls"; ...
    "same asymptotic order; q-only response path applies to the common front"];
attemptedGramOrder = ["not evaluated: K_Z and G_Z remain symbolic"; ...
    "O(E_s*N*Q + E_f*N*M + K*P*L + K*L*P^2 + K*P^3 + K*L*P + K*G_C*L)"; ...
    "O(E_s*N*Q + (E_f+E_r)*N*M + K*P*L + K*L*P^2 + K*P^3 + K*L*P + K*G_A*L)"; ...
    "same direct order because P_p=129 is not smaller than L_p=128"];
musicScoring = ["included as G_Z*L_Z^2 in the stated full-paper structure"; ...
    "O(K*G_C*L)"; "O(K*G_A*L)"; "O(K_p*G_p*L_p)"];
disclosure = ["K_Z and G_Z were not uniquely disclosed; neither is imputed"; ...
    "K=2047, L=160, P=97, G_C=3083"; ...
    "K=2047, L=160, P=97, G_A=93"; ...
    "transparent assumed baseline: K_p=5, L_p=128, P_p=129, G_p=3083"];
output = table(method, publishedOrReference, acceptedAOrder, ...
    attemptedGramOrder, musicScoring, disclosure);
end

function rows = actualRows(cfg, protocol, counts)
methods = ["C_enhanced", "P_A", "C_public"];
rows = table();
for index = 1:height(counts)
    for method = methods
        [K, L, P, G, Er, matrixMacs, evdUnits, recoveryMacs, solver] = ...
            dimensions(method, protocol, counts(index, :));
        Es = counts.Es(index);
        Ef = counts.Ef(index);
        sparseTerms = Es*cfg.numAntennas*protocol.r32.front.carrierCount;
        fullTerms = (Ef+Er)*cfg.numAntennas*cfg.numSubcarriers;
        alignmentTerms = K*P*L;
        searchTerms = K*G*L;
        rows = [rows; table(counts.seed(index), counts.snrDb(index), ...
            method, K, L, P, G, Es, Ef, Er, sparseTerms, fullTerms, ...
            alignmentTerms, matrixMacs, evdUnits, recoveryMacs, ...
            searchTerms, sparseTerms+fullTerms, sparseTerms+fullTerms, ...
            alignmentTerms, searchTerms, solver, ...
            'VariableNames', {'seed', 'snrDb', 'method', 'K', 'L', ...
            'P', 'G', 'Es', 'Ef', 'Er', 'sparseResponseTerms', ...
            'fullResponseTerms', 'phaseAlignmentMacs', ...
            'subspaceMatrixFormationMacs', 'evdCubicUnits', ...
            'subspaceRecoveryMacs', 'musicInnerProductMacs', ...
            'responseSqrtTerms', 'responseExponentialTerms', ...
            'alignmentExponentialTerms', 'musicSteeringExponentialTerms', ...
            'subspaceSolver'})]; %#ok<AGROW>
    end
end
end

function [K, L, P, G, Er, matrixMacs, evdUnits, recoveryMacs, solver] = ...
    dimensions(method, protocol, row)
if method == "C_public"
    K = protocol.r32.publicC.carrierCount;
    L = protocol.r32.publicC.subarraySize;
    P = 256-L+1;
    G = row.G_public;
    Er = 0;
    matrixMacs = row.publicMatrixFormationMacs;
    evdUnits = row.publicEvdCubicUnits;
    recoveryMacs = row.publicRecoveryMacs;
    solver = solverName(row, "publicSolver", ...
        "direct-L-by-L-EVD-because-P-not-less-than-L");
else
    K = protocol.r32.music.carrierCount;
    L = protocol.r32.music.subarraySize;
    P = protocol.r32.music.numSubarrays;
    if method == "C_enhanced"
        G = row.G_C;
        Er = 0;
    else
        G = row.G_A;
        Er = row.Er;
    end
    matrixMacs = row.enhancedMatrixFormationMacs;
    evdUnits = row.enhancedEvdCubicUnits;
    recoveryMacs = row.enhancedRecoveryMacs;
    solver = solverName(row, "enhancedSolver", ...
        "smaller-P-by-P-Gram-EVD-with-frozen-fallback");
end
end

function solver = solverName(row, field, defaultValue)
solver = defaultValue;
if ismember(field, string(row.Properties.VariableNames))
    solver = string(row.(field));
end
end

function summary = summarizeActual(rows)
metrics = ["Es", "Ef", "Er", "sparseResponseTerms", ...
    "fullResponseTerms", "phaseAlignmentMacs", ...
    "subspaceMatrixFormationMacs", "evdCubicUnits", ...
    "subspaceRecoveryMacs", "musicInnerProductMacs", ...
    "responseSqrtTerms", "responseExponentialTerms", ...
    "alignmentExponentialTerms", "musicSteeringExponentialTerms"];
summary = table();
for method = unique(rows.method, "stable").'
    selected = rows.method == method;
    values = zeros(1, 4*numel(metrics));
    names = strings(1, 4*numel(metrics));
    cursor = 1;
    for metric = metrics
        vector = rows.(metric)(selected);
        values(cursor:cursor+3) = [min(vector), median(vector), ...
            mean(vector), max(vector)];
        names(cursor:cursor+3) = ["min_"+metric, "median_"+metric, ...
            "mean_"+metric, "max_"+metric];
        cursor = cursor+4;
    end
    entry = array2table(values, VariableNames=cellstr(names));
    entry = addvars(entry, method, nnz(selected), Before=1, ...
        NewVariableNames=["method", "n"]);
    summary = [summary; entry]; %#ok<AGROW>
end
end

function output = subspaceComparison(protocol)
K = protocol.r32.music.carrierCount;
L = protocol.r32.music.subarraySize;
P = protocol.r32.music.numSubarrays;
quantity = ["matrix_formation_MAC_units"; "EVD_cubic_units"; ...
    "recovery_MAC_units"];
direct = [K*P*L^2; K*L^3; 0];
gram = [K*L*P^2; K*P^3; 3*K*L*P];
reductionPercent = 100*(1-gram./direct);
reductionPercent(direct == 0) = nan;
output = table(quantity, direct, gram, reductionPercent, ...
    'VariableNames', {'quantity', 'directReference', ...
    'gramImplementation', 'nominalReductionPercent'});
end
