function protocol = config()
%CONFIG Freeze the finite equivalent-implementation acceleration audit.

protocol.version = "R33-equivalent-acceleration-audit-v1";
protocol.referenceVersion = "R32-PA-finite-closeout-v1";
protocol.fastMethodVersion = "PA-equivalent-fast-R33-v1";
protocol.r32 = r32.config();
protocol.variants = ["A_response_invariants", "B_gram_subspace", ...
    "AB_combined"];
protocol.validation = struct( ...
    qAbsoluteTolerance=1e-12, derivativeAbsoluteTolerance=1e-10, ...
    profileScoreTolerance=1e-12, projectionTolerance=1e-10, ...
    eigenvalueRelativeTolerance=1e-10, residualTolerance=1e-10, ...
    thetaToleranceDeg=1e-10, rangeToleranceM=1e-7, ...
    candidateScoreTolerance=1e-12, ...
    selectedCandidateTolerance=[1e-10, 1e-7]);
protocol.gram = struct( ...
    useOnlyWhenColumnsLessThanRows=true, ...
    minimumRelativeEigenvalue=1e-12, ...
    minimumRelativeEigengap=1e-10, ...
    residualTolerance=1e-10, ...
    fallback="full-covariance-eig", ...
    allowThirdSolver=false);
protocol.development = struct(snrDb=[-10, 0, 20], ...
    usersPerSnr=3, combinedRegressionUsers=60);
protocol.timing = struct(snrDb=0, positionCount=3, repetitions=3, ...
    warmupsPerMethod=1, ...
    methods=["C_enhanced", "H_A", "P_A", "C_public"], ...
    orderPolicy="deterministic-cyclic-rotation-across-position-repetition", ...
    scanPreparation="shared-offline-constant-excluded");
protocol.finalTest = struct(status="LOCKED-WAITING-FOR-USER-CONFIRMATION", ...
    inheritsR32Design=true, authorized=false);
end
