function output = sharedRegressionSet( ...
    cfg, observation, snapshots, scan, protocol, options)
%SHAREDREGRESSIONSET Compute all four methods with shared common work.
% This helper is for numerical equivalence regression only. It is not used
% for independent online timing because sharing would understate deployment
% costs of a method run by itself.

arguments
    cfg (1, 1) struct
    observation (:, 1) double {mustBeFinite}
    snapshots (:, :) double
    scan (1, 1) struct
    protocol (1, 1) struct = r33.config()
    options.UseFastResponse (1, 1) logical = true
    options.UseGram (1, 1) logical = true
end

r32.assertFrozenConfig(cfg, protocol.r32);
if numel(observation) ~= cfg.numSubcarriers ...
        || size(snapshots, 1) ~= cfg.numAntennas ...
        || size(snapshots, 2) ~= cfg.numSubcarriers
    error("r33:SharedRegressionInputSize", ...
        "The shared regression requires the full z and N-by-M Y arrays.");
end

if options.UseFastResponse
    frontOutput = r33.front(cfg, observation, scan, protocol.r32, ...
        r32.candidate(protocol.r32));
else
    frontProtocol = r30.config();
    frontProtocol.frontVersion = protocol.r32.front.version;
    frontProtocol.angleOffsetsDeg = protocol.r32.front.angleOffsetsDeg;
    frontOutput = r30.front(cfg, observation, scan, frontProtocol, ...
        r32.candidate(protocol.r32));
end
front = frontOutput.selected;
enhancedCarrierIndex = r30.selectLocalCarriers(cfg.numSubcarriers, ...
    protocol.r32.music.carrierCount, frontOutput.peakCarrierIndex);
if ~options.UseFastResponse && ~options.UseGram
    [enhancedState, enhancedCfg, enhancedCost] = r30.prepareMusicState( ...
        cfg, snapshots(:, enhancedCarrierIndex+1), enhancedCarrierIndex, ...
        front.thetaDeg, front.rangeM, protocol.r32.music.subarraySize);
else
    [enhancedState, enhancedCfg, enhancedCost] = r33.prepareMusicState( ...
        cfg, snapshots(:, enhancedCarrierIndex+1), enhancedCarrierIndex, ...
        front.thetaDeg, front.rangeM, protocol.r32.music.subarraySize, ...
        protocol.gram, UseGram=options.UseGram);
end

cEstimate = r31.stagedJointMusic(enhancedCfg, enhancedState, ...
    front.thetaDeg, front.rangeM, ...
    protocol.r32.enhancedC.angleHalfWidthDeg, ...
    protocol.r32.enhancedC.rangeHalfWidthM, ...
    protocol.r32.enhancedC.gridSizes);
angleEstimate = r31.stagedAngleMusic(enhancedCfg, enhancedState, ...
    front.thetaDeg, front.rangeM, protocol.r32.music.angleHalfWidthDeg, ...
    protocol.r32.music.gridSizes);
if options.UseFastResponse
    profile = r33.profileAtAngle(cfg, observation, scan, ...
        angleEstimate.thetaDeg, front.rangeM, protocol);
else
    profile = r32.profileAtAngle(cfg, observation, scan, ...
        angleEstimate.thetaDeg, front.rangeM, protocol.r32);
end

publicCarrierIndex = r30.selectLocalCarriers(cfg.numSubcarriers, ...
    protocol.r32.publicC.carrierCount, frontOutput.peakCarrierIndex);
if ~options.UseFastResponse && ~options.UseGram
    [publicState, publicCfg, publicCost] = r30.prepareMusicState( ...
        cfg, snapshots(:, publicCarrierIndex+1), publicCarrierIndex, ...
        front.thetaDeg, front.rangeM, protocol.r32.publicC.subarraySize);
else
    [publicState, publicCfg, publicCost] = r33.prepareMusicState( ...
        cfg, snapshots(:, publicCarrierIndex+1), publicCarrierIndex, ...
        front.thetaDeg, front.rangeM, protocol.r32.publicC.subarraySize, ...
        protocol.gram, UseGram=options.UseGram);
end
publicEstimate = r31.stagedJointMusic(publicCfg, publicState, ...
    front.thetaDeg, front.rangeM, ...
    protocol.r32.publicC.angleHalfWidthDeg, ...
    protocol.r32.publicC.rangeHalfWidthM, protocol.r32.publicC.gridSizes);

output.version = variantVersion(options.UseFastResponse, options.UseGram);
output.front = frontOutput;
output.enhancedState = enhancedState;
output.enhancedCfg = enhancedCfg;
output.enhancedCarrierIndex = enhancedCarrierIndex;
output.enhancedStateCost = enhancedCost;
output.publicState = publicState;
output.publicCfg = publicCfg;
output.publicCarrierIndex = publicCarrierIndex;
output.publicStateCost = publicCost;
output.C_enhanced = struct(thetaDeg=cEstimate.thetaDeg, ...
    rangeM=cEstimate.rangeM, estimate=cEstimate);
output.H_A = struct(thetaDeg=angleEstimate.thetaDeg, ...
    rangeM=front.rangeM, estimate=angleEstimate);
output.P_A = struct(thetaDeg=angleEstimate.thetaDeg, ...
    rangeM=profile.value, estimate=angleEstimate, profile=profile);
output.C_public = struct(thetaDeg=publicEstimate.thetaDeg, ...
    rangeM=publicEstimate.rangeM, estimate=publicEstimate);
output.counts = struct(sparseResponseCalls=frontOutput.subsetEvaluations, ...
    frontFullResponseCalls=frontOutput.fullEvaluations, ...
    derivativeFrontResponseCalls=fieldOrNaN( ...
        frontOutput, "derivativeFullEvaluations"), ...
    qOnlyFrontResponseCalls=fieldOrNaN( ...
        frontOutput, "qOnlyFullEvaluations"), ...
    profileResponseCalls=profile.evaluationCount, ...
    enhancedSearchEvaluationsC=cEstimate.evaluationCount, ...
    enhancedSearchEvaluationsA=angleEstimate.evaluationCount, ...
    publicSearchEvaluations=publicEstimate.evaluationCount);
end

function value = fieldOrNaN(input, field)
value = nan;
if isfield(input, field)
    value = input.(field);
end
end

function version = variantVersion(useFastResponse, useGram)
if useFastResponse && useGram
    version = "R33-AB-shared-equivalence-regression-v1";
elseif useFastResponse
    version = "R33-A-shared-equivalence-regression-v1";
elseif useGram
    version = "R33-B-shared-equivalence-regression-v1";
else
    version = "R33-reference-shared-equivalence-regression-v1";
end
end
