function diagnostic = round28FrontClosureTrial( ...
    cfg, scan, row, algorithm, protocol, options)
%ROUND28FRONTCLOSURETRIAL Close selected front-end starts at fixed caps.

arguments
    cfg (1, 1) struct
    scan (1, 1) struct
    row (1, :) table
    algorithm (1, 1) struct
    protocol (1, 1) struct
    options.ExistingEstimates cell = cell(0, 1)
end

replay = fsjad.replayRound27Data(cfg, scan, row);
legacy = fsjad.angleMultistartProfileEstimate( ...
    cfg, replay.observation, scan, algorithm.frontOffsetsDeg);
caps = protocol.iterationCaps;
startCount = numel(legacy.refinedThetaDeg);
estimates = cell(startCount, numel(caps));
summary = table();
for capIndex = 1:numel(caps)
    cap = caps(capIndex);
    scores = zeros(startCount, 1);
    for startIndex = 1:startCount
        if numel(options.ExistingEstimates) >= capIndex ...
                && ~isempty(options.ExistingEstimates{capIndex})
            estimate = options.ExistingEstimates{capIndex}{startIndex};
        else
            estimate = fsjad.refineProfileMonotone(cfg, replay.observation, ...
                legacy.refinedThetaDeg(startIndex), ...
                legacy.refinedRangeM(startIndex), scan, ...
                MaxIterations=cap, StepTolerance=protocol.stepTolerance);
        end
        estimates{startIndex, capIndex} = estimate;
        scores(startIndex) = estimate.score;
    end
    [~, order] = sort(scores, "descend");
    rank = zeros(startCount, 1);
    rank(order) = (1:startCount).';
    for startIndex = 1:startCount
        estimate = estimates{startIndex, capIndex};
        entry = table(row.seed, row.snrDb, startIndex, cap, ...
            legacy.refinedThetaDeg(startIndex), ...
            legacy.refinedRangeM(startIndex), estimate.thetaDeg, ...
            estimate.rangeM, estimate.score, estimate.stationarity, ...
            estimate.iterations, estimate.acceptedSteps, estimate.converged, ...
            string(estimate.status), rank(startIndex), ...
            'VariableNames', {'seed', 'snrDb', 'startIndex', ...
            'iterationCap', 'startThetaDeg', 'startRangeM', ...
            'finalThetaDeg', 'finalRangeM', 'objective', ...
            'stationarityResidual', 'iterations', 'acceptedSteps', ...
            'converged', 'status', 'candidateRank'});
        summary = [summary; entry]; %#ok<AGROW>
    end
end

scores200 = cellfun(@(item) item.score, estimates(:, 1));
[~, best200] = max(scores200);
front200 = estimates{best200, 1};
wideBounds = [max(cfg.rangeLimitsM(1), ...
    front200.rangeM-protocol.profileHalfWidthM), ...
    min(cfg.rangeLimitsM(2), ...
    front200.rangeM+protocol.profileHalfWidthM)];
solver = fsjad.maximizeRangeScore( ...
    @(rangeM) fsjad.fixedAngleProfileLogScore(cfg, replay.observation, ...
    front200.thetaDeg, rangeM, scan), wideBounds, front200.rangeM, ...
    InitialSpacingM=protocol.initialSpacingM, ...
    MinimumIntervals=protocol.minimumIntervals, ...
    RefinementLevels=protocol.refinementLevels, ...
    PeakCount=protocol.peakCount, TolX=protocol.tolX, ...
    ScoreTolerance=protocol.scoreTolerance, KeepTrace=true);
pfEstimates = cell(numel(caps), 1);
pfSummary = table();
for capIndex = 1:numel(caps)
    estimate = fsjad.refineProfileMonotone(cfg, replay.observation, ...
        front200.thetaDeg, solver.rangeM, scan, ...
        MaxIterations=caps(capIndex), StepTolerance=protocol.stepTolerance);
    pfEstimates{capIndex} = estimate;
    originalBest = max(cellfun(@(item) item.score, estimates(:, capIndex)));
    entry = table(row.seed, row.snrDb, caps(capIndex), ...
        front200.thetaDeg, solver.rangeM, solver.score, solver.boundary, ...
        estimate.thetaDeg, estimate.rangeM, estimate.score, ...
        estimate.stationarity, estimate.iterations, estimate.converged, ...
        string(estimate.status), originalBest, estimate.score-originalBest, ...
        estimate.score > originalBest+protocol.scoreTolerance, ...
        'VariableNames', {'seed', 'snrDb', 'iterationCap', ...
        'profileThetaDeg', 'profileRangeM', 'profileLogObjective', ...
        'profileBoundary', 'finalThetaDeg', 'finalRangeM', ...
        'objective', 'stationarityResidual', 'iterations', 'converged', ...
        'status', 'originalBestObjective', 'objectiveGain', ...
        'higherLikelihoodSameDomain'});
    pfSummary = [pfSummary; entry]; %#ok<AGROW>
end

diagnostic.version = "Round28-targeted-front-closure-v1";
diagnostic.row = row;
diagnostic.replay = replay;
diagnostic.legacy = legacy;
diagnostic.estimates = estimates;
diagnostic.summary = summary;
diagnostic.profileSolver = solver;
diagnostic.pfEstimates = pfEstimates;
diagnostic.pfSummary = pfSummary;
diagnostic.reusedExistingCaps = cellfun(@(item) ~isempty(item), ...
    options.ExistingEstimates);
end
