function setup = round28Setup(project, round27AggregateFile, countPerSnr, mode)
%ROUND28SETUP Load saved R27 rows and freeze the incremental ablation rules.

arguments
    project (1, 1) string
    round27AggregateFile (1, 1) string
    countPerSnr (1, 1) double {mustBeInteger, mustBePositive}
    mode (1, 1) string {mustBeMember(mode, ["development", "formal"])}
end

if ~isfile(round27AggregateFile)
    error("fsjad:Round28MissingRound27", ...
        "Round 27 aggregate file does not exist: %s", round27AggregateFile);
end
saved = load(round27AggregateFile, "setup", "design", "results");
assert(saved.setup.protocol.version == "Round27-convergence-ablation-v3", ...
    "fsjad:Round28RequiresRound27V3", ...
    "Round 28 accepts only the non-obsolete Round 27 v3 aggregate.");
assert(numel(saved.results) == height(saved.design) ...
    && all(cellfun(@(item) ~isempty(item) && item.success, saved.results)), ...
    "fsjad:Round28InvalidRound27Results", ...
    "Every selected Round 27 row must be present and successful.");
snrValues = unique(saved.design.snrDb, "stable").';
assert(isequal(snrValues, [-10, 0, 20]), "fsjad:Round28UnexpectedSnrGrid");
availablePerSnr = arrayfun(@(snrDb) sum(saved.design.snrDb == snrDb), snrValues);
assert(all(availablePerSnr >= countPerSnr), ...
    "fsjad:Round28InsufficientRound27Rows", ...
    "Requested more incremental rows than the Round 27 aggregate contains.");

rows = false(height(saved.design), 1);
for snrDb = snrValues
    indices = find(saved.design.snrDb == snrDb);
    rows(indices(1:countPerSnr)) = true;
end
setup.design = saved.design(rows, :);
setup.oldResults = saved.results(rows);
setup.cfg = saved.setup.cfg;
setup.zhang = saved.setup.zhang;
setup.ours = saved.setup.ours;
setup.round27Protocol = saved.setup.protocol;
setup.round27AggregateFile = round27AggregateFile;
setup.round27AggregateBytes = dir(round27AggregateFile).bytes;

setup.protocol.version = "Round28-fixed-angle-range-v1";
setup.protocol.mode = mode;
setup.protocol.countPerSnr = countPerSnr;
setup.protocol.sourceData = "saved-Round27-v3-rows-only";
setup.protocol.oldAlphaActive = false;
setup.protocol.profileLambda = setup.ours.profileLambda;
setup.protocol.profileOutput = "conditional-complex-spectrum-range";
setup.protocol.primaryComparison = "P_w-minus-M_w";
setup.protocol.methodNames = ["C", "D", "E", ...
    "profile_at_front_angle", "H", "M_n", "P_n", "M_w", ...
    "P_w", "P_F", "M_adaptive_common", "P_adaptive_common"];
setup.protocol.methodIndex = struct(C=1, D=2, E=3, ...
    ProfileAtFront=4, H=5, Mn=6, Pn=7, Mw=8, Pw=9, PF=10, ...
    MAdaptiveCommon=11, PAdaptiveCommon=12);
setup.protocol.narrowIntervalDefinition = "actual-local-MUSIC-reachable";
setup.protocol.wideHalfWidthM = 2;
setup.protocol.expansionHalfWidthsM = [2, 4, 8];
setup.protocol.initialSpacingM = 0.05;
setup.protocol.minimumIntervals = 40;
setup.protocol.refinementLevels = 3;
setup.protocol.peakCount = 8;
setup.protocol.tolX = 1e-6;
setup.protocol.scoreTolerance = 1e-10;
setup.protocol.maxMusicPointsPerChunk = 128;
setup.protocol.rankingRowsToKeep = 20;
setup.protocol.bootstrapResamples = 20000;
setup.protocol.bootstrapSeed = 20260907;
setup.protocol.confirmatorySamplePerSnr = 1000;
setup.protocol.confirmatorySeedStatus = "not-allocated-until-rule-freeze";
setup.protocol.noSignificanceStopping = true;
setup.protocol.multipleTestingFamily = "three-SNR-primary-comparisons";
setup.protocol.excludedPerformanceMethod = "zhang_declared_protocol";
setup.protocol.excludedPerformanceReason = ...
    "Kept in the independent published-formula audit only.";
setup.protocol.conclusionBoundary = [ ...
    "R27 shows that continuing the same saved starts from 12 to 200 " ...
    "iterations did not materially change the aggregate difference; " ...
    "it does not exclude all numerical insufficiency, missing modes, " ...
    "or candidate omissions."];

paths = ["+jad/freezeLocalMusicSubspace.m"; ...
    "+jad/localMusicLogScore.m"; "+jad/localMusicReachableInterval.m"; ...
    "+fsjad/fixedAngleProfileLogScore.m"; ...
    "+fsjad/maximizeRangeScore.m"; "+fsjad/expandRangeSearch.m"; ...
    "+fsjad/replayRound27Data.m"; "+fsjad/round28Setup.m"; ...
    "+fsjad/round28IncrementalTrial.m"; "+fsjad/sourceHashManifest.m"; ...
    "+fsjad/exactSpectralResponse.m"; "+fsjad/profileScore.m"; ...
    "+fsjad/prepareScan.m"; "+jad/localMusicEstimate.m"; ...
    "+jad/localMusicSpectrum.m"; "+jad/simulateSnapshots.m"; ...
    "experiments/run_round28_fixed_angle_shard.m"; ...
    "experiments/aggregate_round28_fixed_angle.m"; ...
    "experiments/preflight_round28.m"; ...
    "experiments/run_round28_targeted_front_diagnostics.m"; ...
    "+fsjad/round28FrontClosureTrial.m"; ...
    "tests/localMusicLogScoreTest.m"; ...
    "tests/maximizeRangeScoreTest.m"; ...
    "tests/round28FixedAngleTest.m"];
setup.source = fsjad.sourceHashManifest(project, paths);
end
