function protocol = config()
%CONFIG Freeze the R56 q-anchored split-consensus development study.

protocol.version = "R56-PFALFSC-development-v1";
protocol.date = "2026-09-19";
protocol.evidenceRole = "post-R55-independent-development-not-confirmation";
protocol.method = struct(primary="P_FALF_SC", ...
    ablation="P_FALF_QB", base="P_FALF", angleBase="P_FA", ...
    baseline="P_A", paFree=true, musicFree=true, evdFree=true);
protocol.base = r53.config();
protocol.freeze = struct(expectedR53Digest= ...
    "c1476d3b75078a841286bebf6e67812217dd689952b291b4a3213cd915018c5c", ...
    expectedPfaDigest= ...
    "f1483ec49bb59907a9b5b2f70aa95459f11277450a0bbcf715a43b3324439868", ...
    modifyFrozenMethods=false);
protocol.anchor = struct(candidateSource="retained-q-profile-peaks", ...
    basinBounds="immediate-neighbor-q-grid-bracket", ...
    split="one-based-odd-even-selected-carrier-positions", ...
    switchRule="odd-even-full-joint-same-q-candidate", ...
    tieRule="first-candidate-in-frozen-q-retention-order", ...
    scoreThresholdAllowed=false, learnedSelectorAllowed=false, ...
    snrRuleAllowed=false, truthAllowed=false);
protocol.refinement = struct(tolXM=protocol.base.profile.tolXM, ...
    scoreTolerance=protocol.base.profile.scoreTolerance, ...
    invalidPolicy="fallback-q-candidate");
protocol.design = struct(positionCount=30, ...
    snrDb=[-10, -5, 0, 5, 10, 15, 20], ...
    angleLimitsDeg=[-60, 60], rangeLimitsM=[15, 50], ...
    positionSeed=71000000, trialSeedRoot=71100000, expectedRows=210);
protocol.bootstrap = struct(count=10000, seed=71200000, ...
    confidence=0.95, cluster="positionId", sharedAcrossSnr=true);
protocol.gate = struct(maxAngleIdentityDifferenceDeg=1e-12, ...
    maxAggregateRangeMseRatioToPA=1.00, ...
    maxPerSnrRangeMseRatioToPA=1.05, ...
    maxAggregateRangeMseRatioToPFALF=0.98, ...
    maxP95AbsRangeRatioToPFALF=1.00, ...
    maxMissRateDifferenceToPFALF=0, missThresholdM=1.0);
protocol.execution = struct(recommendedWorkers=8, batchSize=7, ...
    finalRowsAccessible=false, R53R54R55RowsAccessible=false, ...
    parameterTuningAllowed=false, calibrationAllowed=false, ...
    stopAfterDevelopment=true);
end
