function output = summarize(design, results, protocol)
%SUMMARIZE Build R56 accuracy, tail mechanism, bootstrap, and gates.

arguments
    design table
    results (:, 1) cell
    protocol (1, 1) struct = r56.config()
end

if numel(results) ~= height(design) || any(cellfun(@isempty, results)) ...
        || any(cellfun(@(item) ~item.success, results))
    error("r56:IncompleteDevelopment", ...
        "R56 requires every development row to succeed.");
end
methods = ["P_A", "P_FA", "P_FALF", "P_FALF_QB", ...
    "P_FALF_SC", "C_enhanced"];
perUser = design(:, ["positionId", "seed", "trialIndex", ...
    "snrDb", "truthThetaDeg", "truthRangeM"]);
for method = methods
    theta = cellfun(@(item) item.(method).thetaDeg, results);
    rangeM = cellfun(@(item) item.(method).rangeM, results);
    perUser.("theta_"+method) = theta;
    perUser.("range_"+method) = rangeM;
    perUser.("angleError_"+method) = theta-perUser.truthThetaDeg;
    perUser.("rangeError_"+method) = rangeM-perUser.truthRangeM;
end
perUser.consensus = cellfun(@(item) item.consensus, results);
perUser.consensusSwitch = cellfun(@(item) item.consensusSwitch, results);
perUser.qSelectedCandidateIndex = cellfun( ...
    @(item) item.qSelectedCandidateIndex, results);
perUser.selectedCandidateIndex = cellfun( ...
    @(item) item.selectedCandidateIndex, results);
perUser.oddBestCandidateIndex = cellfun( ...
    @(item) item.oddBestCandidateIndex, results);
perUser.evenBestCandidateIndex = cellfun( ...
    @(item) item.evenBestCandidateIndex, results);
perUser.jointBestCandidateIndex = cellfun( ...
    @(item) item.jointBestCandidateIndex, results);
perUser.pfalfRangeShiftFromQ = ...
    perUser.range_P_FALF-perUser.range_P_FA;
perUser.qbRangeShiftFromQ = ...
    perUser.range_P_FALF_QB-perUser.range_P_FA;
perUser.scRangeShiftFromQ = ...
    perUser.range_P_FALF_SC-perUser.range_P_FA;
perUser.pfalfLargeShift = cellfun(@(item) item.pfalfLargeShift, results);
perUser.scLargeShift = cellfun(@(item) item.scLargeShift, results);
perUser.pfalfHarmful = cellfun(@(item) item.pfalfHarmful, results);
perUser.scHarmful = cellfun(@(item) item.scHarmful, results);
perUser.pfalfLargeShiftHarmful = cellfun( ...
    @(item) item.pfalfLargeShiftHarmful, results);
perUser.scLargeShiftHarmful = cellfun( ...
    @(item) item.scLargeShiftHarmful, results);
perUser.backendSeconds = cellfun(@(item) item.backendSeconds, results);

methodSummary = summarizeMethods(perUser, methods, protocol);
comparisons = compareAll(perUser, protocol);
bootstrap = [ ...
    r51.bootstrapRatio(perUser, "P_FALF_SC", "P_A", "range", protocol, 1); ...
    r51.bootstrapRatio(perUser, "P_FALF_SC", "P_FALF", "range", protocol, 2); ...
    r51.bootstrapRatio(perUser, "P_FALF_QB", "P_FALF", "range", protocol, 3)];
mechanism = mechanismSummary(perUser, protocol);
mechanismBySnr = mechanismPerSnr(perUser, protocol);
gate = buildGate(perUser, comparisons, mechanism, protocol);
output = struct(version="R56-PFALFSC-summary-v1", ...
    perUser=perUser, methodSummary=methodSummary, ...
    comparisons=comparisons, bootstrap=bootstrap, ...
    mechanism=mechanism, mechanismBySnr=mechanismBySnr, ...
    gate=gate, developmentPass=all(gate.pass));
end

function output = mechanismPerSnr(perUser, protocol)
output = table();
for snr = protocol.design.snrDb
    selected = perUser.snrDb == snr;
    subset = perUser(selected, :);
    pfalfLarge = subset.pfalfLargeShift;
    scLarge = subset.scLargeShift;
    row = table(snr, height(subset), mean(subset.consensus), ...
        mean(subset.consensusSwitch), sum(pfalfLarge), sum(scLarge), ...
        sum(subset.pfalfLargeShiftHarmful), ...
        sum(subset.scLargeShiftHarmful), ...
        conditionalRate(subset.pfalfHarmful, pfalfLarge), ...
        conditionalRate(subset.scHarmful, scLarge), ...
        quantile(abs(subset.rangeError_P_FALF), .95), ...
        quantile(abs(subset.rangeError_P_FALF_SC), .95), ...
        'VariableNames', {'snrDb', 'n', 'consensusRate', ...
        'consensusSwitchRate', 'pfalfLargeShiftCount', ...
        'scLargeShiftCount', 'pfalfHarmfulLargeShiftCount', ...
        'scHarmfulLargeShiftCount', ...
        'pfalfConditionalHarmfulLargeShiftRate', ...
        'scConditionalHarmfulLargeShiftRate', ...
        'pfalfP95AbsRangeM', 'scP95AbsRangeM'});
    output = [output; row]; %#ok<AGROW>
end
end

function output = summarizeMethods(perUser, methods, protocol)
output = table();
for method = methods
    for snr = protocol.design.snrDb
        selected = perUser.snrDb == snr;
        ae = perUser.("angleError_"+method)(selected);
        re = perUser.("rangeError_"+method)(selected);
        output = [output; table(method, snr, nnz(selected), ...
            mean(ae.^2), sqrt(mean(ae.^2)), mean(re.^2), ...
            sqrt(mean(re.^2)), median(abs(re)), ...
            quantile(abs(re), .90), quantile(abs(re), .95), ...
            mean(abs(re)>protocol.gate.missThresholdM), ...
            'VariableNames', {'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', 'rangeMseM2', ...
            'rangeRmseM', 'rangeMedianAbsM', 'rangeP90AbsM', ...
            'rangeP95AbsM', 'rangeMissRateOver1M'})]; %#ok<AGROW>
    end
end
end

function output = compareAll(perUser, protocol)
output = table();
for candidate = ["P_FALF", "P_FALF_QB", "P_FALF_SC"]
    for reference = ["P_A", "P_FA", "P_FALF"]
        candidateMse = zeros(numel(protocol.design.snrDb), 1);
        referenceMse = zeros(numel(protocol.design.snrDb), 1);
        for index = 1:numel(protocol.design.snrDb)
            snr = protocol.design.snrDb(index);
            selected = perUser.snrDb == snr;
            ce = perUser.("rangeError_"+candidate)(selected).^2;
            re = perUser.("rangeError_"+reference)(selected).^2;
            candidateMse(index) = mean(ce);
            referenceMse(index) = mean(re);
            output = [output; comparisonRow(candidate, reference, ...
                "per-SNR", snr, ce, re)]; %#ok<AGROW>
        end
        ce = perUser.("rangeError_"+candidate).^2;
        re = perUser.("rangeError_"+reference).^2;
        row = comparisonRow(candidate, reference, "equal-SNR", nan, ce, re);
        row.rangeMseRatio = mean(candidateMse)/mean(referenceMse);
        row.rangeRmseDifferenceMm = 1000*(sqrt(mean(candidateMse)) ...
            -sqrt(mean(referenceMse)));
        output = [output; row]; %#ok<AGROW>
    end
end
end

function output = comparisonRow(candidate, reference, scope, snrDb, ce, re)
output = table(candidate, reference, scope, snrDb, numel(ce), ...
    mean(ce)/mean(re), 1000*(sqrt(mean(ce))-sqrt(mean(re))), ...
    nnz(ce<re), nnz(ce==re), nnz(ce>re), mean(ce-re), ...
    'VariableNames', {'candidate', 'reference', 'scope', 'snrDb', 'n', ...
    'rangeMseRatio', 'rangeRmseDifferenceMm', 'winCount', ...
    'tieCount', 'lossCount', 'meanSquaredErrorDifference'});
end

function output = mechanismSummary(perUser, protocol)
pfalfLarge = perUser.pfalfLargeShift;
scLarge = perUser.scLargeShift;
output = table(height(perUser), mean(perUser.consensus), ...
    mean(perUser.consensusSwitch), sum(pfalfLarge), sum(scLarge), ...
    sum(perUser.pfalfLargeShiftHarmful), ...
    sum(perUser.scLargeShiftHarmful), ...
    conditionalRate(perUser.pfalfHarmful, pfalfLarge), ...
    conditionalRate(perUser.scHarmful, scLarge), ...
    quantile(abs(perUser.rangeError_P_FALF), .95), ...
    quantile(abs(perUser.rangeError_P_FALF_SC), .95), ...
    mean(perUser.backendSeconds), ...
    'VariableNames', {'n', 'consensusRate', 'consensusSwitchRate', ...
    'pfalfLargeShiftCount', 'scLargeShiftCount', ...
    'pfalfHarmfulLargeShiftCount', 'scHarmfulLargeShiftCount', ...
    'pfalfConditionalHarmfulLargeShiftRate', ...
    'scConditionalHarmfulLargeShiftRate', ...
    'pfalfP95AbsRangeM', 'scP95AbsRangeM', 'meanBackendSeconds'});
output.missThresholdM = protocol.gate.missThresholdM;
end

function output = buildGate(perUser, comparisons, mechanism, protocol)
pa = comparisons(comparisons.candidate == "P_FALF_SC" ...
    & comparisons.reference == "P_A", :);
base = comparisons(comparisons.candidate == "P_FALF_SC" ...
    & comparisons.reference == "P_FALF", :);
aggregatePA = pa(pa.scope == "equal-SNR", :);
aggregateBase = base(base.scope == "equal-SNR", :);
missSC = mean(abs(perUser.rangeError_P_FALF_SC)>protocol.gate.missThresholdM);
missBase = mean(abs(perUser.rangeError_P_FALF)>protocol.gate.missThresholdM);
angleIdentity = max(abs( ...
    perUser.theta_P_FALF_SC-perUser.theta_P_FA), [], "all");
aggregatePARatio = aggregatePA.rangeMseRatio(1);
perSnrPARatio = max(pa.rangeMseRatio(pa.scope == "per-SNR"), [], "all");
aggregateBaseRatio = aggregateBase.rangeMseRatio(1);
p95Ratio = mechanism.scP95AbsRangeM(1)/mechanism.pfalfP95AbsRangeM(1);
missDifference = missSC-missBase;
harmfulRateDifference = ...
    mechanism.scConditionalHarmfulLargeShiftRate(1) ...
    -mechanism.pfalfConditionalHarmfulLargeShiftRate(1);
metric = ["angle-identity-max-deg"; "aggregate-range-MSE/P_A"; ...
    "max-per-SNR-range-MSE/P_A"; "aggregate-range-MSE/P_FALF"; ...
    "P95-absolute-range/P_FALF"; "miss-rate-difference-to-P_FALF"; ...
    "harmful-large-shift-rate-not-increased"];
value = [angleIdentity; aggregatePARatio; perSnrPARatio; ...
    aggregateBaseRatio; p95Ratio; missDifference; harmfulRateDifference];
limit = [protocol.gate.maxAngleIdentityDifferenceDeg; ...
    protocol.gate.maxAggregateRangeMseRatioToPA; ...
    protocol.gate.maxPerSnrRangeMseRatioToPA; ...
    protocol.gate.maxAggregateRangeMseRatioToPFALF; ...
    protocol.gate.maxP95AbsRangeRatioToPFALF; ...
    protocol.gate.maxMissRateDifferenceToPFALF; 0];
pass = isfinite(value) & value <= limit;
output = table(metric, value, repmat("<=", numel(metric), 1), ...
    limit, pass, 'VariableNames', {'metric', 'value', ...
    'direction', 'limit', 'pass'});
output.notes = repmat("predeclared-R56-development-gate", height(output), 1);
end

function value = conditionalRate(event, condition)
if any(condition)
    value = mean(event(condition));
else
    value = 0;
end
end
