function protocol = config()
%CONFIG Freeze the R50 range-conditioning mechanism study.

protocol.version = "R50-PFA-range-conditioning-diagnostics600-v1";
protocol.date = "2026-09-18";
protocol.evidenceRole = "mechanism-diagnostic-no-estimator-selection";
protocol.source = struct(primary="R48-calibration600-existing-rows", ...
    finalAudit="R46-final1400-read-only", newUsers=false, ...
    finalRowsUsedForSelection=false);
protocol.r48 = r48.config();
protocol.localProfile = protocol.r48.r47.r45.r34.r33;
protocol.globalProfile = struct(intervalCount=350, peakCount=8, ...
    tolXM=1e-6, scoreTolerance=1e-10);
protocol.derivative = struct(thetaStepDeg=1e-4, rangeStepM=1e-3, ...
    curvatureFloor=1e-12, modeThresholdM=0.10, ...
    modeSensitivityM=[0.05, 0.10, 0.20]);
protocol.bootstrap = struct(count=10000, seed=65000000, ...
    confidence=0.95, cluster="positionId", ...
    practicalEquivalence=[0.98, 1.02], strongBenefitUpper=0.80);
protocol.r46Audit = struct(count=20000, seed=65010000, ...
    confidence=0.95, trimFraction=0.05, topFractions=[0.01, 0.05], ...
    removalCounts=[3, 5], missThresholdM=1.0, ...
    cannotReplaceFrozenPrimaryConclusion=true);
protocol.execution = struct(batchSize=8, recommendedWorkers=8, ...
    checkpoint="append-only-versioned", ...
    modifyFrozenMethods=false, implementCandidates=false, ...
    pauseAfterDiagnostics=true);
end
