function output = qHessian(cfg, context, thetaDeg, rangeM, protocol)
%QHESSIAN Evaluate local q-profile gradient, Hessian and ridge slope.

arguments
    cfg (1, 1) struct
    context (1, 1) struct
    thetaDeg (1, 1) double {mustBeFinite}
    rangeM (1, 1) double {mustBeFinite, mustBePositive}
    protocol (1, 1) struct = r50.config()
end

hTheta = protocol.derivative.thetaStepDeg;
hRange = protocol.derivative.rangeStepM;
inside = thetaDeg-hTheta >= cfg.thetaLimitsDeg(1) ...
    && thetaDeg+hTheta <= cfg.thetaLimitsDeg(2) ...
    && rangeM-hRange >= cfg.rangeLimitsM(1) ...
    && rangeM+hRange <= cfg.rangeLimitsM(2);
if ~inside
    output = invalidResult(thetaDeg, rangeM, hTheta, hRange, ...
        "physical-boundary");
    return;
end
score = @(theta, rangeValue) r33.fixedAngleProfileLogScore( ...
    cfg, theta, rangeValue, context);
fd = r50.finiteDifference2D(score, thetaDeg, rangeM, hTheta, hRange);
hessian = fd.hessian;
valid = all(isfinite(hessian), "all") ...
    && hessian(2, 2) < -protocol.derivative.curvatureFloor;
if valid
    kappa = -hessian(1, 2)/hessian(2, 2);
    status = "valid-local-range-maximum";
else
    kappa = nan;
    status = "invalid-range-curvature";
end
output = struct(thetaDeg=thetaDeg, rangeM=rangeM, ...
    score=fd.value, gradientThetaPerDeg=fd.gradient(1), ...
    gradientRangePerM=fd.gradient(2), ...
    hessianThetaThetaPerDeg2=hessian(1, 1), ...
    hessianThetaRangePerDegM=hessian(1, 2), ...
    hessianRangeRangePerM2=hessian(2, 2), ...
    kappaMPerDeg=kappa, valid=valid, status=status, ...
    thetaStepDeg=hTheta, rangeStepM=hRange, ...
    evaluationCount=fd.evaluationCount);
end

function output = invalidResult(thetaDeg, rangeM, hTheta, hRange, status)
output = struct(thetaDeg=thetaDeg, rangeM=rangeM, score=nan, ...
    gradientThetaPerDeg=nan, gradientRangePerM=nan, ...
    hessianThetaThetaPerDeg2=nan, ...
    hessianThetaRangePerDegM=nan, ...
    hessianRangeRangePerM2=nan, kappaMPerDeg=nan, ...
    valid=false, status=status, thetaStepDeg=hTheta, ...
    rangeStepM=hRange, evaluationCount=0);
end
