function result = r39AblationTrial( ...
    cfg, scan, designRow, baseline, rowIndex, r34Protocol, protocol)
%R39ABLATIONTRIAL Run three new factorial cells and reuse frozen F.

arguments
    cfg (1, 1) struct
    scan (1, 1) struct
    designRow (1, :) table
    baseline (1, 1) struct
    rowIndex (1, 1) double {mustBeInteger, mustBePositive}
    r34Protocol (1, 1) struct = r34.config()
    protocol (1, 1) struct = r39AblationProtocol()
end

result = failureResult(designRow, rowIndex);
try
    replay = fsjad.replayRound27Data(cfg, scan, designRow);
    [~, peak] = max(abs(replay.observation).^2);
    carrierIndex = r30.selectLocalCarriers(cfg.numSubcarriers, ...
        r34Protocol.r32.music.carrierCount, peak-1);
    finalGrid = baseline.finalGridDeg;
    [distance, selectedIndex] = min(abs( ...
        finalGrid-baseline.P_A.thetaDeg));
    if distance > protocol.search.thetaIdentityToleranceDeg
        error("r39:PAFinalGridIdentityMismatch", ...
            "The P_A angle is not on the actual final grid.");
    end

    contextL = r39PrepareProjectionContext( ...
        cfg, replay.snapshots(:, carrierIndex+1), carrierIndex, 160);
    contextN = r39PrepareProjectionContext( ...
        cfg, replay.snapshots(:, carrierIndex+1), carrierIndex, 256);
    lUniform = evaluateVariant(cfg, scan, replay.observation, ...
        baseline, finalGrid, selectedIndex, contextL, "uniform", ...
        r34Protocol, protocol);
    lVpml = evaluateVariant(cfg, scan, replay.observation, ...
        baseline, finalGrid, selectedIndex, contextL, "vpml", ...
        r34Protocol, protocol);
    nUniform = evaluateVariant(cfg, scan, replay.observation, ...
        baseline, finalGrid, selectedIndex, contextN, "uniform", ...
        r34Protocol, protocol);

    result.success = true;
    result.truthThetaDeg = designRow.truthThetaDeg;
    result.truthRangeM = designRow.truthRangeM;
    result.P_A = baseline.P_A;
    result.E_reference = baseline.E_reference;
    result.C_enhanced = baseline.C_enhanced;
    result.L160_uniform = lUniform;
    result.L160_vpml = lVpml;
    result.N256_uniform = nUniform;
    result.N256_vpml = reusedF(baseline);
    result.carrierIndex = carrierIndex;
    result.centralSubarrayStartIndex = contextL.startIndex;
    result.centralSubarrayElementRows = contextL.elementRows;
catch exception
    result.success = false;
    result.errorIdentifier = string(exception.identifier);
    result.errorMessage = string(getReport( ...
        exception, "extended", "hyperlinks", "off"));
end
end

function output = evaluateVariant(cfg, scan, observation, baseline, ...
    finalGrid, selectedIndex, context, aggregation, r34Protocol, protocol)
score = @(thetaDeg) r39ProjectionScore( ...
    context, thetaDeg, baseline.P_A.rangeM, aggregation);
refinement = r38BracketedVpmlRefinement( ...
    score, finalGrid, selectedIndex, protocol.search);
profileTimer = tic;
profile = r33.profileAtAngle(cfg, observation, scan, ...
    refinement.thetaDeg, baseline.frontRangeM, r34Protocol.r33);
profileSeconds = toc(profileTimer);
runtime = baseline.P_A.runtimeSeconds ...
    +refinement.runtimeSeconds+profileSeconds;
responseCount = baseline.P_A.responseEvaluationCount ...
    +refinement.functionEvaluations+profile.evaluationCount;
output = struct(thetaDeg=refinement.thetaDeg, rangeM=profile.value, ...
    apertureSize=context.apertureSize, aggregation=aggregation, ...
    runtimeSeconds=runtime, responseEvaluationCount=responseCount, ...
    rawProjectionEvaluationCount=refinement.functionEvaluations, ...
    musicEvaluationCount=baseline.P_A.musicEvaluationCount, ...
    evdCount=baseline.P_A.evdCount, profilePassCount=2, ...
    profileEvaluationCount=firstProfileCount(baseline) ...
    +profile.evaluationCount, refinementSeconds=refinement.runtimeSeconds, ...
    profileSeconds=profileSeconds, refinement=refinement, ...
    profile=compactProfile(profile), ...
    elementCarrierProducts=refinement.functionEvaluations ...
    *context.apertureSize*context.carrierCount);
end

function output = reusedF(baseline)
output = baseline.F_raw_vpml;
output.apertureSize = 256;
output.aggregation = "vpml";
output.rawProjectionEvaluationCount = ...
    baseline.refinement.functionEvaluations;
output.profilePassCount = 2;
output.profileEvaluationCount = ...
    baseline.F_raw_vpml.profileEvaluationCount;
output.refinement = baseline.refinement;
output.profile = baseline.profile;
end

function count = firstProfileCount(baseline)
count = baseline.firstProfileEvaluationCount;
end

function output = compactProfile(profile)
output = struct(value=profile.value, score=profile.score, ...
    interval=profile.interval, endpointHit=profile.endpointHit, ...
    evaluationCount=profile.evaluationCount, version=profile.version);
end

function result = failureResult(designRow, rowIndex)
result = struct(success=false, rowIndex=rowIndex, seed=designRow.seed, ...
    trialIndex=designRow.trialIndex, snrDb=designRow.snrDb, ...
    truthThetaDeg=designRow.truthThetaDeg, ...
    truthRangeM=designRow.truthRangeM, ...
    errorIdentifier="", errorMessage="");
end
