function context = r39PrepareProjectionContext( ...
    cfg, snapshots, carrierIndex, apertureSize)
%R39PREPAREPROJECTIONCONTEXT Extract one fixed contiguous raw aperture.

arguments
    cfg (1, 1) struct
    snapshots (:, :) double
    carrierIndex (:, 1) double {mustBeInteger, mustBeNonnegative}
    apertureSize (1, 1) double {mustBeInteger, mustBePositive}
end

if apertureSize > cfg.numAntennas ...
        || size(snapshots, 1) ~= cfg.numAntennas ...
        || size(snapshots, 2) ~= numel(carrierIndex)
    error("r39:ProjectionContextSize", ...
        "The raw snapshots or aperture size are invalid.");
end
startIndex = floor((cfg.numAntennas-apertureSize)/2)+1;
elementRows = startIndex+(0:apertureSize-1);
apertureSnapshots = snapshots(elementRows, :);
energy = real(sum(abs(apertureSnapshots).^2, 1));
if any(energy <= 0) || any(~isfinite(energy))
    error("r39:ProjectionSnapshotEnergy", ...
        "Every aperture snapshot must have positive finite energy.");
end
[~, ~, frequencyHz] = jad.trajectory(cfg, carrierIndex);
x = cfg.elementIndex(elementRows)*cfg.elementSpacing;
context = struct(version="R39-fixed-raw-aperture-context-v1", ...
    snapshots=apertureSnapshots, carrierIndex=carrierIndex, ...
    frequencyHz=frequencyHz(:).', ...
    wavenumber=2*pi*frequencyHz(:).'/cfg.c, ...
    x=x, xSquared=x.^2, snapshotEnergy=energy, ...
    totalEnergy=sum(energy), apertureSize=apertureSize, ...
    startIndex=startIndex, elementRows=elementRows(:), ...
    carrierCount=numel(carrierIndex), ...
    arrayNormalization=sqrt(apertureSize));
end
