function output = r39SummarizeAblation(design, results, protocol)
%R39SUMMARIZEABLATION Summarize the fixed 2-by-2 mechanism ablation.

arguments
    design table
    results cell
    protocol (1, 1) struct = r39AblationProtocol()
end

if numel(results) ~= height(design) || any(cellfun(@isempty, results)) ...
        || any(cellfun(@(x) ~x.success, results))
    error("r39:IncompleteAblationResults", ...
        "R39 requires every fixed development row.");
end
perUser = buildPerUser(design, results);
methodSummary = summarizeMethods(perUser);
factorial = factorialEffects(perUser);
comparisons = factorComparisons(perUser);
diagnostics = summarizeDiagnostics(perUser);
gate = diagnosticGates(methodSummary, protocol);
output = struct(version="R39-factorial-ablation-summary-v1", ...
    dataRole=protocol.evidenceRole, perUser=perUser, ...
    methodSummary=methodSummary, factorial=factorial, ...
    comparisons=comparisons, diagnostics=diagnostics, gate=gate);
end

function perUser = buildPerUser(design, results)
methods = ["P_A", "E_reference", "C_enhanced", "L160_uniform", ...
    "L160_vpml", "N256_uniform", "N256_vpml"];
perUser = design(:, ["seed", "trialIndex", "snrDb", ...
    "truthThetaDeg", "truthRangeM"]);
for method = methods
    perUser.("theta_"+method) = cellfun( ...
        @(x) x.(method).thetaDeg, results);
    perUser.("range_"+method) = cellfun( ...
        @(x) x.(method).rangeM, results);
    perUser.("runtime_"+method) = cellfun( ...
        @(x) x.(method).runtimeSeconds, results);
    perUser.("responseCount_"+method) = cellfun( ...
        @(x) x.(method).responseEvaluationCount, results);
    perUser.("musicCount_"+method) = cellfun( ...
        @(x) x.(method).musicEvaluationCount, results);
    perUser.("evdCount_"+method) = cellfun( ...
        @(x) x.(method).evdCount, results);
end
variants = ["L160_uniform", "L160_vpml", ...
    "N256_uniform", "N256_vpml"];
for variant = variants
    perUser.("scoreGain_"+variant) = cellfun( ...
        @(x) x.(variant).refinement.scoreGain, results);
    perUser.("displacement_"+variant) = cellfun( ...
        @(x) x.(variant).refinement.displacementDeg, results);
    perUser.("endpoint_"+variant) = cellfun( ...
        @(x) x.(variant).refinement.bracketEndpointSelected, results);
    perUser.("functionCount_"+variant) = cellfun( ...
        @(x) x.(variant).refinement.functionEvaluations, results);
end
end

function output = summarizeMethods(perUser)
methods = ["P_A", "E_reference", "C_enhanced", "L160_uniform", ...
    "L160_vpml", "N256_uniform", "N256_vpml"];
output = table();
for method = methods
    theta = perUser.("theta_"+method);
    rangeM = perUser.("range_"+method);
    for snrDb = unique(perUser.snrDb).'
        selected = perUser.snrDb == snrDb;
        angleError = theta(selected)-perUser.truthThetaDeg(selected);
        rangeError = rangeM(selected)-perUser.truthRangeM(selected);
        positionError = positionErrorM(theta(selected), rangeM(selected), ...
            perUser.truthThetaDeg(selected), perUser.truthRangeM(selected));
        angleSquared = angleError.^2;
        rangeSquared = rangeError.^2;
        runtime = perUser.("runtime_"+method);
        response = perUser.("responseCount_"+method);
        music = perUser.("musicCount_"+method);
        evd = perUser.("evdCount_"+method);
        entry = table(method, snrDb, nnz(selected), mean(angleSquared), ...
            sqrt(mean(angleSquared)), median(abs(angleError)), ...
            quantile(abs(angleError), 0.90), ...
            quantile(abs(angleError), 0.95), mean(rangeSquared), ...
            sqrt(mean(rangeSquared)), sqrt(mean(positionError.^2)), ...
            mean(runtime(selected)), mean(response(selected)), ...
            mean(music(selected)), mean(evd(selected)), ...
            'VariableNames', {'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', ...
            'angleMedianAbsoluteErrorDeg', 'angleP90AbsoluteErrorDeg', ...
            'angleP95AbsoluteErrorDeg', 'rangeMseM2', 'rangeRmseM', ...
            'positionRmseM', 'meanRuntimeSeconds', ...
            'meanResponseEvaluationCount', 'meanMusicEvaluationCount', ...
            'meanEvdCount'});
        output = [output; entry]; %#ok<AGROW>
    end
end
end

function output = factorialEffects(perUser)
output = table();
snrValues = unique(perUser.snrDb).';
mse = struct();
variants = ["L160_uniform", "L160_vpml", ...
    "N256_uniform", "N256_vpml"];
for variant = variants
    mse.(variant) = zeros(numel(snrValues), 1);
end
for index = 1:numel(snrValues)
    selected = perUser.snrDb == snrValues(index);
    for variant = variants
        error = perUser.("theta_"+variant)(selected) ...
            -perUser.truthThetaDeg(selected);
        mse.(variant)(index) = mean(error.^2);
    end
    output = [output; factorialRow("per-SNR", snrValues(index), ...
        nnz(selected), indexValues(mse, index))]; %#ok<AGROW>
end
aggregate = zeros(1, 4);
for index = 1:numel(variants)
    aggregate(index) = mean(mse.(variants(index)));
end
output = [output; factorialRow("equal-SNR", nan, height(perUser), ...
    aggregate)];
end

function values = indexValues(mse, index)
values = [mse.L160_uniform(index), mse.L160_vpml(index), ...
    mse.N256_uniform(index), mse.N256_vpml(index)];
end

function row = factorialRow(scope, snrDb, n, values)
lUniform = values(1);
lVpml = values(2);
nUniform = values(3);
nVpml = values(4);
apertureUniform = nUniform/lUniform;
apertureVpml = nVpml/lVpml;
likelihoodL = lVpml/lUniform;
likelihoodN = nVpml/nUniform;
interaction = apertureVpml/apertureUniform;
row = table(scope, snrDb, n, lUniform, lVpml, nUniform, nVpml, ...
    apertureUniform, 100*(1-sqrt(apertureUniform)), ...
    apertureVpml, 100*(1-sqrt(apertureVpml)), likelihoodL, ...
    100*(1-sqrt(likelihoodL)), likelihoodN, ...
    100*(1-sqrt(likelihoodN)), interaction, ...
    'VariableNames', {'scope', 'snrDb', 'n', ...
    'angleMse_L160_uniform', 'angleMse_L160_vpml', ...
    'angleMse_N256_uniform', 'angleMse_N256_vpml', ...
    'apertureMseRatioUnderUniform', ...
    'apertureRmseImprovementUnderUniformPercent', ...
    'apertureMseRatioUnderVpml', ...
    'apertureRmseImprovementUnderVpmlPercent', ...
    'likelihoodMseRatioAtL160', ...
    'likelihoodRmseImprovementAtL160Percent', ...
    'likelihoodMseRatioAtN256', ...
    'likelihoodRmseImprovementAtN256Percent', 'interactionRatio'});
end

function output = factorComparisons(perUser)
pairs = ["N256_uniform", "L160_uniform"; ...
    "N256_vpml", "L160_vpml"; ...
    "L160_vpml", "L160_uniform"; ...
    "N256_vpml", "N256_uniform"];
labels = ["aperture-under-uniform", "aperture-under-vpml", ...
    "likelihood-at-L160", "likelihood-at-N256"];
output = table();
for index = 1:size(pairs, 1)
    output = [output; pairedRows(perUser, pairs(index, 1), ...
        pairs(index, 2), labels(index))]; %#ok<AGROW>
end
end

function output = pairedRows(perUser, candidate, reference, effect)
output = table();
snrValues = unique(perUser.snrDb).';
candidateMse = zeros(numel(snrValues), 1);
referenceMse = zeros(numel(snrValues), 1);
allDifference = zeros(0, 1);
for index = 1:numel(snrValues)
    selected = perUser.snrDb == snrValues(index);
    candidateSquared = (perUser.("theta_"+candidate)(selected) ...
        -perUser.truthThetaDeg(selected)).^2;
    referenceSquared = (perUser.("theta_"+reference)(selected) ...
        -perUser.truthThetaDeg(selected)).^2;
    difference = candidateSquared-referenceSquared;
    candidateMse(index) = mean(candidateSquared);
    referenceMse(index) = mean(referenceSquared);
    output = [output; comparisonRow(effect, candidate, reference, ...
        "per-SNR", snrValues(index), difference, ...
        candidateMse(index), referenceMse(index))]; %#ok<AGROW>
    allDifference = [allDifference; difference]; %#ok<AGROW>
end
output = [output; comparisonRow(effect, candidate, reference, ...
    "equal-SNR", nan, allDifference, mean(candidateMse), ...
    mean(referenceMse))];
end

function row = comparisonRow(effect, candidate, reference, scope, ...
    snrDb, difference, candidateMse, referenceMse)
ratio = candidateMse/referenceMse;
row = table(effect, candidate, reference, scope, snrDb, ...
    numel(difference), ratio, 100*(1-sqrt(ratio)), ...
    nnz(difference < 0), nnz(difference == 0), nnz(difference > 0), ...
    'VariableNames', {'effect', 'candidate', 'reference', 'scope', ...
    'snrDb', 'n', 'angleMseRatio', 'angleRmseImprovementPercent', ...
    'winCount', 'tieCount', 'lossCount'});
end

function output = summarizeDiagnostics(perUser)
variants = ["L160_uniform", "L160_vpml", ...
    "N256_uniform", "N256_vpml"];
output = table();
for variant = variants
    for snrDb = unique(perUser.snrDb).'
        selected = perUser.snrDb == snrDb;
        truthGain = (perUser.theta_P_A(selected) ...
            -perUser.truthThetaDeg(selected)).^2 ...
            -(perUser.("theta_"+variant)(selected) ...
            -perUser.truthThetaDeg(selected)).^2;
        scoreGain = perUser.("scoreGain_"+variant)(selected);
        entry = table(variant, snrDb, nnz(selected), ...
            nnz(perUser.("endpoint_"+variant)(selected)), ...
            mean(abs(perUser.("displacement_"+variant)(selected))), ...
            mean(perUser.("functionCount_"+variant)(selected)), ...
            mean(scoreGain), nnz(truthGain > 0), nnz(truthGain == 0), ...
            nnz(truthGain < 0), finiteCorrelation(scoreGain, truthGain), ...
            'VariableNames', {'variant', 'snrDb', 'n', ...
            'bracketEndpointSelectedCount', ...
            'meanAbsoluteAngleDisplacementDeg', ...
            'meanFunctionEvaluations', 'meanScoreGain', ...
            'truthImproveCount', 'truthTieCount', 'truthWorseCount', ...
            'scoreTruthGainCorrelation'});
        output = [output; entry]; %#ok<AGROW>
    end
end
end

function output = diagnosticGates(summary, protocol)
variants = ["L160_uniform", "L160_vpml", ...
    "N256_uniform", "N256_vpml"];
output = table();
for variant = variants
    pa = summary(summary.method == "P_A", :);
    current = summary(summary.method == variant, :);
    for snrDb = unique(summary.snrDb).'
        paRow = pa(pa.snrDb == snrDb, :);
        row = current(current.snrDb == snrDb, :);
        output = [output; gateRow(variant, "angle", snrDb, ...
            row.angleMseDeg2/paRow.angleMseDeg2, ...
            protocol.gate.maximumPerSnrAngleMseRatio)]; %#ok<AGROW>
        output = [output; gateRow(variant, "range", snrDb, ...
            row.rangeMseM2/paRow.rangeMseM2, ...
            protocol.gate.maximumPerSnrRangeMseRatio)]; %#ok<AGROW>
    end
    output = [output; gateRow(variant, "aggregate-angle", nan, ...
        mean(current.angleMseDeg2)/mean(pa.angleMseDeg2), ...
        protocol.gate.maximumEqualSnrAngleMseRatio)]; %#ok<AGROW>
    c = summary(summary.method == "C_enhanced", :);
    output = [output; gateRow(variant, "runtime-to-C-enhanced", nan, ...
        mean(current.meanRuntimeSeconds)/mean(c.meanRuntimeSeconds), ...
        protocol.gate.maximumRuntimeRatioToCEnhanced)]; %#ok<AGROW>
end
end

function row = gateRow(variant, category, snrDb, observed, limit)
row = table(variant, category, snrDb, observed, limit, observed <= limit, ...
    'VariableNames', {'variant', 'category', 'snrDb', ...
    'observedRatio', 'maximumAllowedRatio', 'pass'});
end

function value = finiteCorrelation(first, second)
if std(first) == 0 || std(second) == 0
    value = nan;
else
    matrix = corrcoef(first, second);
    value = matrix(1, 2);
end
end

function value = positionErrorM(theta, rangeM, truthTheta, truthRange)
xError = rangeM.*sind(theta)-truthRange.*sind(truthTheta);
yError = rangeM.*cosd(theta)-truthRange.*cosd(truthTheta);
value = hypot(xError, yError);
end
