function context = r38PrepareRawArrayVpmlContext( ...
    cfg, snapshots, carrierIndex)
%R38PREPARERAWARRAYVPMLCONTEXT Cache raw-array likelihood invariants.

arguments
    cfg (1, 1) struct
    snapshots (:, :) double
    carrierIndex (:, 1) double {mustBeInteger, mustBeNonnegative}
end

if size(snapshots, 1) ~= cfg.numAntennas ...
        || size(snapshots, 2) ~= numel(carrierIndex) ...
        || any(carrierIndex >= cfg.numSubcarriers)
    error("r38:RawArrayContextSize", ...
        "Snapshots must be N-by-K for the declared zero-based carriers.");
end
snapshotEnergy = real(sum(abs(snapshots).^2, 1));
totalEnergy = sum(snapshotEnergy);
if ~isfinite(totalEnergy) || totalEnergy <= 0
    error("r38:RawArrayZeroEnergy", ...
        "The raw-array snapshots must have positive finite energy.");
end
[~, ~, frequencyHz] = jad.trajectory(cfg, carrierIndex);
context = struct(version="R38-raw-array-vpml-context-v1", ...
    snapshots=snapshots, carrierIndex=carrierIndex, ...
    frequencyHz=frequencyHz(:).', ...
    wavenumber=2*pi*frequencyHz(:).'/cfg.c, ...
    x=cfg.elementIndex*cfg.elementSpacing, ...
    xSquared=(cfg.elementIndex*cfg.elementSpacing).^2, ...
    snapshotEnergy=snapshotEnergy, totalEnergy=totalEnergy, ...
    numAntennas=cfg.numAntennas, carrierCount=numel(carrierIndex), ...
    arrayNormalization=sqrt(cfg.numAntennas));
end
