function [score, diagnostics] = r38RawArrayVpmlScore( ...
    cfg, context, thetaDeg, rangeM)
%R38RAWARRAYVPMLSCORE Concentrated raw-array conditional ML score.

arguments
    cfg (1, 1) struct
    context (1, 1) struct
    thetaDeg (1, 1) double {mustBeFinite}
    rangeM (1, 1) double {mustBeFinite, mustBePositive}
end

if context.numAntennas ~= cfg.numAntennas
    error("r38:RawArrayAntennaMismatch", ...
        "The VPML context does not match cfg.numAntennas.");
end
thetaRad = deg2rad(thetaDeg);
distance = rangeM-context.x*sin(thetaRad) ...
    +context.xSquared*cos(thetaRad)^2/(2*rangeM);
steering = exp(-1i*distance.*context.wavenumber) ...
    /context.arrayNormalization;
alphaHat = sum(conj(steering).*context.snapshots, 1);
explainedEnergy = sum(abs(alphaHat).^2);
residualEnergy = context.totalEnergy-explainedEnergy;
roundoffTolerance = 100*eps*max(context.totalEnergy, 1);
if residualEnergy < -roundoffTolerance
    error("r38:VariableProjectionEnergyInvariant", ...
        "Explained energy exceeds total raw-array energy.");
end
residualEnergy = max(residualEnergy, 0);
score = explainedEnergy/context.totalEnergy;
if nargout > 1
    carrierResidualEnergy = context.snapshotEnergy-abs(alphaHat).^2;
    diagnostics = struct(version="R38-conditional-vpml-score-v1", ...
        score=score, explainedEnergy=explainedEnergy, ...
        residualEnergy=residualEnergy, ...
        normalizedResidualEnergy=residualEnergy/context.totalEnergy, ...
        alphaHat=alphaHat(:), ...
        carrierResidualEnergy=carrierResidualEnergy(:), ...
        responseEvaluationCount=1, ...
        carrierSteeringVectorCount=context.carrierCount, ...
        elementCarrierProductCount= ...
        context.numAntennas*context.carrierCount);
end
end
