function result = r38SchemeFTrial( ...
    cfg, scan, designRow, baseline, rowIndex, r34Protocol, schemeProtocol)
%R38SCHEMEFTRIAL Run raw-array VPML on one frozen development user.

arguments
    cfg (1, 1) struct
    scan (1, 1) struct
    designRow (1, :) table
    baseline (1, 1) struct
    rowIndex (1, 1) double {mustBeInteger, mustBePositive}
    r34Protocol (1, 1) struct = r34.config()
    schemeProtocol (1, 1) struct = r38SchemeFConfig()
end

result = failureResult(designRow, rowIndex);
try
    replay = fsjad.replayRound27Data(cfg, scan, designRow);
    [~, peak] = max(abs(replay.observation).^2);
    carrierIndex = r30.selectLocalCarriers(cfg.numSubcarriers, ...
        r34Protocol.r32.music.carrierCount, peak-1);
    context = r38PrepareRawArrayVpmlContext(cfg, ...
        replay.snapshots(:, carrierIndex+1), carrierIndex);
    finalGridDeg = baseline.finalGridDeg;
    [distance, selectedIndex] = min(abs( ...
        finalGridDeg-baseline.P_A.thetaDeg));
    if distance > schemeProtocol.thetaIdentityToleranceDeg
        error("r38:PAFinalGridIdentityMismatch", ...
            "The frozen P_A angle is not on its actual final grid.");
    end
    score = @(thetaDeg) r38RawArrayVpmlScore( ...
        cfg, context, thetaDeg, baseline.P_A.rangeM);
    refinement = r38BracketedVpmlRefinement( ...
        score, finalGridDeg, selectedIndex, schemeProtocol);

    profileTimer = tic;
    profile = r33.profileAtAngle(cfg, replay.observation, scan, ...
        refinement.thetaDeg, baseline.frontRangeM, r34Protocol.r33);
    profileSeconds = toc(profileTimer);
    completeRuntime = baseline.P_A.runtimeSeconds ...
        +refinement.runtimeSeconds+profileSeconds;
    totalResponseCount = baseline.P_A.responseEvaluationCount ...
        +refinement.functionEvaluations+profile.evaluationCount;
    qOnlyResponseCount = baseline.P_A.responseEvaluationCount ...
        +profile.evaluationCount;
    baseResponseCount = baseline.E_one_step.responseEvaluationCount ...
        -baseline.profile.evaluationCount;
    firstProfileEvaluationCount = ...
        baseline.P_A.responseEvaluationCount-baseResponseCount;
    excludedCarrier = setdiff((0:cfg.numSubcarriers-1).', carrierIndex);

    result.success = true;
    result.truthThetaDeg = designRow.truthThetaDeg;
    result.truthRangeM = designRow.truthRangeM;
    result.frontThetaDeg = baseline.frontThetaDeg;
    result.frontRangeM = baseline.frontRangeM;
    result.P_A = baseline.P_A;
    result.C_enhanced = baseline.C_enhanced;
    result.E_reference = correctedEReference(baseline);
    result.E_reference.profilePassCount = 2;
    result.E_reference.profileEvaluationCount = ...
        firstProfileEvaluationCount+baseline.profile.evaluationCount;
    result.F_raw_vpml = locationRecord(refinement.thetaDeg, ...
        profile.value, completeRuntime, totalResponseCount, ...
        qOnlyResponseCount, refinement.functionEvaluations, ...
        baseline.P_A.musicEvaluationCount, baseline.P_A.evdCount);
    result.F_raw_vpml.refinementSeconds = refinement.runtimeSeconds;
    result.F_raw_vpml.profileSeconds = profileSeconds;
    result.F_raw_vpml.carrierCount = context.carrierCount;
    result.F_raw_vpml.profilePassCount = 2;
    result.F_raw_vpml.profileEvaluationCount = ...
        firstProfileEvaluationCount+profile.evaluationCount;
    result.F_raw_vpml.fullArrayElementCarrierProducts = ...
        refinement.functionEvaluations*cfg.numAntennas*context.carrierCount;
    result.refinement = refinement;
    result.profile = compactProfile(profile);
    result.firstProfileEvaluationCount = firstProfileEvaluationCount;
    result.finalGridDeg = finalGridDeg;
    result.selectedGridIndex = selectedIndex;
    result.excludedCarrierIndex = excludedCarrier;
catch exception
    result.success = false;
    result.errorIdentifier = string(exception.identifier);
    result.errorMessage = string(getReport( ...
        exception, "extended", "hyperlinks", "off"));
end
end

function output = correctedEReference(baseline)
runtime = baseline.P_A.runtimeSeconds ...
    +baseline.E_one_step.refinementSeconds ...
    +baseline.E_one_step.profileSeconds;
responses = baseline.P_A.responseEvaluationCount ...
    +baseline.profile.evaluationCount;
output = baseline.E_one_step;
output.runtimeSeconds = runtime;
output.responseEvaluationCount = responses;
end

function output = locationRecord(thetaDeg, rangeM, runtimeSeconds, ...
    responseEvaluationCount, qOnlyResponseEvaluationCount, ...
    vpmlEvaluationCount, musicEvaluationCount, evdCount)
output = struct(thetaDeg=thetaDeg, rangeM=rangeM, ...
    runtimeSeconds=runtimeSeconds, ...
    responseEvaluationCount=responseEvaluationCount, ...
    qOnlyResponseEvaluationCount=qOnlyResponseEvaluationCount, ...
    rawArrayVpmlEvaluationCount=vpmlEvaluationCount, ...
    musicEvaluationCount=musicEvaluationCount, evdCount=evdCount);
end

function output = compactProfile(profile)
output = struct(version=profile.version, value=profile.value, ...
    score=profile.score, interval=profile.interval, ...
    endpointHit=profile.endpointHit, lambda=profile.lambda, ...
    coarseSpacingM=profile.coarseSpacingM, ...
    peakCount=profile.peakCount, evaluationCount=profile.evaluationCount);
end

function result = failureResult(designRow, rowIndex)
result = struct(success=false, rowIndex=rowIndex, seed=designRow.seed, ...
    trialIndex=designRow.trialIndex, snrDb=designRow.snrDb, ...
    truthThetaDeg=designRow.truthThetaDeg, ...
    truthRangeM=designRow.truthRangeM, ...
    errorIdentifier="", errorMessage="");
end
