function output = r38SummarizeSchemeF(design, results, commonProtocol)
%R38SUMMARIZESCHEMEF Apply frozen metrics and development gates.

arguments
    design table
    results cell
    commonProtocol (1, 1) struct = r38CommonProtocol()
end

if numel(results) ~= height(design) || any(cellfun(@isempty, results)) ...
        || any(cellfun(@(x) ~x.success, results))
    error("r38:IncompleteSchemeFResults", ...
        "Scheme F requires all fixed development rows.");
end
perUser = buildPerUser(design, results);
methodSummary = summarizeMethods(perUser);
comparisons = [pairedRows(perUser, "F_raw_vpml", "P_A"); ...
    pairedRows(perUser, "F_raw_vpml", "E_reference")];
diagnostics = summarizeDiagnostics(perUser);
gate = engineeringGate(methodSummary, commonProtocol);
output = struct(version="R38-schemeF-development-summary-v1", ...
    dataRole=commonProtocol.evidenceRole, perUser=perUser, ...
    methodSummary=methodSummary, comparisons=comparisons, ...
    diagnostics=diagnostics, gate=gate, gatePassed=all(gate.pass));
end

function perUser = buildPerUser(design, results)
paTheta = cellfun(@(x) x.P_A.thetaDeg, results);
paRange = cellfun(@(x) x.P_A.rangeM, results);
fTheta = cellfun(@(x) x.F_raw_vpml.thetaDeg, results);
fRange = cellfun(@(x) x.F_raw_vpml.rangeM, results);
eTheta = cellfun(@(x) x.E_reference.thetaDeg, results);
eRange = cellfun(@(x) x.E_reference.rangeM, results);
bracket = cell2mat(cellfun(@(x) x.refinement.bracketDeg, ...
    results, UniformOutput=false));
truthGain = (paTheta-design.truthThetaDeg).^2 ...
    -(fTheta-design.truthThetaDeg).^2;
perUser = table(design.seed, design.trialIndex, design.snrDb, ...
    design.truthThetaDeg, design.truthRangeM, ...
    cellfun(@(x) x.frontThetaDeg, results), ...
    cellfun(@(x) x.frontRangeM, results), ...
    paTheta, paRange, eTheta, eRange, fTheta, fRange, ...
    cellfun(@(x) x.C_enhanced.thetaDeg, results), ...
    cellfun(@(x) x.C_enhanced.rangeM, results), ...
    bracket(:, 1), bracket(:, 2), fTheta-paTheta, truthGain, ...
    cellfun(@(x) x.refinement.scoreBefore, results), ...
    cellfun(@(x) x.refinement.scoreAfter, results), ...
    cellfun(@(x) x.refinement.scoreGain, results), ...
    cellfun(@(x) x.refinement.functionEvaluations, results), ...
    cellfun(@(x) x.refinement.converged, results), ...
    cellfun(@(x) x.refinement.bracketEndpointSelected, results), ...
    string(cellfun(@(x) x.refinement.selectedSource, ...
    results, UniformOutput=false)), ...
    string(cellfun(@(x) x.refinement.status, ...
    results, UniformOutput=false)), ...
    cellfun(@(x) x.P_A.runtimeSeconds, results), ...
    cellfun(@(x) x.E_reference.runtimeSeconds, results), ...
    cellfun(@(x) x.F_raw_vpml.runtimeSeconds, results), ...
    cellfun(@(x) x.C_enhanced.runtimeSeconds, results), ...
    cellfun(@(x) x.F_raw_vpml.refinementSeconds, results), ...
    cellfun(@(x) x.F_raw_vpml.profileSeconds, results), ...
    cellfun(@(x) x.P_A.responseEvaluationCount, results), ...
    cellfun(@(x) x.E_reference.responseEvaluationCount, results), ...
    cellfun(@(x) x.F_raw_vpml.responseEvaluationCount, results), ...
    cellfun(@(x) x.C_enhanced.responseEvaluationCount, results), ...
    cellfun(@(x) x.F_raw_vpml.qOnlyResponseEvaluationCount, results), ...
    cellfun(@(x) x.F_raw_vpml.rawArrayVpmlEvaluationCount, results), ...
    cellfun(@(x) x.P_A.musicEvaluationCount, results), ...
    cellfun(@(x) x.E_reference.musicEvaluationCount, results), ...
    cellfun(@(x) x.F_raw_vpml.musicEvaluationCount, results), ...
    cellfun(@(x) x.C_enhanced.musicEvaluationCount, results), ...
    cellfun(@(x) x.P_A.evdCount, results), ...
    cellfun(@(x) x.E_reference.evdCount, results), ...
    cellfun(@(x) x.F_raw_vpml.evdCount, results), ...
    cellfun(@(x) x.C_enhanced.evdCount, results), ...
    cellfun(@(x) x.firstProfileEvaluationCount, results), ...
    cellfun(@(x) x.firstProfileEvaluationCount ...
    +x.profile.evaluationCount, results), ...
    cellfun(@(x) x.F_raw_vpml.fullArrayElementCarrierProducts, results), ...
    'VariableNames', {'seed', 'trialIndex', 'snrDb', ...
    'truthThetaDeg', 'truthRangeM', 'frontThetaDeg', 'frontRangeM', ...
    'theta_P_A', 'range_P_A', 'theta_E_reference', ...
    'range_E_reference', 'theta_F_raw_vpml', 'range_F_raw_vpml', ...
    'theta_C_enhanced', 'range_C_enhanced', 'bracketLowerDeg', ...
    'bracketUpperDeg', 'angleDisplacementDeg', ...
    'truthSquaredErrorGainDeg2', 'scoreBefore', 'scoreAfter', ...
    'scoreGain', 'vpmlFunctionEvaluations', 'optimizerConverged', ...
    'bracketEndpointSelected', 'selectedSource', 'status', ...
    'runtime_P_A', 'runtime_E_reference', 'runtime_F_raw_vpml', ...
    'runtime_C_enhanced', 'vpmlSeconds', 'refreshedProfileSeconds', ...
    'responseCount_P_A', 'responseCount_E_reference', ...
    'responseCount_F_raw_vpml', 'responseCount_C_enhanced', ...
    'qOnlyResponseCount_F_raw_vpml', 'rawArrayVpmlCount_F', ...
    'musicCount_P_A', 'musicCount_E_reference', ...
    'musicCount_F_raw_vpml', 'musicCount_C_enhanced', ...
    'evdCount_P_A', 'evdCount_E_reference', 'evdCount_F_raw_vpml', ...
    'evdCount_C_enhanced', 'profileEvaluations_P_A', ...
    'profileEvaluations_F_raw_vpml', ...
    'fullArrayElementCarrierProducts'});
end

function output = summarizeMethods(perUser)
methods = ["P_A", "E_reference", "F_raw_vpml", "C_enhanced"];
output = table();
for method = methods
    [theta, rangeM, runtime, response, music, evd] = ...
        methodColumns(perUser, method);
    for snrDb = unique(perUser.snrDb).'
        selected = perUser.snrDb == snrDb;
        angleError = theta(selected)-perUser.truthThetaDeg(selected);
        rangeError = rangeM(selected)-perUser.truthRangeM(selected);
        positionError = positionErrorM(theta(selected), rangeM(selected), ...
            perUser.truthThetaDeg(selected), perUser.truthRangeM(selected));
        angleSquared = angleError.^2;
        rangeSquared = rangeError.^2;
        entry = table(method, snrDb, nnz(selected), mean(angleSquared), ...
            sqrt(mean(angleSquared)), median(abs(angleError)), ...
            quantile(abs(angleError), 0.90), ...
            quantile(abs(angleError), 0.95), mean(rangeSquared), ...
            sqrt(mean(rangeSquared)), sqrt(mean(positionError.^2)), ...
            mean(runtime(selected)), mean(response(selected)), ...
            mean(music(selected)), mean(evd(selected)), ...
            'VariableNames', {'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', ...
            'angleMedianAbsoluteErrorDeg', 'angleP90AbsoluteErrorDeg', ...
            'angleP95AbsoluteErrorDeg', 'rangeMseM2', 'rangeRmseM', ...
            'positionRmseM', 'meanRuntimeSeconds', ...
            'meanResponseEvaluationCount', 'meanMusicEvaluationCount', ...
            'meanEvdCount'});
        output = [output; entry]; %#ok<AGROW>
    end
end
end

function [theta, rangeM, runtime, response, music, evd] = ...
    methodColumns(input, method)
if method == "P_A"
    name = "P_A";
elseif method == "E_reference"
    name = "E_reference";
elseif method == "F_raw_vpml"
    name = "F_raw_vpml";
else
    name = "C_enhanced";
end
theta = input.("theta_"+name);
rangeM = input.("range_"+name);
runtime = input.("runtime_"+name);
response = input.("responseCount_"+name);
music = input.("musicCount_"+name);
evd = input.("evdCount_"+name);
end

function output = pairedRows(perUser, candidate, reference)
[candidateTheta, ~, ~, ~, ~, ~] = methodColumns(perUser, candidate);
[referenceTheta, ~, ~, ~, ~, ~] = methodColumns(perUser, reference);
output = table();
snrValues = unique(perUser.snrDb).';
candidateMse = zeros(numel(snrValues), 1);
referenceMse = zeros(numel(snrValues), 1);
allDifference = zeros(0, 1);
for index = 1:numel(snrValues)
    selected = perUser.snrDb == snrValues(index);
    candidateSquared = (candidateTheta(selected) ...
        -perUser.truthThetaDeg(selected)).^2;
    referenceSquared = (referenceTheta(selected) ...
        -perUser.truthThetaDeg(selected)).^2;
    difference = candidateSquared-referenceSquared;
    candidateMse(index) = mean(candidateSquared);
    referenceMse(index) = mean(referenceSquared);
    output = [output; comparisonRow(candidate, reference, "per-SNR", ...
        snrValues(index), difference, candidateMse(index), ...
        referenceMse(index))]; %#ok<AGROW>
    allDifference = [allDifference; difference]; %#ok<AGROW>
end
output = [output; comparisonRow(candidate, reference, "equal-SNR", ...
    nan, allDifference, mean(candidateMse), mean(referenceMse))];
end

function row = comparisonRow(candidate, reference, scope, snrDb, ...
    difference, candidateMse, referenceMse)
ratio = candidateMse/referenceMse;
row = table(candidate, reference, scope, snrDb, numel(difference), ...
    candidateMse, referenceMse, ratio, 100*(1-sqrt(ratio)), ...
    mean(difference), nnz(difference < 0), nnz(difference == 0), ...
    nnz(difference > 0), 'VariableNames', {'candidate', 'reference', ...
    'scope', 'snrDb', 'n', 'candidateAngleMseDeg2', ...
    'referenceAngleMseDeg2', 'angleMseRatio', ...
    'angleRmseImprovementPercent', ...
    'meanCandidateMinusReferenceSquaredError', 'winCount', ...
    'tieCount', 'lossCount'});
end

function output = summarizeDiagnostics(perUser)
output = table();
snrValues = [unique(perUser.snrDb).', nan];
for snrDb = snrValues
    if isnan(snrDb)
        selected = true(height(perUser), 1);
        scope = "all-SNR";
    else
        selected = perUser.snrDb == snrDb;
        scope = "per-SNR";
    end
    gain = perUser.truthSquaredErrorGainDeg2(selected);
    scoreGain = perUser.scoreGain(selected);
    output = [output; table(scope, snrDb, nnz(selected), ...
        nnz(perUser.optimizerConverged(selected)), ...
        nnz(perUser.bracketEndpointSelected(selected)), ...
        mean(abs(perUser.angleDisplacementDeg(selected))), ...
        max(abs(perUser.angleDisplacementDeg(selected))), ...
        mean(scoreGain), nnz(scoreGain > 0), nnz(gain > 0), ...
        nnz(gain == 0), nnz(gain < 0), ...
        finiteCorrelation(scoreGain, gain), ...
        mean(perUser.vpmlFunctionEvaluations(selected)), ...
        mean(perUser.vpmlSeconds(selected)), ...
        mean(perUser.refreshedProfileSeconds(selected)), ...
        'VariableNames', {'scope', 'snrDb', 'n', ...
        'optimizerConvergedCount', 'bracketEndpointSelectedCount', ...
        'meanAbsoluteAngleDisplacementDeg', ...
        'maximumAbsoluteAngleDisplacementDeg', 'meanVpmlScoreGain', ...
        'positiveVpmlScoreGainCount', 'truthImproveCount', ...
        'truthTieCount', 'truthWorseCount', ...
        'scoreTruthGainCorrelation', 'meanVpmlFunctionEvaluations', ...
        'meanVpmlSeconds', 'meanRefreshedProfileSeconds'})]; %#ok<AGROW>
end
end

function gate = engineeringGate(summary, protocol)
gate = table();
for snrDb = unique(summary.snrDb).'
    pa = summary(summary.method == "P_A" & summary.snrDb == snrDb, :);
    f = summary(summary.method == "F_raw_vpml" ...
        & summary.snrDb == snrDb, :);
    gate = [gate; gateRow("angle", "per-SNR-angle-MSE", snrDb, ...
        f.angleMseDeg2/pa.angleMseDeg2, ...
        protocol.gate.maximumPerSnrAngleMseRatio)]; %#ok<AGROW>
end
pa = summary(summary.method == "P_A", :);
f = summary(summary.method == "F_raw_vpml", :);
gate = [gate; gateRow("angle", "equal-SNR-aggregate-angle-MSE", ...
    nan, mean(f.angleMseDeg2)/mean(pa.angleMseDeg2), ...
    protocol.gate.maximumEqualSnrAngleMseRatio)];
for snrDb = unique(summary.snrDb).'
    paRow = pa(pa.snrDb == snrDb, :);
    fRow = f(f.snrDb == snrDb, :);
    gate = [gate; gateRow("range", "per-SNR-range-MSE", snrDb, ...
        fRow.rangeMseM2/paRow.rangeMseM2, ...
        protocol.gate.maximumPerSnrRangeMseRatio)]; %#ok<AGROW>
end
c = summary(summary.method == "C_enhanced", :);
gate = [gate; gateRow("runtime", "mean-runtime", nan, ...
    mean(f.meanRuntimeSeconds)/mean(c.meanRuntimeSeconds), ...
    protocol.gate.maximumRuntimeRatioToCEnhanced)];
end

function row = gateRow(category, name, snrDb, observed, limit)
row = table(category, name, snrDb, observed, limit, observed <= limit, ...
    'VariableNames', {'category', 'gate', 'snrDb', 'observedRatio', ...
    'maximumAllowedRatio', 'pass'});
end

function value = finiteCorrelation(first, second)
if std(first) == 0 || std(second) == 0
    value = nan;
else
    matrix = corrcoef(first, second);
    value = matrix(1, 2);
end
end

function value = positionErrorM(theta, rangeM, truthTheta, truthRange)
xError = rangeM.*sind(theta)-truthRange.*sind(truthTheta);
yError = rangeM.*cosd(theta)-truthRange.*cosd(truthTheta);
value = hypot(xError, yError);
end
