function protocol = config()
%CONFIG Freeze the R49 wide-support sequential pilot.

protocol.version = "R49-PFA-wide-support-global-range-pilot60-v1";
protocol.date = "2026-09-18";
protocol.evidenceRole = "new-post-R48-development-not-final-evidence";
protocol.method = struct(base="P_FA", marginalReference="P_FAM5", ...
    candidates=["P_FAW06", "P_FAW10"], ...
    principle="wide-full-aperture-angle-then-global-q-profile", ...
    paFree=true, musicFree=true, evdFree=true, jointObjective=false);
protocol.r48 = r48.config();
protocol.angle = struct(widthDeg=[0.6, 1.0], gridSpacingDeg=0.01, ...
    tolXDeg=1e-7, candidateRetention="best-evaluated-score");
protocol.range = struct(support="full-physical-range", ...
    intervalCount=350, peakCount=8, tolXM=1e-6, ...
    scoreTolerance=1e-10, feasibleCandidate="L06-front-range");
protocol.design = struct(positionCount=20, snrDb=[-10, 0, 20], ...
    angleLimitsDeg=[-60, 60], rangeLimitsM=[15, 50], ...
    positionSeed=64000000, trialSeedRoot=64100000, expectedRows=60);
protocol.selection = struct( ...
    primaryMetric="maximum-per-SNR-range-MSE-ratio-to-P_A", ...
    tieBreaker="equal-SNR-range-MSE-ratio-to-P_A", ...
    maximumPerSnrAngleRatioToPA=1.05, ...
    maximumAggregateAngleRatioToPA=0.85, ...
    maximumPerSnrRangeRatioToPA=1.05, ...
    maximumAggregateRangeRatioToPA=1.00, ...
    requireZeroFailures=true, calibrationRequiresPilotPass=true);
protocol.legacyStress = struct(enabled=true, source="R48-design-only", ...
    positionId=124, snrDb=-10, excludedFromSelection=true);
protocol.execution = struct(r34FinalReadAllowed=false, ...
    r41FinalReadAllowed=false, r46FinalReadAllowed=false, ...
    r48FinalEstimateRowsReadAllowed=false, ...
    parameterTuningAllowed=false, finalTrialsExecuted=0);
end
