function result = fromFront(cfg, observation, snapshots, scan, front, protocol)
%FROMFRONT Run P_FA, P_FAM5 and both R49 wide-support candidates.

arguments
    cfg (1, 1) struct
    observation (:, 1) double {mustBeFinite}
    snapshots (:, :) double
    scan (1, 1) struct
    front (1, 1) struct
    protocol (1, 1) struct = r49.config()
end

timer = tic;
baseProtocol = protocol.r48.r47.r45;
carrierIndex = r30.selectLocalCarriers(cfg.numSubcarriers, ...
    baseProtocol.pfa.carrierCount, front.peakCarrierIndex);
arrayContext = r38PrepareRawArrayVpmlContext(cfg, ...
    snapshots(:, carrierIndex+1), carrierIndex);
responseContext = r33.prepareResponseContext(cfg, scan, observation);

baseAngle = r45.fullArrayAngle( ...
    cfg, arrayContext, front.selected, baseProtocol);
hard = r33.profileAtAngle(cfg, observation, scan, baseAngle.thetaDeg, ...
    front.selected.rangeM, baseProtocol.r34.r33);
uncertainty = r47.angleUncertainty(cfg, arrayContext, ...
    baseAngle.thetaDeg, front.selected.rangeM, protocol.r48.r47);
marginal = r47.marginalProfile(cfg, observation, scan, ...
    baseAngle.thetaDeg, uncertainty.sigmaDeg, front.selected.rangeM, ...
    protocol.r48.r47.quadrature.GH5, protocol.r48.r47);

variants = r49.variantProtocols(protocol);
candidates = struct();
for index = 1:numel(variants)
    candidateTimer = tic;
    angle = r45.fullArrayAngle(cfg, arrayContext, front.selected, ...
        variants(index).angleProtocol);
    profile = r49.globalProfileAtAngle(cfg, angle.thetaDeg, ...
        responseContext, front.selected.rangeM, protocol);
    candidates.(variants(index).name) = struct( ...
        version="R49-wide-angle-global-range-candidate-v1", ...
        thetaDeg=angle.thetaDeg, rangeM=profile.value, ...
        widthDeg=variants(index).widthDeg, angle=angle, ...
        profile=compactProfile(profile), ...
        angleBoundaryHit=isAngleBoundary(angle), ...
        qOnlyResponseEvaluations=profile.qOnlyResponseEvaluations, ...
        backendSeconds=toc(candidateTimer));
end

result = struct(version=protocol.version, ...
    P_FA=struct(thetaDeg=baseAngle.thetaDeg, rangeM=hard.value), ...
    P_FAM5=struct(thetaDeg=baseAngle.thetaDeg, rangeM=marginal.value), ...
    candidates=candidates, frontThetaDeg=front.selected.thetaDeg, ...
    frontRangeM=front.selected.rangeM, carrierIndex=carrierIndex, ...
    baseAngle=baseAngle, uncertainty=uncertainty, ...
    hardProfile=compactProfile(hard), ...
    marginalProfile=compactProfile(marginal), ...
    totalBackendSeconds=toc(timer), musicEvaluationCount=0, evdCount=0);
end

function output = compactProfile(input)
output = struct(value=input.value, score=input.score, ...
    interval=input.interval, endpointHit=input.endpointHit, ...
    nearBoundary=input.nearBoundary, evaluationCount=input.evaluationCount, ...
    retentionMargin=input.retentionMargin);
end

function value = isAngleBoundary(angle)
tolerance = max(1e-10, 16*eps(max(1, max(abs(angle.boundsDeg)))));
value = abs(angle.thetaDeg-angle.boundsDeg(1)) <= tolerance ...
    || abs(angle.thetaDeg-angle.boundsDeg(2)) <= tolerance;
end
