function output = summarize(design, results, protocol)
%SUMMARIZE Compare R49 candidates and apply the frozen pilot gate.

arguments
    design table
    results (:, 1) cell
    protocol (1, 1) struct = r49.config()
end

if numel(results) ~= height(design) || any(cellfun(@isempty, results)) ...
        || any(cellfun(@(item) ~item.success, results))
    error("r49:IncompletePilot", ...
        "R49 summary requires every new development row.");
end

methods = ["P_FA", "P_FAM5", protocol.method.candidates, ...
    "P_A", "C_enhanced"];
perUser = design(:, ["positionId", "seed", "trialIndex", ...
    "snrDb", "truthThetaDeg", "truthRangeM"]);
for method = methods
    theta = cellfun(@(item) item.(method).thetaDeg, results);
    rangeM = cellfun(@(item) item.(method).rangeM, results);
    perUser.("theta_"+method) = theta;
    perUser.("range_"+method) = rangeM;
    perUser.("angleError_"+method) = theta-perUser.truthThetaDeg;
    perUser.("rangeError_"+method) = rangeM-perUser.truthRangeM;
end
for candidate = protocol.method.candidates
    perUser.("angleBoundary_"+candidate) = cellfun( ...
        @(item) item.backend.candidates.(candidate).angleBoundaryHit, results);
    perUser.("rangeEndpoint_"+candidate) = cellfun( ...
        @(item) item.backend.candidates.(candidate).profile.endpointHit, results);
    perUser.("responses_"+candidate) = cellfun( ...
        @(item) item.backend.candidates.(candidate).qOnlyResponseEvaluations, ...
        results);
    perUser.("seconds_"+candidate) = cellfun( ...
        @(item) item.backend.candidates.(candidate).backendSeconds, results);
end

methodSummary = buildMethodSummary(perUser, methods, protocol.design.snrDb);
comparisons = table();
for candidate = protocol.method.candidates
    for reference = ["P_A", "P_FA", "P_FAM5"]
        comparisons = [comparisons; compareMethods( ...
            perUser, candidate, reference, protocol.design.snrDb)]; %#ok<AGROW>
    end
end
selection = selectCandidate(perUser, comparisons, protocol);
diagnostics = buildDiagnostics(perUser, protocol);
output = struct(version="R49-wide-support-pilot-summary-v1", ...
    perUser=perUser, methodSummary=methodSummary, ...
    comparisons=comparisons, selection=selection, ...
    diagnostics=diagnostics, pilotPass=selection.pass);
end

function output = buildMethodSummary(perUser, methods, snrValues)
output = table();
for method = methods
    for snr = snrValues
        selected = perUser.snrDb == snr;
        ae = perUser.("angleError_"+method)(selected);
        re = perUser.("rangeError_"+method)(selected);
        output = [output; table(method, snr, nnz(selected), ...
            mean(ae.^2), sqrt(mean(ae.^2)), mean(re.^2), ...
            sqrt(mean(re.^2)), median(abs(re)), quantile(abs(re), .95), ...
            max(abs(re)), 'VariableNames', {'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', 'rangeMseM2', ...
            'rangeRmseM', 'rangeMedianAbsM', 'rangeP95AbsM', ...
            'rangeMaximumAbsM'})]; %#ok<AGROW>
    end
end
end

function output = compareMethods(perUser, candidate, reference, snrValues)
output = table();
candidateAngle = zeros(numel(snrValues), 1);
referenceAngle = zeros(numel(snrValues), 1);
candidateRange = zeros(numel(snrValues), 1);
referenceRange = zeros(numel(snrValues), 1);
for index = 1:numel(snrValues)
    snr = snrValues(index);
    selected = perUser.snrDb == snr;
    ca = perUser.("angleError_"+candidate)(selected).^2;
    ra = perUser.("angleError_"+reference)(selected).^2;
    cr = perUser.("rangeError_"+candidate)(selected).^2;
    rr = perUser.("rangeError_"+reference)(selected).^2;
    candidateAngle(index) = mean(ca);
    referenceAngle(index) = mean(ra);
    candidateRange(index) = mean(cr);
    referenceRange(index) = mean(rr);
    output = [output; comparisonRow(candidate, reference, ...
        "per-SNR", snr, ca, ra, cr, rr)]; %#ok<AGROW>
end
    cr = perUser.("rangeError_"+candidate).^2;
    rr = perUser.("rangeError_"+reference).^2;
output = [output; table(candidate, reference, "equal-SNR", nan, ...
    height(perUser), mean(candidateAngle)/mean(referenceAngle), ...
    mean(candidateRange)/mean(referenceRange), ...
    100*(1-sqrt(mean(candidateAngle)/mean(referenceAngle))), ...
    100*(1-sqrt(mean(candidateRange)/mean(referenceRange))), ...
    nnz(cr < rr), nnz(cr == rr), nnz(cr > rr), ...
    'VariableNames', output.Properties.VariableNames)];
end

function row = comparisonRow(candidate, reference, scope, snrDb, ...
    candidateAngle, referenceAngle, candidateRange, referenceRange)
angleRatio = mean(candidateAngle)/mean(referenceAngle);
rangeRatio = mean(candidateRange)/mean(referenceRange);
row = table(candidate, reference, scope, snrDb, numel(candidateRange), ...
    angleRatio, rangeRatio, 100*(1-sqrt(angleRatio)), ...
    100*(1-sqrt(rangeRatio)), nnz(candidateRange < referenceRange), ...
    nnz(candidateRange == referenceRange), ...
    nnz(candidateRange > referenceRange), ...
    'VariableNames', {'candidate', 'reference', 'scope', 'snrDb', ...
    'n', 'angleMseRatio', 'rangeMseRatio', ...
    'angleRmseImprovementPct', 'rangeRmseImprovementPct', ...
    'rangeWinCount', 'rangeTieCount', 'rangeLossCount'});
end

function selection = selectCandidate(~, comparisons, protocol)
candidates = protocol.method.candidates(:);
width = protocol.angle.widthDeg(:);
count = numel(candidates);
maxAngle = zeros(count, 1);
aggregateAngle = zeros(count, 1);
maxRange = zeros(count, 1);
aggregateRange = zeros(count, 1);
rangeToPFA = zeros(count, 1);
rangeToPFAM5 = zeros(count, 1);
for index = 1:count
    pa = comparisons(comparisons.candidate == candidates(index) ...
        & comparisons.reference == "P_A", :);
    pfa = comparisons(comparisons.candidate == candidates(index) ...
        & comparisons.reference == "P_FA" ...
        & comparisons.scope == "equal-SNR", :);
    pfam5 = comparisons(comparisons.candidate == candidates(index) ...
        & comparisons.reference == "P_FAM5" ...
        & comparisons.scope == "equal-SNR", :);
    maxAngle(index) = max(pa.angleMseRatio(pa.scope == "per-SNR"));
    aggregateAngle(index) = pa.angleMseRatio(pa.scope == "equal-SNR");
    maxRange(index) = max(pa.rangeMseRatio(pa.scope == "per-SNR"));
    aggregateRange(index) = pa.rangeMseRatio(pa.scope == "equal-SNR");
    rangeToPFA(index) = pfa.rangeMseRatio;
    rangeToPFAM5(index) = pfam5.rangeMseRatio;
end
[~, order] = sortrows([maxRange, aggregateRange, aggregateAngle, width], ...
    [1, 2, 3, 4]);
selectedIndex = order(1);
selected = candidates(selectedIndex);
passEach = maxAngle <= protocol.selection.maximumPerSnrAngleRatioToPA ...
    & aggregateAngle <= protocol.selection.maximumAggregateAngleRatioToPA ...
    & maxRange <= protocol.selection.maximumPerSnrRangeRatioToPA ...
    & aggregateRange <= protocol.selection.maximumAggregateRangeRatioToPA;
summary = table(candidates, width, maxAngle, aggregateAngle, ...
    maxRange, aggregateRange, rangeToPFA, rangeToPFAM5, ...
    candidates == selected, passEach & candidates == selected, ...
    'VariableNames', {'candidate', 'angleWidthDeg', ...
    'maximumPerSnrAngleRatioToPA', 'aggregateAngleRatioToPA', ...
    'maximumPerSnrRangeRatioToPA', 'aggregateRangeRatioToPA', ...
    'aggregateRangeRatioToPFA', 'aggregateRangeRatioToPFAM5', ...
    'selected', 'pass'});
selection = struct(summary=summary, selected=selected, ...
    pass=passEach(selectedIndex));
end

function output = buildDiagnostics(perUser, protocol)
output = table();
for candidate = protocol.method.candidates
    output = [output; table(candidate, height(perUser), ...
        sum(perUser.("angleBoundary_"+candidate)), ...
        sum(perUser.("rangeEndpoint_"+candidate)), ...
        mean(perUser.("responses_"+candidate)), ...
        mean(perUser.("seconds_"+candidate)), ...
        max(abs(perUser.("rangeError_"+candidate))), ...
        'VariableNames', {'candidate', 'n', 'angleBoundaryHits', ...
        'rangeEndpointHits', 'meanQResponses', ...
        'meanBackendSeconds', 'maximumAbsRangeErrorM'})]; %#ok<AGROW>
end
end
