function output = r36SummarizeSchemeE(design, results, commonProtocol)
%R36SUMMARIZESCHEMEE Apply frozen metrics and engineering gates.

arguments
    design table
    results cell
    commonProtocol (1, 1) struct = r36CommonProtocol()
end

if numel(results) ~= height(design) || any(cellfun(@isempty, results))
    error("r36:IncompleteSchemeEResults", ...
        "Scheme E requires all 60 frozen development rows.");
end
if any(cellfun(@(x) ~x.success, results))
    error("r36:SchemeETrialFailure", ...
        "At least one Scheme E row failed.");
end

perUser = buildPerUser(design, results);
methodRows = buildMethodRows(perUser);
summary = summarizeMethods(methodRows, perUser);
comparisons = [pairedRows(methodRows, "E_one_step", "P_A"); ...
    pairedRows(methodRows, "E_one_step", "C_enhanced")];
diagnostics = summarizeDiagnostics(perUser);
gate = engineeringGate(summary, commonProtocol);
output = struct(version="R36-schemeE-development-summary-v1", ...
    dataRole=commonProtocol.evidenceRole, perUser=perUser, ...
    methodRows=methodRows, summary=summary, comparisons=comparisons, ...
    diagnostics=diagnostics, gate=gate, gatePassed=all(gate.pass));
end

function perUser = buildPerUser(design, results)
paTheta = cellfun(@(x) x.P_A.thetaDeg, results);
paRange = cellfun(@(x) x.P_A.rangeM, results);
cTheta = cellfun(@(x) x.C_enhanced.thetaDeg, results);
cRange = cellfun(@(x) x.C_enhanced.rangeM, results);
eTheta = cellfun(@(x) x.E_one_step.thetaDeg, results);
eRange = cellfun(@(x) x.E_one_step.rangeM, results);
truthGain = (paTheta-design.truthThetaDeg).^2 ...
    -(eTheta-design.truthThetaDeg).^2;
brackets = cell2mat(cellfun(@(x) x.refinement.bracketDeg, ...
    results, UniformOutput=false));

perUser = table(design.seed, design.trialIndex, design.snrDb, ...
    design.truthThetaDeg, design.truthRangeM, ...
    cellfun(@(x) x.frontThetaDeg, results), ...
    cellfun(@(x) x.frontRangeM, results), ...
    paTheta, paRange, eTheta, eRange, cTheta, cRange, ...
    brackets(:, 1), brackets(:, 2), eTheta-paTheta, truthGain, ...
    cellfun(@(x) x.refinement.rawDisplacementDeg, results), ...
    cellfun(@(x) x.refinement.diagnosticRangeDisplacementM, results), ...
    cellfun(@(x) x.refinement.validUpdate, results), ...
    cellfun(@(x) x.refinement.clippedToBracket, results), ...
    string(cellfun(@(x) x.refinement.status, ...
    results, UniformOutput=false)), ...
    cellfun(@(x) x.refinement.linearization.cost, results), ...
    cellfun(@(x) x.refinement.predictedCostReduction, results), ...
    cellfun(@(x) x.refinement.actualCostReduction, results), ...
    cellfun(@(x) x.refinement.effectiveGradient, results), ...
    cellfun(@(x) x.refinement.effectiveInformation, results), ...
    cellfun(@(x) x.refinement.couplingCoefficient, results), ...
    string(cellfun(@(x) x.runtimeOrder, results, UniformOutput=false)), ...
    cellfun(@(x) x.P_A.runtimeSeconds, results), ...
    cellfun(@(x) x.E_one_step.runtimeSeconds, results), ...
    cellfun(@(x) x.C_enhanced.runtimeSeconds, results), ...
    cellfun(@(x) x.E_one_step.refinementSeconds, results), ...
    cellfun(@(x) x.E_one_step.profileSeconds, results), ...
    cellfun(@(x) x.P_A.responseEvaluationCount, results), ...
    cellfun(@(x) x.E_one_step.responseEvaluationCount, results), ...
    cellfun(@(x) x.C_enhanced.responseEvaluationCount, results), ...
    cellfun(@(x) x.P_A.musicEvaluationCount, results), ...
    cellfun(@(x) x.E_one_step.musicEvaluationCount, results), ...
    cellfun(@(x) x.C_enhanced.musicEvaluationCount, results), ...
    cellfun(@(x) x.P_A.evdCount, results), ...
    cellfun(@(x) x.E_one_step.evdCount, results), ...
    cellfun(@(x) x.C_enhanced.evdCount, results), ...
    'VariableNames', {'seed', 'trialIndex', 'snrDb', ...
    'truthThetaDeg', 'truthRangeM', 'frontThetaDeg', 'frontRangeM', ...
    'theta_P_A', 'range_P_A', 'theta_E', 'range_E', ...
    'theta_C_enhanced', 'range_C_enhanced', ...
    'bracketLowerDeg', 'bracketUpperDeg', 'angleDisplacementDeg', ...
    'truthSquaredErrorGainDeg2', 'rawDisplacementDeg', ...
    'diagnosticRangeDisplacementM', 'validUpdate', ...
    'clippedToBracket', 'status', 'rawMusicCostBefore', ...
    'predictedCostReduction', 'actualCostReduction', ...
    'effectiveGradient', 'effectiveInformation', ...
    'angleRangeCouplingCoefficient', 'runtimeOrder', ...
    'runtime_P_A', 'runtime_E', 'runtime_C_enhanced', ...
    'refinementSeconds', 'profileSeconds', ...
    'responseCount_P_A', 'responseCount_E', ...
    'responseCount_C_enhanced', 'musicCount_P_A', ...
    'musicCount_E', 'musicCount_C_enhanced', ...
    'evdCount_P_A', 'evdCount_E', 'evdCount_C_enhanced'});
end

function rows = buildMethodRows(perUser)
methods = ["P_A", "E_one_step", "C_enhanced"];
thetaFields = ["theta_P_A", "theta_E", "theta_C_enhanced"];
rangeFields = ["range_P_A", "range_E", "range_C_enhanced"];
runtimeFields = ["runtime_P_A", "runtime_E", "runtime_C_enhanced"];
rows = table();
for index = 1:numel(methods)
    theta = perUser.(thetaFields(index));
    range = perUser.(rangeFields(index));
    angleError = theta-perUser.truthThetaDeg;
    rangeError = range-perUser.truthRangeM;
    xError = range.*sind(theta) ...
        -perUser.truthRangeM.*sind(perUser.truthThetaDeg);
    yError = range.*cosd(theta) ...
        -perUser.truthRangeM.*cosd(perUser.truthThetaDeg);
    current = table(perUser.seed, perUser.trialIndex, perUser.snrDb, ...
        repmat(methods(index), height(perUser), 1), theta, range, ...
        angleError, rangeError, hypot(xError, yError), ...
        perUser.(runtimeFields(index)), ...
        'VariableNames', {'seed', 'trialIndex', 'snrDb', 'method', ...
        'thetaDeg', 'rangeM', 'angleErrorDeg', 'rangeErrorM', ...
        'positionErrorM', 'runtimeSeconds'});
    rows = [rows; current]; %#ok<AGROW>
end
end

function summary = summarizeMethods(rows, perUser)
summary = table();
for method = unique(rows.method, "stable").'
    for snrDb = unique(rows.snrDb).'
        current = rows(rows.method == method & rows.snrDb == snrDb, :);
        angleSquared = current.angleErrorDeg.^2;
        rangeSquared = current.rangeErrorM.^2;
        positionSquared = current.positionErrorM.^2;
        [changed, responses, music, evd] = ...
            methodDiagnostics(method, snrDb, perUser);
        entry = table(method, snrDb, height(current), ...
            mean(angleSquared), sqrt(mean(angleSquared)), ...
            median(abs(current.angleErrorDeg)), ...
            quantile(abs(current.angleErrorDeg), 0.90), ...
            quantile(abs(current.angleErrorDeg), 0.95), ...
            mean(rangeSquared), sqrt(mean(rangeSquared)), ...
            sqrt(mean(positionSquared)), changed, ...
            mean(current.runtimeSeconds), mean(responses), ...
            mean(music), mean(evd), ...
            'VariableNames', {'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', ...
            'angleMedianAbsoluteErrorDeg', ...
            'angleP90AbsoluteErrorDeg', 'angleP95AbsoluteErrorDeg', ...
            'rangeMseM2', 'rangeRmseM', 'positionRmseM', ...
            'fractionAngleChangedFromPA', 'meanRuntimeSeconds', ...
            'meanResponseEvaluationCount', ...
            'meanMusicEvaluationCount', 'meanEvdCount'});
        summary = [summary; entry]; %#ok<AGROW>
    end
end
summary.angleMseRatioToPA = nan(height(summary), 1);
summary.rangeMseRatioToPA = nan(height(summary), 1);
for index = 1:height(summary)
    pa = summary(summary.method == "P_A" ...
        & summary.snrDb == summary.snrDb(index), :);
    summary.angleMseRatioToPA(index) = ...
        summary.angleMseDeg2(index)/pa.angleMseDeg2;
    summary.rangeMseRatioToPA(index) = ...
        summary.rangeMseM2(index)/pa.rangeMseM2;
end
end

function [changed, responses, music, evd] = ...
    methodDiagnostics(method, snrDb, perUser)
selected = perUser.snrDb == snrDb;
if method == "P_A"
    theta = perUser.theta_P_A(selected);
    responses = perUser.responseCount_P_A(selected);
    music = perUser.musicCount_P_A(selected);
    evd = perUser.evdCount_P_A(selected);
elseif method == "E_one_step"
    theta = perUser.theta_E(selected);
    responses = perUser.responseCount_E(selected);
    music = perUser.musicCount_E(selected);
    evd = perUser.evdCount_E(selected);
else
    theta = perUser.theta_C_enhanced(selected);
    responses = perUser.responseCount_C_enhanced(selected);
    music = perUser.musicCount_C_enhanced(selected);
    evd = perUser.evdCount_C_enhanced(selected);
end
changed = mean(theta ~= perUser.theta_P_A(selected));
end

function output = pairedRows(rows, candidateName, referenceName)
output = table();
snrValues = unique(rows.snrDb).';
candidateMse = zeros(numel(snrValues), 1);
referenceMse = zeros(numel(snrValues), 1);
allDifference = zeros(0, 1);
for index = 1:numel(snrValues)
    [entry, difference, candidateMse(index), referenceMse(index)] = ...
        pairedEntry(rows, candidateName, referenceName, snrValues(index));
    output = [output; entry]; %#ok<AGROW>
    allDifference = [allDifference; difference]; %#ok<AGROW>
end
candidateAggregate = mean(candidateMse);
referenceAggregate = mean(referenceMse);
output = [output; comparisonRow(candidateName, referenceName, ...
    "equal-SNR", nan, numel(allDifference), candidateAggregate, ...
    referenceAggregate, allDifference)];
end

function [entry, difference, candidateMse, referenceMse] = ...
    pairedEntry(rows, candidateName, referenceName, snrDb)
candidate = sortrows(rows(rows.method == candidateName ...
    & rows.snrDb == snrDb, :), "seed");
reference = sortrows(rows(rows.method == referenceName ...
    & rows.snrDb == snrDb, :), "seed");
if ~isequal(candidate.seed, reference.seed)
    error("r36:UnpairedSchemeERows", ...
        "Scheme E comparisons require identical old users.");
end
candidateSquared = candidate.angleErrorDeg.^2;
referenceSquared = reference.angleErrorDeg.^2;
candidateMse = mean(candidateSquared);
referenceMse = mean(referenceSquared);
difference = candidateSquared-referenceSquared;
entry = comparisonRow(candidateName, referenceName, "per-SNR", ...
    snrDb, height(candidate), candidateMse, referenceMse, difference);
end

function row = comparisonRow(candidate, reference, scope, snrDb, n, ...
    candidateMse, referenceMse, difference)
ratio = candidateMse/referenceMse;
row = table(candidate, reference, scope, snrDb, n, candidateMse, ...
    referenceMse, ratio, 100*(1-sqrt(ratio)), mean(difference), ...
    nnz(difference < 0), nnz(difference == 0), ...
    nnz(difference > 0), mean(difference < 0), ...
    mean(difference == 0), mean(difference > 0), ...
    'VariableNames', {'candidate', 'reference', 'scope', 'snrDb', ...
    'n', 'candidateAngleMseDeg2', 'referenceAngleMseDeg2', ...
    'angleMseRatio', 'angleRmseImprovementPercent', ...
    'meanCandidateMinusReferenceSquaredError', 'winCount', ...
    'tieCount', 'lossCount', 'winRate', 'tieRate', 'lossRate'});
end

function diagnostics = summarizeDiagnostics(perUser)
diagnostics = table();
for index = 1:4
    snrValues = unique(perUser.snrDb).';
    if index <= numel(snrValues)
        snrDb = snrValues(index);
        selected = perUser.snrDb == snrDb;
        scope = "per-SNR";
    else
        snrDb = nan;
        selected = true(height(perUser), 1);
        scope = "all-SNR";
    end
    gain = perUser.truthSquaredErrorGainDeg2(selected);
    actualReduction = perUser.actualCostReduction(selected);
    entry = table(scope, snrDb, nnz(selected), ...
        nnz(perUser.validUpdate(selected)), ...
        nnz(perUser.clippedToBracket(selected)), ...
        mean(abs(perUser.angleDisplacementDeg(selected))), ...
        max(abs(perUser.angleDisplacementDeg(selected))), ...
        mean(abs(perUser.diagnosticRangeDisplacementM(selected))), ...
        max(abs(perUser.diagnosticRangeDisplacementM(selected))), ...
        mean(perUser.angleRangeCouplingCoefficient(selected)), ...
        max(abs(perUser.angleRangeCouplingCoefficient(selected))), ...
        mean(perUser.predictedCostReduction(selected)), ...
        mean(actualReduction), nnz(actualReduction > 0), ...
        nnz(gain > 0), nnz(gain == 0), nnz(gain < 0), ...
        finiteCorrelation(actualReduction, gain), ...
        'VariableNames', {'scope', 'snrDb', 'n', ...
        'validUpdateCount', 'bracketClippedCount', ...
        'meanAbsoluteAngleDisplacementDeg', ...
        'maximumAbsoluteAngleDisplacementDeg', ...
        'meanAbsoluteDiagnosticRangeDisplacementM', ...
        'maximumAbsoluteDiagnosticRangeDisplacementM', ...
        'meanAngleRangeCouplingCoefficient', ...
        'maximumAbsoluteAngleRangeCouplingCoefficient', ...
        'meanPredictedCostReduction', 'meanActualCostReduction', ...
        'actualCostReductionPositiveCount', 'truthImproveCount', ...
        'truthTieCount', 'truthWorseCount', ...
        'costTruthGainCorrelation'});
    diagnostics = [diagnostics; entry]; %#ok<AGROW>
end
end

function value = finiteCorrelation(first, second)
if std(first) == 0 || std(second) == 0
    value = nan;
else
    matrix = corrcoef(first, second);
    value = matrix(1, 2);
end
end

function gate = engineeringGate(summary, protocol)
gate = table();
for snrDb = unique(summary.snrDb).'
    pa = summary(summary.method == "P_A" & summary.snrDb == snrDb, :);
    e = summary(summary.method == "E_one_step" ...
        & summary.snrDb == snrDb, :);
    gate = [gate; gateRow("angle", "per-SNR-angle-MSE", snrDb, ...
        e.angleMseDeg2/pa.angleMseDeg2, ...
        protocol.engineeringGate.maximumPerSnrAngleMseRatio)]; %#ok<AGROW>
end
paRows = summary(summary.method == "P_A", :);
eRows = summary(summary.method == "E_one_step", :);
gate = [gate; gateRow("angle", "equal-SNR-aggregate-angle-MSE", nan, ...
    mean(eRows.angleMseDeg2)/mean(paRows.angleMseDeg2), ...
    protocol.engineeringGate.maximumEqualSnrAngleMseRatio)];
for snrDb = unique(summary.snrDb).'
    pa = summary(summary.method == "P_A" & summary.snrDb == snrDb, :);
    e = summary(summary.method == "E_one_step" ...
        & summary.snrDb == snrDb, :);
    gate = [gate; gateRow("range", "per-SNR-range-MSE", snrDb, ...
        e.rangeMseM2/pa.rangeMseM2, ...
        protocol.engineeringGate.maximumPerSnrRangeMseRatio)]; %#ok<AGROW>
end
cRows = summary(summary.method == "C_enhanced", :);
gate = [gate; gateRow("runtime", "mean-runtime", nan, ...
    mean(eRows.meanRuntimeSeconds)/mean(cRows.meanRuntimeSeconds), ...
    protocol.engineeringGate.maximumRuntimeRatioToCEnhanced)];
end

function row = gateRow(category, name, snrDb, observed, limit)
row = table(category, name, snrDb, observed, limit, observed <= limit, ...
    'VariableNames', {'category', 'gate', 'snrDb', 'observedRatio', ...
    'maximumAllowedRatio', 'pass'});
end
