function protocol = config()
%CONFIG Freeze the independent R52 basin-consistency development study.

protocol.version = "R52-PFARC2-basin-consistency-development-v2";
protocol.date = "2026-09-18";
protocol.evidenceRole = "independent-post-R51-development-not-calibration";
protocol.method = struct(primary="P_FARC2", base="P_FA", ...
    frozenReference="R51_PFARC", ...
    recoveryControl="R51_trigger_simple", baseline="P_A", ...
    paFree=true, musicFree=true, evdFree=true, ...
    normalFallback="exact-frozen-P_FA");
protocol.r51 = r51.config();
protocol.base = protocol.r51.base;

protocol.basin = struct(angleToleranceDeg=0.2, rangeToleranceM=2.0, ...
    frontDefinition="front-selected-full-spectrum-refined-candidate", ...
    tieRule="first-smallest-candidate-index", ...
    C3b="same-odd-even-and-both-outside-selected-front-basin");
protocol.recovery = struct(angleHalfWidthDeg=0.6, ...
    angleGridSpacingDeg=0.01, rangeSupport="full-physical", ...
    globalIntervalCount=350, peakCount=8, tolXM=1e-6, ...
    scoreTolerance=1e-10, invalidPolicy="fallback-P_FA");

protocol.normalDesign = struct(positionCount=30, snrDb=[-10, 0, 20], ...
    angleLimitsDeg=[-60, 60], rangeLimitsM=[15, 50], ...
    positionSeed=67000000, trialSeedRoot=67100000, expectedRows=90);
protocol.stressPool = struct(positionCount=600, snrDb=-10, ...
    angleLimitsDeg=[-55, 55], rangeLimitsM=[18, 47], ...
    positionSeed=67200000, trialSeedRoot=67300000, ...
    targetPerClass=3, classes=["angle", "range", "joint"], ...
    selection="first-position-id-per-exclusive-support-miss-class", ...
    fixedBudgetNoExtension=true);
protocol.support = struct(angleHalfWidthDeg=0.2, rangeHalfWidthM=2.0, ...
    stableInterior="support-miss-and-C1-C2-C3a-C4-all-false", ...
    falseTrigger="trigger-and-no-angle-or-range-support-miss");

protocol.bootstrap = struct(count=10000, seed=67400000, ...
    confidence=0.95, cluster="positionId", sharedAcrossSnr=true);
protocol.gate = struct( ...
    requireStressConstruction=true, ...
    maxAggregateRangeMseRatioToPA=1.00, ...
    maxPerSnrRangeMseRatioToPA=1.05, ...
    maxAggregateAngleMseRatioToPFA=1.01, ...
    maxNormalFalseTriggerRate=0.05, ...
    maxConditionalNormalHarmfulRecoveryRate=0.10, ...
    minimumStressSensitivity=0.90, ...
    minimumRangeStressSensitivity=0.90, ...
    maxStressHarmfulRecoveryRate=0.10, ...
    minimumAdditionalStableInteriorDetections=1, ...
    minimumRangeSensitivityGainOverR51Trigger=0.20, ...
    maxSimpleRecoveryRangeMseRatioToFrozenR51=1.01, ...
    runtimeReference="C_enhanced-matched-standalone");
protocol.timing = struct(positionIds=1:3, snrDb=0, repetitions=2, ...
    warmups=1, methods=["P_FARC2", "C_enhanced"]);
protocol.execution = struct(recommendedWorkers=8, screenBatchSize=40, ...
    finalRowsAccessible=false, calibrationAllowed=false, ...
    parameterTuningAllowed=false, modifyFrozenR51=false, ...
    historicalR51PositionId=11, historicalR51SnrDb=-10, ...
    historicalR48PositionId=124, historicalR48SnrDb=-10, ...
    stopAfterDevelopment=true);
end
