function output = simpleRecovery( ...
    cfg, observation, snapshots, scan, front, base, protocol)
%SIMPLERECOVERY Run frozen P_FAW06 angle and global exact-q range search.

arguments
    cfg (1, 1) struct
    observation (:, 1) double {mustBeFinite}
    snapshots (:, :) double
    scan (1, 1) struct
    front (1, 1) struct
    base (1, 1) struct
    protocol (1, 1) struct = r52.config()
end

timer = tic;
try
    carrierIndex = r30.selectLocalCarriers(cfg.numSubcarriers, ...
        protocol.base.pfa.carrierCount, front.peakCarrierIndex);
    arrayContext = r38PrepareRawArrayVpmlContext( ...
        cfg, snapshots(:, carrierIndex+1), carrierIndex);
    angleProtocol = protocol.base;
    angleProtocol.pfa.angleHalfWidthDeg = ...
        protocol.recovery.angleHalfWidthDeg;
    angleProtocol.pfa.coarseAngleGridSize = round( ...
        2*protocol.recovery.angleHalfWidthDeg ...
        /protocol.recovery.angleGridSpacingDeg)+1;
    angle = r45.fullArrayAngle( ...
        cfg, arrayContext, front.selected, angleProtocol);
    responseContext = r33.prepareResponseContext(cfg, scan, observation);
    rangeProtocol = r49.config();
    profile = r49.globalProfileAtAngle(cfg, angle.thetaDeg, ...
        responseContext, front.selected.rangeM, rangeProtocol);
    valid = isfinite(angle.thetaDeg) && isfinite(profile.value) ...
        && isfinite(profile.score) ...
        && angle.thetaDeg >= cfg.thetaLimitsDeg(1) ...
        && angle.thetaDeg <= cfg.thetaLimitsDeg(2) ...
        && profile.value >= cfg.rangeLimitsM(1) ...
        && profile.value <= cfg.rangeLimitsM(2);
    if valid
        thetaDeg = angle.thetaDeg;
        rangeM = profile.value;
        status = "accepted-wide-global";
    else
        thetaDeg = base.thetaDeg;
        rangeM = base.rangeM;
        status = "fallback-invalid-numeric-result";
    end
    output = struct(version="R52-simple-conditional-wide-global-v1", ...
        valid=valid, accepted=valid, status=status, ...
        thetaDeg=thetaDeg, rangeM=rangeM, angle=angle, ...
        profile=compactProfile(profile), runtimeSeconds=toc(timer), ...
        errorIdentifier="", errorMessage="");
catch exception
    output = struct(version="R52-simple-conditional-wide-global-v1", ...
        valid=false, accepted=false, status="fallback-exception", ...
        thetaDeg=base.thetaDeg, rangeM=base.rangeM, ...
        angle=struct(), profile=struct(), runtimeSeconds=toc(timer), ...
        errorIdentifier=string(exception.identifier), ...
        errorMessage=string(exception.message));
end
end

function output = compactProfile(input)
output = struct(value=input.value, score=input.score, ...
    interval=input.interval, endpointHit=input.endpointHit, ...
    nearBoundary=input.nearBoundary, evaluationCount=input.evaluationCount, ...
    retentionMargin=input.retentionMargin);
end
