function output = summarize(normalDesign, normalResults, ...
    stressSelection, stressResults, protocol)
%SUMMARIZE Build R52 normal, natural-stress, and mechanism endpoints.

arguments
    normalDesign table
    normalResults (:, 1) cell
    stressSelection (1, 1) struct
    stressResults (:, 1) cell
    protocol (1, 1) struct = r52.config()
end

assertComplete(normalDesign, normalResults, "normal");
assertComplete(stressSelection.design, stressResults, "stress");
methods = ["P_A", "P_FA", "R51_PFARC", ...
    "R51_trigger_simple", "P_FARC2", "C_enhanced"];
normal = appendDiagnostics( ...
    perUserTable(normalDesign, normalResults, methods), normalResults);
stress = appendDiagnostics( ...
    perUserTable(stressSelection.design, stressResults, methods), ...
    stressResults);
methodSummary = summarizeMethods(normal, methods, protocol.normalDesign.snrDb);
comparisons = compareAll(normal, ...
    ["R51_PFARC", "R51_trigger_simple", "P_FARC2"], ...
    ["P_A", "P_FA", "R51_PFARC", "R51_trigger_simple"], ...
    protocol.normalDesign.snrDb);
bootstrap = [ ...
    r51.bootstrapRatio(normal, "P_FARC2", "P_A", "range", protocol, 1); ...
    r51.bootstrapRatio(normal, "P_FARC2", "P_FA", "angle", protocol, 2); ...
    r51.bootstrapRatio(normal, "P_FARC2", "P_FA", "range", protocol, 3); ...
    r51.bootstrapRatio(normal, "R51_trigger_simple", ...
        "R51_PFARC", "range", protocol, 4)];
normalDiagnostics = summarizeNormalDiagnostics(normal);
stressSummary = summarizeStress(stress, protocol);
mechanism = summarizeMechanism(stress, protocol);
gate = buildGate(comparisons, normalDiagnostics, stressSummary, ...
    mechanism, stressSelection, protocol);
output = struct(version="R52-PFARC2-development-summary-v1", ...
    normalPerUser=normal, stressPerUser=stress, ...
    methodSummary=methodSummary, comparisons=comparisons, ...
    bootstrap=bootstrap, normalDiagnostics=normalDiagnostics, ...
    stressSummary=stressSummary, mechanism=mechanism, gate=gate, ...
    developmentPass=all(gate.pass));
end

function assertComplete(design, results, label)
if numel(results) ~= height(design) || any(cellfun(@isempty, results)) ...
        || any(cellfun(@(item) ~item.success, results))
    error("r52:IncompleteDevelopment", ...
        "R52 requires every %s development row.", label);
end
end

function output = perUserTable(design, results, methods)
keep = intersect(["positionId", "seed", "trialIndex", "snrDb", ...
    "stressType", "truthThetaDeg", "truthRangeM"], ...
    string(design.Properties.VariableNames), "stable");
output = design(:, keep);
for method = methods
    theta = cellfun(@(item) item.(method).thetaDeg, results);
    rangeM = cellfun(@(item) item.(method).rangeM, results);
    output.("theta_"+method) = theta;
    output.("range_"+method) = rangeM;
    output.("angleError_"+method) = theta-output.truthThetaDeg;
    output.("rangeError_"+method) = rangeM-output.truthRangeM;
end
end

function output = appendDiagnostics(output, results)
output.angleSupportMiss = cellfun(@(item) item.angleSupportMiss, results);
output.rangeSupportMiss = cellfun(@(item) item.rangeSupportMiss, results);
output.supportClass = strings(height(output), 1);
if ~isempty(results)
    output.supportClass = cellfun( ...
        @(item) string(item.supportClass), results);
end
output.stableInteriorSupportMiss = cellfun( ...
    @(item) item.stableInteriorSupportMiss, results);
output.C1 = cellfun(@(item) item.backend.certificate.C1, results);
output.C2 = cellfun(@(item) item.backend.certificate.C2, results);
output.C3a = cellfun(@(item) item.backend.certificate.C3a, results);
output.C3b = cellfun(@(item) item.backend.certificate.C3b, results);
output.C4 = cellfun(@(item) item.backend.certificate.C4, results);
output.oldTrigger = cellfun( ...
    @(item) item.backend.frozenR51.certificate.trigger, results);
output.newTrigger = cellfun( ...
    @(item) item.backend.certificate.trigger, results);
output.recoveryAccepted = cellfun( ...
    @(item) item.backend.recovery.accepted, results);
output.noTriggerIdentity = ~output.newTrigger ...
    & abs(output.theta_P_FARC2-output.theta_P_FA) <= 1e-12 ...
    & abs(output.range_P_FARC2-output.range_P_FA) <= 1e-12;
baseSquared = output.rangeError_P_FA.^2;
newSquared = output.rangeError_P_FARC2.^2;
tolerance = 100*eps(max(1, max([baseSquared; newSquared])));
output.harmfulRecovery = output.newTrigger ...
    & newSquared > baseSquared+tolerance;
end

function output = summarizeMethods(perUser, methods, snrValues)
output = table();
for method = methods
    for snr = snrValues
        selected = perUser.snrDb == snr;
        ae = perUser.("angleError_"+method)(selected);
        re = perUser.("rangeError_"+method)(selected);
        output = [output; table(method, snr, nnz(selected), ...
            mean(ae.^2), sqrt(mean(ae.^2)), mean(re.^2), ...
            sqrt(mean(re.^2)), quantile(abs(re), .95), mean(abs(re)>1), ...
            'VariableNames', {'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', 'rangeMseM2', ...
            'rangeRmseM', 'rangeP95AbsM', 'rangeMissRateOver1M'})]; %#ok<AGROW>
    end
end
end

function output = compareAll(perUser, candidates, references, snrValues)
output = table();
for candidate = candidates
    for reference = references
        candidateAngle = zeros(numel(snrValues), 1);
        referenceAngle = zeros(numel(snrValues), 1);
        candidateRange = zeros(numel(snrValues), 1);
        referenceRange = zeros(numel(snrValues), 1);
        for index = 1:numel(snrValues)
            selected = perUser.snrDb == snrValues(index);
            ca = perUser.("angleError_"+candidate)(selected).^2;
            ra = perUser.("angleError_"+reference)(selected).^2;
            cr = perUser.("rangeError_"+candidate)(selected).^2;
            rr = perUser.("rangeError_"+reference)(selected).^2;
            candidateAngle(index) = mean(ca);
            referenceAngle(index) = mean(ra);
            candidateRange(index) = mean(cr);
            referenceRange(index) = mean(rr);
            output = [output; comparisonRow(candidate, reference, ...
                "per-SNR", snrValues(index), ca, ra, cr, rr)]; %#ok<AGROW>
        end
        cr = perUser.("rangeError_"+candidate).^2;
        rr = perUser.("rangeError_"+reference).^2;
        output = [output; table(candidate, reference, "equal-SNR", nan, ...
            height(perUser), mean(candidateAngle)/mean(referenceAngle), ...
            mean(candidateRange)/mean(referenceRange), ...
            1000*(sqrt(mean(candidateRange))-sqrt(mean(referenceRange))), ...
            nnz(cr<rr), nnz(cr==rr), nnz(cr>rr), mean(cr-rr), ...
            'VariableNames', output.Properties.VariableNames)]; %#ok<AGROW>
    end
end
end

function output = comparisonRow(candidate, reference, scope, snrDb, ...
    candidateAngle, referenceAngle, candidateRange, referenceRange)
output = table(candidate, reference, scope, snrDb, numel(candidateRange), ...
    mean(candidateAngle)/mean(referenceAngle), ...
    mean(candidateRange)/mean(referenceRange), ...
    1000*(sqrt(mean(candidateRange))-sqrt(mean(referenceRange))), ...
    nnz(candidateRange<referenceRange), nnz(candidateRange==referenceRange), ...
    nnz(candidateRange>referenceRange), mean(candidateRange-referenceRange), ...
    'VariableNames', {'candidate', 'reference', 'scope', 'snrDb', 'n', ...
    'angleMseRatio', 'rangeMseRatio', 'rangeRmseDifferenceMm', ...
    'rangeWinCount', 'rangeTieCount', 'rangeLossCount', ...
    'meanRangeSquaredErrorDifference'});
end

function output = summarizeNormalDiagnostics(perUser)
triggered = perUser.newTrigger;
falseTrigger = triggered & perUser.supportClass == "none";
conditionalHarm = conditionalRate(perUser.harmfulRecovery, triggered);
output = table(height(perUser), mean(perUser.oldTrigger), ...
    mean(perUser.newTrigger), sum(perUser.C1), sum(perUser.C2), ...
    sum(perUser.C3a), sum(perUser.C3b), sum(perUser.C4), ...
    mean(falseTrigger), conditionalHarm, ...
    sum(~perUser.newTrigger & ~perUser.noTriggerIdentity), ...
    'VariableNames', {'n', 'oldTriggerRate', 'newTriggerRate', ...
    'C1Count', 'C2Count', 'C3aCount', 'C3bCount', 'C4Count', ...
    'falseTriggerRate', 'conditionalHarmfulRecoveryRate', ...
    'noTriggerIdentityViolationCount'});
end

function output = summarizeStress(perUser, protocol)
output = table();
for stressType = protocol.stressPool.classes
    rows = perUser.supportClass == stressType;
    oldSensitivity = meanOrNaN(perUser.oldTrigger(rows));
    newSensitivity = meanOrNaN(perUser.newTrigger(rows));
    acceptedRate = meanOrNaN(perUser.recoveryAccepted(rows));
    harmfulRate = conditionalRate( ...
        perUser.harmfulRecovery(rows), perUser.newTrigger(rows));
    baseRange = abs(perUser.rangeError_P_FA(rows));
    newRange = abs(perUser.rangeError_P_FARC2(rows));
    output = [output; table(stressType, nnz(rows), oldSensitivity, ...
        newSensitivity, newSensitivity-oldSensitivity, acceptedRate, ...
        harmfulRate, meanOrNaN(baseRange), meanOrNaN(newRange), ...
        nnz(baseRange>1 & newRange<1), nnz(baseRange>1), ...
        'VariableNames', {'stressType', 'n', 'oldTriggerSensitivity', ...
        'newTriggerSensitivity', 'sensitivityGain', ...
        'recoveryAcceptedRate', 'conditionalHarmfulRecoveryRate', ...
        'baseMeanAbsRangeErrorM', 'newMeanAbsRangeErrorM', ...
        'baseOver1MRecoveredCount', 'baseOver1MCount'})]; %#ok<AGROW>
end
end

function output = summarizeMechanism(perUser, protocol)
stable = perUser.stableInteriorSupportMiss;
oldDetected = stable & perUser.oldTrigger;
newDetected = stable & perUser.newTrigger;
rangeRows = perUser.supportClass == "range";
output = table(nnz(stable), nnz(oldDetected), nnz(newDetected), ...
    nnz(newDetected)-nnz(oldDetected), nnz(stable & perUser.C3b), ...
    meanOrNaN(perUser.oldTrigger(rangeRows)), ...
    meanOrNaN(perUser.newTrigger(rangeRows)), ...
    'VariableNames', {'stableInteriorCount', 'oldDetectedCount', ...
    'newDetectedCount', 'additionalDetections', 'C3bDetectedCount', ...
    'oldRangeSensitivity', 'newRangeSensitivity'});
output.rangeSensitivityGain = output.newRangeSensitivity ...
    -output.oldRangeSensitivity;
output.requiredAdditionalDetections = ...
    protocol.gate.minimumAdditionalStableInteriorDetections;
end

function output = buildGate(comparisons, normal, stress, mechanism, ...
    stressSelection, protocol)
primaryPA = comparisons(comparisons.candidate == "P_FARC2" ...
    & comparisons.reference == "P_A", :);
primaryPFA = comparisons(comparisons.candidate == "P_FARC2" ...
    & comparisons.reference == "P_FA", :);
simpleR51 = comparisons(comparisons.candidate == "R51_trigger_simple" ...
    & comparisons.reference == "R51_PFARC" ...
    & comparisons.scope == "equal-SNR", :);
stressSensitivity = stress.newTriggerSensitivity;
rangeRow = stress.stressType == "range";
metric = ["stress-construction"; "aggregate-range/P_A"; ...
    "max-per-SNR-range/P_A"; "aggregate-angle/P_FA"; ...
    "normal-false-trigger-rate"; ...
    "normal-conditional-harmful-recovery-rate"; ...
    "minimum-stress-trigger-sensitivity"; ...
    "range-stress-trigger-sensitivity"; ...
    "maximum-stress-harmful-recovery-rate"; ...
    "additional-stable-interior-detections"; ...
    "range-sensitivity-gain-over-R51-trigger"; ...
    "simple-recovery-range-MSE/frozen-R51"; ...
    "no-trigger-identity-violations"];
value = [double(stressSelection.constructionPass); ...
    primaryPA.rangeMseRatio(primaryPA.scope == "equal-SNR"); ...
    max(primaryPA.rangeMseRatio(primaryPA.scope == "per-SNR")); ...
    primaryPFA.angleMseRatio(primaryPFA.scope == "equal-SNR"); ...
    normal.falseTriggerRate; normal.conditionalHarmfulRecoveryRate; ...
    min(stressSensitivity); stress.newTriggerSensitivity(rangeRow); ...
    max(stress.conditionalHarmfulRecoveryRate); ...
    mechanism.additionalDetections; mechanism.rangeSensitivityGain; ...
    simpleR51.rangeMseRatio; normal.noTriggerIdentityViolationCount];
limit = [1; protocol.gate.maxAggregateRangeMseRatioToPA; ...
    protocol.gate.maxPerSnrRangeMseRatioToPA; ...
    protocol.gate.maxAggregateAngleMseRatioToPFA; ...
    protocol.gate.maxNormalFalseTriggerRate; ...
    protocol.gate.maxConditionalNormalHarmfulRecoveryRate; ...
    protocol.gate.minimumStressSensitivity; ...
    protocol.gate.minimumRangeStressSensitivity; ...
    protocol.gate.maxStressHarmfulRecoveryRate; ...
    protocol.gate.minimumAdditionalStableInteriorDetections; ...
    protocol.gate.minimumRangeSensitivityGainOverR51Trigger; ...
    protocol.gate.maxSimpleRecoveryRangeMseRatioToFrozenR51; 0];
direction = [">="; "<="; "<="; "<="; "<="; "<="; ...
    ">="; ">="; "<="; ">="; ">="; "<="; "<="];
pass = false(size(value));
for index = 1:numel(value)
    if direction(index) == "<="
        pass(index) = isfinite(value(index)) && value(index) <= limit(index);
    else
        pass(index) = isfinite(value(index)) && value(index) >= limit(index);
    end
end
output = table(metric, value, direction, limit, pass);
output.notes = repmat("predeclared-R52-development-gate", ...
    height(output), 1);
end

function value = conditionalRate(event, condition)
if any(condition)
    value = mean(event(condition));
else
    value = 0;
end
end

function value = meanOrNaN(input)
if isempty(input)
    value = nan;
else
    value = mean(input);
end
end
