function output = r35SummarizeSchemeD( ...
    design, baselines, results, commonProtocol)
%R35SUMMARIZESCHEMED Apply the frozen metrics and engineering gates.

arguments
    design table
    baselines cell
    results cell
    commonProtocol (1, 1) struct = r35CommonProtocol()
end

validateComplete(design, baselines, results);
perUser = buildPerUser(design, baselines, results);
methodRows = buildMethodRows(perUser);
methodSummary = summarizeMethods(methodRows, perUser);
pairedComparisons = table();
for method = ["D1_gap", "D2_information", "D3_mix"]
    pairedComparisons = [pairedComparisons; ...
        pairedRows(methodRows, method, "D0_uniform")]; %#ok<AGROW>
end
weightDiagnostics = buildWeightDiagnostics(design, baselines, results);
weightSummary = summarizeWeights(weightDiagnostics);
runtimeSummary = summarizeRuntime(perUser);
identityAudit = buildIdentityAudit(design, baselines);
engineeringGate = buildEngineeringGate( ...
    methodSummary, commonProtocol);

methods = ["D1_gap", "D2_information", "D3_mix"];
methodPass = false(numel(methods), 1);
for index = 1:numel(methods)
    selected = engineeringGate.method == methods(index);
    methodPass(index) = all(engineeringGate.pass(selected));
end
gateDecision = table(methods.', methodPass, ...
    'VariableNames', {'method', 'pass'});
output = struct(version="R35-schemeD-development-summary-v1", ...
    dataRole="existing-60-user-development-only", ...
    perUser=perUser, methodRows=methodRows, ...
    methodSummary=methodSummary, ...
    pairedComparisons=pairedComparisons, ...
    weightDiagnostics=weightDiagnostics, ...
    weightSummary=weightSummary, runtimeSummary=runtimeSummary, ...
    identityAudit=identityAudit, engineeringGate=engineeringGate, ...
    gateDecision=gateDecision, anyMethodPassed=any(methodPass));
end

function validateComplete(design, baselines, results)
if numel(baselines) ~= height(design) || numel(results) ~= height(design) ...
        || any(cellfun(@isempty, baselines)) || any(cellfun(@isempty, results))
    error("r35:IncompleteSchemeDResults", ...
        "Scheme D requires all 60 frozen development rows.");
end
if any(cellfun(@(x) ~x.success, baselines)) ...
        || any(cellfun(@(x) ~x.d0Identity.passed, baselines))
    error("r35:SchemeDD0IdentityFailure", ...
        "Every D0 row must reproduce P_A before Scheme D is summarized.");
end
if any(cellfun(@(x) ~x.success, results))
    error("r35:SchemeDWeightedTrialFailure", ...
        "At least one D1-D3 row failed.");
end
end

function perUser = buildPerUser(design, baselines, results)
methods = ["D0_uniform", "D1_gap", "D2_information", ...
    "D3_mix", "C_enhanced"];
theta = struct();
range = struct();
runtime = struct();
responses = struct();
music = struct();
carrierMusic = struct();
evd = struct();
for method = methods
    source = results;
    if method == "D0_uniform" || method == "C_enhanced"
        source = baselines;
    end
    theta.(method) = cellfun(@(x) x.(method).thetaDeg, source);
    range.(method) = cellfun(@(x) x.(method).rangeM, source);
    runtime.(method) = cellfun(@(x) x.(method).runtimeSeconds, source);
    responses.(method) = cellfun( ...
        @(x) x.(method).responseEvaluationCount, source);
    music.(method) = cellfun( ...
        @(x) x.(method).musicEvaluationCount, source);
    carrierMusic.(method) = cellfun( ...
        @(x) x.(method).carrierScoreEvaluationCount, source);
    evd.(method) = cellfun(@(x) x.(method).evdCount, source);
end

perUser = table(design.seed, design.trialIndex, design.snrDb, ...
    design.truthThetaDeg, design.truthRangeM, ...
    theta.D0_uniform, range.D0_uniform, ...
    theta.D1_gap, range.D1_gap, ...
    theta.D2_information, range.D2_information, ...
    theta.D3_mix, range.D3_mix, ...
    theta.C_enhanced, range.C_enhanced, ...
    d0Gain(theta.D0_uniform, theta.D1_gap, design.truthThetaDeg), ...
    d0Gain(theta.D0_uniform, theta.D2_information, design.truthThetaDeg), ...
    d0Gain(theta.D0_uniform, theta.D3_mix, design.truthThetaDeg), ...
    theta.D1_gap-theta.D0_uniform, ...
    theta.D2_information-theta.D0_uniform, ...
    theta.D3_mix-theta.D0_uniform, ...
    string(cellfun(@(x) x.runtimeOrder, baselines, UniformOutput=false)), ...
    string(cellfun(@(x) x.executionOrder, results, UniformOutput=false)), ...
    runtime.D0_uniform, runtime.D1_gap, runtime.D2_information, ...
    runtime.D3_mix, runtime.C_enhanced, ...
    cellfun(@(x) x.D1_gap.weightConstructionSeconds, results), ...
    cellfun(@(x) x.D2_information.weightConstructionSeconds, results), ...
    cellfun(@(x) x.D3_mix.weightConstructionSeconds, results), ...
    cellfun(@(x) x.D1_gap.weightedFusionSeconds, results), ...
    cellfun(@(x) x.D2_information.weightedFusionSeconds, results), ...
    cellfun(@(x) x.D3_mix.weightedFusionSeconds, results), ...
    cellfun(@(x) x.D1_gap.profileSeconds, results), ...
    cellfun(@(x) x.D2_information.profileSeconds, results), ...
    cellfun(@(x) x.D3_mix.profileSeconds, results), ...
    responses.D0_uniform, responses.D1_gap, responses.D2_information, ...
    responses.D3_mix, responses.C_enhanced, ...
    music.D0_uniform, music.D1_gap, music.D2_information, ...
    music.D3_mix, music.C_enhanced, ...
    carrierMusic.D0_uniform, carrierMusic.D1_gap, ...
    carrierMusic.D2_information, carrierMusic.D3_mix, ...
    carrierMusic.C_enhanced, ...
    evd.D0_uniform, evd.D1_gap, evd.D2_information, ...
    evd.D3_mix, evd.C_enhanced, ...
    'VariableNames', {'seed', 'trialIndex', 'snrDb', ...
    'truthThetaDeg', 'truthRangeM', ...
    'theta_D0', 'range_D0', 'theta_D1', 'range_D1', ...
    'theta_D2', 'range_D2', 'theta_D3', 'range_D3', ...
    'theta_C_enhanced', 'range_C_enhanced', ...
    'truthSquaredErrorGain_D1', 'truthSquaredErrorGain_D2', ...
    'truthSquaredErrorGain_D3', 'angleDisplacement_D1', ...
    'angleDisplacement_D2', 'angleDisplacement_D3', ...
    'baselineRuntimeOrder', 'weightedRuntimeOrder', ...
    'runtime_D0', 'runtime_D1', 'runtime_D2', 'runtime_D3', ...
    'runtime_C_enhanced', 'weightConstructionSeconds_D1', ...
    'weightConstructionSeconds_D2', 'weightConstructionSeconds_D3', ...
    'weightedFusionSeconds_D1', 'weightedFusionSeconds_D2', ...
    'weightedFusionSeconds_D3', 'profileSeconds_D1', ...
    'profileSeconds_D2', 'profileSeconds_D3', ...
    'responseCount_D0', 'responseCount_D1', 'responseCount_D2', ...
    'responseCount_D3', 'responseCount_C_enhanced', ...
    'musicCount_D0', 'musicCount_D1', 'musicCount_D2', ...
    'musicCount_D3', 'musicCount_C_enhanced', ...
    'carrierMusicCount_D0', 'carrierMusicCount_D1', ...
    'carrierMusicCount_D2', 'carrierMusicCount_D3', ...
    'carrierMusicCount_C_enhanced', 'evdCount_D0', 'evdCount_D1', ...
    'evdCount_D2', 'evdCount_D3', 'evdCount_C_enhanced'});
end

function gain = d0Gain(thetaD0, thetaD, truth)
gain = (thetaD0-truth).^2-(thetaD-truth).^2;
end

function rows = buildMethodRows(perUser)
methods = ["D0_uniform", "D1_gap", "D2_information", ...
    "D3_mix", "C_enhanced"];
thetaFields = ["theta_D0", "theta_D1", "theta_D2", ...
    "theta_D3", "theta_C_enhanced"];
rangeFields = ["range_D0", "range_D1", "range_D2", ...
    "range_D3", "range_C_enhanced"];
runtimeFields = ["runtime_D0", "runtime_D1", "runtime_D2", ...
    "runtime_D3", "runtime_C_enhanced"];
rows = table();
for index = 1:numel(methods)
    theta = perUser.(thetaFields(index));
    range = perUser.(rangeFields(index));
    angleError = theta-perUser.truthThetaDeg;
    rangeError = range-perUser.truthRangeM;
    xError = range.*sind(theta) ...
        -perUser.truthRangeM.*sind(perUser.truthThetaDeg);
    yError = range.*cosd(theta) ...
        -perUser.truthRangeM.*cosd(perUser.truthThetaDeg);
    current = table(perUser.seed, perUser.trialIndex, perUser.snrDb, ...
        repmat(methods(index), height(perUser), 1), theta, range, ...
        angleError, rangeError, hypot(xError, yError), ...
        perUser.(runtimeFields(index)), ...
        'VariableNames', {'seed', 'trialIndex', 'snrDb', 'method', ...
        'thetaDeg', 'rangeM', 'angleErrorDeg', 'rangeErrorM', ...
        'positionErrorM', 'runtimeSeconds'});
    rows = [rows; current]; %#ok<AGROW>
end
end

function summary = summarizeMethods(rows, perUser)
summary = table();
for method = unique(rows.method, "stable").'
    for snrDb = unique(rows.snrDb).'
        current = rows(rows.method == method & rows.snrDb == snrDb, :);
        squared = current.angleErrorDeg.^2;
        rangeSquared = current.rangeErrorM.^2;
        positionSquared = current.positionErrorM.^2;
        [changed, responses, music, carrierMusic, evd] = ...
            diagnosticsForMethod(method, snrDb, perUser);
        entry = table(method, snrDb, height(current), mean(squared), ...
            sqrt(mean(squared)), median(abs(current.angleErrorDeg)), ...
            quantile(abs(current.angleErrorDeg), 0.90), ...
            quantile(abs(current.angleErrorDeg), 0.95), ...
            mean(rangeSquared), sqrt(mean(rangeSquared)), ...
            sqrt(mean(positionSquared)), changed, ...
            mean(current.runtimeSeconds), mean(responses), mean(music), ...
            mean(carrierMusic), mean(evd), ...
            'VariableNames', {'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', ...
            'angleMedianAbsoluteErrorDeg', ...
            'angleP90AbsoluteErrorDeg', 'angleP95AbsoluteErrorDeg', ...
            'rangeMseM2', 'rangeRmseM', 'positionRmseM', ...
            'fractionAngleChangedFromD0', 'meanRuntimeSeconds', ...
            'meanResponseEvaluationCount', 'meanMusicEvaluationCount', ...
            'meanCarrierScoreEvaluationCount', 'meanEvdCount'});
        summary = [summary; entry]; %#ok<AGROW>
    end
end
summary.angleMseRatioToD0 = nan(height(summary), 1);
summary.rangeMseRatioToD0 = nan(height(summary), 1);
for index = 1:height(summary)
    d0 = summary(summary.method == "D0_uniform" ...
        & summary.snrDb == summary.snrDb(index), :);
    summary.angleMseRatioToD0(index) = ...
        summary.angleMseDeg2(index)/d0.angleMseDeg2;
    summary.rangeMseRatioToD0(index) = ...
        summary.rangeMseM2(index)/d0.rangeMseM2;
end
end

function [changed, responses, music, carrierMusic, evd] = ...
    diagnosticsForMethod(method, snrDb, perUser)
selected = perUser.snrDb == snrDb;
suffix = extractAfter(method, 1);
if method == "D0_uniform"
    suffix = "D0";
elseif method == "D1_gap"
    suffix = "D1";
elseif method == "D2_information"
    suffix = "D2";
elseif method == "D3_mix"
    suffix = "D3";
elseif method == "C_enhanced"
    suffix = "C_enhanced";
end
theta = perUser.("theta_"+suffix)(selected);
changed = mean(theta ~= perUser.theta_D0(selected));
responses = perUser.("responseCount_"+suffix)(selected);
music = perUser.("musicCount_"+suffix)(selected);
carrierMusic = perUser.("carrierMusicCount_"+suffix)(selected);
evd = perUser.("evdCount_"+suffix)(selected);
end

function output = pairedRows(rows, candidateName, referenceName)
output = table();
snrValues = unique(rows.snrDb).';
candidateMse = zeros(numel(snrValues), 1);
referenceMse = zeros(numel(snrValues), 1);
allDifference = zeros(0, 1);
for index = 1:numel(snrValues)
    [entry, difference, candidateMse(index), referenceMse(index)] = ...
        pairedEntry(rows, candidateName, referenceName, snrValues(index));
    output = [output; entry]; %#ok<AGROW>
    allDifference = [allDifference; difference]; %#ok<AGROW>
end
candidateAggregate = mean(candidateMse);
referenceAggregate = mean(referenceMse);
output = [output; comparisonRow(candidateName, referenceName, ...
    "equal-SNR", nan, numel(allDifference), candidateAggregate, ...
    referenceAggregate, allDifference)];
end

function [entry, difference, candidateMse, referenceMse] = ...
    pairedEntry(rows, candidateName, referenceName, snrDb)
candidate = sortrows(rows(rows.method == candidateName ...
    & rows.snrDb == snrDb, :), "seed");
reference = sortrows(rows(rows.method == referenceName ...
    & rows.snrDb == snrDb, :), "seed");
if ~isequal(candidate.seed, reference.seed)
    error("r35:UnpairedSchemeDRows", ...
        "Scheme D comparisons require identical old users.");
end
candidateSquared = candidate.angleErrorDeg.^2;
referenceSquared = reference.angleErrorDeg.^2;
candidateMse = mean(candidateSquared);
referenceMse = mean(referenceSquared);
difference = candidateSquared-referenceSquared;
entry = comparisonRow(candidateName, referenceName, "per-SNR", ...
    snrDb, height(candidate), candidateMse, referenceMse, difference);
end

function row = comparisonRow(candidate, reference, scope, snrDb, n, ...
    candidateMse, referenceMse, difference)
ratio = candidateMse/referenceMse;
row = table(candidate, reference, scope, snrDb, n, candidateMse, ...
    referenceMse, ratio, 100*(1-sqrt(ratio)), mean(difference), ...
    nnz(difference < 0), nnz(difference == 0), ...
    nnz(difference > 0), mean(difference < 0), ...
    mean(difference == 0), mean(difference > 0), ...
    'VariableNames', {'candidate', 'reference', 'scope', 'snrDb', ...
    'n', 'candidateAngleMseDeg2', 'referenceAngleMseDeg2', ...
    'angleMseRatio', 'angleRmseImprovementPercent', ...
    'meanCandidateMinusReferenceSquaredError', 'winCount', ...
    'tieCount', 'lossCount', 'winRate', 'tieRate', 'lossRate'});
end

function rows = buildWeightDiagnostics(design, baselines, results)
methods = ["D0_uniform", "D1_gap", "D2_information", "D3_mix"];
rows = table();
for method = methods
    for user = 1:height(design)
        if method == "D0_uniform"
            diagnostic = baselines{user}.d0WeightDiagnostics;
        else
            diagnostic = results{user}.(method).weightDiagnostics;
        end
        gain = 0;
        if method ~= "D0_uniform"
            if method == "D1_gap"
                gain = (baselines{user}.D0_uniform.thetaDeg ...
                    -design.truthThetaDeg(user))^2 ...
                    -(results{user}.D1_gap.thetaDeg ...
                    -design.truthThetaDeg(user))^2;
            elseif method == "D2_information"
                gain = (baselines{user}.D0_uniform.thetaDeg ...
                    -design.truthThetaDeg(user))^2 ...
                    -(results{user}.D2_information.thetaDeg ...
                    -design.truthThetaDeg(user))^2;
            else
                gain = (baselines{user}.D0_uniform.thetaDeg ...
                    -design.truthThetaDeg(user))^2 ...
                    -(results{user}.D3_mix.thetaDeg ...
                    -design.truthThetaDeg(user))^2;
            end
        end
        entry = table(design.seed(user), design.trialIndex(user), ...
            design.snrDb(user), method, diagnostic.maxWeight, ...
            diagnostic.minNonzeroWeight, ...
            diagnostic.effectiveCarrierCount, ...
            diagnostic.normalizedEntropy, diagnostic.top1Cumulative, ...
            diagnostic.top10Cumulative, diagnostic.top100Cumulative, ...
            diagnostic.weightedMeanFrequencyHz, ...
            diagnostic.edgeCumulative, diagnostic.centerCumulative, gain, ...
            'VariableNames', {'seed', 'trialIndex', 'snrDb', 'method', ...
            'maxWeight', 'minNonzeroWeight', 'effectiveCarrierCount', ...
            'normalizedEntropy', 'top1Cumulative', 'top10Cumulative', ...
            'top100Cumulative', 'weightedMeanFrequencyHz', ...
            'edgeCumulative', 'centerCumulative', ...
            'truthSquaredErrorGainDeg2'});
        rows = [rows; entry]; %#ok<AGROW>
    end
end
end

function summary = summarizeWeights(rows)
summary = table();
metrics = ["maxWeight", "minNonzeroWeight", "effectiveCarrierCount", ...
    "normalizedEntropy", "top1Cumulative", "top10Cumulative", ...
    "top100Cumulative", "weightedMeanFrequencyHz", ...
    "edgeCumulative", "centerCumulative"];
for method = unique(rows.method, "stable").'
    for snrDb = unique(rows.snrDb).'
        selected = rows.method == method & rows.snrDb == snrDb;
        for metric = metrics
            values = rows.(metric)(selected);
            entry = table(method, snrDb, metric, numel(values), ...
                min(values), quantile(values, 0.25), median(values), ...
                mean(values), quantile(values, 0.75), max(values), ...
                'VariableNames', {'method', 'snrDb', 'metric', 'n', ...
                'minimum', 'p25', 'median', 'mean', 'p75', 'maximum'});
            summary = [summary; entry]; %#ok<AGROW>
        end
    end
end
end

function summary = summarizeRuntime(perUser)
methods = ["D0_uniform", "D1_gap", "D2_information", ...
    "D3_mix", "C_enhanced"];
runtimeFields = ["runtime_D0", "runtime_D1", "runtime_D2", ...
    "runtime_D3", "runtime_C_enhanced"];
summary = table();
for index = 1:numel(methods)
    values = perUser.(runtimeFields(index));
    if index >= 2 && index <= 4
        suffix = "D"+string(index-1);
        weight = mean(perUser.("weightConstructionSeconds_"+suffix));
        fusion = mean(perUser.("weightedFusionSeconds_"+suffix));
        profile = mean(perUser.("profileSeconds_"+suffix));
    else
        weight = 0;
        fusion = nan;
        profile = nan;
    end
    summary = [summary; table(methods(index), mean(values), ...
        median(values), weight, fusion, profile, ...
        'VariableNames', {'method', 'meanCompleteRuntimeSeconds', ...
        'medianCompleteRuntimeSeconds', ...
        'meanWeightConstructionSeconds', ...
        'meanWeightedFusionSeconds', 'meanProfileSeconds'})]; %#ok<AGROW>
end
cRuntime = summary.meanCompleteRuntimeSeconds( ...
    summary.method == "C_enhanced");
summary.runtimeRatioToCEnhanced = ...
    summary.meanCompleteRuntimeSeconds/cRuntime;
end

function audit = buildIdentityAudit(design, baselines)
audit = table(design.seed, design.trialIndex, design.snrDb, ...
    cellfun(@(x) x.d0Identity.passed, baselines), ...
    cellfun(@(x) x.d0Identity.gridPass, baselines), ...
    cellfun(@(x) x.d0Identity.selectedIndexPass, baselines), ...
    cellfun(@(x) x.d0Identity.selectedThetaPass, baselines), ...
    cellfun(@(x) x.d0Identity.maximumStageScoreDifference, baselines), ...
    cellfun(@(x) x.d0Identity.finalThetaDifferenceDeg, baselines), ...
    cellfun(@(x) x.d0IdentitySearchSeconds, baselines), ...
    'VariableNames', {'seed', 'trialIndex', 'snrDb', 'passed', ...
    'gridPass', 'selectedIndexPass', 'selectedThetaPass', ...
    'maximumStageScoreDifference', 'finalThetaDifferenceDeg', ...
    'identitySearchSeconds'});
end

function gate = buildEngineeringGate(summary, protocol)
gate = table();
for method = ["D1_gap", "D2_information", "D3_mix"]
    for snrDb = unique(summary.snrDb).'
        d0 = summary(summary.method == "D0_uniform" ...
            & summary.snrDb == snrDb, :);
        candidate = summary(summary.method == method ...
            & summary.snrDb == snrDb, :);
        gate = [gate; gateRow(method, "angle", ...
            "per-SNR-angle-MSE", snrDb, ...
            candidate.angleMseDeg2/d0.angleMseDeg2, ...
            protocol.engineeringGate.maximumPerSnrAngleMseRatioToPA)]; %#ok<AGROW>
    end
    d0Rows = summary(summary.method == "D0_uniform", :);
    candidateRows = summary(summary.method == method, :);
    gate = [gate; gateRow(method, "angle", ...
        "equal-SNR-aggregate-angle-MSE", nan, ...
        mean(candidateRows.angleMseDeg2)/mean(d0Rows.angleMseDeg2), ...
        protocol.engineeringGate.maximumEqualSnrAggregateAngleMseRatioToPA)]; %#ok<AGROW>
    for snrDb = unique(summary.snrDb).'
        d0 = summary(summary.method == "D0_uniform" ...
            & summary.snrDb == snrDb, :);
        candidate = summary(summary.method == method ...
            & summary.snrDb == snrDb, :);
        gate = [gate; gateRow(method, "range", ...
            "per-SNR-range-MSE", snrDb, ...
            candidate.rangeMseM2/d0.rangeMseM2, ...
            protocol.engineeringGate.maximumPerSnrRangeMseRatioToPA)]; %#ok<AGROW>
    end
    cRows = summary(summary.method == "C_enhanced", :);
    gate = [gate; gateRow(method, "runtime", "mean-runtime", nan, ...
        mean(candidateRows.meanRuntimeSeconds) ...
        /mean(cRows.meanRuntimeSeconds), ...
        protocol.engineeringGate.maximumRuntimeRatioToCEnhanced)]; %#ok<AGROW>
end
end

function row = gateRow(method, category, name, snrDb, observed, limit)
row = table(method, category, name, snrDb, observed, limit, ...
    observed <= limit, 'VariableNames', {'method', 'category', ...
    'gate', 'snrDb', 'observedRatio', 'maximumAllowedRatio', 'pass'});
end
