function result = r35StagedWeightedAngleMusic( ...
    cfg, state, coarseThetaDeg, fixedRangeM, halfWidthDeg, ...
    gridSizes, weights)
%R35STAGEDWEIGHTEDANGLEMUSIC Run the frozen grid with fixed carrier weights.

arguments
    cfg (1, 1) struct
    state (1, 1) struct
    coarseThetaDeg (1, 1) double {mustBeFinite}
    fixedRangeM (1, 1) double {mustBeFinite, mustBePositive}
    halfWidthDeg (1, 1) double {mustBePositive}
    gridSizes (1, :) double {mustBeInteger, mustBePositive}
    weights (:, 1) double {mustBeFinite, mustBeNonnegative}
end

if numel(weights) ~= numel(state.frequencyHz) ...
        || abs(sum(weights)-1) > 1e-12
    error("r35:InvalidCarrierFusionWeights", ...
        "One normalized nonnegative weight is required per carrier.");
end

timer = tic;
initialBounds = [max(cfg.thetaLimitsDeg(1), coarseThetaDeg-halfWidthDeg), ...
    min(cfg.thetaLimitsDeg(2), coarseThetaDeg+halfWidthDeg)];
thetaCenter = coarseThetaDeg;
currentHalfWidth = halfWidthDeg;
stages = repmat(emptyStage(), numel(gridSizes), 1);
evaluationCount = 0;
for level = 1:numel(gridSizes)
    gridSize = gridSizes(level);
    thetaGrid = linspace(max(thetaCenter-currentHalfWidth, ...
        initialBounds(1)), min(thetaCenter+currentHalfWidth, ...
        initialBounds(2)), gridSize);
    carrierScore = r35SingleCarrierMusicLogScores( ...
        cfg, state, thetaGrid, fixedRangeM);
    score = weights.'*carrierScore;
    [selectedScore, selectedIndex] = max(score);
    thetaCenter = thetaGrid(selectedIndex);
    thetaStep = thetaGrid(2)-thetaGrid(1);
    currentHalfWidth = 2*thetaStep;
    evaluationCount = evaluationCount+gridSize;
    stages(level) = struct(thetaGridDeg=thetaGrid, score=score, ...
        selectedIndex=selectedIndex, selectedThetaDeg=thetaCenter, ...
        selectedScore=selectedScore, endpointHit=selectedIndex == 1 ...
        || selectedIndex == gridSize);
end

result = struct(version="R35-weighted-staged-angle-MUSIC-v1", ...
    thetaDeg=thetaCenter, fixedRangeM=fixedRangeM, ...
    score=stages(end).selectedScore, initialBoundsDeg=initialBounds, ...
    gridSizes=gridSizes, evaluationCount=evaluationCount, ...
    carrierScoreEvaluationCount=evaluationCount*numel(weights), ...
    stages=stages, finalEndpointHit=stages(end).endpointHit, ...
    runtimeSeconds=toc(timer));
end

function stage = emptyStage()
stage = struct(thetaGridDeg=zeros(1, 0), score=zeros(1, 0), ...
    selectedIndex=nan, selectedThetaDeg=nan, selectedScore=nan, ...
    endpointHit=false);
end
