function result = r35SchemeDWeightedTrial( ...
    cfg, scan, designRow, rowIndex, baseline, r34Protocol, schemeProtocol)
%R35SCHEMEDWEIGHTEDTRIAL Run D1-D3 and refresh the frozen range profile.

arguments
    cfg (1, 1) struct
    scan (1, 1) struct
    designRow (1, :) table
    rowIndex (1, 1) double {mustBeInteger, mustBePositive}
    baseline (1, 1) struct
    r34Protocol (1, 1) struct = r34.config()
    schemeProtocol (1, 1) struct = r35SchemeDConfig()
end

result = failureResult(designRow, rowIndex);
try
    if ~baseline.success || ~baseline.d0Identity.passed
        error("r35:D0GateNotSatisfied", ...
            "D1-D3 cannot run before this row passes D0 identity.");
    end
    replay = fsjad.replayRound27Data(cfg, scan, designRow);
    pa = baseline.paFrozen;
    methods = ["D1_gap", "D2_information", "D3_mix"];
    methods = circshift(methods, -(mod(rowIndex-1, numel(methods))));
    outputs = struct();
    for index = 1:numel(methods)
        method = methods(index);
        weightResult = r35BuildCarrierWeights( ...
            pa.musicCfg, pa.state, pa.cost, method, schemeProtocol);
        angle = r35StagedWeightedAngleMusic(pa.musicCfg, pa.state, ...
            pa.front.selected.thetaDeg, pa.front.selected.rangeM, ...
            r34Protocol.r32.music.angleHalfWidthDeg, ...
            schemeProtocol.gridSizes, weightResult.weights);
        profileTimer = tic;
        profile = r33.profileAtAngle(cfg, replay.observation, scan, ...
            angle.thetaDeg, pa.front.selected.rangeM, r34Protocol.r33);
        profileSeconds = toc(profileTimer);
        baseCoreSeconds = pa.cost.totalOnlineSeconds ...
            -pa.cost.searchSeconds-pa.cost.profileSeconds;
        completeRuntimeSeconds = baseCoreSeconds ...
            +weightResult.constructionSeconds ...
            +angle.runtimeSeconds+profileSeconds;
        responseCount = pa.cost.sparseResponseCalls ...
            +pa.cost.frontFullResponseCalls+profile.evaluationCount;
        outputs.(method) = struct(thetaDeg=angle.thetaDeg, ...
            rangeM=profile.value, runtimeSeconds=completeRuntimeSeconds, ...
            coreRuntimeSeconds=baseCoreSeconds, ...
            weightConstructionSeconds=weightResult.constructionSeconds, ...
            weightedFusionSeconds=angle.runtimeSeconds, ...
            profileSeconds=profileSeconds, ...
            responseEvaluationCount=responseCount, ...
            musicEvaluationCount=angle.evaluationCount, ...
            carrierScoreEvaluationCount=angle.carrierScoreEvaluationCount, ...
            evdCount=pa.cost.directCount, weights=weightResult.weights, ...
            rawMeasure=weightResult.rawMeasure, ...
            rawGap=weightResult.rawGap, ...
            rawInformation=weightResult.rawInformation, ...
            weightDiagnostics=weightResult.diagnostics, ...
            angleSearch=angle, profile=compactProfile(profile));
    end
    result.success = true;
    result.executionOrder = strjoin(methods, "-then-");
    result.P_A = baseline.P_A;
    result.D0_uniform = baseline.D0_uniform;
    result.C_enhanced = baseline.C_enhanced;
    result.D1_gap = outputs.D1_gap;
    result.D2_information = outputs.D2_information;
    result.D3_mix = outputs.D3_mix;
catch exception
    result.success = false;
    result.errorIdentifier = string(exception.identifier);
    result.errorMessage = string(getReport( ...
        exception, "extended", "hyperlinks", "off"));
end
end

function output = compactProfile(profile)
output = struct(version=profile.version, score=profile.score, ...
    interval=profile.interval, endpointHit=profile.endpointHit, ...
    lambda=profile.lambda, coarseSpacingM=profile.coarseSpacingM, ...
    peakCount=profile.peakCount, evaluationCount=profile.evaluationCount);
end

function result = failureResult(designRow, rowIndex)
result = struct(success=false, rowIndex=rowIndex, seed=designRow.seed, ...
    trialIndex=designRow.trialIndex, snrDb=designRow.snrDb, ...
    truthThetaDeg=designRow.truthThetaDeg, ...
    truthRangeM=designRow.truthRangeM, executionOrder="", ...
    errorIdentifier="", errorMessage="");
end
