function output = r35SummarizeSchemeA(design, results, commonProtocol)
%R35SUMMARIZESCHEMEA Apply the common metrics and engineering gate.

arguments
    design table
    results cell
    commonProtocol (1, 1) struct = r35CommonProtocol()
end

if numel(results) ~= height(design) || any(cellfun(@isempty, results))
    error("r35:IncompleteSchemeAResults", ...
        "Scheme A requires all 60 frozen development rows.");
end
failed = cellfun(@(item) ~item.success, results);
if any(failed)
    error("r35:SchemeATrialFailure", ...
        "At least one Scheme A development row failed.");
end

perUser = buildPerUser(design, results);
methodRows = buildMethodRows(perUser);
summary = summarizeMethods(methodRows);
comparisons = [pairedRows(methodRows, "A_cont", "P_A"); ...
    pairedRows(methodRows, "C_cont", "C_enhanced"); ...
    pairedRows(methodRows, "A_cont", "C_cont")];
refinement = [refinementRows(perUser, "A"); ...
    refinementRows(perUser, "C")];
gate = engineeringGate(summary, commonProtocol);

output = struct(version="R35-schemeA-development-summary-v1", ...
    dataRole="existing-60-user-development-only", ...
    perUser=perUser, methodRows=methodRows, summary=summary, ...
    comparisons=comparisons, refinement=refinement, gate=gate, ...
    gatePassed=all(gate.pass));
end

function perUser = buildPerUser(design, results)
paTheta = cellfun(@(x) x.P_A.thetaDeg, results);
paRange = cellfun(@(x) x.P_A.rangeM, results);
cTheta = cellfun(@(x) x.C_enhanced.thetaDeg, results);
cRange = cellfun(@(x) x.C_enhanced.rangeM, results);
aTheta = cellfun(@(x) x.A_cont.thetaDeg, results);
aRange = cellfun(@(x) x.A_cont.rangeM, results);
ccTheta = cellfun(@(x) x.C_cont.thetaDeg, results);
ccRange = cellfun(@(x) x.C_cont.rangeM, results);
aBracket = cell2mat(cellfun(@(x) x.aRefinement.bracketDeg, ...
    results, UniformOutput=false));
cBracket = cell2mat(cellfun(@(x) x.cRefinement.bracketDeg, ...
    results, UniformOutput=false));

perUser = table(design.seed, design.trialIndex, design.snrDb, ...
    design.truthThetaDeg, design.truthRangeM, ...
    paTheta, aTheta, cTheta, ccTheta, paRange, aRange, cRange, ccRange, ...
    aBracket(:, 1), aBracket(:, 2), cBracket(:, 1), cBracket(:, 2), ...
    cellfun(@(x) x.aRefinement.scoreBefore, results), ...
    cellfun(@(x) x.aRefinement.scoreAfter, results), ...
    cellfun(@(x) x.cRefinement.scoreBefore, results), ...
    cellfun(@(x) x.cRefinement.scoreAfter, results), ...
    cellfun(@(x) x.aRefinement.displacementDeg, results), ...
    cellfun(@(x) x.cRefinement.displacementDeg, results), ...
    cellfun(@(x) x.aRefinement.functionEvaluations, results), ...
    cellfun(@(x) x.cRefinement.functionEvaluations, results), ...
    cellfun(@(x) x.aRefinement.converged, results), ...
    cellfun(@(x) x.cRefinement.converged, results), ...
    string(cellfun(@(x) x.aRefinement.selectedSource, ...
    results, UniformOutput=false)), ...
    string(cellfun(@(x) x.cRefinement.selectedSource, ...
    results, UniformOutput=false)), ...
    string(cellfun(@(x) x.runtimeOrder, results, UniformOutput=false)), ...
    cellfun(@(x) x.P_A.runtimeSeconds, results), ...
    cellfun(@(x) x.A_cont.runtimeSeconds, results), ...
    cellfun(@(x) x.C_enhanced.runtimeSeconds, results), ...
    cellfun(@(x) x.C_cont.runtimeSeconds, results), ...
    cellfun(@(x) x.P_A.responseEvaluationCount, results), ...
    cellfun(@(x) x.A_cont.responseEvaluationCount, results), ...
    cellfun(@(x) x.C_enhanced.responseEvaluationCount, results), ...
    cellfun(@(x) x.C_cont.responseEvaluationCount, results), ...
    cellfun(@(x) x.P_A.musicEvaluationCount, results), ...
    cellfun(@(x) x.A_cont.musicEvaluationCount, results), ...
    cellfun(@(x) x.C_enhanced.musicEvaluationCount, results), ...
    cellfun(@(x) x.C_cont.musicEvaluationCount, results), ...
    'VariableNames', {'seed', 'trialIndex', 'snrDb', ...
    'truthThetaDeg', 'truthRangeM', 'theta_P_A', 'theta_A_cont', ...
    'theta_C_enhanced', 'theta_C_cont', 'range_P_A', 'range_A_cont', ...
    'range_C_enhanced', 'range_C_cont', 'aBracketLowerDeg', ...
    'aBracketUpperDeg', 'cBracketLowerDeg', 'cBracketUpperDeg', ...
    'aScoreBefore', 'aScoreAfter', 'cScoreBefore', 'cScoreAfter', ...
    'aDisplacementDeg', 'cDisplacementDeg', 'aFunctionEvaluations', ...
    'cFunctionEvaluations', 'aConverged', 'cConverged', ...
    'aSelectedSource', 'cSelectedSource', 'runtimeOrder', ...
    'runtime_P_A', 'runtime_A_cont', 'runtime_C_enhanced', ...
    'runtime_C_cont', 'responseCount_P_A', 'responseCount_A_cont', ...
    'responseCount_C_enhanced', 'responseCount_C_cont', ...
    'musicCount_P_A', 'musicCount_A_cont', ...
    'musicCount_C_enhanced', 'musicCount_C_cont'});
end

function rows = buildMethodRows(perUser)
methods = ["P_A", "A_cont", "C_enhanced", "C_cont"];
thetaFields = ["theta_P_A", "theta_A_cont", ...
    "theta_C_enhanced", "theta_C_cont"];
rangeFields = ["range_P_A", "range_A_cont", ...
    "range_C_enhanced", "range_C_cont"];
runtimeFields = ["runtime_P_A", "runtime_A_cont", ...
    "runtime_C_enhanced", "runtime_C_cont"];
responseFields = ["responseCount_P_A", "responseCount_A_cont", ...
    "responseCount_C_enhanced", "responseCount_C_cont"];
musicFields = ["musicCount_P_A", "musicCount_A_cont", ...
    "musicCount_C_enhanced", "musicCount_C_cont"];
rows = table();
for index = 1:numel(methods)
    theta = perUser.(thetaFields(index));
    range = perUser.(rangeFields(index));
    angleError = theta-perUser.truthThetaDeg;
    rangeError = range-perUser.truthRangeM;
    xError = range.*sind(theta) ...
        -perUser.truthRangeM.*sind(perUser.truthThetaDeg);
    yError = range.*cosd(theta) ...
        -perUser.truthRangeM.*cosd(perUser.truthThetaDeg);
    positionError = hypot(xError, yError);
    current = table(perUser.seed, perUser.trialIndex, perUser.snrDb, ...
        repmat(methods(index), height(perUser), 1), theta, range, ...
        angleError, rangeError, positionError, ...
        perUser.(runtimeFields(index)), perUser.(responseFields(index)), ...
        perUser.(musicFields(index)), 'VariableNames', {'seed', ...
        'trialIndex', 'snrDb', 'method', 'thetaDeg', 'rangeM', ...
        'angleErrorDeg', 'rangeErrorM', 'positionErrorM', ...
        'runtimeSeconds', 'responseEvaluationCount', ...
        'musicEvaluationCount'});
    rows = [rows; current]; %#ok<AGROW>
end
end

function summary = summarizeMethods(rows)
summary = table();
for method = unique(rows.method, "stable").'
    for snrDb = unique(rows.snrDb).'
        selected = rows.method == method & rows.snrDb == snrDb;
        current = rows(selected, :);
        angleSquared = current.angleErrorDeg.^2;
        rangeSquared = current.rangeErrorM.^2;
        entry = table(method, snrDb, height(current), ...
            mean(angleSquared), sqrt(mean(angleSquared)), ...
            median(abs(current.angleErrorDeg)), ...
            quantile(abs(current.angleErrorDeg), 0.95), ...
            mean(rangeSquared), sqrt(mean(rangeSquared)), ...
            sqrt(mean(current.positionErrorM.^2)), ...
            mean(current.runtimeSeconds), ...
            mean(current.responseEvaluationCount), ...
            mean(current.musicEvaluationCount), 'VariableNames', ...
            {'method', 'snrDb', 'n', 'angleMseDeg2', 'angleRmseDeg', ...
            'angleMedianAbsoluteErrorDeg', 'angleP95AbsoluteErrorDeg', ...
            'rangeMseM2', 'rangeRmseM', 'positionRmseM', ...
            'meanRuntimeSeconds', 'meanResponseEvaluationCount', ...
            'meanMusicEvaluationCount'});
        summary = [summary; entry]; %#ok<AGROW>
    end
end
end

function output = pairedRows(rows, candidateName, referenceName)
output = table();
snrValues = unique(rows.snrDb).';
for snrDb = snrValues
    entry = pairedEntry(rows, candidateName, referenceName, snrDb);
    output = [output; entry]; %#ok<AGROW>
end
candidateMse = zeros(numel(snrValues), 1);
referenceMse = zeros(numel(snrValues), 1);
allDifference = zeros(0, 1);
for index = 1:numel(snrValues)
    candidate = rows(rows.method == candidateName ...
        & rows.snrDb == snrValues(index), :);
    reference = rows(rows.method == referenceName ...
        & rows.snrDb == snrValues(index), :);
    candidateMse(index) = mean(candidate.angleErrorDeg.^2);
    referenceMse(index) = mean(reference.angleErrorDeg.^2);
    currentDifference = candidate.angleErrorDeg.^2 ...
        - reference.angleErrorDeg.^2;
    allDifference = [allDifference; currentDifference]; %#ok<AGROW>
end
aggregateCandidate = mean(candidateMse);
aggregateReference = mean(referenceMse);
aggregate = table(candidateName, referenceName, "equal-SNR", nan, ...
    numel(allDifference), aggregateCandidate, aggregateReference, ...
    aggregateCandidate/aggregateReference, ...
    100*(1-sqrt(aggregateCandidate/aggregateReference)), ...
    mean(allDifference, "all"), nnz(allDifference < 0), ...
    nnz(allDifference == 0), nnz(allDifference > 0), ...
    mean(allDifference < 0, "all"), ...
    mean(allDifference == 0, "all"), ...
    mean(allDifference > 0, "all"), 'VariableNames', ...
    output.Properties.VariableNames);
output = [output; aggregate];
end

function entry = pairedEntry(rows, candidateName, referenceName, snrDb)
candidate = sortrows(rows(rows.method == candidateName ...
    & rows.snrDb == snrDb, :), "seed");
reference = sortrows(rows(rows.method == referenceName ...
    & rows.snrDb == snrDb, :), "seed");
if ~isequal(candidate.seed, reference.seed)
    error("r35:UnpairedSchemeARows", ...
        "Scheme A comparisons require identical old users.");
end
candidateSquared = candidate.angleErrorDeg.^2;
referenceSquared = reference.angleErrorDeg.^2;
difference = candidateSquared-referenceSquared;
entry = table(candidateName, referenceName, "per-SNR", snrDb, ...
    height(candidate), mean(candidateSquared), mean(referenceSquared), ...
    mean(candidateSquared)/mean(referenceSquared), ...
    100*(1-sqrt(mean(candidateSquared)/mean(referenceSquared))), ...
    mean(difference, "all"), nnz(difference < 0), ...
    nnz(difference == 0), nnz(difference > 0), ...
    mean(difference < 0, "all"), mean(difference == 0, "all"), ...
    mean(difference > 0, "all"), ...
    'VariableNames', {'candidate', 'reference', 'scope', 'snrDb', ...
    'n', 'candidateAngleMseDeg2', 'referenceAngleMseDeg2', ...
    'angleMseRatio', 'angleRmseImprovementPercent', ...
    'meanPairedSquaredErrorDifference', 'winCount', 'tieCount', ...
    'lossCount', 'winRate', 'tieRate', 'lossRate'});
end

function output = refinementRows(perUser, label)
if label == "A"
    scoreGain = perUser.aScoreAfter-perUser.aScoreBefore;
    squaredErrorGain = (perUser.theta_P_A-perUser.truthThetaDeg).^2 ...
        -(perUser.theta_A_cont-perUser.truthThetaDeg).^2;
    displacement = perUser.aDisplacementDeg;
    evaluations = perUser.aFunctionEvaluations;
    converged = perUser.aConverged;
    selectedSource = perUser.aSelectedSource;
else
    scoreGain = perUser.cScoreAfter-perUser.cScoreBefore;
    squaredErrorGain = ...
        (perUser.theta_C_enhanced-perUser.truthThetaDeg).^2 ...
        -(perUser.theta_C_cont-perUser.truthThetaDeg).^2;
    displacement = perUser.cDisplacementDeg;
    evaluations = perUser.cFunctionEvaluations;
    converged = perUser.cConverged;
    selectedSource = perUser.cSelectedSource;
end
output = table();
for snrDb = [unique(perUser.snrDb).', nan]
    if isnan(snrDb)
        selected = true(height(perUser), 1);
        scope = "all-SNR";
    else
        selected = perUser.snrDb == snrDb;
        scope = "per-SNR";
    end
    score = scoreGain(selected);
    truth = squaredErrorGain(selected);
    correlation = finiteCorrelation(score, truth);
    entry = table(label, scope, snrDb, nnz(selected), ...
        mean(score), median(score), max(score), ...
        mean(truth), nnz(truth > 0), nnz(truth == 0), ...
        nnz(truth < 0), correlation, ...
        mean(abs(displacement(selected))), ...
        max(abs(displacement(selected))), ...
        mean(evaluations(selected)), nnz(converged(selected)), ...
        nnz(selectedSource(selected) == "continuous"), ...
        'VariableNames', {'refinement', 'scope', 'snrDb', 'n', ...
        'meanScoreGain', 'medianScoreGain', 'maximumScoreGain', ...
        'meanTruthSquaredErrorReduction', 'truthImproveCount', ...
        'truthTieCount', 'truthWorseCount', ...
        'scoreTruthPearsonCorrelation', 'meanAbsoluteDisplacementDeg', ...
        'maximumAbsoluteDisplacementDeg', 'meanFunctionEvaluations', ...
        'convergedCount', 'continuousSelectedCount'});
    output = [output; entry]; %#ok<AGROW>
end
end

function value = finiteCorrelation(first, second)
if std(first) == 0 || std(second) == 0
    value = nan;
else
    matrix = corrcoef(first, second);
    value = matrix(1, 2);
end
end

function gate = engineeringGate(summary, protocol)
gate = table();
for snrDb = unique(summary.snrDb).'
    pa = summary(summary.method == "P_A" & summary.snrDb == snrDb, :);
    a = summary(summary.method == "A_cont" & summary.snrDb == snrDb, :);
    angleRatio = a.angleMseDeg2/pa.angleMseDeg2;
    rangeRatio = a.rangeMseM2/pa.rangeMseM2;
    gate = [gate; gateRow("per-SNR-angle-MSE", snrDb, angleRatio, ...
        protocol.engineeringGate.maximumPerSnrAngleMseRatioToPA)]; %#ok<AGROW>
    gate = [gate; gateRow("per-SNR-range-MSE", snrDb, rangeRatio, ...
        protocol.engineeringGate.maximumPerSnrRangeMseRatioToPA)]; %#ok<AGROW>
end
paRows = summary(summary.method == "P_A", :);
aRows = summary(summary.method == "A_cont", :);
aggregateRatio = mean(aRows.angleMseDeg2)/mean(paRows.angleMseDeg2);
gate = [gate; gateRow("equal-SNR-aggregate-angle-MSE", nan, ...
    aggregateRatio, ...
    protocol.engineeringGate.maximumEqualSnrAggregateAngleMseRatioToPA)];
cRows = summary(summary.method == "C_enhanced", :);
runtimeRatio = mean(aRows.meanRuntimeSeconds) ...
    /mean(cRows.meanRuntimeSeconds);
gate = [gate; gateRow("mean-runtime", nan, runtimeRatio, ...
    protocol.engineeringGate.maximumRuntimeRatioToCEnhanced)];
end

function row = gateRow(name, snrDb, observed, limit)
row = table(name, snrDb, observed, limit, observed <= limit, ...
    'VariableNames', {'gate', 'snrDb', 'observedRatio', ...
    'maximumAllowedRatio', 'pass'});
end
