function result = r35SchemeATrial( ...
    cfg, scan, designRow, rowIndex, r34Protocol, schemeProtocol)
%R35SCHEMEATRIAL Run frozen baselines and Scheme A on one old user.

arguments
    cfg (1, 1) struct
    scan (1, 1) struct
    designRow (1, :) table
    rowIndex (1, 1) double {mustBeInteger, mustBePositive}
    r34Protocol (1, 1) struct = r34.config()
    schemeProtocol (1, 1) struct = r35SchemeAConfig()
end

result = failureResult(designRow, rowIndex);
try
    replay = fsjad.replayRound27Data(cfg, scan, designRow);
    if mod(rowIndex, 2) == 1
        order = "P_A-then-C_enhanced";
        pa = r34.estimate(cfg, replay.observation, replay.snapshots, ...
            scan, "P_A", r34Protocol);
        c = r34.estimate(cfg, replay.observation, replay.snapshots, ...
            scan, "C_enhanced", r34Protocol);
    else
        order = "C_enhanced-then-P_A";
        c = r34.estimate(cfg, replay.observation, replay.snapshots, ...
            scan, "C_enhanced", r34Protocol);
        pa = r34.estimate(cfg, replay.observation, replay.snapshots, ...
            scan, "P_A", r34Protocol);
    end

    aStage = pa.estimate.stages(end);
    aScore = @(thetaDeg) jad.localMusicLogScore( ...
        pa.musicCfg, pa.state, thetaDeg, pa.front.selected.rangeM);
    aRefinement = r35BracketedMusicRefinement(aScore, ...
        aStage.thetaGridDeg, aStage.selectedIndex, ...
        pa.estimate.score, schemeProtocol);

    cStage = c.estimate.stages(end);
    cScore = @(thetaDeg) jad.localMusicLogScore( ...
        c.musicCfg, c.state, thetaDeg, c.rangeM);
    cRefinement = r35BracketedMusicRefinement(cScore, ...
        cStage.thetaGridDeg, cStage.selectedThetaIndex, ...
        c.estimate.score, schemeProtocol);

    profileTimer = tic;
    aProfile = r33.profileAtAngle(cfg, replay.observation, scan, ...
        aRefinement.thetaContDeg, pa.front.selected.rangeM, ...
        r34Protocol.r33);
    aProfileSeconds = toc(profileTimer);

    aRuntimeSeconds = pa.cost.totalOnlineSeconds-pa.cost.profileSeconds ...
        +aRefinement.runtimeSeconds+aProfileSeconds;
    cContRuntimeSeconds = c.cost.totalOnlineSeconds ...
        +cRefinement.runtimeSeconds;
    aResponseCount = pa.cost.sparseResponseCalls ...
        +pa.cost.frontFullResponseCalls+aProfile.evaluationCount;
    cResponseCount = c.cost.sparseResponseCalls ...
        +c.cost.frontFullResponseCalls;

    result.success = aRefinement.status ~= "optimizer-exception" ...
        && cRefinement.status ~= "optimizer-exception";
    result.runtimeOrder = order;
    result.truthThetaDeg = designRow.truthThetaDeg;
    result.truthRangeM = designRow.truthRangeM;
    result.frontThetaDeg = pa.front.selected.thetaDeg;
    result.frontRangeM = pa.front.selected.rangeM;
    result.P_A = locationRecord(pa.thetaDeg, pa.rangeM, ...
        pa.cost.totalOnlineSeconds, pa.cost.sparseResponseCalls ...
        +pa.cost.frontFullResponseCalls+pa.cost.profileResponseCalls, ...
        pa.estimate.evaluationCount);
    result.C_enhanced = locationRecord(c.thetaDeg, c.rangeM, ...
        c.cost.totalOnlineSeconds, cResponseCount, ...
        c.estimate.evaluationCount);
    result.A_cont = locationRecord(aRefinement.thetaContDeg, ...
        aProfile.value, aRuntimeSeconds, aResponseCount, ...
        pa.estimate.evaluationCount+aRefinement.functionEvaluations);
    result.C_cont = locationRecord(cRefinement.thetaContDeg, c.rangeM, ...
        cContRuntimeSeconds, cResponseCount, ...
        c.estimate.evaluationCount+cRefinement.functionEvaluations);
    result.aRefinement = aRefinement;
    result.cRefinement = cRefinement;
    result.aProfile = compactProfile(aProfile, aProfileSeconds);
    result.aFinalGridDeg = aStage.thetaGridDeg;
    result.cFinalGridDeg = cStage.thetaGridDeg;
    result.aSolverAudit = pa.solverAudit;
    result.cSolverAudit = c.solverAudit;
catch exception
    result.success = false;
    result.errorIdentifier = string(exception.identifier);
    result.errorMessage = string(getReport( ...
        exception, "extended", "hyperlinks", "off"));
end
end

function output = locationRecord(thetaDeg, rangeM, runtimeSeconds, ...
    responseEvaluationCount, musicEvaluationCount)
output = struct(thetaDeg=thetaDeg, rangeM=rangeM, ...
    runtimeSeconds=runtimeSeconds, ...
    responseEvaluationCount=responseEvaluationCount, ...
    musicEvaluationCount=musicEvaluationCount);
end

function output = compactProfile(profile, runtimeSeconds)
output = struct(value=profile.value, score=profile.score, ...
    interval=profile.interval, evaluationCount=profile.evaluationCount, ...
    endpointHit=profile.endpointHit, runtimeSeconds=runtimeSeconds, ...
    version=profile.version, lambda=profile.lambda, ...
    coarseSpacingM=profile.coarseSpacingM, peakCount=profile.peakCount);
end

function result = failureResult(designRow, rowIndex)
result = struct(success=false, rowIndex=rowIndex, seed=designRow.seed, ...
    trialIndex=designRow.trialIndex, snrDb=designRow.snrDb, ...
    truthThetaDeg=designRow.truthThetaDeg, ...
    truthRangeM=designRow.truthRangeM, runtimeOrder="", ...
    errorIdentifier="", errorMessage="");
end
