function result = fromFront(cfg, observation, snapshots, scan, front, protocol)
%FROMFRONT Run hard and angle-marginal P_FA backends from one L06 front.

arguments
    cfg (1, 1) struct
    observation (:, 1) double {mustBeFinite}
    snapshots (:, :) double
    scan (1, 1) struct
    front (1, 1) struct
    protocol (1, 1) struct = r47.config()
end

timer = tic;
carrierIndex = r30.selectLocalCarriers(cfg.numSubcarriers, ...
    protocol.r45.pfa.carrierCount, front.peakCarrierIndex);
context = r38PrepareRawArrayVpmlContext(cfg, ...
    snapshots(:, carrierIndex+1), carrierIndex);
angle = r45.fullArrayAngle(cfg, context, front.selected, protocol.r45);
hard = r33.profileAtAngle(cfg, observation, scan, angle.thetaDeg, ...
    front.selected.rangeM, protocol.r45.r34.r33);
uncertainty = r47.angleUncertainty(cfg, context, angle.thetaDeg, ...
    front.selected.rangeM, protocol);

gh3Timer = tic;
gh3 = r47.marginalProfile(cfg, observation, scan, angle.thetaDeg, ...
    uncertainty.sigmaDeg, front.selected.rangeM, ...
    protocol.quadrature.GH3, protocol);
gh3Seconds = toc(gh3Timer);
gh5Timer = tic;
gh5 = r47.marginalProfile(cfg, observation, scan, angle.thetaDeg, ...
    uncertainty.sigmaDeg, front.selected.rangeM, ...
    protocol.quadrature.GH5, protocol);
gh5Seconds = toc(gh5Timer);

result = struct(version=protocol.version, thetaDeg=angle.thetaDeg, ...
    hardRangeM=hard.value, marginal3RangeM=gh3.value, ...
    marginal5RangeM=gh5.value, frontThetaDeg=front.selected.thetaDeg, ...
    frontRangeM=front.selected.rangeM, carrierIndex=carrierIndex, ...
    angle=angle, uncertainty=uncertainty, ...
    hardProfile=compactProfile(hard), ...
    marginal3Profile=compactProfile(gh3), ...
    marginal5Profile=compactProfile(gh5), ...
    marginal3Seconds=gh3Seconds, marginal5Seconds=gh5Seconds, ...
    totalBackendSeconds=toc(timer), ...
    hardProfileResponseEvaluations=hard.evaluationCount, ...
    marginal3ResponseEvaluations=gh3.qOnlyResponseEvaluations, ...
    marginal5ResponseEvaluations=gh5.qOnlyResponseEvaluations, ...
    musicEvaluationCount=0, evdCount=0);
end

function output = compactProfile(input)
output = struct(version=input.version, value=input.value, ...
    score=input.score, interval=input.interval, ...
    endpointHit=input.endpointHit, nearBoundary=input.nearBoundary, ...
    evaluationCount=input.evaluationCount, ...
    retentionMargin=input.retentionMargin);
if isfield(input, "sigmaThetaDeg")
    output.sigmaThetaDeg = input.sigmaThetaDeg;
    output.angleNodeDeg = input.angleNodeDeg;
    output.angleWeight = input.angleWeight;
    output.quadratureOrder = input.quadratureOrder;
    output.qOnlyResponseEvaluations = input.qOnlyResponseEvaluations;
end
end
