function output = summarize(design, results, protocol)
%SUMMARIZE Compare R47 candidates and apply the frozen pilot gate.

arguments
    design table
    results (:, 1) cell
    protocol (1, 1) struct = r47.config()
end

if numel(results) ~= height(design) || any(cellfun(@isempty, results)) ...
        || any(cellfun(@(item) ~item.success, results))
    error("r47:IncompletePilot", ...
        "R47 summary requires every new development row.");
end
perUser = design(:, ["positionId", "seed", "trialIndex", ...
    "snrDb", "truthThetaDeg", "truthRangeM"]);
methods = ["P_FA", "P_FAM3", "P_FAM5", ...
    "P_A", "G_schur", "C_enhanced"];
for method = methods
    theta = cellfun(@(item) item.(method).thetaDeg, results);
    rangeM = cellfun(@(item) item.(method).rangeM, results);
    perUser.("theta_"+method) = theta;
    perUser.("range_"+method) = rangeM;
    perUser.("angleError_"+method) = theta-perUser.truthThetaDeg;
    perUser.("rangeError_"+method) = rangeM-perUser.truthRangeM;
end
perUser.sigmaThetaDeg = cellfun( ...
    @(item) item.backend.uncertainty.sigmaDeg, results);
perUser.validAngleCurvature = cellfun( ...
    @(item) item.backend.uncertainty.validCurvature, results);
perUser.hardEndpointHit = cellfun( ...
    @(item) item.backend.hardProfile.endpointHit, results);
perUser.marginal3EndpointHit = cellfun( ...
    @(item) item.backend.marginal3Profile.endpointHit, results);
perUser.marginal5EndpointHit = cellfun( ...
    @(item) item.backend.marginal5Profile.endpointHit, results);
perUser.marginal3Responses = cellfun( ...
    @(item) item.backend.marginal3ResponseEvaluations, results);
perUser.marginal5Responses = cellfun( ...
    @(item) item.backend.marginal5ResponseEvaluations, results);
perUser.marginal3Seconds = cellfun( ...
    @(item) item.backend.marginal3Seconds, results);
perUser.marginal5Seconds = cellfun( ...
    @(item) item.backend.marginal5Seconds, results);

methodSummary = table();
for method = methods
    for snr = protocol.design.snrDb
        selected = perUser.snrDb == snr;
        ae = perUser.("angleError_"+method)(selected);
        re = perUser.("rangeError_"+method)(selected);
        methodSummary = [methodSummary; table(method, snr, nnz(selected), ...
            mean(ae.^2), sqrt(mean(ae.^2)), ...
            mean(re.^2), sqrt(mean(re.^2)), ...
            median(abs(re)), quantile(abs(re), .95), ...
            'VariableNames', {'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', 'rangeMseM2', ...
            'rangeRmseM', 'rangeMedianAbsM', 'rangeP95AbsM'})]; %#ok<AGROW>
    end
end

comparison = table();
for candidate = ["P_FAM3", "P_FAM5"]
    for reference = ["P_A", "P_FA"]
        comparison = [comparison; compareRange( ...
            perUser, candidate, reference, protocol.design.snrDb)]; %#ok<AGROW>
    end
end
selection = selectCandidate(perUser, comparison, protocol);
diagnostics = table(height(perUser), ...
    mean(perUser.validAngleCurvature), ...
    min(perUser.sigmaThetaDeg), median(perUser.sigmaThetaDeg), ...
    max(perUser.sigmaThetaDeg), sum(perUser.hardEndpointHit), ...
    sum(perUser.marginal3EndpointHit), ...
    sum(perUser.marginal5EndpointHit), ...
    mean(perUser.marginal3Responses), ...
    mean(perUser.marginal5Responses), ...
    mean(perUser.marginal3Seconds), mean(perUser.marginal5Seconds), ...
    'VariableNames', {'n', 'validAngleCurvatureRate', ...
    'minimumSigmaThetaDeg', 'medianSigmaThetaDeg', ...
    'maximumSigmaThetaDeg', 'hardEndpointHits', ...
    'marginal3EndpointHits', 'marginal5EndpointHits', ...
    'meanMarginal3Responses', 'meanMarginal5Responses', ...
    'meanMarginal3Seconds', 'meanMarginal5Seconds'});
output = struct(version="R47-PFA-marginal-pilot-summary-v1", ...
    perUser=perUser, methodSummary=methodSummary, comparison=comparison, ...
    selection=selection, diagnostics=diagnostics, ...
    pilotPass=selection.pass);
end

function output = compareRange(perUser, candidate, reference, snrValues)
output = table();
candidateMse = zeros(numel(snrValues), 1);
referenceMse = zeros(numel(snrValues), 1);
for index = 1:numel(snrValues)
    snr = snrValues(index);
    selected = perUser.snrDb == snr;
    c = perUser.("rangeError_"+candidate)(selected).^2;
    r = perUser.("rangeError_"+reference)(selected).^2;
    candidateMse(index) = mean(c);
    referenceMse(index) = mean(r);
    output = [output; rangeRow(candidate, reference, "per-SNR", ...
        snr, c, r)]; %#ok<AGROW>
end
allC = perUser.("rangeError_"+candidate).^2;
allR = perUser.("rangeError_"+reference).^2;
ratio = mean(candidateMse)/mean(referenceMse);
output = [output; table(candidate, reference, "equal-SNR", nan, ...
    height(perUser), mean(candidateMse), mean(referenceMse), ratio, ...
    100*(1-sqrt(ratio)), nnz(allC < allR), nnz(allC == allR), ...
    nnz(allC > allR), 'VariableNames', output.Properties.VariableNames)];
end

function row = rangeRow(candidate, reference, scope, snrDb, c, r)
ratio = mean(c)/mean(r);
row = table(candidate, reference, scope, snrDb, numel(c), ...
    mean(c), mean(r), ratio, 100*(1-sqrt(ratio)), ...
    nnz(c < r), nnz(c == r), nnz(c > r), ...
    'VariableNames', {'candidate', 'reference', 'scope', 'snrDb', ...
    'n', 'candidateMse', 'referenceMse', 'mseRatio', ...
    'rmseImprovementPct', 'winCount', 'tieCount', 'lossCount'});
end

function selection = selectCandidate(perUser, comparison, protocol)
candidates = ["P_FAM3"; "P_FAM5"];
maximumPerSnrRatio = zeros(2, 1);
aggregateRatio = zeros(2, 1);
angleIdentity = false(2, 1);
for index = 1:2
    rows = comparison(comparison.candidate == candidates(index) ...
        & comparison.reference == "P_A", :);
    maximumPerSnrRatio(index) = max(rows.mseRatio(rows.scope == "per-SNR"));
    aggregateRatio(index) = rows.mseRatio(rows.scope == "equal-SNR");
    angleIdentity(index) = all(perUser.("theta_"+candidates(index)) ...
        == perUser.theta_P_FA);
end
[~, order] = sortrows([maximumPerSnrRatio, aggregateRatio], [1, 2]);
selected = candidates(order(1));
selectedIndex = order(1);
pass = maximumPerSnrRatio(selectedIndex) ...
    <= protocol.selection.maximumPerSnrRangeRatio ...
    && aggregateRatio(selectedIndex) ...
    <= protocol.selection.maximumAggregateRangeRatio ...
    && angleIdentity(selectedIndex);
summary = table(candidates, maximumPerSnrRatio, aggregateRatio, ...
    angleIdentity, candidates == selected, ...
    maximumPerSnrRatio <= protocol.selection.maximumPerSnrRangeRatio ...
    & aggregateRatio <= protocol.selection.maximumAggregateRangeRatio ...
    & angleIdentity, 'VariableNames', {'candidate', ...
    'maximumPerSnrRangeRatioToPA', 'aggregateRangeRatioToPA', ...
    'angleIdentityToPFA', 'selected', 'pass'});
summary.pass = summary.pass & (candidates == selected);
selection = struct(summary=summary, selected=selected, pass=pass);
end
