function result = r37ImplicitProfileTransport(cfg, scan, observation, ...
    thetaBaseDeg, rangeBaseM, thetaNewDeg, centerRangeM, protocol)
%R37IMPLICITPROFILETRANSPORT Move one profile optimum without a new search.

arguments
    cfg (1, 1) struct
    scan (1, 1) struct
    observation (:, 1) double {mustBeFinite}
    thetaBaseDeg (1, 1) double {mustBeFinite}
    rangeBaseM (1, 1) double {mustBeFinite, mustBePositive}
    thetaNewDeg (1, 1) double {mustBeFinite}
    centerRangeM (1, 1) double {mustBeFinite, mustBePositive}
    protocol (1, 1) struct = r37SingleProfileProtocol()
end

timer = tic;
profileProtocol = protocol.profile;
boundsM = [max(cfg.rangeLimitsM(1), ...
    centerRangeM-profileProtocol.halfWidthM), ...
    min(cfg.rangeLimitsM(2), ...
    centerRangeM+profileProtocol.halfWidthM)];
if rangeBaseM < boundsM(1)-profileProtocol.endpointToleranceM ...
        || rangeBaseM > boundsM(2)+profileProtocol.endpointToleranceM
    error("r37:BaseRangeOutsideFrozenProfile", ...
        "The P_A range is outside the original frozen profile bounds.");
end

context = r33.prepareResponseContext(cfg, scan, observation);
derivatives = r37ExactProfileLogDerivatives( ...
    cfg, deg2rad(thetaBaseDeg), rangeBaseM, context);
deltaThetaRad = deg2rad(thetaNewDeg-thetaBaseDeg);
rangeGradient = derivatives.gradient(2);
rangeCurvature = derivatives.hessian(2, 2);
mixedCurvature = derivatives.hessian(2, 1);
curvatureTolerance = profileProtocol.curvatureScaleTolerance ...
    *max(abs(rangeCurvature), 1);
endpointHit = rangeBaseM <= boundsM(1) ...
    +profileProtocol.endpointToleranceM ...
    || rangeBaseM >= boundsM(2)-profileProtocol.endpointToleranceM;
validCurvature = derivatives.valid ...
    && rangeCurvature < -curvatureTolerance;
validTransport = validCurvature && ~endpointHit;

rawDisplacementM = 0;
transportedRangeM = rangeBaseM;
clippedToBounds = false;
if validTransport
    rawDisplacementM = -(rangeGradient ...
        +mixedCurvature*deltaThetaRad)/rangeCurvature;
    rawRangeM = rangeBaseM+rawDisplacementM;
    transportedRangeM = min(max(rawRangeM, boundsM(1)), boundsM(2));
    clippedToBounds = transportedRangeM ~= rawRangeM;
else
    rawRangeM = rangeBaseM;
end

scoreRetained = r33.fixedAngleProfileLogScore( ...
    cfg, thetaNewDeg, rangeBaseM, context);
scoreTransported = r33.fixedAngleProfileLogScore( ...
    cfg, thetaNewDeg, transportedRangeM, context);
useTransported = validTransport ...
    && scoreTransported > scoreRetained+profileProtocol.scoreTolerance;
if useTransported
    rangeM = transportedRangeM;
    selectedScore = scoreTransported;
    selectedSource = "implicit-transport";
    status = "completed-transport-selected";
elseif validTransport
    rangeM = rangeBaseM;
    selectedScore = scoreRetained;
    selectedSource = "P_A-retained";
    status = "completed-retained-higher-score";
elseif endpointHit
    rangeM = rangeBaseM;
    selectedScore = scoreRetained;
    selectedSource = "P_A-retained";
    status = "profile-endpoint-retained";
else
    rangeM = rangeBaseM;
    selectedScore = scoreRetained;
    selectedSource = "P_A-retained";
    status = "invalid-curvature-retained";
end

result = struct(version=protocol.version, thetaBaseDeg=thetaBaseDeg, ...
    thetaDeg=thetaNewDeg, rangeBaseM=rangeBaseM, rangeM=rangeM, ...
    centerRangeM=centerRangeM, boundsM=boundsM, ...
    deltaThetaRad=deltaThetaRad, ...
    rangeGradient=rangeGradient, rangeCurvature=rangeCurvature, ...
    mixedCurvature=mixedCurvature, ...
    rawRangeM=rawRangeM, transportedRangeM=transportedRangeM, ...
    rawDisplacementM=rawDisplacementM, ...
    selectedDisplacementM=rangeM-rangeBaseM, ...
    clippedToBounds=clippedToBounds, endpointHit=endpointHit, ...
    validCurvature=validCurvature, validTransport=validTransport, ...
    scoreRetained=scoreRetained, scoreTransported=scoreTransported, ...
    selectedScore=selectedScore, scoreGain=selectedScore-scoreRetained, ...
    selectedSource=selectedSource, status=status, ...
    completeProfilePassCount=1, newCompleteProfilePassCount=0, ...
    derivativeResponseEvaluationCount=1, ...
    candidateResponseEvaluationCount=2, ...
    addedResponseEvaluationCount=3, ...
    derivatives=compactDerivatives(derivatives), ...
    runtimeSeconds=toc(timer));
end

function output = compactDerivatives(input)
output = struct(version=input.version, score=input.score, ...
    logScore=input.logScore, gradient=input.gradient, ...
    hessian=input.hessian, valid=input.valid, ...
    responseEvaluationCount=input.responseEvaluationCount);
end
