function output = r37SummarizeSingleProfile( ...
    design, baselineResults, transportResults, developmentMask, protocol)
%R37SUMMARIZESINGLEPROFILE Summarize fixed R37 populations and gates.

arguments
    design table
    baselineResults cell
    transportResults cell
    developmentMask (:, 1) logical
    protocol (1, 1) struct = r37SingleProfileProtocol()
end

if numel(baselineResults) ~= height(design) ...
        || numel(transportResults) ~= height(design) ...
        || any(cellfun(@isempty, transportResults)) ...
        || any(cellfun(@(x) ~x.success, baselineResults)) ...
        || any(cellfun(@(x) ~x.success, transportResults))
    error("r37:IncompleteSingleProfileResults", ...
        "R37 requires every frozen baseline and transport row.");
end
if nnz(developmentMask) ~= protocol.input.developmentOverlapUsers
    error("r37:DevelopmentMaskMismatch", ...
        "R37 requires the fixed 60-row development overlap.");
end

perUser = buildPerUser(design, baselineResults, transportResults);
perUser.subset = repmat("holdout540", height(perUser), 1);
perUser.subset(developmentMask) = "development-overlap60";
all600 = populationSummary(perUser, protocol, "all600");
holdout540 = populationSummary( ...
    perUser(~developmentMask, :), protocol, "holdout540");
development60 = populationSummary( ...
    perUser(developmentMask, :), protocol, "development-overlap60");
gate = [all600.gate; holdout540.gate];
decision = table(all(all600.gate.pass), all(holdout540.gate.pass), ...
    all(gate.pass), 'VariableNames', {'all600GatePassed', ...
    'holdout540GatePassed', 'r37EngineeringPassed'});
output = struct(version="R37-single-profile-summary-v1", ...
    dataRole=protocol.evidenceRole, perUser=perUser, all600=all600, ...
    holdout540=holdout540, developmentOverlap60=development60, ...
    gate=gate, decision=decision, ...
    engineeringPassed=decision.r37EngineeringPassed);
end

function perUser = buildPerUser(design, baseline, transport)
thetaPA = cellfun(@(x) x.P_A.thetaDeg, baseline);
rangePA = cellfun(@(x) x.P_A.rangeM, baseline);
thetaFull = cellfun(@(x) x.E_one_step.thetaDeg, baseline);
rangeFull = cellfun(@(x) x.E_one_step.rangeM, baseline);
thetaSingle = cellfun(@(x) x.transport.thetaDeg, transport);
rangeSingle = cellfun(@(x) x.transport.rangeM, transport);
paRuntime = cellfun(@(x) x.P_A.runtimeSeconds, baseline);
refinementSeconds = cellfun( ...
    @(x) x.E_one_step.refinementSeconds, baseline);
secondProfileSeconds = cellfun( ...
    @(x) x.E_one_step.profileSeconds, baseline);
transportSeconds = cellfun(@(x) x.transport.runtimeSeconds, transport);
fullRuntime = paRuntime+refinementSeconds+secondProfileSeconds;
singleRuntime = paRuntime+refinementSeconds+transportSeconds;
paResponse = cellfun(@(x) x.P_A.responseEvaluationCount, baseline);
reportedFullResponse = cellfun( ...
    @(x) x.E_one_step.responseEvaluationCount, baseline);
secondProfileEvaluations = cellfun( ...
    @(x) x.profile.evaluationCount, baseline);
baseResponse = reportedFullResponse-secondProfileEvaluations;
firstProfileEvaluations = paResponse-baseResponse;
fullResponse = paResponse+secondProfileEvaluations;
singleResponse = paResponse+cellfun( ...
    @(x) x.transport.addedResponseEvaluationCount, transport);

perUser = table(design.seed, design.trialIndex, design.snrDb, ...
    design.truthThetaDeg, design.truthRangeM, thetaPA, rangePA, ...
    thetaFull, rangeFull, thetaSingle, rangeSingle, ...
    cellfun(@(x) x.C_enhanced.thetaDeg, baseline), ...
    cellfun(@(x) x.C_enhanced.rangeM, baseline), ...
    paRuntime, fullRuntime, singleRuntime, ...
    cellfun(@(x) x.C_enhanced.runtimeSeconds, baseline), ...
    refinementSeconds, secondProfileSeconds, transportSeconds, ...
    paResponse, fullResponse, singleResponse, ...
    cellfun(@(x) x.C_enhanced.responseEvaluationCount, baseline), ...
    cellfun(@(x) x.P_A.musicEvaluationCount, baseline), ...
    cellfun(@(x) x.E_one_step.musicEvaluationCount, baseline), ...
    cellfun(@(x) x.E_one_step.musicEvaluationCount, baseline), ...
    cellfun(@(x) x.C_enhanced.musicEvaluationCount, baseline), ...
    cellfun(@(x) x.P_A.evdCount, baseline), ...
    cellfun(@(x) x.E_one_step.evdCount, baseline), ...
    cellfun(@(x) x.E_one_step.evdCount, baseline), ...
    cellfun(@(x) x.C_enhanced.evdCount, baseline), ...
    ones(height(design), 1), 2*ones(height(design), 1), ...
    ones(height(design), 1), firstProfileEvaluations, ...
    firstProfileEvaluations+secondProfileEvaluations, ...
    firstProfileEvaluations, ...
    cellfun(@(x) x.transport.rawDisplacementM, transport), ...
    cellfun(@(x) x.transport.selectedDisplacementM, transport), ...
    cellfun(@(x) x.transport.rangeCurvature, transport), ...
    cellfun(@(x) x.transport.mixedCurvature, transport), ...
    cellfun(@(x) x.transport.scoreGain, transport), ...
    cellfun(@(x) x.transport.validTransport, transport), ...
    cellfun(@(x) x.transport.clippedToBounds, transport), ...
    cellfun(@(x) x.transport.endpointHit, transport), ...
    string(cellfun(@(x) x.transport.selectedSource, ...
    transport, UniformOutput=false)), ...
    string(cellfun(@(x) x.transport.status, ...
    transport, UniformOutput=false)), rangeSingle-rangeFull, ...
    'VariableNames', {'seed', 'trialIndex', 'snrDb', ...
    'truthThetaDeg', 'truthRangeM', 'theta_P_A', 'range_P_A', ...
    'theta_E_full', 'range_E_full', 'theta_E_single', ...
    'range_E_single', 'theta_C_enhanced', 'range_C_enhanced', ...
    'runtime_P_A', 'runtime_E_full', 'runtime_E_single', ...
    'runtime_C_enhanced', 'refinementSeconds', ...
    'secondProfileSeconds', 'transportSeconds', ...
    'responseCount_P_A', 'responseCount_E_full', ...
    'responseCount_E_single', 'responseCount_C_enhanced', ...
    'musicCount_P_A', 'musicCount_E_full', ...
    'musicCount_E_single', 'musicCount_C_enhanced', ...
    'evdCount_P_A', 'evdCount_E_full', 'evdCount_E_single', ...
    'evdCount_C_enhanced', 'profilePasses_P_A', ...
    'profilePasses_E_full', 'profilePasses_E_single', ...
    'profileEvaluations_P_A', 'profileEvaluations_E_full', ...
    'profileEvaluations_E_single', 'rawTransportDisplacementM', ...
    'selectedTransportDisplacementM', 'rangeCurvature', ...
    'mixedCurvature', 'transportScoreGain', 'validTransport', ...
    'clippedToBounds', 'endpointHit', 'selectedSource', 'status', ...
    'singleMinusFullRangeM'});
end

function output = populationSummary(perUser, protocol, population)
methodSummary = summarizeMethods(perUser);
angleComparisons = [pairedAngle(perUser, "E_single_profile", ...
    "P_A"); pairedAngle(perUser, "E_single_profile", "Scheme_E_full")];
rangeComparisons = pairedRange(perUser);
diagnostics = summarizeTransport(perUser);
gate = engineeringGate(perUser, methodSummary, protocol, population);
output = struct(population=population, perUser=perUser, ...
    methodSummary=methodSummary, angleComparisons=angleComparisons, ...
    rangeComparisons=rangeComparisons, diagnostics=diagnostics, ...
    gate=gate, gatePassed=all(gate.pass));
end

function output = summarizeMethods(perUser)
methods = ["P_A", "Scheme_E_full", "E_single_profile", "C_enhanced"];
output = table();
for method = methods
    [theta, rangeM, runtime, response, music, evd, passes, evaluations] = ...
        methodColumns(perUser, method);
    for snrDb = unique(perUser.snrDb).'
        selected = perUser.snrDb == snrDb;
        angleError = theta(selected)-perUser.truthThetaDeg(selected);
        rangeError = rangeM(selected)-perUser.truthRangeM(selected);
        positionError = positionErrorM(theta(selected), rangeM(selected), ...
            perUser.truthThetaDeg(selected), perUser.truthRangeM(selected));
        angleSquared = angleError.^2;
        rangeSquared = rangeError.^2;
        entry = table(method, snrDb, nnz(selected), mean(angleSquared), ...
            sqrt(mean(angleSquared)), median(abs(angleError)), ...
            quantile(abs(angleError), 0.90), ...
            quantile(abs(angleError), 0.95), mean(rangeSquared), ...
            sqrt(mean(rangeSquared)), sqrt(mean(positionError.^2)), ...
            mean(runtime(selected)), mean(response(selected)), ...
            mean(music(selected)), mean(evd(selected)), ...
            mean(passes(selected)), mean(evaluations(selected)), ...
            'VariableNames', {'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', ...
            'angleMedianAbsoluteErrorDeg', 'angleP90AbsoluteErrorDeg', ...
            'angleP95AbsoluteErrorDeg', 'rangeMseM2', 'rangeRmseM', ...
            'positionRmseM', 'meanRuntimeSeconds', ...
            'meanResponseEvaluationCount', 'meanMusicEvaluationCount', ...
            'meanEvdCount', 'meanCompleteProfilePassCount', ...
            'meanProfileEvaluationCount'});
        output = [output; entry]; %#ok<AGROW>
    end
end
end

function [theta, rangeM, runtime, response, music, evd, passes, evals] = ...
    methodColumns(input, method)
suffix = containers.Map( ...
    ["P_A", "Scheme_E_full", "E_single_profile", "C_enhanced"], ...
    ["P_A", "E_full", "E_single", "C_enhanced"]);
name = suffix(method);
theta = input.("theta_"+name);
rangeM = input.("range_"+name);
runtime = input.("runtime_"+name);
response = input.("responseCount_"+name);
music = input.("musicCount_"+name);
evd = input.("evdCount_"+name);
if method == "C_enhanced"
    passes = nan(height(input), 1);
    evals = nan(height(input), 1);
else
    passes = input.("profilePasses_"+name);
    evals = input.("profileEvaluations_"+name);
end
end

function output = pairedAngle(perUser, candidate, reference)
[candidateTheta, ~, ~, ~, ~, ~, ~, ~] = ...
    methodColumns(perUser, candidate);
[referenceTheta, ~, ~, ~, ~, ~, ~, ~] = ...
    methodColumns(perUser, reference);
output = table();
candidateMse = zeros(3, 1);
referenceMse = zeros(3, 1);
allDifference = zeros(0, 1);
snrValues = unique(perUser.snrDb).';
for index = 1:numel(snrValues)
    selected = perUser.snrDb == snrValues(index);
    candidateSquared = (candidateTheta(selected) ...
        -perUser.truthThetaDeg(selected)).^2;
    referenceSquared = (referenceTheta(selected) ...
        -perUser.truthThetaDeg(selected)).^2;
    difference = candidateSquared-referenceSquared;
    candidateMse(index) = mean(candidateSquared);
    referenceMse(index) = mean(referenceSquared);
    output = [output; comparisonRow(candidate, reference, "per-SNR", ...
        snrValues(index), difference, candidateMse(index), ...
        referenceMse(index))]; %#ok<AGROW>
    allDifference = [allDifference; difference]; %#ok<AGROW>
end
output = [output; comparisonRow(candidate, reference, "equal-SNR", ...
    nan, allDifference, mean(candidateMse), mean(referenceMse))];
end

function row = comparisonRow(candidate, reference, scope, snrDb, ...
    difference, candidateMse, referenceMse)
ratio = candidateMse/referenceMse;
row = table(candidate, reference, scope, snrDb, numel(difference), ...
    candidateMse, referenceMse, ratio, 100*(1-sqrt(ratio)), ...
    mean(difference), nnz(difference < 0), nnz(difference == 0), ...
    nnz(difference > 0), 'VariableNames', {'candidate', 'reference', ...
    'scope', 'snrDb', 'n', 'candidateAngleMseDeg2', ...
    'referenceAngleMseDeg2', 'angleMseRatio', ...
    'angleRmseImprovementPercent', ...
    'meanCandidateMinusReferenceSquaredError', 'winCount', ...
    'tieCount', 'lossCount'});
end

function output = pairedRange(perUser)
output = table();
for snrDb = unique(perUser.snrDb).'
    selected = perUser.snrDb == snrDb;
    paMse = mean((perUser.range_P_A(selected) ...
        -perUser.truthRangeM(selected)).^2);
    fullMse = mean((perUser.range_E_full(selected) ...
        -perUser.truthRangeM(selected)).^2);
    singleMse = mean((perUser.range_E_single(selected) ...
        -perUser.truthRangeM(selected)).^2);
    output = [output; table(snrDb, nnz(selected), paMse, fullMse, ...
        singleMse, singleMse/paMse, singleMse/fullMse, ...
        'VariableNames', {'snrDb', 'n', 'rangeMsePA', ...
        'rangeMseSchemeEFull', 'rangeMseSingleProfile', ...
        'singleToPARatio', 'singleToFullSchemeERatio'})]; %#ok<AGROW>
end
end

function output = summarizeTransport(perUser)
output = table();
snrValues = [unique(perUser.snrDb).', nan];
for snrDb = snrValues
    if isnan(snrDb)
        selected = true(height(perUser), 1);
        scope = "all-SNR";
    else
        selected = perUser.snrDb == snrDb;
        scope = "per-SNR";
    end
    difference = abs(perUser.singleMinusFullRangeM(selected));
    output = [output; table(scope, snrDb, nnz(selected), ...
        nnz(perUser.validTransport(selected)), ...
        nnz(perUser.selectedSource(selected) == "implicit-transport"), ...
        nnz(perUser.clippedToBounds(selected)), ...
        nnz(perUser.endpointHit(selected)), ...
        mean(abs(perUser.rawTransportDisplacementM(selected))), ...
        mean(abs(perUser.selectedTransportDisplacementM(selected))), ...
        max(abs(perUser.selectedTransportDisplacementM(selected))), ...
        nnz(perUser.transportScoreGain(selected) > 0), ...
        mean(perUser.transportScoreGain(selected)), mean(difference), ...
        quantile(difference, 0.95), max(difference), ...
        'VariableNames', {'scope', 'snrDb', 'n', ...
        'validTransportCount', 'transportSelectedCount', ...
        'boundsClippedCount', 'endpointRetainedCount', ...
        'meanAbsoluteRawTransportM', ...
        'meanAbsoluteSelectedTransportM', ...
        'maximumAbsoluteSelectedTransportM', ...
        'positiveScoreGainCount', 'meanScoreGain', ...
        'meanAbsoluteDifferenceFromFullProfileM', ...
        'p95AbsoluteDifferenceFromFullProfileM', ...
        'maximumAbsoluteDifferenceFromFullProfileM'})]; %#ok<AGROW>
end
end

function gate = engineeringGate(perUser, summary, protocol, population)
gate = table();
for snrDb = unique(perUser.snrDb).'
    pa = summary(summary.method == "P_A" & summary.snrDb == snrDb, :);
    single = summary(summary.method == "E_single_profile" ...
        & summary.snrDb == snrDb, :);
    gate = [gate; gateRow(population, "angle", ...
        "per-SNR-angle-MSE", snrDb, ...
        single.angleMseDeg2/pa.angleMseDeg2, ...
        protocol.gate.maximumPerSnrAngleMseRatio, "<=")]; %#ok<AGROW>
end
pa = summary(summary.method == "P_A", :);
single = summary(summary.method == "E_single_profile", :);
gate = [gate; gateRow(population, "angle", ...
    "equal-SNR-aggregate-angle-MSE", nan, ...
    mean(single.angleMseDeg2)/mean(pa.angleMseDeg2), ...
    protocol.gate.maximumEqualSnrAngleMseRatio, "<=")];
for snrDb = unique(perUser.snrDb).'
    paRow = pa(pa.snrDb == snrDb, :);
    singleRow = single(single.snrDb == snrDb, :);
    gate = [gate; gateRow(population, "range", ...
        "per-SNR-range-MSE", snrDb, ...
        singleRow.rangeMseM2/paRow.rangeMseM2, ...
        protocol.gate.maximumPerSnrRangeMseRatio, "<=")]; %#ok<AGROW>
end
meanSingleRuntime = mean(perUser.runtime_E_single);
gate = [gate; gateRow(population, "runtime", "runtime-to-C", nan, ...
    meanSingleRuntime/mean(perUser.runtime_C_enhanced), ...
    protocol.gate.maximumRuntimeRatioToCEnhanced, "<=")];
gate = [gate; gateRow(population, "runtime", "runtime-to-P_A", nan, ...
    meanSingleRuntime/mean(perUser.runtime_P_A), ...
    protocol.gate.maximumRuntimeRatioToPA, "<=")];
gate = [gate; gateRow(population, "runtime", ...
    "runtime-below-full-Scheme-E", nan, ...
    meanSingleRuntime/mean(perUser.runtime_E_full), 1, "<")];
angleDifference = max(abs(perUser.theta_E_single ...
    -perUser.theta_E_full));
gate = [gate; gateRow(population, "identity", ...
    "frozen-Scheme-E-angle", nan, angleDifference, ...
    protocol.angle.thetaToleranceDeg, "<=")];
profileDeviation = max(abs(perUser.profilePasses_E_single ...
    -protocol.gate.requiredCompleteProfilePasses));
gate = [gate; gateRow(population, "identity", ...
    "one-complete-profile", nan, profileDeviation, 0, "<=")];
end

function row = gateRow(population, category, name, snrDb, observed, ...
    limit, relation)
if relation == "<"
    pass = observed < limit;
else
    pass = observed <= limit;
end
row = table(population, category, name, snrDb, observed, limit, ...
    relation, pass, 'VariableNames', {'population', 'category', ...
    'gate', 'snrDb', 'observed', 'limit', 'relation', 'pass'});
end

function value = positionErrorM(theta, rangeM, truthTheta, truthRange)
xError = rangeM.*sind(theta)-truthRange.*sind(truthTheta);
yError = rangeM.*cosd(theta)-truthRange.*cosd(truthTheta);
value = hypot(xError, yError);
end
