function protocol = r37SingleProfileProtocol()
%R37SINGLEPROFILEPROTOCOL Freeze the implicit profile transport study.

protocol.version = "R37-schemeE-single-profile-implicit-transport-v1";
protocol.date = "2026-09-13";
protocol.evidenceRole = ...
    "retrospective-post-calibration-engineering-not-independent-validation";
protocol.studyLabel = ...
    "Retrospective calibration engineering study - not R34 final validation";
protocol.input = struct( ...
    r36ResultSha256= ...
    "f998fc2258210c13ef98345ea04b4637c7d93b762795fc575c8da92a200bb446", ...
    r36AlgorithmDigest= ...
    "27879e532e1ffefa1223a7a2ed56a6845ade09ed97e98f58ed56851436ba5908", ...
    calibrationDataDigest= ...
    "39538d66a6724e198d9c569c2f9e24b9185c4d3d979bc4f224724fbf5d50dcc0", ...
    allUsers=600, developmentOverlapUsers=60, holdoutUsers=540, ...
    usersPerSnr=200, holdoutUsersPerSnr=180, snrDb=[-10, 0, 20]);
protocol.angle = struct(source="frozen-R36-Scheme-E", ...
    thetaToleranceDeg=1e-12, allowReestimation=false, ...
    allowModification=false);
protocol.profile = struct(objective="exact-q-only-log-profile-score", ...
    originalCompleteProfilePasses=1, newCompleteProfilePasses=0, ...
    totalCompleteProfilePasses=1, halfWidthM=2, lambda=1, ...
    derivativeAngleUnit="radian", derivativeRangeUnit="meter", ...
    transportFormula="-(J_r+J_rtheta*delta_theta)/J_rr", ...
    derivativeResponseEvaluations=1, candidateResponseEvaluations=2, ...
    candidateRule="max-of-retained-rP-and-transported-range", ...
    invalidPolicy="retain-rP", endpointPolicy="retain-rP", ...
    curvatureScaleTolerance=100*eps, endpointToleranceM=1e-7, ...
    scoreTolerance=1e-12, optimizer="none");
protocol.gate = struct(maximumPerSnrAngleMseRatio=1.01, ...
    maximumEqualSnrAngleMseRatio=0.98, ...
    maximumPerSnrRangeMseRatio=1.02, ...
    maximumRuntimeRatioToCEnhanced=1.00, ...
    maximumRuntimeRatioToPA=1.02, ...
    requireRuntimeBelowFullSchemeE=true, ...
    requiredCompleteProfilePasses=1, ...
    requireAll600AndHoldout540=true);
protocol.execution = struct(deterministicReplayOnly=true, ...
    newUsersAllowed=false, r34FinalAuthorized=false, ...
    schemeBOrDAuthorized=false, parameterTuningAuthorized=false);
end
