function decision = evaluateControlThresholds(summary, baseline, protocol)
%EVALUATECONTROLTHRESHOLDS Apply the unchanged Round30 engineering limits.

arguments
    summary table
    baseline table
    protocol (1, 1) struct
end

decision = table();
for method = unique(summary.method, "stable").'
    maximumAngleRatio = 0;
    maximumRangeRatio = 0;
    maximumPositionRatio = 0;
    maximumP95Ratio = 0;
    maximumMissIncrease = 0;
    for snrDb = [-10, 0, 20]
        row = summary(summary.method == method & summary.snrDb == snrDb, :);
        c = baseline(baseline.method == "C_star" ...
            & baseline.snrDb == snrDb, :);
        h = baseline(baseline.method == "H_star" ...
            & baseline.snrDb == snrDb, :);
        maximumAngleRatio = max(maximumAngleRatio, ...
            row.angleRmseDeg/c.angleRmseDeg);
        maximumRangeRatio = max(maximumRangeRatio, ...
            row.rangeRmseM/min(c.rmseM, h.rmseM));
        maximumPositionRatio = max(maximumPositionRatio, ...
            row.positionRmseM/min(c.jointRmseM, h.jointRmseM));
        maximumP95Ratio = max(maximumP95Ratio, ...
            row.p95RangeM/min(c.p95M, h.p95M));
        maximumMissIncrease = max(maximumMissIncrease, ...
            row.missOver1m-min(c.missOver1m, h.missOver1m));
    end
    anglePass = maximumAngleRatio <= protocol.acceptance.angleRmseRatio;
    allAccuracyPass = anglePass ...
        && maximumRangeRatio <= protocol.acceptance.rangeRmseRatio ...
        && maximumPositionRatio <= protocol.acceptance.positionRmseRatio ...
        && maximumP95Ratio <= protocol.acceptance.p95Ratio ...
        && maximumMissIncrease <= protocol.acceptance.missRateIncrease;
    entry = table(method, maximumAngleRatio, maximumRangeRatio, ...
        maximumPositionRatio, maximumP95Ratio, maximumMissIncrease, ...
        anglePass, allAccuracyPass, ...
        'VariableNames', {'method', 'maximumAngleRatio', ...
        'maximumRangeRatio', 'maximumPositionRatio', 'maximumP95Ratio', ...
        'maximumMissIncrease', 'anglePass', 'allAccuracyPass'});
    decision = [decision; entry]; %#ok<AGROW>
end
end
