function summary = reviseRound30Summary(design, rowResults, candidates, protocol)
%REVISEROUND30SUMMARY Separate F, H, and P deployment costs and diagnostics.

arguments
    design table
    rowResults cell
    candidates table
    protocol (1, 1) struct
end

methodNames = ["F_L", "H_L", "P_L"];
summary = table();
for candidateIndex = 1:height(candidates)
    extracted = extractCandidate(design, rowResults, candidateIndex, protocol);
    for snrDb = [-10, 0, 20]
        rows = design.snrDb == snrDb;
        for methodIndex = 1:numel(methodNames)
            entry = summarizeMethod(design(rows, :), extracted, rows, ...
                candidates.candidateId(candidateIndex), ...
                methodNames(methodIndex), methodIndex);
            summary = [summary; entry]; %#ok<AGROW>
        end
    end
end
end

function output = extractCandidate(design, rowResults, candidateIndex, protocol)
count = height(design);
output.theta = nan(count, 3);
output.range = nan(count, 3);
output.equivalent = nan(count, 3);
output.seconds = nan(count, 3);
output.sessionSeconds = nan(count, 1);
output.phaseTerms = zeros(count, 3);
output.covarianceMacs = zeros(count, 3);
output.evdUnits = zeros(count, 3);
output.angleProjectionMacs = zeros(count, 3);
output.profileResponses = zeros(count, 3);
output.angleEndpoint = nan(count, 3);
output.angleNear = nan(count, 3);
output.profileEndpoint = nan(count, 3);
output.profileNear = nan(count, 3);
output.legacyAngleBoundary = nan(count, 3);
output.legacyProfileBoundary = nan(count, 3);

for row = 1:count
    item = rowResults{row}.candidateResults{candidateIndex};
    output.theta(row, :) = item.thetaDeg(1:3);
    output.range(row, :) = item.rangeM(1:3);
    frontResponses = item.front.fullEquivalentResponses;
    output.equivalent(row, :) = [frontResponses, frontResponses, ...
        frontResponses+item.profileSolver.evaluationCount];
    frontSeconds = item.front.runtimeSeconds;
    hSeconds = frontSeconds + item.musicStateCost.seconds ...
        + item.angleSeconds;
    output.seconds(row, :) = [frontSeconds, hSeconds, ...
        hSeconds+item.profileSeconds];
    output.sessionSeconds(row) = item.totalSeconds;
    output.phaseTerms(row, 2:3) = item.complexity.musicPhaseAlignmentTerms;
    output.covarianceMacs(row, 2:3) = item.complexity.musicCovarianceMacs;
    output.evdUnits(row, 2:3) = item.complexity.musicEvdCubicUnits;
    output.angleProjectionMacs(row, 2:3) = ...
        item.complexity.angleScoreProjectionMacs;
    output.profileResponses(row, 3) = item.profileSolver.evaluationCount;
    angleFlags = boundaryFlags(item.angleSolver, ...
        protocol.angleToleranceDeg);
    profileFlags = boundaryFlags(item.profileSolver, ...
        protocol.profileToleranceM);
    output.angleEndpoint(row, 2:3) = angleFlags.endpointHit;
    output.angleNear(row, 2:3) = angleFlags.nearBoundary;
    output.profileEndpoint(row, 3) = profileFlags.endpointHit;
    output.profileNear(row, 3) = profileFlags.nearBoundary;
    output.legacyAngleBoundary(row, 2:3) = item.angleSolver.boundary;
    output.legacyProfileBoundary(row, 3) = item.profileSolver.boundary;
end
end

function entry = summarizeMethod(design, extracted, rows, ...
    candidateId, method, methodIndex)
theta = extracted.theta(rows, methodIndex);
range = extracted.range(rows, methodIndex);
rangeError = range-design.truthRangeM;
angleError = theta-design.truthThetaDeg;
xError = range.*sind(theta)-design.truthRangeM.*sind(design.truthThetaDeg);
yError = range.*cosd(theta)-design.truthRangeM.*cosd(design.truthThetaDeg);

entry = table(candidateId, design.snrDb(1), method, height(design), ...
    sqrt(mean(angleError.^2)), sqrt(mean(rangeError.^2)), ...
    sqrt(mean(xError.^2+yError.^2)), quantile(abs(rangeError), 0.95), ...
    mean(abs(rangeError) > 1), ...
    mean(extracted.equivalent(rows, methodIndex)), ...
    median(extracted.equivalent(rows, methodIndex)), ...
    mean(extracted.seconds(rows, methodIndex)), ...
    median(extracted.seconds(rows, methodIndex)), ...
    quantile(extracted.seconds(rows, methodIndex), 0.95), ...
    max(extracted.seconds(rows, methodIndex)), ...
    mean(extracted.sessionSeconds(rows)), ...
    mean(extracted.phaseTerms(rows, methodIndex)), ...
    mean(extracted.covarianceMacs(rows, methodIndex)), ...
    mean(extracted.evdUnits(rows, methodIndex)), ...
    mean(extracted.angleProjectionMacs(rows, methodIndex)), ...
    mean(extracted.profileResponses(rows, methodIndex)), ...
    mean(extracted.angleEndpoint(rows, methodIndex), "omitnan"), ...
    mean(extracted.angleNear(rows, methodIndex), "omitnan"), ...
    mean(extracted.profileEndpoint(rows, methodIndex), "omitnan"), ...
    mean(extracted.profileNear(rows, methodIndex), "omitnan"), ...
    mean(extracted.legacyAngleBoundary(rows, methodIndex), "omitnan"), ...
    mean(extracted.legacyProfileBoundary(rows, methodIndex), "omitnan"), ...
    'VariableNames', {'candidateId', 'snrDb', 'method', 'n', ...
    'angleRmseDeg', 'rangeRmseM', 'positionRmseM', 'p95RangeM', ...
    'missOver1m', 'meanEquivalentResponses', ...
    'medianEquivalentResponses', 'meanDeploymentSeconds', ...
    'medianDeploymentSeconds', 'p95DeploymentSeconds', ...
    'maxDeploymentSeconds', 'meanExperimentSessionSeconds', ...
    'meanMusicPhaseTerms', 'meanMusicCovarianceMacs', ...
    'meanMusicEvdUnits', 'meanAngleProjectionMacs', ...
    'meanProfileResponses', 'angleEndpointHitRate', ...
    'angleNearBoundaryRate', 'profileEndpointHitRate', ...
    'profileNearBoundaryRate', 'legacyAngleBoundaryRate', ...
    'legacyProfileBoundaryRate'});
end

function flags = boundaryFlags(solver, tolerance)
step = diff(solver.interval)/(numel(solver.grid)-1);
endpointTolerance = max(tolerance, ...
    16*eps(max(1, max(abs(solver.interval)))));
flags.endpointHit = abs(solver.value-solver.interval(1)) ...
    <= endpointTolerance || abs(solver.value-solver.interval(2)) ...
    <= endpointTolerance;
flags.nearBoundary = abs(solver.value-solver.interval(1)) ...
    <= max(endpointTolerance, step/2) ...
    || abs(solver.value-solver.interval(2)) ...
    <= max(endpointTolerance, step/2);
end
