function [candidates, levels] = zhangJointSearchSpace
%ZHANGJOINTSEARCHSPACE Deterministic joint search over unpublished settings.

levels.fusionCarrierCount = [65, 129, 257, 513, 1025, 2047];
levels.subarraySize = [32, 64, 96, 128, 160, 192, 224];
levels.angleHalfWidthDeg = [0.005, 0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1];
levels.rangeHalfWidthM = [0.0025, 0.005, 0.01, 0.02, ...
    0.05, 0.1, 0.25, 0.5, 1];
levels.gridSizes = {[21, 15, 11], [31, 21, 15], [37, 27, 19], ...
    [41, 31, 21], [49, 35, 25], [61, 41, 31]};

levelCounts = [numel(levels.fusionCarrierCount), ...
    numel(levels.subarraySize), numel(levels.angleHalfWidthDeg), ...
    numel(levels.rangeHalfWidthM), numel(levels.gridSizes)];
fullCount = prod(levelCounts);
stream = RandStream("mt19937ar", Seed=20260904);
numRandomCandidates = 128;
covered = false;
while ~covered
    linearIndex = randperm(stream, fullCount, numRandomCandidates).';
    [fusionIndex, subarrayIndex, angleIndex, rangeIndex, gridIndex] = ...
        ind2sub(levelCounts, linearIndex);
    indices = [fusionIndex, subarrayIndex, angleIndex, ...
        rangeIndex, gridIndex];
    covered = all(arrayfun(@(column) ...
        numel(unique(indices(:, column))) == levelCounts(column), 1:5));
end

anchors = [ ...
    levelIndex(levels.fusionCarrierCount, 513), ...
    levelIndex(levels.subarraySize, 96), ...
    levelIndex(levels.angleHalfWidthDeg, 0.02), ...
    levelIndex(levels.rangeHalfWidthM, 0.02), 6; ...
    levelIndex(levels.fusionCarrierCount, 513), ...
    levelIndex(levels.subarraySize, 96), ...
    levelIndex(levels.angleHalfWidthDeg, 0.02), ...
    levelIndex(levels.rangeHalfWidthM, 0.005), 6; ...
    levelIndex(levels.fusionCarrierCount, 1025), ...
    levelIndex(levels.subarraySize, 96), ...
    levelIndex(levels.angleHalfWidthDeg, 0.02), ...
    levelIndex(levels.rangeHalfWidthM, 0.01), 6; ...
    levelIndex(levels.fusionCarrierCount, 2047), ...
    levelIndex(levels.subarraySize, 96), ...
    levelIndex(levels.angleHalfWidthDeg, 0.02), ...
    levelIndex(levels.rangeHalfWidthM, 0.01), 6; ...
    levelIndex(levels.fusionCarrierCount, 257), ...
    levelIndex(levels.subarraySize, 64), ...
    levelIndex(levels.angleHalfWidthDeg, 0.01), ...
    levelIndex(levels.rangeHalfWidthM, 0.005), 5; ...
    levelIndex(levels.fusionCarrierCount, 513), ...
    levelIndex(levels.subarraySize, 128), ...
    levelIndex(levels.angleHalfWidthDeg, 0.01), ...
    levelIndex(levels.rangeHalfWidthM, 0.005), 5; ...
    levelIndex(levels.fusionCarrierCount, 1025), ...
    levelIndex(levels.subarraySize, 160), ...
    levelIndex(levels.angleHalfWidthDeg, 0.005), ...
    levelIndex(levels.rangeHalfWidthM, 0.0025), 4; ...
    levelIndex(levels.fusionCarrierCount, 65), ...
    levelIndex(levels.subarraySize, 224), ...
    levelIndex(levels.angleHalfWidthDeg, 1), ...
    levelIndex(levels.rangeHalfWidthM, 1), 1];
indices = unique([indices; anchors], "rows", "stable");

fusionCarrierCount = levels.fusionCarrierCount(indices(:, 1)).';
subarraySize = levels.subarraySize(indices(:, 2)).';
angleHalfWidthDeg = levels.angleHalfWidthDeg(indices(:, 3)).';
rangeHalfWidthM = levels.rangeHalfWidthM(indices(:, 4)).';
gridIndex = indices(:, 5);
gridLevels = strings(size(gridIndex));
for row = 1:numel(gridIndex)
    gridLevels(row) = strjoin(string(levels.gridSizes{gridIndex(row)}), "/");
end
candidateId = (1:size(indices, 1)).';
candidates = table(candidateId, fusionCarrierCount, subarraySize, ...
    angleHalfWidthDeg, rangeHalfWidthM, gridIndex, gridLevels);
end

function index = levelIndex(levels, value)
index = find(abs(levels - value) <= 10 * eps(max(1, abs(value))), 1);
assert(~isempty(index), "zhangJointSearchSpace:MissingAnchorLevel");
end
