function output = classifyInterpretation( ...
    coreSuccess, pointwisePass, strongSuccess, families)
%CLASSIFYINTERPRETATION Freeze allowed final wording before data exist.

arguments
    coreSuccess (1, 1) logical
    pointwisePass (1, 1) logical
    strongSuccess (1, 1) logical
    families table
end

angleSubset = families.snrDb(families.family == "A-angle" ...
    & families.statisticallySuperior).';
rangeSubset = families.snrDb(families.family == "B-range" ...
    & families.statisticallySuperior).';
if ~coreSuccess
    level = "Level 1";
    statement = "Final joint angle-and-range superiority was not established.";
elseif ~pointwisePass
    level = "Core-only: pointwise inconsistency";
    statement = "G achieved statistically superior overall angle and range " + ...
        "MSE across the tested SNR set, but uniform numerical improvement " + ...
        "cannot be claimed because at least one observed per-SNR MSE was not lower.";
elseif strongSuccess
    level = "Level 3";
    statement = "G achieved statistically superior angle and range " + ...
        "performance at every tested SNR.";
else
    level = "Level 2";
    statement = "G achieved statistically superior overall angle and range " + ...
        "MSE across the tested SNR set, with numerically lower errors at every " + ...
        "tested SNR; per-SNR superiority was established at angle SNR [" + ...
        join(string(angleSubset), ",") + "] dB and range SNR [" + ...
        join(string(rangeSubset), ",") + "] dB by the frozen simultaneous inference.";
end
output = table(level, coreSuccess, pointwisePass, strongSuccess, ...
    statement, {angleSubset}, {rangeSubset}, ...
    'VariableNames', {'level', 'coreGlobalSuccess', ...
    'pointwiseConsistencyPass', 'strongAllSnrSuccess', ...
    'allowedClaim', 'angleSuperiorSnrSubset', 'rangeSuperiorSnrSubset'});
end
