function protocol = config()
%CONFIG Freeze the R41 v2 statistical hierarchy over unchanged execution.

protocol = r41.config();
protocol.version = "R41-SchemeG-independent-final-confirmation-v2";
protocol.statistics = struct( ...
    version="R41-position-cluster-bootstrap-superiority-v2", ...
    hierarchy="co-primary-global-ratios-pointwise-gate-per-SNR-characterization", ...
    coreFinalSuccessRule= ...
    "both-global-one-sided-upper-95-ratios-below-one", ...
    cluster="positionId", bootstrapCount=20000, ...
    bootstrapSeed=54300000, confidence=0.95, ...
    sharedIndicesAcrossSnr=true, equalSnrWeights=ones(1, 7)/7, ...
    globalAngleEstimand= ...
    "mean-over-seven-SNR-MSE-G-angle-divided-by-C-angle", ...
    globalRangeEstimand= ...
    "mean-over-seven-SNR-MSE-G-range-divided-by-C-range", ...
    globalInterval= ...
    "one-sided-95-percentile-position-cluster-bootstrap-ratio", ...
    globalStudentization="none-fixed-percentile-before-final-data", ...
    divisionByZeroPolicy="undefined-and-stop-no-claim", ...
    pointwiseConsistencyGate= ...
    "observed-G-MSE-strictly-below-C-at-all-seven-SNR-for-angle-and-range", ...
    pointwiseGateRole="descriptive-engineering-not-significance-test", ...
    familyA="angle-squared-error-G-minus-C-seven-SNR", ...
    familyB="range-squared-error-G-minus-C-seven-SNR", ...
    familyMultiplicity="separate-studentized-max-statistic-per-family", ...
    perSnrRole="confirmatory-characterization-not-core-success-requirement", ...
    perSnrClaimRule="simultaneous-upper-95-below-zero", ...
    strongAllSnrRule= ...
    "all-seven-angle-and-all-seven-range-simultaneous-upper-bounds-below-zero", ...
    secondaryCannotRescueFailedGlobal=true, ...
    missThresholdM=1, tieTolerance=0);
protocol.execution.authorizationPhrase = ...
    "I_EXPLICITLY_AUTHORIZE_R41_V2_SCHEME_G_FINAL_1400";
protocol.execution.status = ...
    "LOCKED-R41-V2-WAITING-FOR-EXPLICIT-USER-AUTHORIZATION";
protocol.execution.authorized = false;
protocol.execution.trialsExecuted = 0;
end
