function [endpoints, audit] = globalCoPrimary(perUser, protocol)
%GLOBALCOPRIMARY Compute explicit equal-SNR cluster-bootstrap MSE ratios.

arguments
    perUser table
    protocol (1, 1) struct = r41statsv2.config()
end

snrValues = protocol.design.snrDb;
positionIds = unique(perUser.positionId);
clusterCount = numel(positionIds);
snrCount = numel(snrValues);
if snrCount ~= 7 ...
        || ~isequal(protocol.statistics.equalSnrWeights, ones(1, 7)/7)
    error("r41v2:EqualSnrDefinitionMismatch", ...
        "The v2 co-primary estimands require seven exactly equal SNR weights.");
end
gAngle = zeros(clusterCount, snrCount);
cAngle = zeros(clusterCount, snrCount);
gRange = zeros(clusterCount, snrCount);
cRange = zeros(clusterCount, snrCount);
for snrIndex = 1:snrCount
    g = methodRows(perUser, "G_schur", snrValues(snrIndex));
    c = methodRows(perUser, "C_enhanced", snrValues(snrIndex));
    if ~isequal(g.positionId, positionIds) ...
            || ~isequal(c.positionId, positionIds)
        error("r41v2:PositionClusterAlignment", ...
            "G_schur and C_enhanced clusters are not aligned.");
    end
    gAngle(:, snrIndex) = g.angleErrorDeg.^2;
    cAngle(:, snrIndex) = c.angleErrorDeg.^2;
    gRange(:, snrIndex) = g.rangeErrorM.^2;
    cRange(:, snrIndex) = c.rangeErrorM.^2;
end

stream = RandStream("mt19937ar", Seed=protocol.statistics.bootstrapSeed);
indices = randi(stream, clusterCount, clusterCount, ...
    protocol.statistics.bootstrapCount);
[angleRatio, angleBootstrap, angleMinimumDenominator] = ratioEndpoint( ...
    gAngle, cAngle, indices, protocol.statistics.equalSnrWeights);
[rangeRatio, rangeBootstrap, rangeMinimumDenominator] = ratioEndpoint( ...
    gRange, cRange, indices, protocol.statistics.equalSnrWeights);
confidence = protocol.statistics.confidence;
metric = ["angle"; "range"];
observedRatio = [angleRatio; rangeRatio];
upper95 = [quantile(angleBootstrap, confidence); ...
    quantile(rangeBootstrap, confidence)];
statisticallySuperior = upper95 < 1;
role = repmat("co-primary-global", 2, 1);
endpoints = table(metric, observedRatio, upper95, ...
    statisticallySuperior, role);
audit = struct( ...
    version=protocol.statistics.version, ...
    estimand="ratio-of-equal-SNR-mean-cluster-MSE-G-over-C", ...
    cluster="positionId", clusterCount=clusterCount, snrCount=snrCount, ...
    equalSnrWeights=protocol.statistics.equalSnrWeights, ...
    bootstrapCount=protocol.statistics.bootstrapCount, ...
    bootstrapSeed=protocol.statistics.bootstrapSeed, ...
    sharedClusterIndicesAcrossSnr=true, ...
    indexShape=size(indices), indexHash=r31.arrayHash(indices), ...
    intervalAlgorithm=protocol.statistics.globalInterval, ...
    studentization=protocol.statistics.globalStudentization, ...
    confidence=confidence, ...
    angleMinimumBootstrapDenominator=angleMinimumDenominator, ...
    rangeMinimumBootstrapDenominator=rangeMinimumDenominator, ...
    divisionByZeroChecked=true, posthocStudentizationAllowed=false);
end

function [observed, bootstrap, minimumDenominator] = ratioEndpoint( ...
    candidate, reference, indices, weights)
candidateMse = mean(candidate, 1);
referenceMse = mean(reference, 1);
observedDenominator = sum(weights.*referenceMse);
candidateBootstrapMse = r41.clusterBootstrapMeans(candidate, indices);
referenceBootstrapMse = r41.clusterBootstrapMeans(reference, indices);
bootstrapNumerator = candidateBootstrapMse*weights(:);
bootstrapDenominator = referenceBootstrapMse*weights(:);
minimumDenominator = min([observedDenominator; bootstrapDenominator]);
if ~isfinite(observedDenominator) || observedDenominator <= 0 ...
        || any(~isfinite(bootstrapDenominator)) ...
        || any(bootstrapDenominator <= 0)
    error("r41v2:UndefinedGlobalRatio", ...
        "Co-primary global ratios require positive C_enhanced denominators.");
end
observed = sum(weights.*candidateMse)/observedDenominator;
bootstrap = bootstrapNumerator./bootstrapDenominator;
end

function rows = methodRows(perUser, method, snrDb)
rows = sortrows(perUser(perUser.method == method ...
    & perUser.snrDb == snrDb, :), "positionId");
end
