function output = paths(project)
%PATHS Isolate the v2 protocol, authorization, execution, and verification.

arguments
    project (1, 1) string
end

resultsRoot = fullfile(project, "results", "full_spectrum");
protocolFolder = fullfile(resultsRoot, ...
    "round41_schemeG_independent_final_protocol_v2");
output = struct( ...
    protocolFolder=protocolFolder, ...
    protocolFile=fullfile(protocolFolder, "protocol.mat"), ...
    designFile=fullfile(protocolFolder, "design.csv"), ...
    authorizationFile=fullfile(protocolFolder, ...
        "FINAL_TEST_AUTHORIZATION.mat"), ...
    executionFolder=fullfile(resultsRoot, ...
        "round41_schemeG_independent_final_v2"), ...
    verificationFolder=fullfile(resultsRoot, ...
        "round41_schemeG_final_framework_verification_v2"));
end
