function output = summarizeFinal(design, results, protocol)
%SUMMARIZEFINAL Reclassify unchanged v1 calculations under v2 hierarchy.

arguments
    design table
    results cell
    protocol (1, 1) struct = r41statsv2.config()
end

base = r41.summarizeFinal(design, results, protocol);
[coPrimary, globalAudit] = r41statsv2.globalCoPrimary( ...
    base.perUser, protocol);
if any(abs(coPrimary.observedRatio ...
        -base.globalSecondary.observedRatio) > 10*eps) ...
        || any(abs(coPrimary.upper95 ...
        -base.globalSecondary.upper95) > 10*eps)
    error("r41v2:GlobalCalculationDrift", ...
        "The explicit v2 global calculation differs from frozen v1 numerics.");
end
pointwise = r41statsv2.pointwiseConsistency(base.summary, protocol);
families = base.primaryFamilies;
families.role = repmat( ...
    "per-SNR-confirmatory-characterization", height(families), 1);
coreSuccess = all(coPrimary.statisticallySuperior);
pointwisePass = all(pointwise.bothStrictlyLower);
strongSuccess = all(families.statisticallySuperior);
interpretation = r41statsv2.classifyInterpretation( ...
    coreSuccess, pointwisePass, strongSuccess, families);
statisticsAudit = base.statisticsAudit;
statisticsAudit.version = protocol.statistics.version;
statisticsAudit.statisticsHash = r41.structHash(protocol.statistics);
statisticsAudit.global = globalAudit;
statisticsAudit.coreFinalSuccessUsesOnlyGlobalCoPrimary = true;
statisticsAudit.pointwiseGateIsSignificanceTest = false;
statisticsAudit.perSnrFamiliesCanRescueGlobalFailure = false;
statisticsAudit.strongAllSnrPredeclared = true;
output = struct(perUser=base.perUser, summary=base.summary, ...
    paired=base.paired, coPrimaryGlobal=coPrimary, ...
    pointwiseConsistency=pointwise, ...
    perSnrConfirmatoryFamilies=families, ...
    complexityCounts=base.complexityCounts, ...
    coreFinalStatisticalSuccess=coreSuccess, ...
    pointwiseConsistencyPass=pointwisePass, ...
    strongAllSnrSuccess=strongSuccess, ...
    uniformNumericalImprovementClaimAllowed=pointwisePass, ...
    interpretation=interpretation, statisticsAudit=statisticsAudit);
end
