function saved = validateProtocolPackage(project)
%VALIDATEPROTOCOLPACKAGE Verify v2 while preserving the complete v1 archive.

arguments
    project (1, 1) string
end

r41.addPaths(project);
v1 = r41.validateProtocolPackage(project);
v1Locations = r41.paths(project);
locations = r41statsv2.paths(project);
if ~isfile(locations.protocolFile) || ~isfile(locations.designFile)
    error("r41v2:MissingFinalProtocol", ...
        "The reviewed R41 v2 protocol.mat and design.csv are required.");
end
saved = load(locations.protocolFile, "identity", "protocol", ...
    "design", "source", "v1Artifacts", "hierarchyAudit");
required = ["identity", "protocol", "design", "source", ...
    "v1Artifacts", "hierarchyAudit"];
if ~all(isfield(saved, required))
    error("r41v2:MalformedFinalProtocol", ...
        "The R41 v2 protocol package is structurally incomplete.");
end

currentProtocol = r41statsv2.config();
currentSource = r41statsv2.sourceManifest(project);
currentV1Artifacts = r41statsv2.v1ArtifactManifest(project);
csvDesign = readtable(locations.designFile);
v1DesignArtifact = currentV1Artifacts( ...
    currentV1Artifacts.path == replace(extractAfter(v1Locations.designFile, ...
    strlength(project)+1), string(filesep), "/"), :);
v2RelativeDesign = replace(extractAfter(locations.designFile, ...
    strlength(project)+1), string(filesep), "/");
v2DesignArtifact = fsjad.sourceHashManifest(project, v2RelativeDesign);
checks = [ ...
    v1.identity.statisticsVersion ...
        == "R41-position-cluster-bootstrap-superiority-v1"; ...
    v1.identity.statisticsHash ...
        == "112009eca7e02688f355edde944b7cd125be38bcaaa05da4af8d180be2da423c"; ...
    saved.protocol.version == currentProtocol.version; ...
    isequaln(saved.protocol.design, v1.protocol.design); ...
    isequaln(saved.protocol.algorithm, v1.protocol.algorithm); ...
    isequaln(saved.protocol.schemeG, v1.protocol.schemeG); ...
    isequaln(saved.protocol.r34, v1.protocol.r34); ...
    isequaln(saved.protocol.complexity, v1.protocol.complexity); ...
    isequaln(saved.design, v1.design); ...
    isequaln(csvDesign, saved.design); ...
    height(v1DesignArtifact) == 1; ...
    v2DesignArtifact.sha256 == v1DesignArtifact.sha256; ...
    r41.designHash(saved.design) == saved.identity.designHash; ...
    saved.identity.designHash == v1.identity.designHash; ...
    saved.identity.algorithmDigest == v1.identity.algorithmDigest; ...
    saved.identity.r33Digest == v1.identity.r33Digest; ...
    saved.identity.r34Digest == v1.identity.r34Digest; ...
    saved.identity.frozenDependencyDigest ...
        == v1.identity.frozenDependencyDigest; ...
    saved.identity.inheritedV1SourceDigest == v1.identity.sourceDigest; ...
    r41.structHash(saved.protocol.statistics) ...
        == saved.identity.statisticsHash; ...
    saved.identity.statisticsVersion ...
        == "R41-position-cluster-bootstrap-superiority-v2"; ...
    r32.sourceDigest(currentSource) == saved.identity.sourceDigest; ...
    isequaln(saved.source, currentSource); ...
    isequaln(saved.v1Artifacts, currentV1Artifacts); ...
    all(saved.hierarchyAudit.pass)];
if ~all(checks)
    error("r41v2:ProtocolIdentityDrift", ...
        "The v2 hierarchy, design, v1 archive, source, or dependency identity drifted.");
end
end
