function authorization = assertAuthorized(packageFolder, identity)
%ASSERTAUTHORIZED Require an exact future user-issued authorization.

arguments
    packageFolder (1, 1) string
    identity (1, 1) struct
end

file = fullfile(packageFolder, "FINAL_TEST_AUTHORIZATION.mat");
if ~isfile(file)
    error("r41:FinalTestNotAuthorized", ...
        "R41 is locked; no explicit final-test authorization exists.");
end
saved = load(file, "authorization");
if ~isfield(saved, "authorization")
    error("r41:MalformedFinalAuthorization", ...
        "The R41 authorization file has no authorization record.");
end
authorization = saved.authorization;
required = ["approved", "protocolVersion", "designHash", ...
    "statisticsHash", "sourceDigest", "algorithmDigest", ...
    "r33Digest", "r34Digest", "frozenDependencyDigest", ...
    "statement"];
valid = all(isfield(authorization, required)) ...
    && authorization.approved ...
    && authorization.protocolVersion == identity.protocolVersion ...
    && authorization.designHash == identity.designHash ...
    && authorization.statisticsHash == identity.statisticsHash ...
    && authorization.sourceDigest == identity.sourceDigest ...
    && authorization.algorithmDigest == identity.algorithmDigest ...
    && authorization.r33Digest == identity.r33Digest ...
    && authorization.r34Digest == identity.r34Digest ...
    && authorization.frozenDependencyDigest ...
        == identity.frozenDependencyDigest ...
    && authorization.statement ...
        == "user-explicitly-authorized-one-frozen-R41-1400-trial-final";
if ~valid
    error("r41:FinalAuthorizationIdentityMismatch", ...
        "Authorization does not match the exact R41 protocol identity.");
end
end
