function protocol = config()
%CONFIG Freeze the independent Scheme G final-confirmation protocol.

protocol.version = "R41-SchemeG-independent-final-confirmation-v1";
protocol.date = "2026-09-14";
protocol.evidenceRole = "independent-final-confirmation-if-authorized";
protocol.algorithm = struct( ...
    primary="G_schur", reference="C_enhanced", ...
    secondary="P_A", optionalMethodsIncluded=false, ...
    schemeGDigest= ...
    "b1b823826a707591f49ada5ff6cb093683e3bcab2e2b8479334c20076aec02a4", ...
    schemeGVersion="R40-schemeG-full-aperture-range-profiled-v1", ...
    cLabel="strengthened-Zhang-style-executable-baseline", ...
    cAuthorshipClaim="not-author-supplied-Zhang2026-code");
protocol.design = struct( ...
    positionCount=200, snrDb=[-10, -5, 0, 5, 10, 15, 20], ...
    angleLimitsDeg=[-60, 60], rangeLimitsM=[15, 50], ...
    userLaw="independent-uniform-angle-and-range", ...
    positionSeedRoot=54100000, trialSeedRoot=54200000, ...
    positionSeedRule="positionSeedRoot+positionId", ...
    trialSeedRule= ...
    "trialSeedRoot+1000*snrIndex+positionId-with-one-based-snrIndex", ...
    ordering="position-major-then-ascending-SNR", ...
    shardRule="positions-1-to-100-versus-101-to-200", ...
    expectedRows=1400, expectedShardCount=2, ...
    expectedRowsPerShard=700, expectedPositionsPerShard=100);
protocol.statistics = struct( ...
    version="R41-position-cluster-bootstrap-superiority-v1", ...
    hierarchy="SNR-families-primary-global-ratios-secondary-confirmatory", ...
    primaryOverallRule= ...
    "all-seven-angle-and-all-seven-range-simultaneous-upper-bounds-below-zero", ...
    globalEndpointsCanRescuePrimary=false, ...
    cluster="positionId", bootstrapCount=20000, ...
    bootstrapSeed=54300000, confidence=0.95, ...
    sharedIndicesAcrossSnr=true, ...
    familyA="angle-squared-error-G-minus-C-seven-SNR", ...
    familyB="range-squared-error-G-minus-C-seven-SNR", ...
    familyMultiplicity="separate-studentized-max-statistic-per-family", ...
    globalAngle="equal-SNR-mean-MSE-ratio-G-over-C", ...
    globalRange="equal-SNR-mean-MSE-ratio-G-over-C", ...
    globalInterval="one-sided-percentile-cluster-bootstrap-upper-95", ...
    missThresholdM=1, tieTolerance=0);
protocol.complexity = struct( ...
    role="implementation-level-evidence-not-statistical-endpoint", ...
    methods=["G_schur", "P_A", "C_enhanced"], ...
    timingSnrDb=0, timingPositionIds=1:20, repetitions=3, warmups=1, ...
    order="deterministic-cyclic-within-position-and-repetition", ...
    claim="complete-online-runtime-G-less-than-or-equal-to-C", ...
    serverThroughputIsRuntimeEvidence=false, ...
    compareToPublishedMilliseconds=false);
protocol.execution = struct( ...
    authorizationPhrase= ...
    "I_EXPLICITLY_AUTHORIZE_R41_SCHEME_G_FINAL_1400", ...
    status="LOCKED-WAITING-FOR-EXPLICIT-USER-AUTHORIZATION", ...
    authorized=false, trialsExecuted=0, oneFinalRunOnly=true, ...
    noSignificanceStopping=true, noAdditionalUsers=true, ...
    noTailDeletion=true, noUnfavorableSeedRerun=true, ...
    noDesignRegeneration=true, noMethodModification=true, ...
    failedTrialStopsPrimaryInference=true, ...
    existingResultDirectoryRequiresManualResolution=true);
protocol.schemeG = r40SchemeGProtocol();
protocol.r34 = r34.config();
end
