function design = finalDesign(protocol)
%FINALDESIGN Generate the one deterministic 200-position paired design.

arguments
    protocol (1, 1) struct = r41.config()
end

spec = protocol.design;
positions = table('Size', [spec.positionCount, 5], ...
    'VariableTypes', {'double', 'double', 'double', 'double', 'double'}, ...
    'VariableNames', {'positionId', 'positionSeed', ...
    'truthThetaDeg', 'truthRangeM', 'shardId'});
for positionId = 1:spec.positionCount
    positionSeed = spec.positionSeedRoot+positionId;
    stream = RandStream("mt19937ar", Seed=positionSeed);
    theta = spec.angleLimitsDeg(1) ...
        +diff(spec.angleLimitsDeg)*rand(stream);
    rangeM = spec.rangeLimitsM(1) ...
        +diff(spec.rangeLimitsM)*rand(stream);
    shardId = 1+(positionId > spec.expectedPositionsPerShard);
    positions(positionId, :) = {positionId, positionSeed, ...
        theta, rangeM, shardId};
end

design = table('Size', [0, 9], ...
    'VariableTypes', repmat({'double'}, 1, 9), ...
    'VariableNames', {'positionId', 'positionSeed', ...
    'truthThetaDeg', 'truthRangeM', 'snrIndex', 'snrDb', ...
    'seed', 'trialIndex', 'shardId'});
for positionId = 1:spec.positionCount
    for snrIndex = 1:numel(spec.snrDb)
        trialIndex = (positionId-1)*numel(spec.snrDb)+snrIndex;
        seed = spec.trialSeedRoot+1000*snrIndex+positionId;
        condition = table(snrIndex, spec.snrDb(snrIndex), seed, ...
            trialIndex, 'VariableNames', ...
            {'snrIndex', 'snrDb', 'seed', 'trialIndex'});
        row = [positions(positionId, 1:4), condition, ...
            positions(positionId, 5)];
        design = [design; row]; %#ok<AGROW>
    end
end

if height(design) ~= spec.expectedRows ...
        || numel(unique(design.seed)) ~= spec.expectedRows ...
        || numel(unique(design.positionSeed)) ~= spec.positionCount
    error("r41:FinalDesignInvariant", ...
        "The R41 design must contain 200 positions and 1400 unique trials.");
end
end
