function result = finalTrial(cfg, scan, row, rowIndex, protocol)
%FINALTRIAL Execute one frozen independent performance row.

arguments
    cfg (1, 1) struct
    scan (1, 1) struct
    row (1, :) table
    rowIndex (1, 1) double {mustBeInteger, mustBePositive}
    protocol (1, 1) struct = r41.config()
end

result = failureResult(row);
timer = tic;
try
    replay = fsjad.replayRound27Data(cfg, scan, row);
    if mod(rowIndex, 2) == 1
        runtimeOrder = "P_A-C_enhanced-G_schur";
        pa = r34.estimate(cfg, replay.observation, replay.snapshots, ...
            scan, "P_A", protocol.r34);
        c = r34.estimate(cfg, replay.observation, replay.snapshots, ...
            scan, "C_enhanced", protocol.r34);
    else
        runtimeOrder = "C_enhanced-P_A-G_schur";
        c = r34.estimate(cfg, replay.observation, replay.snapshots, ...
            scan, "C_enhanced", protocol.r34);
        pa = r34.estimate(cfg, replay.observation, replay.snapshots, ...
            scan, "P_A", protocol.r34);
    end
    g = r41.gFromPA(cfg, scan, replay, pa, protocol);
    paRecord = baselineRecord(pa, 1);
    cRecord = baselineRecord(c, 0);
    incrementalSeconds = g.contextSeconds ...
        +g.angle.standaloneAngleSeconds+g.transport.runtimeSeconds;
    gRecord = struct(thetaDeg=g.angle.thetaDeg, ...
        rangeM=g.transport.rangeM, ...
        runtimeSeconds=paRecord.runtimeSeconds+incrementalSeconds, ...
        responseEquivalentCount=paRecord.responseEquivalentCount ...
        +g.angle.fullArrayEvaluationCount ...
        +g.transport.addedResponseEvaluationCount, ...
        musicEvaluationCount=paRecord.musicEvaluationCount, ...
        evdCount=paRecord.evdCount, ...
        fullArrayEvaluationCount=g.angle.fullArrayEvaluationCount, ...
        profilePassCount=1, ...
        profileEvaluationCount=paRecord.profileEvaluationCount, ...
        qTransportEvaluationCount= ...
        g.transport.addedResponseEvaluationCount, ...
        incrementalSeconds=incrementalSeconds);
    result.success = true;
    result.runtimeOrder = runtimeOrder;
    result.methodNames = ["G_schur", "C_enhanced", "P_A"];
    result.thetaDeg = [gRecord.thetaDeg, cRecord.thetaDeg, ...
        paRecord.thetaDeg];
    result.rangeM = [gRecord.rangeM, cRecord.rangeM, paRecord.rangeM];
    result.runtimeSeconds = [gRecord.runtimeSeconds, ...
        cRecord.runtimeSeconds, paRecord.runtimeSeconds];
    result.responseEquivalentCount = [gRecord.responseEquivalentCount, ...
        cRecord.responseEquivalentCount, paRecord.responseEquivalentCount];
    result.musicEvaluationCount = [gRecord.musicEvaluationCount, ...
        cRecord.musicEvaluationCount, paRecord.musicEvaluationCount];
    result.evdCount = [gRecord.evdCount, cRecord.evdCount, ...
        paRecord.evdCount];
    result.fullArrayEvaluationCount = [gRecord.fullArrayEvaluationCount, 0, 0];
    result.profilePassCount = [gRecord.profilePassCount, ...
        cRecord.profilePassCount, paRecord.profilePassCount];
    result.profileEvaluationCount = [gRecord.profileEvaluationCount, ...
        cRecord.profileEvaluationCount, paRecord.profileEvaluationCount];
    result.gDiagnostics = g;
catch exception
    result.errorIdentifier = string(exception.identifier);
    result.errorMessage = string(getReport( ...
        exception, "extended", "hyperlinks", "off"));
end
result.sessionSeconds = toc(timer);
end

function output = baselineRecord(input, profilePassCount)
output = struct(thetaDeg=input.thetaDeg, rangeM=input.rangeM, ...
    runtimeSeconds=input.cost.totalOnlineSeconds, ...
    responseEquivalentCount=input.cost.sparseResponseCalls ...
    +input.cost.frontFullResponseCalls+input.cost.profileResponseCalls, ...
    musicEvaluationCount=input.estimate.evaluationCount, ...
    evdCount=input.cost.directCount, ...
    profilePassCount=profilePassCount, ...
    profileEvaluationCount=input.cost.profileResponseCalls);
end

function result = failureResult(row)
result = struct(success=false, positionId=row.positionId, ...
    positionSeed=row.positionSeed, seed=row.seed, ...
    trialIndex=row.trialIndex, snrIndex=row.snrIndex, ...
    snrDb=row.snrDb, truthThetaDeg=row.truthThetaDeg, ...
    truthRangeM=row.truthRangeM, errorIdentifier="", ...
    errorMessage="");
end
