function output = gFromPA(cfg, scan, replay, pa, protocol)
%GFROMPA Apply the frozen R40 G_schur step to one frozen P_A estimate.

arguments
    cfg (1, 1) struct
    scan (1, 1) struct
    replay (1, 1) struct
    pa (1, 1) struct
    protocol (1, 1) struct = r41.config()
end

finalStage = pa.estimate.stages(end);
[~, selectedIndex] = min(abs(finalStage.thetaGridDeg-pa.thetaDeg));
[~, peak] = max(abs(replay.observation).^2);
carrierIndex = r30.selectLocalCarriers(cfg.numSubcarriers, ...
    protocol.r34.r32.music.carrierCount, peak-1);
contextTimer = tic;
context = r38PrepareRawArrayVpmlContext(cfg, ...
    replay.snapshots(:, carrierIndex+1), carrierIndex);
contextSeconds = toc(contextTimer);
angle = r40AngleVariants(cfg, context, finalStage.thetaGridDeg, ...
    selectedIndex, pa.rangeM, protocol.schemeG);
transport = r37ImplicitProfileTransport(cfg, scan, ...
    replay.observation, pa.thetaDeg, pa.rangeM, ...
    angle.schur.thetaDeg, pa.front.selected.rangeM, ...
    protocol.schemeG.range.transportProtocol);
if transport.completeProfilePassCount ~= 1 ...
        || transport.newCompleteProfilePassCount ~= 0
    error("r41:SchemeGProfileIdentity", ...
        "G_schur must retain one complete P_A profile and add none.");
end
output = struct(angle=angle.schur, transport=transport, ...
    contextSeconds=contextSeconds, carrierIndex=carrierIndex, ...
    finalGridDeg=finalStage.thetaGridDeg, selectedGridIndex=selectedIndex, ...
    contextCarrierCount=context.carrierCount, ...
    contextWorkingSetBytes=16*(6*cfg.numAntennas*context.carrierCount ...
    +3*context.carrierCount));
end
