function audit = historicalExclusionAudit(project, design)
%HISTORICALEXCLUSIONAUDIT Prove separation from R29-R40 design sources.

arguments
    project (1, 1) string
    design table
end

r29Setup = r29.setup(project, "calibration600");
r29Design = r29Setup.design;
r34File = fullfile(project, "results", "full_spectrum", ...
    "round34_final_test_protocol_v1", "protocol.mat");
if ~isfile(r34File)
    error("r41:MissingR34Design", ...
        "The frozen R34 design is required for exclusion auditing.");
end
r34Saved = load(r34File, "design");
r34Design = r34Saved.design;

historicalSeeds = unique([r29Design.seed; r34Design.seed]);
newTrialSeeds = unique(design.seed);
newPositionSeeds = unique(design.positionSeed);
newPositions = unique(design(:, ["truthThetaDeg", "truthRangeM"]), ...
    "rows");
r29Positions = unique(r29Design(:, ...
    ["truthThetaDeg", "truthRangeM"]), "rows");
r34Positions = unique(r34Design(:, ...
    ["truthThetaDeg", "truthRangeM"]), "rows");

trialSeedOverlap = intersect(newTrialSeeds, historicalSeeds);
positionSeedOverlap = intersect(newPositionSeeds, historicalSeeds);
r29PositionOverlap = intersect(table2array(newPositions), ...
    table2array(r29Positions), "rows");
r34PositionOverlap = intersect(table2array(newPositions), ...
    table2array(r34Positions), "rows");
check = ["R29-R40 inherited development/calibration trial seeds"; ...
    "R29-R40 inherited development/calibration truth positions"; ...
    "R34 final-design trial seeds"; ...
    "R34 final-design truth positions"; ...
    "new position seeds versus all historical trial seeds"];
overlapCount = [numel(intersect(newTrialSeeds, r29Design.seed)); ...
    size(r29PositionOverlap, 1); ...
    numel(intersect(newTrialSeeds, r34Design.seed)); ...
    size(r34PositionOverlap, 1); numel(positionSeedOverlap)];
pass = overlapCount == 0;
audit = table(check, overlapCount, pass);
audit.Properties.UserData = struct( ...
    r29Rows=height(r29Design), r34Rows=height(r34Design), ...
    historicalUniqueTrialSeeds=numel(historicalSeeds), ...
    newUniqueTrialSeeds=numel(newTrialSeeds), ...
    newUniquePositions=height(newPositions), ...
    r29DesignDigest=r31.arrayHash(table2array(r29Design(:, ...
    ["truthThetaDeg", "truthRangeM", "snrDb", "seed", "trialIndex"]))), ...
    r34DesignDigest=r32.designHash(r34Design), ...
    trialSeedOverlap=trialSeedOverlap, ...
    positionSeedOverlap=positionSeedOverlap);
if ~all(pass)
    error("r41:HistoricalDesignCollision", ...
        "The proposed R41 design overlaps a frozen R29-R40 source.");
end
end
