function results = mergeShardPayloads(expectedDesign, payloads, identity)
%MERGESHARDPAYLOADS Merge two disjoint complete shards in frozen row order.

arguments
    expectedDesign table
    payloads (2, 1) cell
    identity (1, 1) struct
end

results = cell(height(expectedDesign), 1);
assigned = false(height(expectedDesign), 1);
for shardId = 1:2
    payload = payloads{shardId};
    required = ["identity", "design", "results"];
    valid = all(isfield(payload, required)) ...
        && payload.identity.protocolVersion == identity.protocolVersion ...
        && payload.identity.designHash == identity.designHash ...
        && payload.identity.statisticsHash == identity.statisticsHash ...
        && payload.identity.sourceDigest == identity.sourceDigest ...
        && payload.identity.algorithmDigest == identity.algorithmDigest ...
        && payload.identity.shardId == shardId;
    if ~valid
        error("r41:ShardIdentityMismatch", ...
            "A final shard does not match the frozen R41 identity.");
    end
    rows = payload.identity.globalRows(:);
    if numel(rows) ~= height(payload.design) ...
            || numel(rows) ~= numel(payload.results) ...
            || any(rows < 1 | rows > height(expectedDesign)) ...
            || any(assigned(rows)) ...
            || ~isequaln(payload.design, expectedDesign(rows, :))
        error("r41:InvalidOrOverlappingShard", ...
            "Shard rows are missing, overlapping, reordered, or changed.");
    end
    results(rows) = payload.results;
    assigned(rows) = true;
end
if ~all(assigned) || any(cellfun(@isempty, results))
    error("r41:IncompleteShardMerge", ...
        "Every frozen R41 design row must appear exactly once.");
end
end
