function output = paths(project)
%PATHS Centralize immutable protocol and future execution locations.

arguments
    project (1, 1) string
end

resultsRoot = fullfile(project, "results", "full_spectrum");
output = struct( ...
    protocolFolder=fullfile(resultsRoot, ...
        "round41_schemeG_independent_final_protocol_v1"), ...
    protocolFile=fullfile(resultsRoot, ...
        "round41_schemeG_independent_final_protocol_v1", "protocol.mat"), ...
    designFile=fullfile(resultsRoot, ...
        "round41_schemeG_independent_final_protocol_v1", "design.csv"), ...
    authorizationFile=fullfile(resultsRoot, ...
        "round41_schemeG_independent_final_protocol_v1", ...
        "FINAL_TEST_AUTHORIZATION.mat"), ...
    executionFolder=fullfile(resultsRoot, ...
        "round41_schemeG_independent_final_v1"), ...
    verificationFolder=fullfile(resultsRoot, ...
        "round41_schemeG_final_framework_verification_v1"));
end
