function source = schemeGManifest(project)
%SCHEMEGMANIFEST Reproduce the exact frozen R40 Scheme G digest scope.

arguments
    project (1, 1) string
end

paths = ["+r40/schemeG/r40SchemeGProtocol.m"; ...
    "+r40/schemeG/r40FullArrayFresnelSteering.m"; ...
    "+r40/schemeG/r40FullArrayFresnelDerivatives.m"; ...
    "+r40/schemeG/r40ConcentratedCost.m"; ...
    "+r40/schemeG/r40VariableProjectionLinearization.m"; ...
    "+r40/schemeG/r40LocalStepScalars.m"; ...
    "+r40/schemeG/r40AngleVariants.m"; ...
    "+r40/schemeG/r40SchemeGTrial.m"];
source = fsjad.sourceHashManifest(project, paths);
end
