function output = summarizeFinal(design, results, protocol)
%SUMMARIZEFINAL Apply the predeclared R41 descriptive and primary analyses.

arguments
    design table
    results cell
    protocol (1, 1) struct = r41.config()
end

validateInputs(design, results, protocol);
methodNames = ["G_schur", "C_enhanced", "P_A"];
perUser = table();
for methodIndex = 1:numel(methodNames)
    theta = cellfun(@(item) item.thetaDeg(methodIndex), results);
    rangeM = cellfun(@(item) item.rangeM(methodIndex), results);
    runtimeSeconds = cellfun( ...
        @(item) item.runtimeSeconds(methodIndex), results);
    responseCount = cellfun( ...
        @(item) item.responseEquivalentCount(methodIndex), results);
    musicCount = cellfun( ...
        @(item) item.musicEvaluationCount(methodIndex), results);
    evdCount = cellfun(@(item) item.evdCount(methodIndex), results);
    fullArrayCount = cellfun( ...
        @(item) item.fullArrayEvaluationCount(methodIndex), results);
    profilePassCount = cellfun( ...
        @(item) item.profilePassCount(methodIndex), results);
    profileEvaluationCount = cellfun( ...
        @(item) item.profileEvaluationCount(methodIndex), results);
    [angleError, rangeError, positionError] = errors( ...
        design, theta, rangeM);
    method = repmat(methodNames(methodIndex), height(design), 1);
    rows = table(design.positionId, design.positionSeed, design.seed, ...
        design.snrDb, method, theta, rangeM, angleError, rangeError, ...
        positionError, runtimeSeconds, responseCount, musicCount, ...
        evdCount, fullArrayCount, profilePassCount, ...
        profileEvaluationCount, 'VariableNames', {'positionId', ...
        'positionSeed', 'seed', 'snrDb', 'method', 'thetaDeg', ...
        'rangeM', 'angleErrorDeg', 'rangeErrorM', 'positionErrorM', ...
        'performanceSessionReportedSeconds', 'responseEquivalentCount', ...
        'musicEvaluationCount', 'evdCount', 'fullArrayEvaluationCount', ...
        'profilePassCount', 'profileEvaluationCount'});
    perUser = [perUser; rows]; %#ok<AGROW>
end

summary = descriptiveSummary(perUser, protocol);
paired = pairedSummary(perUser, protocol);
[families, globals, statisticsAudit] = primaryInference( ...
    perUser, protocol);
complexityCounts = countSummary(perUser, protocol);
output = struct(perUser=perUser, summary=summary, paired=paired, ...
    primaryFamilies=families, globalSecondary=globals, ...
    complexityCounts=complexityCounts, ...
    primaryOverallPass=all(families.statisticallySuperior), ...
    statisticsAudit=statisticsAudit);
end

function validateInputs(design, results, protocol)
if height(design) ~= protocol.design.expectedRows ...
        || r41.designHash(design) ~= r41.designHash(r41.finalDesign(protocol))
    error("r41:FinalDesignMismatch", ...
        "Primary inference requires the exact frozen 1400-row design.");
end
if numel(results) ~= height(design) || any(cellfun(@isempty, results))
    error("r41:IncompleteFinalResults", ...
        "Every frozen row requires exactly one result.");
end
expectedMethods = ["G_schur", "C_enhanced", "P_A"];
for index = 1:height(design)
    item = results{index};
    required = ["success", "positionId", "seed", "snrDb", ...
        "methodNames", "thetaDeg", "rangeM", "runtimeSeconds", ...
        "responseEquivalentCount", "musicEvaluationCount", ...
        "evdCount", "fullArrayEvaluationCount", "profilePassCount", ...
        "profileEvaluationCount"];
    if ~all(isfield(item, required))
        error("r41:MalformedFinalResult", ...
            "A final result lacks a frozen identity or output field.");
    end
    if ~item.success
        error("r41:FinalFailuresStopPrimaryInference", ...
            "At least one failed final trial exists; primary inference stops.");
    end
    numeric = [item.thetaDeg, item.rangeM, item.runtimeSeconds, ...
        item.responseEquivalentCount, item.musicEvaluationCount, ...
        item.evdCount, item.fullArrayEvaluationCount, ...
        item.profilePassCount, item.profileEvaluationCount];
    valid = item.positionId == design.positionId(index) ...
        && item.seed == design.seed(index) ...
        && item.snrDb == design.snrDb(index) ...
        && isequal(string(item.methodNames), expectedMethods) ...
        && all(isfinite(numeric));
    if ~valid
        error("r41:FinalResultIdentityMismatch", ...
            "A final result does not match its exact design row.");
    end
end
end

function output = descriptiveSummary(perUser, protocol)
output = table();
for method = ["G_schur", "C_enhanced", "P_A"]
    for snrDb = protocol.design.snrDb
        rows = perUser(perUser.method == method ...
            & perUser.snrDb == snrDb, :);
        angleAbs = abs(rows.angleErrorDeg);
        rangeAbs = abs(rows.rangeErrorM);
        entry = table(snrDb, method, height(rows), ...
            mean(rows.angleErrorDeg.^2), rms(rows.angleErrorDeg), ...
            median(angleAbs), quantile(angleAbs, 0.90), ...
            quantile(angleAbs, 0.95), ...
            mean(rows.rangeErrorM.^2), rms(rows.rangeErrorM), ...
            median(rangeAbs), quantile(rangeAbs, 0.90), ...
            quantile(rangeAbs, 0.95), ...
            mean(rangeAbs > protocol.statistics.missThresholdM), ...
            rms(rows.positionErrorM), ...
            mean(rows.performanceSessionReportedSeconds), ...
            'VariableNames', {'snrDb', 'method', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', 'angleMedianAbsDeg', ...
            'angleP90AbsDeg', 'angleP95AbsDeg', 'rangeMseM2', ...
            'rangeRmseM', 'rangeMedianAbsM', 'rangeP90AbsM', ...
            'rangeP95AbsM', 'rangeMissOver1mRate', 'positionRmseM', ...
            'performanceSessionReportedMeanSeconds'});
        output = [output; entry]; %#ok<AGROW>
    end
end
end

function output = pairedSummary(perUser, protocol)
output = table();
for snrDb = protocol.design.snrDb
    g = methodRows(perUser, "G_schur", snrDb);
    c = methodRows(perUser, "C_enhanced", snrDb);
    for metric = ["angle", "range"]
        if metric == "angle"
            candidate = abs(g.angleErrorDeg);
            reference = abs(c.angleErrorDeg);
        else
            candidate = abs(g.rangeErrorM);
            reference = abs(c.rangeErrorM);
        end
        tie = abs(candidate-reference) <= protocol.statistics.tieTolerance;
        win = candidate < reference & ~tie;
        loss = candidate > reference & ~tie;
        entry = table(snrDb, metric, height(g), ...
            mean(candidate.^2-reference.^2), nnz(win), nnz(tie), ...
            nnz(loss), mean(win), mean(tie), mean(loss), ...
            'VariableNames', {'snrDb', 'metric', 'n', ...
            'meanSquaredErrorDifferenceGMinusC', 'winCount', ...
            'tieCount', 'lossCount', 'winRate', 'tieRate', 'lossRate'});
        output = [output; entry]; %#ok<AGROW>
    end
end
end

function [families, globals, audit] = primaryInference(perUser, protocol)
snrValues = protocol.design.snrDb;
positionIds = unique(perUser.positionId);
clusterCount = numel(positionIds);
snrCount = numel(snrValues);
gAngle = zeros(clusterCount, snrCount);
cAngle = zeros(clusterCount, snrCount);
gRange = zeros(clusterCount, snrCount);
cRange = zeros(clusterCount, snrCount);
for snrIndex = 1:snrCount
    g = methodRows(perUser, "G_schur", snrValues(snrIndex));
    c = methodRows(perUser, "C_enhanced", snrValues(snrIndex));
    if ~isequal(g.positionId, positionIds) ...
            || ~isequal(c.positionId, positionIds)
        error("r41:PositionClusterAlignment", ...
            "G_schur and C_enhanced clusters are not aligned.");
    end
    gAngle(:, snrIndex) = g.angleErrorDeg.^2;
    cAngle(:, snrIndex) = c.angleErrorDeg.^2;
    gRange(:, snrIndex) = g.rangeErrorM.^2;
    cRange(:, snrIndex) = c.rangeErrorM.^2;
end

stream = RandStream("mt19937ar", Seed=protocol.statistics.bootstrapSeed);
indices = randi(stream, clusterCount, clusterCount, ...
    protocol.statistics.bootstrapCount);
angleDelta = gAngle-cAngle;
rangeDelta = gRange-cRange;
angleObserved = mean(angleDelta, 1);
rangeObserved = mean(rangeDelta, 1);
angleBootstrap = r41.clusterBootstrapMeans(angleDelta, indices);
rangeBootstrap = r41.clusterBootstrapMeans(rangeDelta, indices);
angleUpper = r41.simultaneousUpper(angleObserved, angleBootstrap, ...
    protocol.statistics.confidence);
rangeUpper = r41.simultaneousUpper(rangeObserved, rangeBootstrap, ...
    protocol.statistics.confidence);
angleRows = table(repmat("A-angle", snrCount, 1), snrValues(:), ...
    angleObserved(:), angleUpper(:), angleUpper(:) < 0, ...
    'VariableNames', {'family', 'snrDb', 'meanDifferenceGMinusC', ...
    'simultaneousUpper95', 'statisticallySuperior'});
rangeRows = table(repmat("B-range", snrCount, 1), snrValues(:), ...
    rangeObserved(:), rangeUpper(:), rangeUpper(:) < 0, ...
    'VariableNames', angleRows.Properties.VariableNames);
families = [angleRows; rangeRows];

gAngleBootstrap = r41.clusterBootstrapMeans(gAngle, indices);
cAngleBootstrap = r41.clusterBootstrapMeans(cAngle, indices);
gRangeBootstrap = r41.clusterBootstrapMeans(gRange, indices);
cRangeBootstrap = r41.clusterBootstrapMeans(cRange, indices);
[angleRatio, angleRatioBootstrap] = globalRatio( ...
    gAngle, cAngle, gAngleBootstrap, cAngleBootstrap);
[rangeRatio, rangeRatioBootstrap] = globalRatio( ...
    gRange, cRange, gRangeBootstrap, cRangeBootstrap);
confidence = protocol.statistics.confidence;
globalMetric = ["angle"; "range"];
observedRatio = [angleRatio; rangeRatio];
upper95 = [quantile(angleRatioBootstrap, confidence); ...
    quantile(rangeRatioBootstrap, confidence)];
statisticallySuperior = upper95 < 1;
hierarchy = repmat("secondary-confirmatory-cannot-rescue-primary", 2, 1);
globals = table(globalMetric, observedRatio, upper95, ...
    statisticallySuperior, hierarchy);

audit = struct(version=protocol.statistics.version, ...
    statisticsHash=r41.structHash(protocol.statistics), ...
    clusterCount=clusterCount, ...
    bootstrapCount=protocol.statistics.bootstrapCount, ...
    bootstrapSeed=protocol.statistics.bootstrapSeed, ...
    sharedIndicesAcrossSevenSnr=true, indexShape=size(indices), ...
    indexHash=r31.arrayHash(indices), confidence=confidence, ...
    separateSevenComparisonFamilies=true, ...
    globalHierarchy="secondary-confirmatory");
end

function [observed, bootstrap] = globalRatio( ...
    candidate, reference, candidateBootstrap, referenceBootstrap)
denominator = mean(reference, "all");
bootstrapDenominator = mean(referenceBootstrap, 2);
if denominator <= 0 || any(bootstrapDenominator <= 0)
    error("r41:UndefinedGlobalRatio", ...
        "Global MSE ratios require positive C_enhanced MSE.");
end
observed = mean(candidate, "all")/denominator;
bootstrap = mean(candidateBootstrap, 2)./bootstrapDenominator;
end

function output = countSummary(perUser, protocol)
output = table();
for method = ["G_schur", "C_enhanced", "P_A"]
    for snrDb = protocol.design.snrDb
        rows = perUser(perUser.method == method ...
            & perUser.snrDb == snrDb, :);
        entry = table(snrDb, method, ...
            mean(rows.responseEquivalentCount), ...
            mean(rows.musicEvaluationCount), mean(rows.evdCount), ...
            mean(rows.fullArrayEvaluationCount), ...
            mean(rows.profilePassCount), ...
            mean(rows.profileEvaluationCount), ...
            'VariableNames', {'snrDb', 'method', ...
            'meanResponseEquivalentCount', 'meanMusicEvaluationCount', ...
            'meanEvdCount', 'meanFullArrayEvaluationCount', ...
            'meanProfilePassCount', 'meanProfileEvaluationCount'});
        output = [output; entry]; %#ok<AGROW>
    end
end
end

function rows = methodRows(perUser, method, snrDb)
rows = sortrows(perUser(perUser.method == method ...
    & perUser.snrDb == snrDb, :), "positionId");
end

function [angleError, rangeError, positionError] = errors( ...
    design, theta, rangeM)
angleError = theta-design.truthThetaDeg;
rangeError = rangeM-design.truthRangeM;
xError = rangeM.*sind(theta) ...
    -design.truthRangeM.*sind(design.truthThetaDeg);
yError = rangeM.*cosd(theta) ...
    -design.truthRangeM.*cosd(design.truthThetaDeg);
positionError = hypot(xError, yError);
end
