function validateFrozenSystem(cfg, protocol)
%VALIDATEFROZENSYSTEM Verify the R34 and R40 algorithm constants.

arguments
    cfg (1, 1) struct
    protocol (1, 1) struct = r41.config()
end

g = protocol.schemeG;
a = protocol.r34;
pass = cfg.numAntennas == g.system.N ...
    && cfg.numSubcarriers == g.system.M ...
    && a.r32.music.carrierCount == g.system.K ...
    && a.r32.music.subarraySize == g.system.L ...
    && a.r32.music.numSubarrays == g.system.P ...
    && ~a.implementation.useGram ...
    && isequal(a.r32.music.gridSizes, g.system.angleGridSizes) ...
    && a.r32.profile.halfWidthM == g.system.profileHalfWidthM ...
    && a.r32.profile.lambda == g.system.lambda ...
    && g.model.primary == "Schur-profiled-one-step" ...
    && g.range.completeProfilePasses == 1 ...
    && g.range.newCompleteProfilePasses == 0;
if ~pass
    error("r41:FrozenSystemMismatch", ...
        "R34 P_A/C or the frozen R40 Scheme G system has changed.");
end
end
