function saved = validateProtocolPackage(project)
%VALIDATEPROTOCOLPACKAGE Recompute every frozen protocol identity.

arguments
    project (1, 1) string
end

r41.addPaths(project);
locations = r41.paths(project);
if ~isfile(locations.protocolFile) || ~isfile(locations.designFile)
    error("r41:MissingFinalProtocol", ...
        "The reviewed R41 protocol.mat and design.csv are required.");
end
saved = load(locations.protocolFile, "identity", "protocol", ...
    "design", "source", "schemeGSource", "dependencies", ...
    "historicalAudit");
required = ["identity", "protocol", "design", "source", ...
    "schemeGSource", "dependencies", "historicalAudit"];
if ~all(isfield(saved, required))
    error("r41:MalformedFinalProtocol", ...
        "The R41 protocol package is structurally incomplete.");
end

currentProtocol = r41.config();
currentDesign = r41.finalDesign(currentProtocol);
currentSchemeG = r41.schemeGManifest(project);
currentDependencies = r41.dependencyManifests(project);
currentSource = r41.sourceManifest(project);
currentHistoricalAudit = r41.historicalExclusionAudit( ...
    project, saved.design);
csvDesign = readtable(locations.designFile);
checks = [ ...
    saved.protocol.version == currentProtocol.version; ...
    isequaln(saved.design, currentDesign); ...
    isequaln(csvDesign, saved.design); ...
    r41.designHash(saved.design) == saved.identity.designHash; ...
    r41.structHash(saved.protocol.statistics) ...
        == saved.identity.statisticsHash; ...
    r32.sourceDigest(currentSchemeG) ...
        == saved.identity.algorithmDigest; ...
    saved.identity.algorithmDigest ...
        == saved.protocol.algorithm.schemeGDigest; ...
    r32.sourceDigest(currentDependencies.r33) ...
        == saved.identity.r33Digest; ...
    r32.sourceDigest(currentDependencies.r34) ...
        == saved.identity.r34Digest; ...
    r32.sourceDigest(currentDependencies.all) ...
        == saved.identity.frozenDependencyDigest; ...
    r32.sourceDigest(currentSource) == saved.identity.sourceDigest; ...
    isequaln(saved.schemeGSource, currentSchemeG); ...
    isequaln(saved.dependencies, currentDependencies); ...
    isequaln(saved.source, currentSource); ...
    all(saved.historicalAudit.pass); ...
    all(currentHistoricalAudit.pass)];
if ~all(checks)
    error("r41:ProtocolIdentityDrift", ...
        "Source, dependency, statistics, design, CSV, or exclusion identity drifted.");
end
end
