function protocol = config()
%CONFIG Freeze the P_FA Calibration-600 protocol.

protocol.version = "R45-PFA-calibration600-v1";
protocol.date = "2026-09-17";
protocol.evidenceRole = "pre-final-calibration-not-independent-validation";
protocol.method = struct(primary="P_FA", baseline="P_A", ...
    reference="C_enhanced", secondary="G_schur", ...
    methodVersion="PFA-full-aperture-sequential-v1");
protocol.r34 = r34.config();
protocol.r41 = r41.config();
protocol.pfa = struct(carrierCount=2047, angleHalfWidthDeg=0.2, ...
    coarseAngleGridSize=41, tolXDeg=1e-7, ...
    gainModel="independent-complex-alpha-per-carrier", ...
    steering="full-N-Fresnel", ...
    candidateRetention="best-evaluated-score", ...
    rangeBackend="unchanged-R33-q-only-profile");
protocol.design = struct(positionCount=200, snrDb=[-10, 0, 20], ...
    angleLimitsDeg=[-60, 60], rangeLimitsM=[15, 50], ...
    positionSeed=59000000, trialSeedRoot=59100000, ...
    diagnosticPositionIds=1:20, holdoutPositionIds=21:200, ...
    expectedRows=600);
protocol.bootstrap = struct(count=10000, seed=59200000, ...
    confidence=0.95, cluster="positionId", ...
    sharedIndicesAcrossSnr=true, ...
    angleUpperLimit=1.0, rangeUpperLimit=1.02);
protocol.gate = struct(maxPerSnrAngleMseRatioToPA=1.05, ...
    maxAggregateAngleMseRatioToPA=0.85, ...
    maxPerSnrRangeMseRatioToPA=1.02, ...
    maxAggregateRangeMseRatioToPA=1.01, ...
    maxAggregateMseRatioToC=1.0);
protocol.execution = struct(r34FinalReadAllowed=false, ...
    r41FinalReadAllowed=false, priorDevelopmentRowsReadAllowed=false, ...
    parameterTuningAllowed=false, finalTrialsExecuted=0, ...
    independentFinalAuthorized=false, ...
    failedTrialStopsCalibration=true, sourceDriftStopsCalibration=true);
end
