function result = fromFront(cfg, observation, snapshots, scan, front, protocol)
%FROMFRONT Run the frozen P_FA backend from one equivalent L06 front.

arguments
    cfg (1, 1) struct
    observation (:, 1) double {mustBeFinite}
    snapshots (:, :) double
    scan (1, 1) struct
    front (1, 1) struct
    protocol (1, 1) struct = r45.config()
end

timer = tic;
carrierIndex = r30.selectLocalCarriers(cfg.numSubcarriers, ...
    protocol.pfa.carrierCount, front.peakCarrierIndex);
contextTimer = tic;
context = r38PrepareRawArrayVpmlContext(cfg, ...
    snapshots(:, carrierIndex+1), carrierIndex);
contextSeconds = toc(contextTimer);
angle = r45.fullArrayAngle(cfg, context, front.selected, protocol);
profileTimer = tic;
profile = r33.profileAtAngle(cfg, observation, scan, ...
    angle.thetaDeg, front.selected.rangeM, protocol.r34.r33);
profileSeconds = toc(profileTimer);
result = struct(version=protocol.method.methodVersion, ...
    thetaDeg=angle.thetaDeg, rangeM=profile.value, ...
    frontThetaDeg=front.selected.thetaDeg, ...
    frontRangeM=front.selected.rangeM, carrierIndex=carrierIndex, ...
    angle=angle, profile=compactProfile(profile), ...
    contextSeconds=contextSeconds, angleSeconds=angle.runtimeSeconds, ...
    profileSeconds=profileSeconds, backendSeconds=toc(timer), ...
    fullArrayEvaluationCount=angle.fullArrayEvaluationCount, ...
    profileEvaluationCount=profile.evaluationCount, ...
    profilePassCount=1, musicEvaluationCount=0, evdCount=0);
end

function output = compactProfile(input)
output = struct(version=input.version, value=input.value, ...
    score=input.score, interval=input.interval, ...
    endpointHit=input.endpointHit, nearBoundary=input.nearBoundary, ...
    endpointOutwardTrend=input.endpointOutwardTrend, ...
    evaluationCount=input.evaluationCount, ...
    retentionMargin=input.retentionMargin);
end
