function output = summarize(design, results, protocol)
%SUMMARIZE Build R45 calibration tables and frozen gates.

arguments
    design table
    results (:, 1) cell
    protocol (1, 1) struct = r45.config()
end

if numel(results) ~= height(design) || any(cellfun(@isempty, results)) ...
        || any(cellfun(@(x) ~x.success, results))
    error("r45:IncompleteCalibration", ...
        "R45 summary requires every frozen calibration row.");
end
perUser = design(:, ["positionId", "seed", "trialIndex", ...
    "snrDb", "truthThetaDeg", "truthRangeM", "subset"]);
methods = ["P_FA", "P_A", "G_schur", "C_enhanced"];
for method = methods
    theta = cellfun(@(x) x.(method).thetaDeg, results);
    rangeM = cellfun(@(x) x.(method).rangeM, results);
    perUser.("theta_"+method) = theta;
    perUser.("range_"+method) = rangeM;
    perUser.("angleError_"+method) = theta-perUser.truthThetaDeg;
    perUser.("rangeError_"+method) = rangeM-perUser.truthRangeM;
    perUser.("positionError_"+method) = hypot( ...
        rangeM.*sind(theta)-perUser.truthRangeM.*sind(perUser.truthThetaDeg), ...
        rangeM.*cosd(theta)-perUser.truthRangeM.*cosd(perUser.truthThetaDeg));
end
perUser.pfaEndpointHit = cellfun( ...
    @(x) x.pfaDiagnostics.profile.endpointHit, results);
perUser.pfaNearBoundary = cellfun( ...
    @(x) x.pfaDiagnostics.profile.nearBoundary, results);
perUser.pfaAngleRetentionMargin = cellfun( ...
    @(x) x.pfaDiagnostics.angle.retentionMargin, results);
perUser.pfaFullArrayEvaluationCount = cellfun( ...
    @(x) x.pfaDiagnostics.fullArrayEvaluationCount, results);
perUser.pfaProfileEvaluationCount = cellfun( ...
    @(x) x.pfaDiagnostics.profileEvaluationCount, results);
perUser.sharedDirectEvdCount = cellfun( ...
    @(x) x.sharedAudit.totalDirectEvdCount, results);
perUser.sharedGramCount = cellfun( ...
    @(x) x.sharedAudit.totalGramCount, results);
perUser.sharedFallbackCount = cellfun( ...
    @(x) x.sharedAudit.totalFallbackCount, results);

all600 = populationSummary(perUser, "all600", protocol, 0);
holdout = populationSummary( ...
    perUser(perUser.subset == "holdout540", :), ...
    "holdout540", protocol, 1);
diagnostic = populationSummary( ...
    perUser(perUser.subset == "diagnostic60", :), ...
    "diagnostic60", protocol, 2);
identityPass = all(perUser.sharedGramCount == 0) ...
    && all(perUser.sharedFallbackCount == 0) ...
    && all(perUser.pfaAngleRetentionMargin >= -1000*eps) ...
    && all(isfinite(perUser.theta_P_FA)) ...
    && all(isfinite(perUser.range_P_FA));
calibrationReady = all(all600.gate.pass) && all(holdout.gate.pass) ...
    && all(all600.bootstrap.summary.pass) ...
    && all(holdout.bootstrap.summary.pass) && identityPass;
decision = table(all(all600.gate.pass), all(holdout.gate.pass), ...
    all(all600.bootstrap.summary.pass), ...
    all(holdout.bootstrap.summary.pass), identityPass, ...
    calibrationReady, 'VariableNames', {'all600EngineeringPass', ...
    'holdout540EngineeringPass', 'all600BootstrapPass', ...
    'holdout540BootstrapPass', 'identityPass', 'calibrationReady'});
output = struct(version="R45-PFA-calibration-summary-v1", ...
    perUser=perUser, all600=all600, holdout540=holdout, ...
    diagnostic60=diagnostic, decision=decision, ...
    calibrationReady=calibrationReady);
end

function output = populationSummary(perUser, population, protocol, seedOffset)
methods = ["P_FA", "P_A", "G_schur", "C_enhanced"];
methodSummary = table();
for method = methods
    for snr = protocol.design.snrDb
        selected = perUser.snrDb == snr;
        angleError = perUser.("angleError_"+method)(selected);
        rangeError = perUser.("rangeError_"+method)(selected);
        positionError = perUser.("positionError_"+method)(selected);
        methodSummary = [methodSummary; table(method, snr, nnz(selected), ...
            mean(angleError.^2), sqrt(mean(angleError.^2)), ...
            median(abs(angleError)), quantile(abs(angleError), 0.90), ...
            quantile(abs(angleError), 0.95), mean(rangeError.^2), ...
            sqrt(mean(rangeError.^2)), median(abs(rangeError)), ...
            quantile(abs(rangeError), 0.90), ...
            quantile(abs(rangeError), 0.95), ...
            sqrt(mean(positionError.^2)), ...
            'VariableNames', {'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', 'angleMedianAbsDeg', ...
            'angleP90AbsDeg', 'angleP95AbsDeg', 'rangeMseM2', ...
            'rangeRmseM', 'rangeMedianAbsM', 'rangeP90AbsM', ...
            'rangeP95AbsM', 'positionRmseM'})]; %#ok<AGROW>
    end
end
comparisons = table();
for reference = ["P_A", "G_schur", "C_enhanced"]
    for metric = ["angle", "range"]
        comparisons = [comparisons; comparisonRows( ...
            perUser, "P_FA", reference, metric, protocol)]; %#ok<AGROW>
    end
end
gate = engineeringGate(comparisons, population, protocol);
bootstrap = r45.clusterBootstrap(perUser, protocol, seedOffset);
diagnostics = table(population, height(perUser), ...
    sum(perUser.pfaEndpointHit), sum(perUser.pfaNearBoundary), ...
    min(perUser.pfaAngleRetentionMargin), ...
    mean(perUser.pfaFullArrayEvaluationCount), ...
    mean(perUser.pfaProfileEvaluationCount), ...
    'VariableNames', {'population', 'n', 'profileEndpointHits', ...
    'profileNearBoundaryHits', 'minimumAngleRetentionMargin', ...
    'meanFullArrayEvaluationCount', 'meanProfileEvaluationCount'});
output = struct(population=population, perUser=perUser, ...
    methodSummary=methodSummary, comparisons=comparisons, ...
    gate=gate, bootstrap=bootstrap, diagnostics=diagnostics);
end

function output = comparisonRows(perUser, candidate, reference, metric, protocol)
output = table();
candidateMse = zeros(numel(protocol.design.snrDb), 1);
referenceMse = zeros(numel(protocol.design.snrDb), 1);
allCandidate = zeros(0, 1);
allReference = zeros(0, 1);
for index = 1:numel(protocol.design.snrDb)
    snr = protocol.design.snrDb(index);
    selected = perUser.snrDb == snr;
    candidateError = perUser.(metric+"Error_"+candidate)(selected).^2;
    referenceError = perUser.(metric+"Error_"+reference)(selected).^2;
    candidateMse(index) = mean(candidateError);
    referenceMse(index) = mean(referenceError);
    output = [output; comparisonRow(candidate, reference, metric, ...
        "per-SNR", snr, candidateError, referenceError)]; %#ok<AGROW>
    allCandidate = [allCandidate; candidateError]; %#ok<AGROW>
    allReference = [allReference; referenceError]; %#ok<AGROW>
end
ratio = mean(candidateMse)/mean(referenceMse);
output = [output; table(candidate, reference, metric, "equal-SNR", ...
    nan, numel(allCandidate), mean(candidateMse), mean(referenceMse), ...
    ratio, 100*(1-sqrt(ratio)), ...
    nnz(allCandidate < allReference), ...
    nnz(allCandidate == allReference), ...
    nnz(allCandidate > allReference), ...
    'VariableNames', output.Properties.VariableNames)];
end

function row = comparisonRow(candidate, reference, metric, scope, snrDb, ...
    candidateError, referenceError)
candidateMse = mean(candidateError);
referenceMse = mean(referenceError);
ratio = candidateMse/referenceMse;
row = table(candidate, reference, metric, scope, snrDb, ...
    numel(candidateError), candidateMse, referenceMse, ratio, ...
    100*(1-sqrt(ratio)), nnz(candidateError < referenceError), ...
    nnz(candidateError == referenceError), ...
    nnz(candidateError > referenceError), ...
    'VariableNames', {'candidate', 'reference', 'metric', 'scope', ...
    'snrDb', 'n', 'candidateMse', 'referenceMse', 'mseRatio', ...
    'rmseImprovementPct', 'winCount', 'tieCount', 'lossCount'});
end

function gate = engineeringGate(comparisons, population, protocol)
paAngle = comparisons(comparisons.reference == "P_A" ...
    & comparisons.metric == "angle", :);
paRange = comparisons(comparisons.reference == "P_A" ...
    & comparisons.metric == "range", :);
cAngle = comparisons(comparisons.reference == "C_enhanced" ...
    & comparisons.metric == "angle" ...
    & comparisons.scope == "equal-SNR", :);
cRange = comparisons(comparisons.reference == "C_enhanced" ...
    & comparisons.metric == "range" ...
    & comparisons.scope == "equal-SNR", :);
name = ["per-SNR-angle-to-PA"; "aggregate-angle-to-PA"; ...
    "per-SNR-range-to-PA"; "aggregate-range-to-PA"; ...
    "aggregate-angle-to-C"; "aggregate-range-to-C"];
observed = [max(paAngle.mseRatio(paAngle.scope == "per-SNR")); ...
    paAngle.mseRatio(paAngle.scope == "equal-SNR"); ...
    max(paRange.mseRatio(paRange.scope == "per-SNR")); ...
    paRange.mseRatio(paRange.scope == "equal-SNR"); ...
    cAngle.mseRatio; cRange.mseRatio];
limit = [protocol.gate.maxPerSnrAngleMseRatioToPA; ...
    protocol.gate.maxAggregateAngleMseRatioToPA; ...
    protocol.gate.maxPerSnrRangeMseRatioToPA; ...
    protocol.gate.maxAggregateRangeMseRatioToPA; ...
    protocol.gate.maxAggregateMseRatioToC; ...
    protocol.gate.maxAggregateMseRatioToC];
gate = table(repmat(population, numel(name), 1), name, ...
    observed, limit, observed <= limit, ...
    'VariableNames', {'population', 'gate', 'observedRatio', ...
    'maximumAllowedRatio', 'pass'});
end
