function protocol = config()
%CONFIG Freeze the R57 coherent-array range (P_FACR) development study.

protocol.version = "R57-PFACR-development-v1";
protocol.date = "2026-09-20";
protocol.evidenceRole = "post-R56-independent-development-not-confirmation";
protocol.method = struct(primary="P_FACR", ...
    robustAmplitude="P_FACR_A", robustDispersion="P_FACR_D", ...
    falsification="P_FACR_T", arrayOnly="P_FACR_Yonly", ...
    base="P_FALF", angleBase="P_FA", baseline="P_A", ...
    reference="C_enhanced", ...
    finalAngle="exact-frozen-P_FA-angle", ...
    paFree=true, musicFree=true, evdFree=true);
protocol.base = r53.config();
protocol.freeze = struct(expectedR53Digest= ...
    "c1476d3b75078a841286bebf6e67812217dd689952b291b4a3213cd915018c5c", ...
    expectedPfaDigest= ...
    "f1483ec49bb59907a9b5b2f70aa95459f11277450a0bbcf715a43b3324439868", ...
    modifyFrozenMethods=false);

% Array-block gain models. The degree-1 (delay) phase direction is exactly
% collinear with the range score, so it is forbidden in every branch except
% the P_FACR_T falsification branch. See research/141 Theorems 1 and 3.
protocol.gain = struct( ...
    primaryModel="one-common-complex-beta", ...
    amplitudeModel="free-real-rho-per-carrier-plus-common-phase", ...
    dispersionModel="common-beta-plus-orthonormal-phase-degrees-2-3", ...
    dispersionDegrees=[2, 3], ...
    forbiddenPhaseDegree=1, ...
    basis="gram-schmidt-uniform-weight-on-selected-carriers", ...
    tauBranchAllowed=true, tauBranchIsFalsificationOnly=true, ...
    fusionWeightAllowed=false, thresholdAllowed=false, ...
    selectorAllowed=false, snrRuleAllowed=false, truthAllowed=false);

% Search constants. coarseSpacingM and tolXM are fixed by the sampling
% theorem and the target bound, never retuned from any outcome.
protocol.profile = protocol.base.profile;
protocol.profile.coarseSpacingM = 299792458/(4*3e9);
protocol.profile.tolXM = 1e-7;
protocol.profile.mainlobeM = 299792458/3e9;
protocol.profile.samplesPerMainlobe = 4;
protocol.tau = struct(halfWidthSeconds=protocol.profile.halfWidthM/299792458, ...
    coarseCount=201, tolSeconds=1e-18);
protocol.dispersion = struct(maxIterations=200, tolX=1e-4, tolFun=1e-6);

% Delay stress branch. Runs on a MODIFIED data path and is therefore kept in
% its own result directory; it never enters the primary judgement.
protocol.stress = struct( ...
    sigmaTauSeconds=[0, 1e-13, 1e-12, 1e-11, 1e-10, 1e-9], ...
    modes=["array", "common"], ...
    positionCount=20, snrDb=[-10, 0, 20], ...
    positionSeed=74000000, trialSeedRoot=74100000, tauSeed=74200000, ...
    methods=["P_A", "P_FALF", "P_FACR"], ...
    sharedNoiseAcrossLevels=true, ...
    invarianceToleranceM=1e-5, ...
    entersPrimaryJudgement=false, ...
    expectedRows=20*3*6*2);

protocol.design = struct(positionCount=30, ...
    snrDb=[-10, -5, 0, 5, 10, 15, 20], ...
    angleLimitsDeg=[-60, 60], rangeLimitsM=[15, 50], ...
    positionSeed=72000000, trialSeedRoot=72100000, expectedRows=210);
protocol.smoke = struct(positionCount=3, expectedRows=21, ...
    positionSeed=73000000, trialSeedRoot=73100000);
protocol.bootstrap = struct(count=10000, seed=72200000, ...
    confidence=0.95, cluster="positionId", sharedAcrossSnr=true);

% Consumed unchanged by the frozen r55.clusterBootstrap simultaneous family.
protocol.statistics = struct(version="R57-cluster-bootstrap-v1", ...
    bootstrapSeed=72200000, bootstrapCount=10000, ...
    familyConfidence=0.975, aggregateConfidence=0.95, ...
    rangeNoninferiorityLimit=0.10, aggregateSuperiorityLimit=0.02);
protocol.timing = struct(positionIds=1:3, snrDb=0, repetitions=2, ...
    warmups=1, methods=["P_FACR", "C_enhanced"]);

% G9 is an efficiency gate against the closed-form coherent CRLB. It replaced
% a per-SNR ratio-spread gate on 2026-09-20 after the 21-row smoke showed the
% spread measures the heavy tail of the P_A denominator rather than Theorem 2.
% No R57 development row had been executed at that time. See research/141 8.1.
protocol.gate = struct(maxAngleIdentityDifferenceDeg=0, ...
    maxAggregateRangeMseRatioToPA=0.01, ...
    maxAggregateRangeMseRatioUpper95ToPA=0.02, ...
    maxSimultaneousPerSnrRangeMseRatioToPA=0.10, ...
    maxAggregateRangeMseRatioUpper95ToPFALF=0.05, ...
    maxP95AbsRangeRatioToPFALF=0.10, ...
    maxMissRateDifferenceToPFALF=0, missThresholdM=1.0, ...
    efficiencyBand=[0.3, 3.0], ...
    tauBranchBandToPFALF=[0.85, 1.15], ...
    robustBandToPrimary=[0.9, 1.3], ...
    maxMatchedRuntimeRatioToC=1.0);
protocol.execution = struct(recommendedWorkers=8, batchSize=7, ...
    finalRowsAccessible=false, R53R54R55R56RowsAccessible=false, ...
    parameterTuningAllowed=false, calibrationAllowed=false, ...
    smokeBeforeDevelopment=true, stopAfterDevelopment=true);
end
