function output = stressDesign(protocol)
%STRESSDESIGN Grid of positions, SNR, injection mode and timing jitter.
%   The data seed depends only on position and SNR, so every jitter level and
%   both modes reuse the same underlying z and Y realization. That isolates
%   the timing effect and makes the P_A and P_FALF invariance check exact.

arguments
    protocol (1, 1) struct = r57.config()
end

stress = protocol.stress;
stream = RandStream("mt19937ar", Seed=stress.positionSeed);
baseId = (1:stress.positionCount).';
theta = protocol.design.angleLimitsDeg(1) ...
    +diff(protocol.design.angleLimitsDeg)*rand(stream, stress.positionCount, 1);
rangeM = protocol.design.rangeLimitsM(1) ...
    +diff(protocol.design.rangeLimitsM)*rand(stream, stress.positionCount, 1);

output = table();
for modeIndex = 1:numel(stress.modes)
    for levelIndex = 1:numel(stress.sigmaTauSeconds)
        for snrIndex = 1:numel(stress.snrDb)
            positionId = baseId;
            block = table(positionId, ...
                repmat(stress.positionSeed, stress.positionCount, 1), ...
                stress.trialSeedRoot+100000*snrIndex+positionId, ...
                repmat(snrIndex, stress.positionCount, 1), ...
                repmat(stress.snrDb(snrIndex), stress.positionCount, 1), ...
                theta, rangeM, ...
                repmat(modeIndex, stress.positionCount, 1), ...
                repmat(stress.modes(modeIndex), stress.positionCount, 1), ...
                repmat(levelIndex, stress.positionCount, 1), ...
                repmat(stress.sigmaTauSeconds(levelIndex), ...
                stress.positionCount, 1), ...
                stress.tauSeed+1000000*(modeIndex-1) ...
                +100000*(levelIndex-1)+1000*(snrIndex-1)+positionId, ...
                'VariableNames', {'positionId', 'positionSeed', 'seed', ...
                'snrIndex', 'snrDb', 'truthThetaDeg', 'truthRangeM', ...
                'modeIndex', 'mode', 'levelIndex', 'sigmaTauSeconds', ...
                'tauSeed'});
            output = [output; block]; %#ok<AGROW>
        end
    end
end
output.trialIndex = (1:height(output)).';
if height(output) ~= protocol.stress.expectedRows
    error("r57:StressDesignSize", ...
        "The stress design produced %d rows, expected %d.", ...
        height(output), protocol.stress.expectedRows);
end
end
