function output = summarize(design, results, protocol)
%SUMMARIZE Build R57 accuracy, efficiency, bootstrap and gate tables.
%   Every per-row scalar is cast to double before concatenation. R56 stopped
%   on a table-variable concatenation fault at this step; the cast and the
%   smoke stage exist to prevent a repeat.

arguments
    design table
    results (:, 1) cell
    protocol (1, 1) struct = r57.config()
end

if numel(results) ~= height(design) || any(cellfun(@isempty, results)) ...
        || any(cellfun(@(item) ~item.success, results))
    error("r57:IncompleteRun", ...
        "R57 requires every row to succeed before summarizing.");
end
methods = ["P_A", "P_FA", "P_FALF", "P_FACR", "P_FACR_A", ...
    "P_FACR_D", "P_FACR_T", "P_FACR_Yonly", "C_enhanced"];
perUser = design(:, ["positionId", "seed", "trialIndex", ...
    "snrDb", "truthThetaDeg", "truthRangeM"]);
for method = methods
    theta = double(cellfun(@(item) double(item.(method).thetaDeg), results));
    rangeM = double(cellfun(@(item) double(item.(method).rangeM), results));
    perUser.("theta_"+method) = theta;
    perUser.("range_"+method) = rangeM;
    perUser.("angleError_"+method) = theta-double(perUser.truthThetaDeg);
    perUser.("rangeError_"+method) = rangeM-double(perUser.truthRangeM);
end
perUser.angleIdentityDifferenceDeg = double(cellfun( ...
    @(item) double(item.angleIdentityDifferenceDeg), results));
perUser.crlbCoherentStdM = double(cellfun( ...
    @(item) double(item.crlbCoherentStdM), results));
perUser.crlbFreeAlphaStdM = double(cellfun( ...
    @(item) double(item.crlbFreeAlphaStdM), results));
perUser.crlbGainFactor = double(cellfun( ...
    @(item) double(item.crlbGainFactor), results));
perUser.coarseSpacingM = double(cellfun( ...
    @(item) double(item.coarseSpacingM), results));
perUser.backendSeconds = double(cellfun( ...
    @(item) double(item.backendSeconds), results));

methodSummary = summarizeMethods(perUser, methods, protocol);
efficiency = efficiencyBySnr(perUser, protocol);
familyToPA = r55.clusterBootstrap(perUser, "P_FACR", "P_A", protocol, 0);
aggregateToPA = r51.bootstrapRatio( ...
    perUser, "P_FACR", "P_A", "range", protocol, 1);
aggregateToPFALF = r51.bootstrapRatio( ...
    perUser, "P_FACR", "P_FALF", "range", protocol, 2);
predictions = predictionTable(perUser, protocol);
gate = buildGate(perUser, efficiency, familyToPA, ...
    aggregateToPA, aggregateToPFALF, protocol);
output = struct(version="R57-PFACR-summary-v1", ...
    perUser=perUser, methodSummary=methodSummary, ...
    efficiency=efficiency, family=familyToPA, ...
    aggregateToPA=aggregateToPA, aggregateToPFALF=aggregateToPFALF, ...
    predictions=predictions, gate=gate, ...
    developmentPass=all(gate.pass(gate.evaluated)));
end

function output = summarizeMethods(perUser, methods, protocol)
output = table();
for method = methods
    for snr = protocol.design.snrDb
        selected = perUser.snrDb == snr;
        ae = perUser.("angleError_"+method)(selected);
        re = perUser.("rangeError_"+method)(selected);
        output = [output; table(method, double(snr), double(nnz(selected)), ...
            double(mean(ae.^2)), double(sqrt(mean(ae.^2))), ...
            double(mean(re.^2)), double(sqrt(mean(re.^2))), ...
            double(median(abs(re))), double(quantile(abs(re), .95)), ...
            double(mean(abs(re) > protocol.gate.missThresholdM)), ...
            'VariableNames', {'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', 'rangeMseM2', 'rangeRmseM', ...
            'rangeMedianAbsM', 'rangeP95AbsM', ...
            'rangeMissRateOver1M'})]; %#ok<AGROW>
    end
end
end

function output = efficiencyBySnr(perUser, protocol)
output = table();
band = protocol.gate.efficiencyBand;
for snr = protocol.design.snrDb
    selected = perUser.snrDb == snr;
    re = perUser.rangeError_P_FACR(selected);
    bound = perUser.crlbCoherentStdM(selected);
    rmse = sqrt(mean(re.^2));
    rmsBound = sqrt(mean(bound.^2));
    ratio = rmse/rmsBound;
    output = [output; table(double(snr), double(nnz(selected)), ...
        double(rmse), double(rmsBound), double(ratio), ...
        ratio >= band(1) && ratio <= band(2), ...
        'VariableNames', {'snrDb', 'n', 'rangeRmseM', ...
        'rmsCrlbM', 'efficiencyRatio', 'pass'})]; %#ok<AGROW>
end
end

function output = predictionTable(perUser, protocol)
tauBand = protocol.gate.tauBranchBandToPFALF;
robustBand = protocol.gate.robustBandToPrimary;
ratio = @(a, b) mean(perUser.("rangeError_"+a).^2) ...
    /mean(perUser.("rangeError_"+b).^2);
entries = ["P1-tau-branch-reproduces-P_FALF", "P_FACR_T", "P_FALF"; ...
    "P2-free-amplitude-is-free", "P_FACR_A", "P_FACR"; ...
    "P2-orthogonal-dispersion-is-free", "P_FACR_D", "P_FACR"; ...
    "diagnostic-array-only-matches-joint", "P_FACR_Yonly", "P_FACR"];
output = table();
for index = 1:size(entries, 1)
    value = ratio(entries(index, 2), entries(index, 3));
    if startsWith(entries(index, 1), "P1")
        band = tauBand;
    else
        band = robustBand;
    end
    output = [output; table(entries(index, 1), entries(index, 2), ...
        entries(index, 3), double(value), double(band(1)), ...
        double(band(2)), value >= band(1) && value <= band(2), ...
        'VariableNames', {'prediction', 'candidate', 'reference', ...
        'mseRatio', 'lower', 'upper', 'withinBand'})]; %#ok<AGROW>
end
end

function output = buildGate(perUser, efficiency, family, ...
    aggregateToPA, aggregateToPFALF, protocol)
limits = protocol.gate;
aggregateRatioToPA = mean(perUser.rangeError_P_FACR.^2) ...
    /mean(perUser.rangeError_P_A.^2);
p95Ratio = quantile(abs(perUser.rangeError_P_FACR), .95) ...
    /quantile(abs(perUser.rangeError_P_FALF), .95);
missDifference = mean(abs(perUser.rangeError_P_FACR) > limits.missThresholdM) ...
    -mean(abs(perUser.rangeError_P_FALF) > limits.missThresholdM);
tauRatio = mean(perUser.rangeError_P_FACR_T.^2) ...
    /mean(perUser.rangeError_P_FALF.^2);

name = ["G1-angle-identity"; "G2-aggregate-mse-ratio-to-PA"; ...
    "G3-aggregate-upper95-to-PA"; "G4-simultaneous-per-snr-to-PA"; ...
    "G5-aggregate-upper95-to-PFALF"; "G6-p95-ratio-to-PFALF"; ...
    "G7-miss-rate-difference"; "G8-tau-branch-reproduces-PFALF"; ...
    "G9-efficiency-against-closed-form-crlb"; ...
    "G10-matched-runtime-ratio-to-C"];
value = double([max(perUser.angleIdentityDifferenceDeg); ...
    aggregateRatioToPA; aggregateToPA.oneSidedUpper95; ...
    max(family.family.simultaneousUpper975); ...
    aggregateToPFALF.oneSidedUpper95; p95Ratio; missDifference; ...
    tauRatio; max(abs(log(efficiency.efficiencyRatio))); NaN]);
pass = [max(perUser.angleIdentityDifferenceDeg) <= limits.maxAngleIdentityDifferenceDeg; ...
    aggregateRatioToPA < limits.maxAggregateRangeMseRatioToPA; ...
    aggregateToPA.oneSidedUpper95 < limits.maxAggregateRangeMseRatioUpper95ToPA; ...
    all(family.family.simultaneousUpper975 < limits.maxSimultaneousPerSnrRangeMseRatioToPA); ...
    aggregateToPFALF.oneSidedUpper95 < limits.maxAggregateRangeMseRatioUpper95ToPFALF; ...
    p95Ratio < limits.maxP95AbsRangeRatioToPFALF; ...
    missDifference <= limits.maxMissRateDifferenceToPFALF; ...
    tauRatio >= limits.tauBranchBandToPFALF(1) ...
        && tauRatio <= limits.tauBranchBandToPFALF(2); ...
    all(efficiency.pass); false];
% G10 needs the separate matched-timing protocol; it is reported as not
% evaluated here rather than silently counted as a pass.
evaluated = [true(9, 1); false];
output = table(name, value, pass, evaluated);
end
