function report = r36AssertSchemeECalibration(project, setup, protocol)
%R36ASSERTSCHEMEECALIBRATION Verify frozen algorithm, evidence and data.

arguments
    project (1, 1) string
    setup (1, 1) struct
    protocol (1, 1) struct = r36SchemeECalibrationProtocol()
end

if ~isequaln(protocol, r36SchemeECalibrationProtocol())
    error("r36:CalibrationProtocolDrift", ...
        "The Scheme E calibration protocol has changed.");
end
r36AssertCommonProtocol(setup.cfg, r36CommonProtocol());
algorithmSource = frozenAlgorithmManifest(project);
algorithmDigest = r32.sourceDigest(algorithmSource);
if algorithmDigest ~= protocol.algorithmDigest
    error("r36:FrozenSchemeEAlgorithmDrift", ...
        "The development-passed Scheme E algorithm has changed.");
end

developmentFolder = fullfile(project, "results", "full_spectrum", ...
    "round36_schemeE_range_orthogonal_v1");
files = ["result.mat", "per_user_outputs.csv", "engineering_gate.csv"];
expected = [protocol.development.resultSha256, ...
    protocol.development.perUserSha256, protocol.development.gateSha256];
for index = 1:numel(files)
    actual = hashFile(project, fullfile(developmentFolder, files(index)));
    if actual ~= expected(index)
        error("r36:DevelopmentEvidenceDrift", ...
            "A frozen Scheme E development artifact has changed.");
    end
end
development = load(fullfile(developmentFolder, "result.mat"), ...
    "identity", "design", "summary");
if ~development.identity.gatePassed ...
        || height(development.design) ~= protocol.development.requiredUsers ...
        || ~development.summary.gatePassed
    error("r36:DevelopmentGateNotSatisfied", ...
        "Scheme E calibration requires the passed 60-user evidence.");
end

counts = groupcounts(setup.design, "snrDb");
dataDigest = setup.dataHash.sha256(1);
designPass = height(setup.design) == protocol.calibration.allUsers ...
    && numel(unique(setup.design.seed)) == protocol.calibration.allUsers ...
    && isequal(sort(counts.snrDb).', sort(protocol.calibration.snrDb)) ...
    && all(counts.GroupCount == protocol.calibration.usersPerSnr) ...
    && dataDigest == protocol.calibration.dataHash;
if ~designPass
    error("r36:CalibrationDesignMismatch", ...
        "The existing 600-user calibration identity does not match.");
end
[found, ~] = ismember(development.design.seed, setup.design.seed);
if ~all(found)
    error("r36:DevelopmentSubsetMismatch", ...
        "The 60 development users must be the fixed subset of 600.");
end
holdout = ~ismember(setup.design.seed, development.design.seed);
holdoutCounts = groupcounts(setup.design(holdout, :), "snrDb");
if nnz(holdout) ~= protocol.calibration.holdoutUsers ...
        || any(holdoutCounts.GroupCount ...
        ~= protocol.calibration.holdoutUsersPerSnr)
    error("r36:CalibrationHoldoutMismatch", ...
        "The fixed non-development calibration subset must be 540 rows.");
end

report = struct(passed=true, algorithmSource=algorithmSource, ...
    algorithmDigest=algorithmDigest, development=development, ...
    developmentMask=~holdout, holdoutMask=holdout, ...
    dataDigest=dataDigest, allRows=height(setup.design), ...
    holdoutRows=nnz(holdout), estimationExecuted=false);
end

function source = frozenAlgorithmManifest(project)
listing = [dir(fullfile(project, "+r36", "common", ...
    "r36CommonProtocol.m")); ...
    dir(fullfile(project, "+r36", "common", ...
    "r36AssertCommonProtocol.m")); ...
    dir(fullfile(project, "+r36", "schemeE", "r36SchemeEConfig.m")); ...
    dir(fullfile(project, "+r36", "schemeE", "r36SteeringDerivatives.m")); ...
    dir(fullfile(project, "+r36", "schemeE", ...
    "r36SubspaceResidualGaussNewton.m")); ...
    dir(fullfile(project, "+r36", "schemeE", ...
    "r36RangeOrthogonalOneStep.m")); ...
    dir(fullfile(project, "+r36", "schemeE", "r36SchemeETrial.m"))];
source = sourceFromListing(project, listing);
end

function digest = hashFile(project, file)
if ~isfile(file)
    error("r36:MissingDevelopmentEvidence", ...
        "A required Scheme E development artifact is missing.");
end
relative = replace(extractAfter(file, strlength(project)+1), ...
    string(filesep), "/");
manifest = fsjad.sourceHashManifest(project, relative);
digest = manifest.sha256(1);
end

function source = sourceFromListing(project, listing)
paths = strings(numel(listing), 1);
for index = 1:numel(listing)
    file = string(fullfile(listing(index).folder, listing(index).name));
    paths(index) = replace(extractAfter(file, strlength(project)+1), ...
        string(filesep), "/");
end
source = fsjad.sourceHashManifest(project, sort(unique(paths)));
end
