function protocol = config()
%CONFIG Freeze the R53 full-aperture likelihood-fusion development study.

protocol.version = "R53-PFALF-development-v1";
protocol.date = "2026-09-18";
protocol.evidenceRole = "independent-distance-backend-development-not-calibration";
protocol.method = struct(primary="P_FALF", base="P_FA", ...
    baseline="P_A", diagnostic="Y_only", ...
    finalAngle="exact-frozen-P_FA-angle", ...
    rangeObjective="conditional-plug-in-two-block-concentrated-ML", ...
    paFree=true, musicFree=true, evdFree=true);
protocol.base = r45.config();

protocol.audit = struct( ...
    zDerivedFromY=false, ...
    sharedNoiseRealization=false, ...
    sequentialNonoverlappingRandomDraws=true, ...
    conditionallyIndependentUnderSimulator=true, ...
    separatelyNormalized=true, ...
    physicalSameReceiverInterpretationEstablished=false, ...
    statisticalModelGate=true, ...
    qualification="valid-under-current-hybrid-simulator-only");

protocol.likelihood = struct( ...
    scalarObservationCountRule="M", ...
    arrayObservationCountRule="N-times-K", ...
    scalarNoiseVariance="unknown-block-specific-common", ...
    arrayNoiseVariance="unknown-block-specific-common", ...
    scalarGain="one-common-complex-beta", ...
    arrayGain="independent-complex-alpha-per-carrier", ...
    scalarSteering="exact-spherical-q", ...
    arraySteering="frozen-full-N-Fresnel", ...
    numericalEnergyFloorScale=100*eps, ...
    noFusionWeight=true);

protocol.profile = protocol.base.r34.r32.profile;
protocol.curvature = struct(rangeStepM=1e-3, curvatureFloor=1e-12, ...
    commonEvaluationPoint="P_FA-q-profile-selected-range", ...
    basinDefinition="nearest-retained-q-coarse-peak-index");
protocol.design = struct(positionCount=30, snrDb=[-10, 0, 20], ...
    angleLimitsDeg=[-60, 60], rangeLimitsM=[15, 50], ...
    positionSeed=68000000, trialSeedRoot=68100000, expectedRows=90);
protocol.bootstrap = struct(count=10000, seed=68200000, ...
    confidence=0.95, cluster="positionId", sharedAcrossSnr=true);
protocol.gate = struct( ...
    maxAngleIdentityDifferenceDeg=1e-12, ...
    maxAggregateRangeMseRatioToPA=0.98, ...
    maxPerSnrRangeMseRatioToPA=1.05, ...
    maxRangeMissRateDifferenceToPA=0, ...
    missThresholdM=1.0, runtimeReference="C_enhanced-standalone");
protocol.timing = struct(positionIds=1:3, snrDb=0, repetitions=2, ...
    warmups=1, methods=["P_FALF", "C_enhanced"]);
protocol.execution = struct(recommendedWorkers=8, batchSize=6, ...
    finalRowsAccessible=false, calibrationAllowed=false, ...
    priorR51R52RowsAccessible=false, parameterTuningAllowed=false, ...
    modifyFrozenPFA=false, stopAfterDevelopment=true);
end
