function output = summarize(design, results, protocol)
%SUMMARIZE Build R53 performance, mechanism, bootstrap, and gate tables.

arguments
    design table
    results (:, 1) cell
    protocol (1, 1) struct = r53.config()
end

if numel(results) ~= height(design) || any(cellfun(@isempty, results)) ...
        || any(cellfun(@(item) ~item.success, results))
    error("r53:IncompleteDevelopment", ...
        "R53 requires every development row to succeed.");
end
methods = ["P_A", "P_FA", "Y_only", "P_FALF"];
perUser = design(:, ["positionId", "seed", "trialIndex", ...
    "snrDb", "truthThetaDeg", "truthRangeM"]);
for method = methods
    theta = cellfun(@(item) item.(method).thetaDeg, results);
    rangeM = cellfun(@(item) item.(method).rangeM, results);
    perUser.("theta_"+method) = theta;
    perUser.("range_"+method) = rangeM;
    perUser.("angleError_"+method) = theta-perUser.truthThetaDeg;
    perUser.("rangeError_"+method) = rangeM-perUser.truthRangeM;
end
perUser.angleIdentityDifferenceDeg = cellfun( ...
    @(item) item.angleIdentityDifferenceDeg, results);
perUser.rangeShiftM = cellfun(@(item) item.rangeShiftM, results);
perUser.qPeakChanged = cellfun(@(item) item.qPeakChanged, results);
perUser.yOnlyZBasinAgreement = cellfun( ...
    @(item) item.yOnlyZBasinAgreement, results);
perUser.hessianZAtPFA = cellfun( ...
    @(item) item.commonCurvature.hessianZ, results);
perUser.hessianYAtPFA = cellfun( ...
    @(item) item.commonCurvature.hessianY, results);
perUser.hessianJointAtPFA = cellfun( ...
    @(item) item.commonCurvature.hessianJoint, results);
perUser.curvatureRatioYToZ = cellfun( ...
    @(item) item.commonCurvature.curvatureRatioYToZ, results);
perUser.hessianJointAtSelected = cellfun( ...
    @(item) item.selectedCurvature.hessianJoint, results);
perUser.pfaBackendSeconds = cellfun( ...
    @(item) item.runtime.pfaBackendSeconds, results);
perUser.jointProfileSeconds = cellfun( ...
    @(item) item.runtime.jointProfileSeconds, results);
perUser.yDiagnosticSeconds = cellfun( ...
    @(item) item.runtime.yDiagnosticSeconds, results);

methodSummary = summarizeMethods(perUser, methods, protocol);
comparisons = compareAll(perUser, protocol);
bootstrap = [ ...
    r51.bootstrapRatio(perUser, "P_FALF", "P_A", "range", protocol, 1); ...
    r51.bootstrapRatio(perUser, "P_FALF", "P_FA", "range", protocol, 2)];
mechanism = mechanismSummary(perUser);
gate = buildGate(perUser, comparisons, protocol);
output = struct(version="R53-PFALF-summary-v1", perUser=perUser, ...
    methodSummary=methodSummary, comparisons=comparisons, ...
    bootstrap=bootstrap, mechanism=mechanism, gate=gate, ...
    developmentPass=all(gate.pass));
end

function output = summarizeMethods(perUser, methods, protocol)
output = table();
for method = methods
    for snr = protocol.design.snrDb
        selected = perUser.snrDb == snr;
        ae = perUser.("angleError_"+method)(selected);
        re = perUser.("rangeError_"+method)(selected);
        output = [output; table(method, snr, nnz(selected), ...
            mean(ae.^2), sqrt(mean(ae.^2)), mean(re.^2), ...
            sqrt(mean(re.^2)), median(abs(re)), quantile(abs(re), .90), ...
            quantile(abs(re), .95), ...
            mean(abs(re)>protocol.gate.missThresholdM), ...
            'VariableNames', {'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', 'rangeMseM2', ...
            'rangeRmseM', 'rangeMedianAbsM', 'rangeP90AbsM', ...
            'rangeP95AbsM', 'rangeMissRateOver1M'})]; %#ok<AGROW>
    end
end
end

function output = compareAll(perUser, protocol)
output = table();
for candidate = ["P_FA", "Y_only", "P_FALF"]
    for reference = ["P_A", "P_FA"]
        candidateMse = zeros(numel(protocol.design.snrDb), 1);
        referenceMse = zeros(numel(protocol.design.snrDb), 1);
        for index = 1:numel(protocol.design.snrDb)
            snr = protocol.design.snrDb(index);
            selected = perUser.snrDb == snr;
            ce = perUser.("rangeError_"+candidate)(selected).^2;
            re = perUser.("rangeError_"+reference)(selected).^2;
            candidateMse(index) = mean(ce);
            referenceMse(index) = mean(re);
            output = [output; comparisonRow( ...
                candidate, reference, "per-SNR", snr, ce, re)]; %#ok<AGROW>
        end
        ce = perUser.("rangeError_"+candidate).^2;
        re = perUser.("rangeError_"+reference).^2;
        row = comparisonRow(candidate, reference, "equal-SNR", ...
            nan, ce, re);
        row.rangeMseRatio = mean(candidateMse)/mean(referenceMse);
        row.rangeRmseDifferenceMm = 1000*(sqrt(mean(candidateMse)) ...
            -sqrt(mean(referenceMse)));
        output = [output; row]; %#ok<AGROW>
    end
end
end

function output = comparisonRow(candidate, reference, scope, snrDb, ce, re)
output = table(candidate, reference, scope, snrDb, numel(ce), ...
    mean(ce)/mean(re), 1000*(sqrt(mean(ce))-sqrt(mean(re))), ...
    nnz(ce<re), nnz(ce==re), nnz(ce>re), mean(ce-re), ...
    'VariableNames', {'candidate', 'reference', 'scope', 'snrDb', 'n', ...
    'rangeMseRatio', 'rangeRmseDifferenceMm', 'winCount', ...
    'tieCount', 'lossCount', 'meanSquaredErrorDifference'});
end

function output = mechanismSummary(perUser)
validRatio = isfinite(perUser.curvatureRatioYToZ);
ratio = perUser.curvatureRatioYToZ(validRatio);
if isempty(ratio)
    ratioQuartiles = [nan, nan, nan];
else
    ratioQuartiles = [quantile(ratio, .25), median(ratio), ...
        quantile(ratio, .75)];
end
output = table(height(perUser), mean(perUser.qPeakChanged), ...
    mean(perUser.yOnlyZBasinAgreement), rms(perUser.rangeShiftM), ...
    median(abs(perUser.rangeShiftM)), ratioQuartiles(2), ...
    ratioQuartiles(1), ratioQuartiles(3), ...
    mean(perUser.hessianZAtPFA<0), mean(perUser.hessianYAtPFA<0), ...
    mean(perUser.hessianJointAtSelected<0), ...
    'VariableNames', {'n', 'qPeakChangeRate', ...
    'yOnlyZBasinAgreementRate', 'rangeShiftRmsM', ...
    'rangeShiftMedianAbsM', 'curvatureRatioMedian', ...
    'curvatureRatioQ25', 'curvatureRatioQ75', ...
    'negativeZCurvatureRate', 'negativeYCurvatureRate', ...
    'negativeSelectedJointCurvatureRate'});
end

function output = buildGate(perUser, comparisons, protocol)
primary = comparisons(comparisons.candidate == "P_FALF" ...
    & comparisons.reference == "P_A", :);
aggregate = primary(primary.scope == "equal-SNR", :);
perSnr = primary(primary.scope == "per-SNR", :);
missF = mean(abs(perUser.rangeError_P_FALF)>protocol.gate.missThresholdM);
missA = mean(abs(perUser.rangeError_P_A)>protocol.gate.missThresholdM);
metric = ["statistical-model-gate"; "angle-identity-max-deg"; ...
    "aggregate-range-MSE/P_A"; "max-per-SNR-range-MSE/P_A"; ...
    "range-miss-rate-difference-to-P_A"];
value = [double(protocol.audit.statisticalModelGate); ...
    max(perUser.angleIdentityDifferenceDeg); aggregate.rangeMseRatio; ...
    max(perSnr.rangeMseRatio); missF-missA];
direction = [">="; "<="; "<="; "<="; "<="];
limit = [1; protocol.gate.maxAngleIdentityDifferenceDeg; ...
    protocol.gate.maxAggregateRangeMseRatioToPA; ...
    protocol.gate.maxPerSnrRangeMseRatioToPA; ...
    protocol.gate.maxRangeMissRateDifferenceToPA];
pass = value <= limit;
pass(1) = value(1) >= limit(1);
output = table(metric, value, direction, limit, pass);
output.notes = repmat("predeclared-R53-development-gate", height(output), 1);
end
