function protocol = config()
%CONFIG Frozen R42 Scheme H development protocol.

protocol.version = "R42-schemeH-pa-free-joint-development-v1";
protocol.date = "2026-09-17";
protocol.evidenceRole = "new-development-not-independent-final";
protocol.method = struct(primary="H_joint", ablation="H_array", ...
    baseline="P_A", frontControl="F_L06");
r32Protocol = r32.config();
protocol.front = r32Protocol.front;
protocol.array = struct(carrierCount=2047, angleHalfWidthDeg=0.2, ...
    coarseAngleGridSize=41, tolXDeg=1e-7);
protocol.joint = struct(numStarts=3, maxIterations=8, ...
    angleScaleRad=deg2rad(0.02), rangeScaleM=0.25, ...
    maximumScaledStep=1, stepTolerance=1e-5, ...
    gradientTolerance=1e-6, armijo=1e-4, maxBacktracks=12, ...
    damping=[1e-8, 1e-5, 1e-2, 1, 100], ...
    energyFloorScale=1000*eps, costToleranceScale=1000*eps);
protocol.profile = r32Protocol.profile;
protocol.development = struct(snrDb=[-10, 0, 20], ...
    pilotPositionCount=10, expandedPositionCount=20, ...
    positionSeed=56000000, trialSeedRoot=56100000, ...
    angleLimitsDeg=[-55, 55], rangeLimitsM=[17, 48], ...
    missThresholdM=1);
protocol.gate = struct(maxPerSnrAngleMseRatio=1.05, ...
    maxAggregateAngleMseRatio=0.98, ...
    maxPerSnrRangeMseRatio=1.05, ...
    maxAggregateRangeMseRatio=0.99);
protocol.execution = struct(r34FinalReadAllowed=false, ...
    r41FinalReadAllowed=false, finalTrialsExecuted=0, ...
    parameterTuningFromPilotAllowed=false, ...
    calibrationAuthorized=false, independentFinalAuthorized=false);
end
