function context = prepareContext(cfg, scan, observation, snapshots, carrierIndex)
%PREPARECONTEXT Cache invariants for the PA-free joint objective.

arguments
    cfg (1, 1) struct
    scan (1, 1) struct
    observation (:, 1) double {mustBeFinite}
    snapshots (:, :) double
    carrierIndex (:, 1) double {mustBeInteger, mustBeNonnegative}
end

if numel(observation) ~= cfg.numSubcarriers ...
        || size(snapshots, 1) ~= cfg.numAntennas ...
        || size(snapshots, 2) ~= numel(carrierIndex) ...
        || any(carrierIndex >= cfg.numSubcarriers)
    error("r42:ContextSize", ...
        "Scheme H requires full z and an N-by-K selected snapshot matrix.");
end
[~, ~, frequencyHz] = jad.trajectory(cfg, carrierIndex);
x = cfg.elementIndex*cfg.elementSpacing;
snapshotEnergy = real(sum(abs(snapshots).^2, 1));
totalEnergy = sum(snapshotEnergy);
context = struct(version="R42-joint-context-v1", scan=scan, ...
    observation=observation, snapshots=snapshots, ...
    carrierIndex=carrierIndex, frequencyHz=frequencyHz(:).', ...
    wavenumber=2*pi*frequencyHz(:).'/cfg.c, x=x, xSquared=x.^2, ...
    arrayNormalization=sqrt(cfg.numAntennas), ...
    numAntennas=cfg.numAntennas, ...
    scalarCount=cfg.numSubcarriers, ...
    arrayCount=cfg.numAntennas*numel(carrierIndex), ...
    carrierCount=numel(carrierIndex), ...
    observationEnergy=real(observation'*observation), ...
    snapshotEnergy=snapshotEnergy, totalEnergy=totalEnergy);
if context.observationEnergy <= 0 || context.totalEnergy <= 0
    error("r42:ZeroEnergy", "Scheme H observations must have positive energy.");
end
end
