function output = summarize(design, results, protocol)
%SUMMARIZE Build paired R42 performance tables and engineering gates.

arguments
    design table
    results (:, 1) cell
    protocol (1, 1) struct = r42.config()
end

if height(design) ~= numel(results) || ~all(cellfun(@(x) x.success, results))
    error("r42:IncompleteResults", ...
        "R42 summary requires one successful result per design row.");
end
methods = ["P_A", "H_array", "H_joint", "F_L06"];
numMethods = numel(methods);
numRows = height(design)*numMethods;
positionId = repelem(design.positionId, numMethods);
seed = repelem(design.seed, numMethods);
snrDb = repelem(design.snrDb, numMethods);
truthThetaDeg = repelem(design.truthThetaDeg, numMethods);
truthRangeM = repelem(design.truthRangeM, numMethods);
method = repmat(methods(:), height(design), 1);
thetaDeg = zeros(numRows, 1);
rangeM = zeros(numRows, 1);
runtimeSeconds = zeros(numRows, 1);
for row = 1:height(design)
    indices = (row-1)*numMethods+(1:numMethods);
    thetaDeg(indices) = results{row}.thetaDeg(:);
    rangeM(indices) = results{row}.rangeM(:);
    runtimeSeconds(indices) = results{row}.runtimeSeconds(:);
end
angleErrorDeg = thetaDeg-truthThetaDeg;
rangeErrorM = rangeM-truthRangeM;
positionErrorM = hypot(rangeErrorM, ...
    truthRangeM.*deg2rad(angleErrorDeg));
perUser = table(positionId, seed, snrDb, method, truthThetaDeg, ...
    truthRangeM, thetaDeg, rangeM, angleErrorDeg, rangeErrorM, ...
    positionErrorM, runtimeSeconds);

summary = table();
for methodName = methods
    for snr = protocol.development.snrDb
        rows = perUser.method == methodName & perUser.snrDb == snr;
        part = metricRow(perUser(rows, :), methodName, snr, ...
            protocol.development.missThresholdM);
        summary = [summary; part]; %#ok<AGROW>
    end
end

comparison = table();
for snr = protocol.development.snrDb
    pa = perUser(perUser.method == "P_A" & perUser.snrDb == snr, :);
    h = perUser(perUser.method == "H_joint" & perUser.snrDb == snr, :);
    comparison = [comparison; comparisonRow(pa, h, snr)]; %#ok<AGROW>
end
paAll = perUser(perUser.method == "P_A", :);
hAll = perUser(perUser.method == "H_joint", :);
aggregate = comparisonRow(paAll, hAll, nan);
anglePass = all(comparison.angleMseRatio <= ...
    protocol.gate.maxPerSnrAngleMseRatio) ...
    && aggregate.angleMseRatio <= protocol.gate.maxAggregateAngleMseRatio;
rangePass = all(comparison.rangeMseRatio <= ...
    protocol.gate.maxPerSnrRangeMseRatio) ...
    && aggregate.rangeMseRatio <= protocol.gate.maxAggregateRangeMseRatio;
monotone = all(cellfun(@(x) x.h.joint.cost <= x.h.joint.initialCost ...
    +protocol.joint.costToleranceScale*max(1, abs(x.h.joint.initialCost)), ...
    results));
gate = table(anglePass, rangePass, monotone, ...
    anglePass && rangePass && monotone, ...
    'VariableNames', {'anglePass', 'rangePass', ...
    'monotonePass', 'pilotPass'});
output = struct(perUser=perUser, summary=summary, ...
    comparison=comparison, aggregate=aggregate, gate=gate);
end

function row = metricRow(input, method, snrDb, missThreshold)
angleAbs = abs(input.angleErrorDeg);
rangeAbs = abs(input.rangeErrorM);
row = table(method, snrDb, height(input), ...
    mean(input.angleErrorDeg.^2), sqrt(mean(input.angleErrorDeg.^2)), ...
    median(angleAbs), prctile(angleAbs, 90), prctile(angleAbs, 95), ...
    mean(input.rangeErrorM.^2), sqrt(mean(input.rangeErrorM.^2)), ...
    median(rangeAbs), prctile(rangeAbs, 90), prctile(rangeAbs, 95), ...
    mean(rangeAbs > missThreshold), sqrt(mean(input.positionErrorM.^2)), ...
    mean(input.runtimeSeconds), ...
    'VariableNames', {'method', 'snrDb', 'n', ...
    'angleMseDeg2', 'angleRmseDeg', 'angleMedianAbsDeg', ...
    'angleP90AbsDeg', 'angleP95AbsDeg', 'rangeMseM2', ...
    'rangeRmseM', 'rangeMedianAbsM', 'rangeP90AbsM', ...
    'rangeP95AbsM', 'rangeMissRate', 'positionRmseM', ...
    'meanRuntimeSeconds'});
end

function row = comparisonRow(pa, h, snrDb)
anglePa = pa.angleErrorDeg.^2;
angleH = h.angleErrorDeg.^2;
rangePa = pa.rangeErrorM.^2;
rangeH = h.rangeErrorM.^2;
angleRatio = mean(angleH)/mean(anglePa);
rangeRatio = mean(rangeH)/mean(rangePa);
row = table(snrDb, angleRatio, 100*(1-sqrt(angleRatio)), ...
    rangeRatio, 100*(1-sqrt(rangeRatio)), ...
    sum(angleH < anglePa), sum(angleH == anglePa), sum(angleH > anglePa), ...
    sum(rangeH < rangePa), sum(rangeH == rangePa), sum(rangeH > rangePa), ...
    'VariableNames', {'snrDb', 'angleMseRatio', ...
    'angleRmseImprovementPct', 'rangeMseRatio', ...
    'rangeRmseImprovementPct', 'angleWins', 'angleTies', ...
    'angleLosses', 'rangeWins', 'rangeTies', 'rangeLosses'});
end
