classdef deterministicMultipeakFrontTest < matlab.unittest.TestCase
    %DETERMINISTICMULTIPEAKFRONTTEST Deterministic front candidate tests.

    methods (TestClassSetup)
        function addSourcePath(testCase)
            sourceFolder = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                sourceFolder));
        end
    end

    methods (Test)
        function retainsEndpointsAndMultiplePeaks(testCase)
            [cfg, scan, observation] = reducedObservation();
            estimate = fsjad.deterministicMultipeakFrontEstimate( ...
                cfg, observation, scan, 0, IterationCaps=[4, 8], ...
                InitialSpacingM=0.1, MinimumIntervals=20, ...
                RefinementLevels=2, PeakCount=4, ...
                StepTolerance=1e-5, KeepTrace=true);

            testCase.verifyEqual(estimate.version, ...
                "FS-Front-Deterministic-Multipeak-R28-v2");
            testCase.verifyTrue(any(abs(estimate.candidateBank.rangeM ...
                - cfg.rangeLimitsM(1)) <= 1e-12));
            testCase.verifyTrue(any(abs(estimate.candidateBank.rangeM ...
                - cfg.rangeLimitsM(2)) <= 1e-12));
            testCase.verifyGreaterThan(height(estimate.candidateBank), 3);
            testCase.verifyEqual(estimate.iterationCaps, [4, 8]);
        end

        function repeatedCallsAreDeterministic(testCase)
            [cfg, scan, observation] = reducedObservation();
            first = fsjad.deterministicMultipeakFrontEstimate( ...
                cfg, observation, scan, [-0.05; 0.05], ...
                IterationCaps=5, InitialSpacingM=0.15, ...
                MinimumIntervals=15, RefinementLevels=2, ...
                PeakCount=3, StepTolerance=1e-5);
            second = fsjad.deterministicMultipeakFrontEstimate( ...
                cfg, observation, scan, [-0.05; 0.05], ...
                IterationCaps=5, InitialSpacingM=0.15, ...
                MinimumIntervals=15, RefinementLevels=2, ...
                PeakCount=3, StepTolerance=1e-5);

            testCase.verifyEqual(first.candidateBank, second.candidateBank, ...
                AbsTol=1e-12);
            testCase.verifyEqual(first.summary.finalThetaDeg, ...
                second.summary.finalThetaDeg, AbsTol=1e-12);
            testCase.verifyEqual(first.summary.finalRangeM, ...
                second.summary.finalRangeM, AbsTol=1e-12);
            testCase.verifyEqual(first.summary.objective, ...
                second.summary.objective, AbsTol=1e-14);
        end

        function rejectsUnorderedIterationCaps(testCase)
            [cfg, scan, observation] = reducedObservation();
            action = @() fsjad.deterministicMultipeakFrontEstimate( ...
                cfg, observation, scan, 0, IterationCaps=[8, 4]);

            testCase.verifyError(action, "fsjad:DeterministicFrontCaps");
        end

        function retainsFrozenFeasibleStart(testCase)
            [cfg, scan, observation] = reducedObservation();
            frozen = table("old_start", 12.25, 20.35, ...
                'VariableNames', {'source', 'thetaDeg', 'rangeM'});
            estimate = fsjad.deterministicMultipeakFrontEstimate( ...
                cfg, observation, scan, 0, IterationCaps=3, ...
                InitialSpacingM=0.2, MinimumIntervals=10, ...
                RefinementLevels=1, PeakCount=2, ...
                FeasibleCandidates=frozen);

            row = estimate.candidateBank.source == "old_start";
            testCase.verifyEqual(nnz(row), 1);
            testCase.verifyEqual(estimate.candidateBank.thetaDeg(row), ...
                12.25, AbsTol=1e-12);
            testCase.verifyEqual(estimate.candidateBank.rangeM(row), ...
                20.35, AbsTol=1e-12);
        end
    end
end

function [cfg, scan, observation] = reducedObservation()
cfg = jad.defaultConfig();
cfg.numAntennas = 24;
cfg.numSubcarriers = 33;
cfg.elementIndex = (0:cfg.numAntennas-1).'-(cfg.numAntennas-1)/2;
cfg.subarraySize = 12;
cfg.numSubarrays = cfg.numAntennas-cfg.subarraySize+1;
cfg.rangeLimitsM = [18, 22];
scan = fsjad.prepareScan(cfg);
observation = fsjad.exactSpectralResponse( ...
    cfg, deg2rad(12.3), 20.2, scan);
end
