classdef round35AngleImprovementIdentityTest < matlab.unittest.TestCase
    %ROUND35ANGLEIMPROVEMENTIDENTITYTEST Static R35 protocol identity tests.

    properties (SetAccess = private)
        MatlabRoot string
    end

    methods (TestClassSetup)
        function addR35Paths(testCase)
            testCase.MatlabRoot = string(fileparts(fileparts( ...
                mfilename("fullpath"))));
            commonRoot = fullfile(testCase.MatlabRoot, ...
                "+r35", "common");
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                testCase.MatlabRoot));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                commonRoot));
        end
    end

    methods (Test)
        function frozenIdentityPassesWithoutEstimation(testCase)
            protocol = r35CommonProtocol();
            report = r35AssertCommonProtocol( ...
                jad.defaultConfig(), protocol);

            testCase.verifyTrue(report.passed);
            testCase.verifyFalse(report.estimationExecuted);
            testCase.verifyEqual(report.evidenceRole, ...
                "development-calibration-evidence-only");
            testCase.verifyEqual(protocol.system, ...
                struct(N=256, M=2048, K=2047, L=160, P=97, ...
                thetaLimitsDeg=[-60, 60], rangeLimitsM=[15, 50]));
            testCase.verifyFalse(protocol.algorithm.useGram);
            testCase.verifyTrue(protocol.rangeProfile.rerunAfterAnyNewAngle);
            testCase.verifyFalse(protocol.data.r34FinalReuseAllowed);
        end

        function systemDriftIsRejected(testCase)
            cfg = jad.defaultConfig();
            cfg.numAntennas = 255;

            testCase.verifyError( ...
                @() r35AssertCommonProtocol(cfg, r35CommonProtocol()), ...
                "r32:FrozenConfigurationMismatch");
        end

        function protocolRelaxationIsRejected(testCase)
            protocol = r35CommonProtocol();
            protocol.engineeringGate.maximumPerSnrAngleMseRatioToPA = 1.02;

            testCase.verifyError( ...
                @() r35AssertCommonProtocol(jad.defaultConfig(), protocol), ...
                "r35:CommonProtocolDrift");
        end

        function schemesAThroughDAreIsolated(testCase)
            schemeA = fullfile(testCase.MatlabRoot, "+r35", "schemeA");
            schemeB = fullfile(testCase.MatlabRoot, "+r35", "schemeB");
            schemeD = fullfile(testCase.MatlabRoot, "+r35", "schemeD");
            schemeAFiles = string({dir(fullfile(schemeA, "*.m")).name});
            schemeBFiles = string({dir(fullfile(schemeB, "*.m")).name});
            schemeDFiles = string({dir(fullfile(schemeD, "*.m")).name});

            testCase.verifyTrue(isfolder(schemeA));
            testCase.verifyTrue(isfolder(schemeB));
            testCase.verifyTrue(isfolder(schemeD));
            testCase.verifyEqual(sort(schemeAFiles), sort([ ...
                "r35BracketedMusicRefinement.m", "r35SchemeAConfig.m", ...
                "r35SchemeATrial.m", "r35SummarizeSchemeA.m"]));
            testCase.verifyEqual(sort(schemeBFiles), sort([ ...
                "r35BracketedSpectralRefinement.m", ...
                "r35BuildSchemeBFigures.m", "r35SchemeBConfig.m", ...
                "r35SchemeBPrimaryTrial.m", ...
                "r35SchemeBRangeRefreshTrial.m", ...
                "r35SummarizeSchemeB.m", ...
                "r35SummarizeSchemeBRefresh.m"]));
            testCase.verifyEqual(sort(schemeDFiles), sort([ ...
                "r35AngleSteeringDerivative.m", "r35AssertD0Identity.m", ...
                "r35BuildCarrierWeights.m", "r35BuildSchemeDFigures.m", ...
                "r35SchemeDBaselineTrial.m", "r35SchemeDConfig.m", ...
                "r35SchemeDWeightedTrial.m", ...
                "r35SingleCarrierMusicLogScores.m", ...
                "r35StagedWeightedAngleMusic.m", ...
                "r35SummarizeSchemeD.m"]));
        end
    end
end
