function result = backend(cfg, observation, snapshots, scan, front, protocol)
%BACKEND Run frozen hard P_FA and selected P_FAM5 from one L06 front.

arguments
    cfg (1, 1) struct
    observation (:, 1) double {mustBeFinite}
    snapshots (:, :) double
    scan (1, 1) struct
    front (1, 1) struct
    protocol (1, 1) struct = r48.config()
end

timer = tic;
r45Protocol = protocol.r47.r45;
carrierIndex = r30.selectLocalCarriers(cfg.numSubcarriers, ...
    r45Protocol.pfa.carrierCount, front.peakCarrierIndex);
context = r38PrepareRawArrayVpmlContext(cfg, ...
    snapshots(:, carrierIndex+1), carrierIndex);
angle = r45.fullArrayAngle(cfg, context, front.selected, r45Protocol);
hard = r33.profileAtAngle(cfg, observation, scan, angle.thetaDeg, ...
    front.selected.rangeM, r45Protocol.r34.r33);
uncertainty = r47.angleUncertainty(cfg, context, angle.thetaDeg, ...
    front.selected.rangeM, protocol.r47);
marginal = r47.marginalProfile(cfg, observation, scan, angle.thetaDeg, ...
    uncertainty.sigmaDeg, front.selected.rangeM, ...
    protocol.r47.quadrature.GH5, protocol.r47);
result = struct(version=protocol.version, thetaDeg=angle.thetaDeg, ...
    hardRangeM=hard.value, marginalRangeM=marginal.value, ...
    frontThetaDeg=front.selected.thetaDeg, ...
    frontRangeM=front.selected.rangeM, carrierIndex=carrierIndex, ...
    angle=angle, uncertainty=uncertainty, ...
    hardProfile=compact(hard), marginalProfile=compact(marginal), ...
    marginalResponseEvaluations=marginal.qOnlyResponseEvaluations, ...
    totalBackendSeconds=toc(timer), musicEvaluationCount=0, evdCount=0);
end

function output = compact(input)
output = struct(value=input.value, score=input.score, ...
    interval=input.interval, endpointHit=input.endpointHit, ...
    nearBoundary=input.nearBoundary, evaluationCount=input.evaluationCount, ...
    retentionMargin=input.retentionMargin);
end
