function protocol = config()
%CONFIG Freeze the selected P_FAM5 Calibration-600 protocol.

protocol.version = "R48-PFAM5-calibration600-v1";
protocol.date = "2026-09-17";
protocol.evidenceRole = "post-R47-calibration-not-final-evidence";
protocol.method = struct(primary="P_FAM5", hardReference="P_FA", ...
    mainReference="P_A", secondary=["G_schur", "C_enhanced"], ...
    quadrature="R47-GH5-frozen", paFree=true, musicFree=true, evdFree=true);
protocol.r47 = r47.config();
protocol.design = struct(positionCount=200, snrDb=[-10, 0, 20], ...
    angleLimitsDeg=[-60, 60], rangeLimitsM=[15, 50], ...
    positionSeed=63000000, trialSeedRoot=63100000, ...
    diagnosticPositionIds=1:20, holdoutPositionIds=21:200, ...
    expectedRows=600);
protocol.bootstrap = struct(count=10000, seed=63200000, ...
    confidence=.95, cluster="positionId", sharedIndicesAcrossSnr=true, ...
    paUpperLimit=1.02, hardUpperLimit=1.00);
protocol.gate = struct(maxPerSnrRangeRatioToPA=1.02, ...
    maxAggregateRangeRatioToPA=1.01, ...
    maxPerSnrRangeRatioToHardPFA=1.01, ...
    maxAggregateRangeRatioToHardPFA=1.00, ...
    requireAngleIdentity=true, requireZeroFailures=true);
protocol.execution = struct(r34FinalReadAllowed=false, ...
    r41FinalReadAllowed=false, r46FinalReadAllowed=false, ...
    priorEstimateRowsReadAllowed=false, parameterTuningAllowed=false, ...
    failedTrialStopsCalibration=true, finalTrialsExecuted=0);
end
