function output = summarize(design, results, protocol)
%SUMMARIZE Build R48 calibration tables and frozen decisions.

arguments
    design table
    results (:, 1) cell
    protocol (1, 1) struct = r48.config()
end

if numel(results) ~= height(design) || any(cellfun(@isempty, results)) ...
        || any(cellfun(@(item) ~item.success, results))
    error("r48:IncompleteCalibration", ...
        "R48 summary requires all frozen rows to succeed.");
end
perUser = design(:, ["positionId", "seed", "trialIndex", ...
    "snrDb", "truthThetaDeg", "truthRangeM", "subset"]);
methods = ["P_FAM5", "P_FA", "P_A", "G_schur", "C_enhanced"];
for method = methods
    theta = cellfun(@(item) item.(method).thetaDeg, results);
    rangeM = cellfun(@(item) item.(method).rangeM, results);
    perUser.("theta_"+method) = theta;
    perUser.("range_"+method) = rangeM;
    perUser.("angleError_"+method) = theta-perUser.truthThetaDeg;
    perUser.("rangeError_"+method) = rangeM-perUser.truthRangeM;
end
perUser.sigmaThetaDeg = cellfun( ...
    @(item) item.backend.uncertainty.sigmaDeg, results);
perUser.hardEndpointHit = cellfun( ...
    @(item) item.backend.hardProfile.endpointHit, results);
perUser.marginalEndpointHit = cellfun( ...
    @(item) item.backend.marginalProfile.endpointHit, results);
perUser.marginalResponses = cellfun( ...
    @(item) item.backend.marginalResponseEvaluations, results);
perUser.backendSeconds = cellfun( ...
    @(item) item.backend.totalBackendSeconds, results);
perUser.sharedGramCount = cellfun( ...
    @(item) item.sharedAudit.totalGramCount, results);
perUser.sharedFallbackCount = cellfun( ...
    @(item) item.sharedAudit.totalFallbackCount, results);

all600 = populationSummary(perUser, "all600", protocol, 0);
holdout = populationSummary(perUser(perUser.subset == "holdout540", :), ...
    "holdout540", protocol, 1);
diagnostic = populationSummary( ...
    perUser(perUser.subset == "diagnostic60", :), ...
    "diagnostic60", protocol, 2);
identityPass = all(perUser.theta_P_FAM5 == perUser.theta_P_FA) ...
    && all(perUser.sharedGramCount == 0) ...
    && all(perUser.sharedFallbackCount == 0) ...
    && all(isfinite(perUser.range_P_FAM5));
calibrationReady = all(all600.gate.pass) && all(holdout.gate.pass) ...
    && all(all600.bootstrap.summary.pass) ...
    && all(holdout.bootstrap.summary.pass) && identityPass;
decision = table(all(all600.gate.pass), all(holdout.gate.pass), ...
    all(all600.bootstrap.summary.pass), ...
    all(holdout.bootstrap.summary.pass), identityPass, ...
    calibrationReady, 'VariableNames', {'all600EngineeringPass', ...
    'holdout540EngineeringPass', 'all600BootstrapPass', ...
    'holdout540BootstrapPass', 'identityPass', 'calibrationReady'});
output = struct(version="R48-PFAM5-calibration-summary-v1", ...
    perUser=perUser, all600=all600, holdout540=holdout, ...
    diagnostic60=diagnostic, decision=decision, ...
    calibrationReady=calibrationReady);
end

function output = populationSummary(perUser, population, protocol, seedOffset)
methods = ["P_FAM5", "P_FA", "P_A", "G_schur", "C_enhanced"];
methodSummary = table();
for method = methods
    for snr = protocol.design.snrDb
        selected = perUser.snrDb == snr;
        ae = perUser.("angleError_"+method)(selected);
        re = perUser.("rangeError_"+method)(selected);
        methodSummary = [methodSummary; table(method, snr, nnz(selected), ...
            mean(ae.^2), sqrt(mean(ae.^2)), mean(re.^2), ...
            sqrt(mean(re.^2)), median(abs(re)), quantile(abs(re), .95), ...
            'VariableNames', {'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', 'rangeMseM2', ...
            'rangeRmseM', 'rangeMedianAbsM', 'rangeP95AbsM'})]; %#ok<AGROW>
    end
end
comparisons = [compareRange(perUser, "P_A", protocol.design.snrDb); ...
    compareRange(perUser, "P_FA", protocol.design.snrDb); ...
    compareRange(perUser, "G_schur", protocol.design.snrDb); ...
    compareRange(perUser, "C_enhanced", protocol.design.snrDb)];
gate = engineeringGate(comparisons, population, protocol);
bootstrap = r48.clusterBootstrap(perUser, protocol, seedOffset);
diagnostics = table(population, height(perUser), ...
    min(perUser.sigmaThetaDeg), median(perUser.sigmaThetaDeg), ...
    max(perUser.sigmaThetaDeg), sum(perUser.hardEndpointHit), ...
    sum(perUser.marginalEndpointHit), mean(perUser.marginalResponses), ...
    mean(perUser.backendSeconds), 'VariableNames', {'population', 'n', ...
    'minimumSigmaThetaDeg', 'medianSigmaThetaDeg', ...
    'maximumSigmaThetaDeg', 'hardEndpointHits', ...
    'marginalEndpointHits', 'meanMarginalResponses', ...
    'meanBackendSeconds'});
output = struct(population=population, methodSummary=methodSummary, ...
    comparisons=comparisons, gate=gate, bootstrap=bootstrap, ...
    diagnostics=diagnostics);
end

function output = compareRange(perUser, reference, snrValues)
output = table();
cMse = zeros(numel(snrValues), 1);
rMse = zeros(numel(snrValues), 1);
for index = 1:numel(snrValues)
    snr = snrValues(index);
    selected = perUser.snrDb == snr;
    c = perUser.rangeError_P_FAM5(selected).^2;
    r = perUser.("rangeError_"+reference)(selected).^2;
    cMse(index) = mean(c);
    rMse(index) = mean(r);
    output = [output; comparisonRow(reference, "per-SNR", snr, c, r)]; %#ok<AGROW>
end
allC = perUser.rangeError_P_FAM5.^2;
allR = perUser.("rangeError_"+reference).^2;
ratio = mean(cMse)/mean(rMse);
output = [output; table("P_FAM5", reference, "equal-SNR", nan, ...
    height(perUser), mean(cMse), mean(rMse), ratio, ...
    100*(1-sqrt(ratio)), nnz(allC < allR), nnz(allC == allR), ...
    nnz(allC > allR), 'VariableNames', output.Properties.VariableNames)];
end

function row = comparisonRow(reference, scope, snrDb, c, r)
ratio = mean(c)/mean(r);
row = table("P_FAM5", reference, scope, snrDb, numel(c), ...
    mean(c), mean(r), ratio, 100*(1-sqrt(ratio)), ...
    nnz(c < r), nnz(c == r), nnz(c > r), ...
    'VariableNames', {'candidate', 'reference', 'scope', 'snrDb', ...
    'n', 'candidateMse', 'referenceMse', 'mseRatio', ...
    'rmseImprovementPct', 'winCount', 'tieCount', 'lossCount'});
end

function gate = engineeringGate(comparisons, population, protocol)
pa = comparisons(comparisons.reference == "P_A", :);
hard = comparisons(comparisons.reference == "P_FA", :);
name = ["per-SNR-range-to-PA"; "aggregate-range-to-PA"; ...
    "per-SNR-range-to-hard-PFA"; "aggregate-range-to-hard-PFA"];
observed = [max(pa.mseRatio(pa.scope == "per-SNR")); ...
    pa.mseRatio(pa.scope == "equal-SNR"); ...
    max(hard.mseRatio(hard.scope == "per-SNR")); ...
    hard.mseRatio(hard.scope == "equal-SNR")];
limit = [protocol.gate.maxPerSnrRangeRatioToPA; ...
    protocol.gate.maxAggregateRangeRatioToPA; ...
    protocol.gate.maxPerSnrRangeRatioToHardPFA; ...
    protocol.gate.maxAggregateRangeRatioToHardPFA];
gate = table(repmat(population, 4, 1), name, observed, limit, ...
    observed <= limit, 'VariableNames', {'population', 'gate', ...
    'observedRatio', 'maximumAllowedRatio', 'pass'});
end
