function report = r36AssertCommonProtocol(cfg, protocol)
%R36ASSERTCOMMONPROTOCOL Reject frozen-system or R36 protocol drift.

arguments
    cfg (1, 1) struct = jad.defaultConfig()
    protocol (1, 1) struct = r36CommonProtocol()
end

if ~isequaln(protocol, r36CommonProtocol())
    error("r36:CommonProtocolDrift", ...
        "The R36 protocol differs from its frozen identity.");
end
r34Protocol = r34.config();
r32.assertFrozenConfig(cfg, r34Protocol.r32);
identityPass = r34Protocol.finalTest.designHash ...
    == protocol.frozenSource.finalDesignHash ...
    && r34Protocol.estimatorVersion ...
    == "R33-A-q-only-invariants-direct-EVD-v1" ...
    && r34Protocol.implementation.useFastResponse ...
    && ~r34Protocol.implementation.useGram ...
    && r34Protocol.r32.front.candidateId == protocol.algorithm.front ...
    && r34Protocol.r32.music.carrierCount ...
    == protocol.algorithm.carrierCount ...
    && r34Protocol.r32.music.subarraySize ...
    == protocol.algorithm.subarraySize ...
    && r34Protocol.r32.music.numSubarrays ...
    == protocol.algorithm.numSubarrays ...
    && isequal(r34Protocol.r32.music.gridSizes, ...
    protocol.algorithm.angleGridSizes) ...
    && r34Protocol.r32.profile.halfWidthM ...
    == protocol.rangeProfile.halfWidthM ...
    && r34Protocol.r32.profile.lambda == protocol.rangeProfile.lambda;
if ~identityPass
    error("r36:InheritedAlgorithmDrift", ...
        "The frozen P_A/C_enhanced identity no longer matches R36.");
end

matlabRoot = string(fileparts(fileparts(fileparts( ...
    mfilename("fullpath")))));
sourceDigest = r32.sourceDigest(r34.manifest(matlabRoot));
if sourceDigest ~= protocol.frozenSource.sourceDigest
    error("r36:FrozenSourceDrift", ...
        "R34/R33/R32 or an inherited frozen source has changed.");
end
report = struct(passed=true, protocolVersion=protocol.version, ...
    sourceDigest=sourceDigest, finalDesignHash= ...
    r34Protocol.finalTest.designHash, estimationExecuted=false, ...
    evidenceRole=protocol.evidenceRole);
end
