function protocol = r36CommonProtocol()
%R36COMMONPROTOCOL Frozen policy for range-orthogonal angle research.

protocol.version = "R36-range-orthogonal-angle-protocol-v1";
protocol.date = "2026-09-12";
protocol.evidenceRole = "existing-60-user-development-only";
protocol.independentFinalValidation = false;
protocol.system = struct(N=256, M=2048, K=2047, L=160, P=97, ...
    thetaLimitsDeg=[-60, 60], rangeLimitsM=[15, 50]);
protocol.frozenSource = struct(sourceDigest= ...
    "2d40cca46c84cccd580ba8bfc48d1b2bc74dfc4390920f17c80f00428f0a9684", ...
    finalDesignHash= ...
    "e1f6cc945644e88806432a52d2b6e18d0df026024c279790c9bf26edb9792cd6");
protocol.data = struct(developmentUsers=60, snrDb=[-10, 0, 20], ...
    usersPerSnr=20, newUsersAllowed=false, calibrationUsersExecuted=0, ...
    r34FinalReuseAllowed=false);
protocol.algorithm = struct(front="L06", response="q-only", ...
    subspaceSolver="direct-covariance-eig", useGram=false, ...
    carrierCount=2047, subarraySize=160, numSubarrays=97, ...
    angleHalfWidthDeg=0.2, angleGridSizes=[41, 31, 21], ...
    oneStepOnly=true, optimizer="none", ...
    evaluationPoint="frozen-P_A-theta-and-profile-range", ...
    objective="uniform-all-carrier-subspace-residual-least-squares", ...
    nuisance="range-via-Gauss-Newton-Schur-complement", ...
    bracket="actual-final-grid-two-sided-neighbors", ...
    angleDerivativeUnit="radian", rangeDerivativeUnit="meter");
protocol.rangeProfile = struct(center="frozen-L06-front-range", ...
    halfWidthM=2, lambda=1, rerunAfterNewAngle=true, ...
    reusePaRange=false, useDiagnosticNewtonRange=false);
protocol.numerics = struct(curvatureScaleTolerance=100*eps, ...
    scoreTolerance=1e-10, thetaToleranceDeg=1e-12);
protocol.engineeringGate = struct(maximumPerSnrAngleMseRatio=1.01, ...
    maximumEqualSnrAngleMseRatio=0.98, ...
    maximumPerSnrRangeMseRatio=1.02, ...
    maximumRuntimeRatioToCEnhanced=1.00);
protocol.studyLabel = "Development study – not R34 final confirmation";
protocol.prohibited = ["R34-final-reuse", "new-users", ...
    "R35-A-B-D-execution-or-combination", "continuous-maximization", ...
    "coordinate-ascent", "new-grid", "expanded-bracket", ...
    "alpha-temperature-topK-threshold-search", ...
    "adaptive-selector", "ML-weighting", "posthoc-gate-relaxation"];
end
