function protocol = config()
%CONFIG Frozen R43 coherent sequential development protocol.

protocol.version = "R43-coherent-sequential-development-v1";
protocol.date = "2026-09-17";
protocol.evidenceRole = "new-development-not-independent-final";
protocol.method = struct(primary="H_seqY", baseline="P_A", ...
    zhangBaseline="C_enhanced", ablations=["H_seqZ", "H_seqZY"]);
r32Protocol = r32.config();
protocol.front = r32Protocol.front;
protocol.array = struct(carrierCount=2047, angleHalfWidthDeg=0.2, ...
    coarseAngleGridSize=41, tolXDeg=1e-7);
protocol.profile = r32Protocol.profile;
protocol.coherent = struct(gainModel="one-common-complex-gain-over-array-and-carriers", ...
    scoreFloor=1e-12, combinedRule="equal-block-profile-residual-log-score");
protocol.development = struct(snrDb=[-10, 0, 20], ...
    pilotPositionCount=10, expandedPositionCount=20, ...
    positionSeed=57000000, trialSeedRoot=57100000, ...
    angleLimitsDeg=[-55, 55], rangeLimitsM=[17, 48], ...
    missThresholdM=1);
protocol.gate = struct(maxPerSnrMseRatio=1.05, ...
    maxAggregateAngleMseRatioToPA=0.98, ...
    maxAggregateRangeMseRatioToPA=0.95, ...
    maxAggregateMseRatioToC=1.0);
protocol.execution = struct(r34FinalReadAllowed=false, ...
    r41FinalReadAllowed=false, r42ResultReadAllowed=false, ...
    finalTrialsExecuted=0, parameterTuningFromPilotAllowed=false, ...
    calibrationAuthorized=false, independentFinalAuthorized=false);
end
