function output = summarize(design, results, protocol)
%SUMMARIZE Build paired R43 performance and attack-gate tables.

arguments
    design table
    results (:, 1) cell
    protocol (1, 1) struct = r43.config()
end

if height(design) ~= numel(results) || ~all(cellfun(@(x) x.success, results))
    error("r43:IncompleteResults", ...
        "R43 summary requires one successful result per design row.");
end
methods = ["P_A", "C_enhanced", "H_seqZ", ...
    "H_seqY", "H_seqZY", "F_L06"];
numMethods = numel(methods);
numRows = height(design)*numMethods;
positionId = repelem(design.positionId, numMethods);
seed = repelem(design.seed, numMethods);
snrDb = repelem(design.snrDb, numMethods);
truthThetaDeg = repelem(design.truthThetaDeg, numMethods);
truthRangeM = repelem(design.truthRangeM, numMethods);
method = repmat(methods(:), height(design), 1);
thetaDeg = zeros(numRows, 1);
rangeM = zeros(numRows, 1);
runtimeSeconds = zeros(numRows, 1);
for rowIndex = 1:height(design)
    indices = (rowIndex-1)*numMethods+(1:numMethods);
    thetaDeg(indices) = results{rowIndex}.thetaDeg(:);
    rangeM(indices) = results{rowIndex}.rangeM(:);
    runtimeSeconds(indices) = results{rowIndex}.runtimeSeconds(:);
end
angleErrorDeg = thetaDeg-truthThetaDeg;
rangeErrorM = rangeM-truthRangeM;
positionErrorM = hypot(rangeErrorM, ...
    truthRangeM.*deg2rad(angleErrorDeg));
perUser = table(positionId, seed, snrDb, method, truthThetaDeg, ...
    truthRangeM, thetaDeg, rangeM, angleErrorDeg, rangeErrorM, ...
    positionErrorM, runtimeSeconds);

methodSummary = table();
for methodName = methods
    for snr = protocol.development.snrDb
        rows = perUser.method == methodName & perUser.snrDb == snr;
        methodSummary = [methodSummary; metricRow( ...
            perUser(rows, :), methodName, snr, ...
            protocol.development.missThresholdM)]; %#ok<AGROW>
    end
end

comparison = table();
for baseline = ["P_A", "C_enhanced"]
    for candidate = ["H_seqZ", "H_seqY", "H_seqZY"]
        for snr = protocol.development.snrDb
            comparison = [comparison; comparisonRow(perUser, ...
                candidate, baseline, snr)]; %#ok<AGROW>
        end
        comparison = [comparison; comparisonRow(perUser, ...
            candidate, baseline, nan)]; %#ok<AGROW>
    end
end

paRows = comparison.baseline == "P_A" ...
    & comparison.candidate == protocol.method.primary;
cRows = comparison.baseline == "C_enhanced" ...
    & comparison.candidate == protocol.method.primary;
paPerSnr = comparison(paRows & ~isnan(comparison.snrDb), :);
paAggregate = comparison(paRows & isnan(comparison.snrDb), :);
cPerSnr = comparison(cRows & ~isnan(comparison.snrDb), :);
cAggregate = comparison(cRows & isnan(comparison.snrDb), :);
paAnglePass = all(paPerSnr.angleMseRatio <= ...
    protocol.gate.maxPerSnrMseRatio) ...
    && paAggregate.angleMseRatio <= ...
    protocol.gate.maxAggregateAngleMseRatioToPA;
paRangePass = all(paPerSnr.rangeMseRatio <= ...
    protocol.gate.maxPerSnrMseRatio) ...
    && paAggregate.rangeMseRatio <= ...
    protocol.gate.maxAggregateRangeMseRatioToPA;
cAnglePass = all(cPerSnr.angleMseRatio <= ...
    protocol.gate.maxPerSnrMseRatio) ...
    && cAggregate.angleMseRatio < ...
    protocol.gate.maxAggregateMseRatioToC;
cRangePass = all(cPerSnr.rangeMseRatio <= ...
    protocol.gate.maxPerSnrMseRatio) ...
    && cAggregate.rangeMseRatio < ...
    protocol.gate.maxAggregateMseRatioToC;
finitePass = all(isfinite(perUser.thetaDeg)) && all(isfinite(perUser.rangeM));
pilotPass = paAnglePass && paRangePass && cAnglePass && cRangePass ...
    && finitePass;
gate = table(paAnglePass, paRangePass, cAnglePass, cRangePass, ...
    finitePass, pilotPass);
output = struct(perUser=perUser, methodSummary=methodSummary, ...
    comparison=comparison, gate=gate);
end

function row = metricRow(input, method, snrDb, missThreshold)
angleAbs = abs(input.angleErrorDeg);
rangeAbs = abs(input.rangeErrorM);
row = table(method, snrDb, height(input), ...
    mean(input.angleErrorDeg.^2), sqrt(mean(input.angleErrorDeg.^2)), ...
    median(angleAbs), prctile(angleAbs, 90), prctile(angleAbs, 95), ...
    mean(input.rangeErrorM.^2), sqrt(mean(input.rangeErrorM.^2)), ...
    median(rangeAbs), prctile(rangeAbs, 90), prctile(rangeAbs, 95), ...
    mean(rangeAbs > missThreshold), sqrt(mean(input.positionErrorM.^2)), ...
    mean(input.runtimeSeconds), ...
    'VariableNames', {'method', 'snrDb', 'n', 'angleMseDeg2', ...
    'angleRmseDeg', 'angleMedianAbsDeg', 'angleP90AbsDeg', ...
    'angleP95AbsDeg', 'rangeMseM2', 'rangeRmseM', ...
    'rangeMedianAbsM', 'rangeP90AbsM', 'rangeP95AbsM', ...
    'rangeMissRate', 'positionRmseM', 'meanRuntimeSeconds'});
end

function row = comparisonRow(input, candidate, baseline, snrDb)
rowsCandidate = input.method == candidate;
rowsBaseline = input.method == baseline;
if ~isnan(snrDb)
    rowsCandidate = rowsCandidate & input.snrDb == snrDb;
    rowsBaseline = rowsBaseline & input.snrDb == snrDb;
end
candidateRows = input(rowsCandidate, :);
baselineRows = input(rowsBaseline, :);
angleCandidate = candidateRows.angleErrorDeg.^2;
angleBaseline = baselineRows.angleErrorDeg.^2;
rangeCandidate = candidateRows.rangeErrorM.^2;
rangeBaseline = baselineRows.rangeErrorM.^2;
angleRatio = mean(angleCandidate)/mean(angleBaseline);
rangeRatio = mean(rangeCandidate)/mean(rangeBaseline);
row = table(candidate, baseline, snrDb, angleRatio, ...
    100*(1-sqrt(angleRatio)), rangeRatio, 100*(1-sqrt(rangeRatio)), ...
    sum(angleCandidate < angleBaseline), ...
    sum(angleCandidate == angleBaseline), ...
    sum(angleCandidate > angleBaseline), ...
    sum(rangeCandidate < rangeBaseline), ...
    sum(rangeCandidate == rangeBaseline), ...
    sum(rangeCandidate > rangeBaseline), ...
    'VariableNames', {'candidate', 'baseline', 'snrDb', ...
    'angleMseRatio', 'angleRmseImprovementPct', 'rangeMseRatio', ...
    'rangeRmseImprovementPct', 'angleWins', 'angleTies', ...
    'angleLosses', 'rangeWins', 'rangeTies', 'rangeLosses'});
end
