function output = summarize(design, results, protocol)
%SUMMARIZE Build R54 all-600 and holdout-540 calibration endpoints.

arguments
    design table
    results (:, 1) cell
    protocol (1, 1) struct = r54.config()
end

if numel(results) ~= height(design) || any(cellfun(@isempty, results)) ...
        || any(cellfun(@(item) ~item.success, results))
    error("r54:IncompleteCalibration", ...
        "R54 requires every calibration row to succeed.");
end
perUser = buildPerUser(design, results);
all600 = populationSummary(perUser, "all600", protocol, 0);
holdout = populationSummary( ...
    perUser(perUser.subset == "holdout540", :), ...
    "holdout540", protocol, 1);
diagnostic = populationSummary( ...
    perUser(perUser.subset == "diagnostic60", :), ...
    "diagnostic60", protocol, 2);
gate = [all600.gate; holdout.gate];
identityPass = max(perUser.angleIdentityDifferenceDeg) ...
    <= protocol.gate.maxAngleIdentityDifferenceDeg;
calibrationReady = identityPass && all(gate.pass);
decision = table(identityPass, all(all600.gate.pass), ...
    all(holdout.gate.pass), calibrationReady, ...
    'VariableNames', {'angleIdentityPass', 'all600Pass', ...
    'holdout540Pass', 'calibrationReady'});
output = struct(version="R54-PFALF-calibration-summary-v1", ...
    perUser=perUser, all600=all600, holdout540=holdout, ...
    diagnostic60=diagnostic, gate=gate, decision=decision, ...
    calibrationReady=calibrationReady);
end

function output = buildPerUser(design, results)
methods = ["P_A", "P_FA", "Y_only", "P_FALF"];
output = design(:, ["positionId", "seed", "trialIndex", ...
    "snrDb", "truthThetaDeg", "truthRangeM", "subset"]);
for method = methods
    theta = cellfun(@(item) item.(method).thetaDeg, results);
    rangeM = cellfun(@(item) item.(method).rangeM, results);
    output.("theta_"+method) = theta;
    output.("range_"+method) = rangeM;
    output.("angleError_"+method) = theta-output.truthThetaDeg;
    output.("rangeError_"+method) = rangeM-output.truthRangeM;
end
output.angleIdentityDifferenceDeg = cellfun( ...
    @(item) item.angleIdentityDifferenceDeg, results);
output.rangeShiftM = cellfun(@(item) item.rangeShiftM, results);
output.qPeakChanged = cellfun(@(item) item.qPeakChanged, results);
output.yOnlyZBasinAgreement = cellfun( ...
    @(item) item.yOnlyZBasinAgreement, results);
output.hessianZAtPFA = cellfun( ...
    @(item) item.commonCurvature.hessianZ, results);
output.hessianYAtPFA = cellfun( ...
    @(item) item.commonCurvature.hessianY, results);
output.hessianJointAtPFA = cellfun( ...
    @(item) item.commonCurvature.hessianJoint, results);
output.curvatureRatioYToZ = cellfun( ...
    @(item) item.commonCurvature.curvatureRatioYToZ, results);
output.hessianJointAtSelected = cellfun( ...
    @(item) item.selectedCurvature.hessianJoint, results);
end

function output = populationSummary(perUser, population, protocol, seedOffset)
methods = ["P_A", "P_FA", "Y_only", "P_FALF"];
methodSummary = table();
for method = methods
    for snr = protocol.design.snrDb
        selected = perUser.snrDb == snr;
        ae = perUser.("angleError_"+method)(selected);
        re = perUser.("rangeError_"+method)(selected);
        methodSummary = [methodSummary; table(population, method, snr, ...
            nnz(selected), mean(ae.^2), sqrt(mean(ae.^2)), ...
            mean(re.^2), sqrt(mean(re.^2)), median(abs(re)), ...
            quantile(abs(re), .90), quantile(abs(re), .95), ...
            mean(abs(re)>protocol.gate.missThresholdM), ...
            'VariableNames', {'population', 'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', 'rangeMseM2', ...
            'rangeRmseM', 'rangeMedianAbsM', 'rangeP90AbsM', ...
            'rangeP95AbsM', 'rangeMissRateOver1M'})]; %#ok<AGROW>
    end
end
comparisons = compareAll(perUser, population, protocol);
bootstrap = r54.bootstrapRatio(perUser, population, protocol, seedOffset);
mechanism = mechanismSummary(perUser, population, protocol);
gate = buildGate(perUser, comparisons, bootstrap, population, protocol);
output = struct(population=population, perUser=perUser, ...
    methodSummary=methodSummary, comparisons=comparisons, ...
    bootstrap=bootstrap, mechanism=mechanism, gate=gate);
end

function output = compareAll(perUser, population, protocol)
output = table();
for candidate = ["P_FA", "Y_only", "P_FALF"]
    for reference = ["P_A", "P_FA"]
        candidateMse = zeros(numel(protocol.design.snrDb), 1);
        referenceMse = zeros(numel(protocol.design.snrDb), 1);
        for index = 1:numel(protocol.design.snrDb)
            snr = protocol.design.snrDb(index);
            selected = perUser.snrDb == snr;
            ce = perUser.("rangeError_"+candidate)(selected).^2;
            re = perUser.("rangeError_"+reference)(selected).^2;
            candidateMse(index) = mean(ce);
            referenceMse(index) = mean(re);
            output = [output; comparisonRow(population, candidate, ...
                reference, "per-SNR", snr, ce, re)]; %#ok<AGROW>
        end
        ce = perUser.("rangeError_"+candidate).^2;
        re = perUser.("rangeError_"+reference).^2;
        row = comparisonRow(population, candidate, reference, ...
            "equal-SNR", nan, ce, re);
        row.rangeMseRatio = mean(candidateMse)/mean(referenceMse);
        row.rangeRmseDifferenceMm = 1000*(sqrt(mean(candidateMse)) ...
            -sqrt(mean(referenceMse)));
        output = [output; row]; %#ok<AGROW>
    end
end
end

function output = comparisonRow(population, candidate, reference, ...
    scope, snrDb, ce, re)
output = table(population, candidate, reference, scope, snrDb, ...
    numel(ce), mean(ce)/mean(re), ...
    1000*(sqrt(mean(ce))-sqrt(mean(re))), ...
    nnz(ce<re), nnz(ce==re), nnz(ce>re), mean(ce-re), ...
    'VariableNames', {'population', 'candidate', 'reference', ...
    'scope', 'snrDb', 'n', 'rangeMseRatio', ...
    'rangeRmseDifferenceMm', 'winCount', 'tieCount', ...
    'lossCount', 'meanSquaredErrorDifference'});
end

function output = mechanismSummary(perUser, population, protocol)
output = table();
for snr = [protocol.design.snrDb, nan]
    if isnan(snr)
        selected = true(height(perUser), 1);
        scope = "equal-SNR";
    else
        selected = perUser.snrDb == snr;
        scope = "per-SNR";
    end
    qSwitch = perUser.qPeakChanged(selected);
    difference = perUser.rangeError_P_FALF(selected).^2 ...
        -perUser.rangeError_P_A(selected).^2;
    ratio = perUser.curvatureRatioYToZ(selected);
    ratio = ratio(isfinite(ratio));
    output = [output; table(population, scope, snr, nnz(selected), ...
        sum(qSwitch), mean(qSwitch), sum(difference(qSwitch)), ...
        sum(difference(~qSwitch)), rms(perUser.rangeShiftM(selected)), ...
        median(abs(perUser.rangeShiftM(selected))), median(ratio), ...
        mean(perUser.yOnlyZBasinAgreement(selected)), ...
        'VariableNames', {'population', 'scope', 'snrDb', 'n', ...
        'qPeakChangeCount', 'qPeakChangeRate', ...
        'switchSquaredErrorDifferenceSum', ...
        'nonSwitchSquaredErrorDifferenceSum', 'rangeShiftRmsM', ...
        'rangeShiftMedianAbsM', 'curvatureRatioMedian', ...
        'yOnlyZBasinAgreementRate'})]; %#ok<AGROW>
end
end

function output = buildGate(perUser, comparisons, bootstrap, ...
    population, protocol)
primary = comparisons(comparisons.candidate == "P_FALF" ...
    & comparisons.reference == "P_A", :);
aggregate = primary(primary.scope == "equal-SNR", :);
perSnr = primary(primary.scope == "per-SNR", :);
missF = mean(abs(perUser.rangeError_P_FALF)>protocol.gate.missThresholdM);
missA = mean(abs(perUser.rangeError_P_A)>protocol.gate.missThresholdM);
metric = ["angle-identity-max-deg"; "aggregate-range-MSE/P_A"; ...
    "max-per-SNR-range-MSE/P_A"; "cluster-U95-range-MSE/P_A"; ...
    "range-miss-rate-difference-to-P_A"];
value = [max(perUser.angleIdentityDifferenceDeg); ...
    aggregate.rangeMseRatio; max(perSnr.rangeMseRatio); ...
    bootstrap.oneSidedUpper95; missF-missA];
limit = [protocol.gate.maxAngleIdentityDifferenceDeg; ...
    protocol.gate.maxAggregateRangeMseRatioToPA; ...
    protocol.gate.maxPerSnrRangeMseRatioToPA; ...
    protocol.gate.maxBootstrapUpper95ToPA; ...
    protocol.gate.maxRangeMissRateDifferenceToPA];
pass = isfinite(value) & value <= limit;
output = table(repmat(population, numel(metric), 1), metric, ...
    value, repmat("<=", numel(metric), 1), limit, pass, ...
    'VariableNames', {'population', 'metric', 'value', ...
    'direction', 'limit', 'pass'});
output.notes = repmat("predeclared-R54-calibration-gate", height(output), 1);
end
