function authorization = assertAuthorized(packageFolder, identity)
%ASSERTAUTHORIZED Require the exact one-time R46 authorization.

arguments
    packageFolder (1, 1) string
    identity (1, 1) struct
end

file = fullfile(packageFolder, "FINAL_TEST_AUTHORIZATION.mat");
if ~isfile(file)
    error("r46:FinalTestNotAuthorized", ...
        "R46 is locked; no explicit final-test authorization exists.");
end
saved = load(file, "authorization");
if ~isfield(saved, "authorization")
    error("r46:MalformedFinalAuthorization", ...
        "The R46 authorization file is malformed.");
end
authorization = saved.authorization;
required = ["approved", "protocolVersion", "designHash", ...
    "statisticsHash", "sourceDigest", "calibrationSourceDigest", ...
    "statement"];
valid = all(isfield(authorization, required)) ...
    && authorization.approved ...
    && authorization.protocolVersion == identity.protocolVersion ...
    && authorization.designHash == identity.designHash ...
    && authorization.statisticsHash == identity.statisticsHash ...
    && authorization.sourceDigest == identity.sourceDigest ...
    && authorization.calibrationSourceDigest ...
    == identity.calibrationSourceDigest ...
    && authorization.statement ...
    == "user-explicitly-authorized-one-frozen-R46-1400-trial-final";
if ~valid
    error("r46:FinalAuthorizationIdentityMismatch", ...
        "Authorization does not match the exact R46 package.");
end
end
