function protocol = config()
%CONFIG Freeze the P_FA independent final-comparison protocol.

protocol.version = "R46-PFA-independent-final1400-v1";
protocol.date = "2026-09-17";
protocol.evidenceRole = "independent-final-comparison-if-authorized";
protocol.algorithm = struct( ...
    primary="P_FA", primaryReference="P_A", ...
    secondary=["G_schur", "C_enhanced"], ...
    methodVersion="PFA-full-aperture-sequential-v1", ...
    calibrationSourceDigest= ...
    "f1483ec49bb59907a9b5b2f70aa95459f11277450a0bbcf715a43b3324439868", ...
    cLabel="strengthened-Zhang-style-executable-baseline", ...
    cAuthorshipClaim="not-author-supplied-Zhang2026-code");
protocol.design = struct(positionCount=200, ...
    snrDb=[-10, -5, 0, 5, 10, 15, 20], ...
    angleLimitsDeg=[-60, 60], rangeLimitsM=[15, 50], ...
    positionSeed=61000000, trialSeedRoot=61100000, ...
    trialSeedRule="trialSeedRoot+100000*snrIndex+positionId", ...
    ordering="position-major-then-ascending-SNR", ...
    expectedRows=1400);
protocol.statistics = struct( ...
    version="R46-log-ratio-position-cluster-max-v1", ...
    cluster="positionId", bootstrapCount=20000, ...
    bootstrapSeed=61200000, familyConfidence=0.975, ...
    sharedIndicesAcrossSnr=true, ...
    angleLimit=1.0, rangeLimit=1.02, ...
    angleFamily="P_FA-over-P_A-angle-MSE-ratios-seven-SNR", ...
    rangeFamily="P_FA-over-P_A-range-MSE-ratios-seven-SNR", ...
    multiplicity="separate-97.5pct-simultaneous-families-Bonferroni", ...
    primaryRule="all-seven-angle-and-range-upper-bounds-pass", ...
    aggregateCanRescuePrimary=false);
protocol.complexity = struct( ...
    recommendedPoolType="Threads", recommendedWorkers=8, ...
    recommendedBatchSize=8, calibrationRows=600, ...
    calibrationElapsedMinutes=86.6109, ...
    projectedRows=1400, projectedCoreHours=3.3682, ...
    recommendedWallClockHours=[3.5, 4.0], ...
    serverThroughputIsAlgorithmRuntimeEvidence=false);
protocol.execution = struct( ...
    authorizationPhrase="I_EXPLICITLY_AUTHORIZE_R46_PFA_FINAL_1400", ...
    status="LOCKED-WAITING-FOR-EXPLICIT-USER-AUTHORIZATION", ...
    authorized=false, trialsExecuted=0, oneFinalRunOnly=true, ...
    noSignificanceStopping=true, noAdditionalUsers=true, ...
    noTailDeletion=true, noUnfavorableSeedRerun=true, ...
    noDesignRegeneration=true, noMethodModification=true, ...
    failedTrialStopsPrimaryInference=true);
protocol.r45 = r45.config();
end
