function output = paths(project)
%PATHS Centralize the immutable R46 package and execution folders.

arguments
    project (1, 1) string
end

root = fullfile(project, "results", "full_spectrum");
output = struct( ...
    protocolFolder=fullfile(root, "round46_pfa_final_protocol_v1"), ...
    protocolFile=fullfile(root, "round46_pfa_final_protocol_v1", ...
    "protocol.mat"), ...
    authorizationFile=fullfile(root, "round46_pfa_final_protocol_v1", ...
    "FINAL_TEST_AUTHORIZATION.mat"), ...
    executionFolder=fullfile(root, "round46_pfa_independent_final_v1"));
end
