function output = summarize(design, results, protocol)
%SUMMARIZE Build R46 final tables and co-primary decisions.

arguments
    design table
    results (:, 1) cell
    protocol (1, 1) struct = r46.config()
end

if numel(results) ~= height(design) || any(cellfun(@isempty, results)) ...
        || any(cellfun(@(item) ~item.success, results))
    error("r46:IncompleteFinal", ...
        "R46 summary requires all 1400 frozen rows to succeed.");
end
perUser = design(:, ["positionId", "seed", "trialIndex", ...
    "snrDb", "truthThetaDeg", "truthRangeM"]);
methods = ["P_FA", "P_A", "G_schur", "C_enhanced"];
for method = methods
    theta = cellfun(@(item) item.(method).thetaDeg, results);
    rangeM = cellfun(@(item) item.(method).rangeM, results);
    perUser.("theta_"+method) = theta;
    perUser.("range_"+method) = rangeM;
    perUser.("angleError_"+method) = theta-perUser.truthThetaDeg;
    perUser.("rangeError_"+method) = rangeM-perUser.truthRangeM;
    perUser.("positionError_"+method) = hypot( ...
        rangeM.*sind(theta)-perUser.truthRangeM.*sind(perUser.truthThetaDeg), ...
        rangeM.*cosd(theta)-perUser.truthRangeM.*cosd(perUser.truthThetaDeg));
end
perUser.pfaEndpointHit = cellfun( ...
    @(item) item.pfaDiagnostics.profile.endpointHit, results);
perUser.pfaNearBoundary = cellfun( ...
    @(item) item.pfaDiagnostics.profile.nearBoundary, results);
perUser.pfaAngleRetentionMargin = cellfun( ...
    @(item) item.pfaDiagnostics.angle.retentionMargin, results);
perUser.pfaFullArrayEvaluationCount = cellfun( ...
    @(item) item.pfaDiagnostics.fullArrayEvaluationCount, results);
perUser.pfaProfileEvaluationCount = cellfun( ...
    @(item) item.pfaDiagnostics.profileEvaluationCount, results);
perUser.sharedDirectEvdCount = cellfun( ...
    @(item) item.sharedAudit.totalDirectEvdCount, results);
perUser.sharedGramCount = cellfun( ...
    @(item) item.sharedAudit.totalGramCount, results);
perUser.sharedFallbackCount = cellfun( ...
    @(item) item.sharedAudit.totalFallbackCount, results);

methodSummary = buildMethodSummary(perUser, methods, protocol.design.snrDb);
comparisons = table();
for reference = ["P_A", "G_schur", "C_enhanced"]
    for metric = ["angle", "range", "position"]
        comparisons = [comparisons; comparisonRows( ...
            perUser, reference, metric, protocol.design.snrDb)]; %#ok<AGROW>
    end
end
bootstrap = r46.clusterBootstrap(perUser, protocol);
identityPass = height(perUser) == protocol.design.expectedRows ...
    && numel(unique(perUser.positionId)) == protocol.design.positionCount ...
    && all(perUser.sharedDirectEvdCount > 0) ...
    && all(perUser.sharedGramCount == 0) ...
    && all(perUser.sharedFallbackCount == 0) ...
    && all(perUser.pfaAngleRetentionMargin >= -1000*eps) ...
    && all(perUser.pfaFullArrayEvaluationCount > 0) ...
    && all(perUser.pfaProfileEvaluationCount > 0) ...
    && all(isfinite(perUser.theta_P_FA)) ...
    && all(isfinite(perUser.range_P_FA));
primaryPass = bootstrap.primaryPass && identityPass;
decision = table(all(bootstrap.angleFamily.pass), ...
    all(bootstrap.rangeFamily.pass), identityPass, primaryPass, ...
    'VariableNames', {'angleFamilyPass', 'rangeFamilyPass', ...
    'identityPass', 'primaryPass'});
diagnostics = table(height(perUser), sum(perUser.pfaEndpointHit), ...
    sum(perUser.pfaNearBoundary), min(perUser.pfaAngleRetentionMargin), ...
    mean(perUser.pfaFullArrayEvaluationCount), ...
    mean(perUser.pfaProfileEvaluationCount), ...
    sum(perUser.sharedDirectEvdCount), sum(perUser.sharedGramCount), ...
    sum(perUser.sharedFallbackCount), ...
    'VariableNames', {'n', 'profileEndpointHits', ...
    'profileNearBoundaryHits', 'minimumAngleRetentionMargin', ...
    'meanFullArrayEvaluationCount', 'meanProfileEvaluationCount', ...
    'totalDirectEvdCount', 'totalGramCount', 'totalFallbackCount'});
output = struct(version="R46-PFA-final-summary-v1", ...
    perUser=perUser, methodSummary=methodSummary, ...
    comparisons=comparisons, bootstrap=bootstrap, ...
    diagnostics=diagnostics, decision=decision, primaryPass=primaryPass);
end

function output = buildMethodSummary(perUser, methods, snrValues)
output = table();
for method = methods
    for snr = snrValues
        selected = perUser.snrDb == snr;
        angleError = perUser.("angleError_"+method)(selected);
        rangeError = perUser.("rangeError_"+method)(selected);
        positionError = perUser.("positionError_"+method)(selected);
        output = [output; table(method, snr, nnz(selected), ...
            mean(angleError.^2), sqrt(mean(angleError.^2)), ...
            median(abs(angleError)), quantile(abs(angleError), 0.90), ...
            quantile(abs(angleError), 0.95), mean(rangeError.^2), ...
            sqrt(mean(rangeError.^2)), median(abs(rangeError)), ...
            quantile(abs(rangeError), 0.90), ...
            quantile(abs(rangeError), 0.95), ...
            sqrt(mean(positionError.^2)), ...
            'VariableNames', {'method', 'snrDb', 'n', ...
            'angleMseDeg2', 'angleRmseDeg', 'angleMedianAbsDeg', ...
            'angleP90AbsDeg', 'angleP95AbsDeg', 'rangeMseM2', ...
            'rangeRmseM', 'rangeMedianAbsM', 'rangeP90AbsM', ...
            'rangeP95AbsM', 'positionRmseM'})]; %#ok<AGROW>
    end
end
end

function output = comparisonRows(perUser, reference, metric, snrValues)
output = table();
candidateMse = zeros(numel(snrValues), 1);
referenceMse = zeros(numel(snrValues), 1);
for index = 1:numel(snrValues)
    snr = snrValues(index);
    selected = perUser.snrDb == snr;
    candidateError = perUser.(metric+"Error_P_FA")(selected).^2;
    baselineError = perUser.(metric+"Error_"+reference)(selected).^2;
    candidateMse(index) = mean(candidateError);
    referenceMse(index) = mean(baselineError);
    output = [output; comparisonRow(reference, metric, ...
        "per-SNR", snr, candidateError, baselineError)]; %#ok<AGROW>
end
ratio = mean(candidateMse)/mean(referenceMse);
allCandidate = perUser.(metric+"Error_P_FA").^2;
allReference = perUser.(metric+"Error_"+reference).^2;
output = [output; table("P_FA", reference, metric, "equal-SNR", nan, ...
    height(perUser), mean(candidateMse), mean(referenceMse), ratio, ...
    100*(1-sqrt(ratio)), nnz(allCandidate < allReference), ...
    nnz(allCandidate == allReference), nnz(allCandidate > allReference), ...
    'VariableNames', output.Properties.VariableNames)];
end

function row = comparisonRow(reference, metric, scope, snrDb, ...
    candidateError, referenceError)
candidateMse = mean(candidateError);
referenceMse = mean(referenceError);
ratio = candidateMse/referenceMse;
row = table("P_FA", reference, metric, scope, snrDb, ...
    numel(candidateError), candidateMse, referenceMse, ratio, ...
    100*(1-sqrt(ratio)), nnz(candidateError < referenceError), ...
    nnz(candidateError == referenceError), ...
    nnz(candidateError > referenceError), ...
    'VariableNames', {'candidate', 'reference', 'metric', 'scope', ...
    'snrDb', 'n', 'candidateMse', 'referenceMse', 'mseRatio', ...
    'rmseImprovementPct', 'winCount', 'tieCount', 'lossCount'});
end
