function saved = validateProtocolPackage(project)
%VALIDATEPROTOCOLPACKAGE Reject any drift in the locked R46 package.

arguments
    project (1, 1) string
end

locations = r46.paths(project);
if ~isfile(locations.protocolFile)
    error("r46:MissingProtocolPackage", ...
        "The locked R46 protocol package has not been prepared.");
end
saved = load(locations.protocolFile, "identity", "protocol", ...
    "design", "source");
required = ["identity", "protocol", "design", "source"];
if ~all(isfield(saved, required))
    error("r46:MalformedProtocolPackage", ...
        "The R46 protocol package is incomplete.");
end
currentProtocol = r46.config();
currentDesign = r46.design(currentProtocol);
currentSource = r46.sourceManifest(project);
currentCalibrationDigest = r32.sourceDigest(r45.manifest(project));
valid = isequaln(saved.protocol, currentProtocol) ...
    && isequaln(saved.design, currentDesign) ...
    && r46.designHash(saved.design) == saved.identity.designHash ...
    && r41.structHash(saved.protocol.statistics) ...
    == saved.identity.statisticsHash ...
    && currentCalibrationDigest ...
    == saved.identity.calibrationSourceDigest ...
    && currentCalibrationDigest ...
    == saved.protocol.algorithm.calibrationSourceDigest ...
    && r32.sourceDigest(currentSource) == saved.identity.sourceDigest ...
    && isequaln(currentSource, saved.source) ...
    && saved.identity.trialsExecuted == 0 ...
    && ~saved.identity.authorized;
if ~valid
    error("r46:ProtocolPackageDrift", ...
        "Protocol, design, statistics, P_FA source, or R46 source drifted.");
end
end
